import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_DIAGNOSTICS_LABS = {
    "diagnostics_labs": {
        "label": "Diagnostics & Labs",
        "blurb": "Clinical diagnostic and pathology labs: order and specimen management, analyzer middleware, digital pathology, result reporting, QC and CLIA/CAP accreditation, and revenue cycle.",
        "medallion": medallion(
            "Raw lab and result feeds",
            "HL7 v2 orders and results, FHIR resources, analyzer ASTM messages through the middleware, LIMS specimen records, whole-slide image metadata and claims, landed exactly as received so an order or a result can be replayed as it stood.",
            "Conformed order, specimen, result",
            "Orders, specimens, accessions, patients and results resolved into single conformed entities across the LIS, LIMS, instrument and billing estates, with LOINC and SNOMED codes reconciled and reflex and send-out chains stitched to one accession.",
            "TAT, utilization, QC",
            "Contracted products the lab runs on: turnaround time and backlog by bench, test utilization and send-out cost, QC drift and proficiency testing, and denial rate and net collection by payer.",
        ),
        "rails": {
            "src": [
                {
                    "box": "LIS & Pathology",
                    "ic": "db",
                    "tiles": [
                        tile("Epic Beaker LIS", "db", "Laboratory information system inside Epic: the system of record for orders, accessions and results in the integrated hospital lab.", "epic-beaker",
                             cat="Laboratory Information System (LIS)",
                             what="The order, accession and result system of record for the integrated hospital lab, embedded in the Epic clinical estate.",
                             users="Lab Operations, Bench supervisors and Medical director.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch + intraday"),
                                 stream=flow(["semi-structured"], "100s of HL7 result msgs/sec", "Continuous (HL7 / CDC)"))),
                        tile("Sunquest LIS", "db", "Clinisys Sunquest laboratory information system for hospital and reference labs: order entry, specimen tracking and result reporting.", "sunquest",
                             cat="Laboratory Information System (LIS)",
                             what="Order entry, specimen tracking and result reporting for hospital and reference labs on the Clinisys Sunquest platform.",
                             users="Lab Operations, Bench supervisors and Operations managers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch"),
                                 stream=flow(["semi-structured"], "100s of HL7 msgs/sec", "Continuous (HL7)"))),
                        tile("Oracle Health PathNet", "db", "Oracle Health (Cerner) Millennium PathNet: laboratory and pathology workflows where Cerner is the incumbent clinical estate.", "oracle-pathnet",
                             cat="Laboratory Information System (LIS)",
                             what="Laboratory and pathology workflows on Oracle Health (Cerner) Millennium PathNet where Cerner is the incumbent clinical estate.",
                             users="Lab Operations, Anatomic pathologists and Medical director.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch"),
                                 stream=flow(["semi-structured"], "100s of HL7 msgs/sec", "Continuous (HL7)"))),
                        tile("Orchard Harvest LIS", "db", "Orchard Harvest LIS for independent and physician-office labs: order management, autoverification rules and result delivery.", "orchard",
                             cat="Laboratory Information System (LIS)",
                             what="Order management, autoverification rules and result delivery for independent and physician-office labs on Orchard Harvest.",
                             users="Lab Operations, Bench supervisors and Billing & coding.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Nightly batch + intraday"))),
                    ],
                },
                {
                    "box": "LIMS & Molecular",
                    "ic": "erp",
                    "tiles": [
                        tile("LabWare LIMS", "erp", "Laboratory information management for molecular, reference and specialty testing: specimen lifecycle, batch and result management.", "labware",
                             cat="Laboratory Information Management System (LIMS)",
                             what="Manages specimen lifecycle, batch and result management for molecular, reference and specialty testing beyond the routine LIS.",
                             users="Molecular pathology, Bench supervisors and QA & QC managers.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "2-10 GB/day", "Nightly batch + result release"))),
                        tile("Thermo LIMS", "erp", "Thermo Fisher SampleManager LIMS: sample lifecycle, workflow and instrument integration across the diagnostic lab.", "samplemanager",
                             cat="Laboratory Information Management System (LIMS)",
                             what="Sample lifecycle, workflow and instrument integration across the diagnostic lab on Thermo Fisher SampleManager.",
                             users="Bench supervisors, Operations managers and QA & QC managers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-8 GB/day", "Nightly batch"))),
                        tile("LabVantage LIMS", "erp", "LabVantage LIMS for clinical and molecular labs: specimen, workflow and QC management on a single platform.", "labvantage",
                             cat="Laboratory Information Management System (LIMS)",
                             what="Specimen, workflow and QC management for clinical and molecular labs on a single LabVantage platform.",
                             users="Molecular pathology, QA & QC managers and Operations managers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-8 GB/day", "Nightly batch"))),
                        tile("STARLIMS", "db", "STARLIMS laboratory informatics for clinical diagnostics: specimen tracking, testing workflow and compliance records.", "starlims",
                             cat="Laboratory Information Management System (LIMS)",
                             what="Specimen tracking, testing workflow and compliance records for clinical diagnostics on STARLIMS laboratory informatics.",
                             users="Bench supervisors, Accreditation leads and QA & QC managers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-6 GB/day", "Nightly batch"))),
                    ],
                },
                {
                    "box": "Analyzers & Middleware",
                    "ic": "iot",
                    "tiles": [
                        tile("DI Instrument Manager", "connect", "Data Innovations Instrument Manager: the analyzer middleware that routes orders and results between instruments and the LIS with autoverification rules.", "di-instrument-manager",
                             cat="Analyzer Middleware / Connectivity",
                             what="The analyzer middleware that routes orders and results between instruments and the LIS and applies autoverification rules at the bench.",
                             users="Bench supervisors, Operations managers and QA & QC managers.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "1-5k result + QC msgs/sec", "Continuous (ASTM / HL7)"))),
                        tile("Roche cobas infinity", "iot", "Roche cobas central-lab instruments and informatics feeding chemistry, immunoassay and molecular results into the lab estate.", "roche-cobas",
                             cat="Clinical Analyzer & Informatics (IVD)",
                             what="Roche cobas central-lab instruments and informatics feeding chemistry, immunoassay and molecular results into the lab estate.",
                             users="Bench supervisors, Molecular pathology and QA & QC managers.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "100s-1000s of results/sec", "Continuous during runs"))),
                        tile("Abbott AlinIQ", "iot", "Abbott AlinIQ informatics and Alinity analyzers: connectivity and result management across the core laboratory.", "abbott-aliniq",
                             cat="Clinical Analyzer & Informatics (IVD)",
                             what="Abbott AlinIQ informatics and Alinity analyzers providing connectivity and result management across the core laboratory.",
                             users="Bench supervisors, Operations managers and QA & QC managers.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "100s-1000s of results/sec", "Continuous during runs"))),
                        tile("Analyzer Data", "iot", "Raw instrument telemetry, flags and QC readings from every analyzer on the bench, the ground truth for autoverification and uptime.",
                             cat="Analyzer Instrument Telemetry",
                             what="Raw instrument telemetry, flags and QC readings from every analyzer on the bench, the ground truth for autoverification and instrument uptime.",
                             users="QC & Accred, Bench supervisors and Diagnostics DS.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "continuous telemetry per analyzer", "Continuous"))),
                    ],
                },
                {
                    "box": "Digital Pathology",
                    "ic": "media",
                    "tiles": [
                        tile("Philips IntelliSite", "media", "Philips IntelliSite Pathology Solution: whole-slide scanning, image management and viewing for primary diagnosis.", "philips-pathology",
                             cat="Digital Pathology Platform",
                             what="Whole-slide scanning, image management and viewing for primary diagnosis on the Philips IntelliSite Pathology Solution.",
                             users="Anatomic pathologists, Cytology and Diagnostics DS.",
                             data_out=data_out(
                                 batch=flow(["unstructured", "structured"], "50-500 GB/day (whole-slide images)", "Per-scan on acquisition"))),
                        tile("Leica Aperio", "media", "Leica Aperio digital pathology: slide scanning and image analysis feeding whole-slide images into the diagnostic workflow.", "leica-aperio",
                             cat="Digital Pathology Platform",
                             what="Slide scanning and image analysis feeding whole-slide images into the diagnostic workflow on Leica Aperio.",
                             users="Anatomic pathologists, Molecular pathology and Diagnostics DS.",
                             data_out=data_out(
                                 batch=flow(["unstructured", "structured"], "50-500 GB/day (WSI)", "Per-scan on acquisition"))),
                        tile("Sectra Pathology", "media", "Sectra digital pathology module: whole-slide image storage and reading integrated with the diagnostic imaging estate.", "sectra",
                             cat="Digital Pathology Platform",
                             what="Whole-slide image storage and reading integrated with the diagnostic imaging estate on the Sectra digital pathology module.",
                             users="Anatomic pathologists, Cytology and Medical director.",
                             data_out=data_out(
                                 batch=flow(["unstructured", "structured"], "50-300 GB/day (WSI)", "Per-scan on acquisition"))),
                        tile("Paige AI Pathology", "model", "Paige clinical AI applications and whole-slide image outputs used to assist detection and prioritisation before sign-out.", "paige",
                             cat="Clinical AI (Pathology)",
                             what="Clinical AI applications and whole-slide image outputs used to assist detection and case prioritisation before pathologist sign-out.",
                             users="Anatomic pathologists, Diagnostics DS and Medical director.",
                             data_out=data_out(
                                 batch=flow(["structured", "unstructured"], "GBs/day (scores + overlays)", "Per-slide on inference"))),
                    ],
                },
                {
                    "box": "Interfaces, RCM & QC",
                    "ic": "api",
                    "tiles": [
                        tile("Rhapsody Engine", "api", "Rhapsody integration engine: HL7 v2 and FHIR order and result interfaces between the lab, EHRs and clients.", "rhapsody",
                             cat="Integration Engine (HL7/FHIR)",
                             what="Routes HL7 v2 and FHIR order and result interfaces between the lab, EHRs and clients, the messaging backbone of the lab estate.",
                             users="Interface Eng, Lab Operations and Bench supervisors.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "1-10k messages/sec at peak", "Continuous (HL7 / FHIR)"))),
                        tile("NextGen Connect", "connect", "NextGen Connect (Mirth) interface engine routing HL7 and API messages across the lab's ordering and result channels.", "mirth",
                             cat="Integration Engine (HL7/FHIR)",
                             what="Routes HL7 and API messages across the lab's ordering and result channels on the NextGen Connect (Mirth) interface engine.",
                             users="Interface Eng, Lab Operations and Billing & coding.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "100s-1000s of msgs/sec", "Continuous (HL7 / API)"))),
                        tile("XiFin RCM", "market", "XiFin revenue cycle management: claims, medical-necessity checking, denials and reimbursement for the diagnostic lab.", "xifin",
                             cat="Revenue Cycle Management (RCM)",
                             what="Manages claims, medical-necessity checking, denials and reimbursement for the diagnostic lab on XiFin RCM.",
                             users="Billing & coding, Denials management and Payer contracting.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day claims + remits", "Daily claim + remittance cycles"))),
                        tile("Bio-Rad Unity QC", "gauge", "Bio-Rad Unity quality control and QCNet: control results, Levey-Jennings and peer-group comparison across analytes.", "biorad-unity",
                             cat="Quality Control Data Management",
                             what="Captures control results, Levey-Jennings and peer-group comparison across analytes on Bio-Rad Unity QC and QCNet.",
                             users="QA & QC managers, Accreditation leads and Bench supervisors.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.2-1 GB/day QC results", "Per-run + daily peer comparison"))),
                    ],
                },
                fed_group("Billing & Claims Marts", "Historical billing, denial and claims marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the reconciled financial numbers.",
                          cat="Revenue Cycle Data Warehouse",
                          what="Historical billing, denial and claims marts kept in the incumbent warehouse and queried in place through federation, avoiding a second copy of the reconciled financial numbers.",
                          users="Revenue Cycle, Denials management and CFO & finance.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("LOINC & SNOMED", "ontology", "LOINC test codes and SNOMED CT clinical terminology ingested as reference so orders and results map to one coding standard.", ["loinc", "snomed"],
                     cat="Clinical Terminology / Ontology",
                     what="LOINC test codes and SNOMED CT clinical terminology ingested as reference so orders and results map to one coding standard across the estate.",
                     users="Interface Eng, Lab Leadership and QA & QC managers.",
                     data_out=data_out(
                         batch=flow(["structured"], "GBs (terminology releases)", "Periodic version releases"))),
                tile("Public Health ELR", "gavel", "Electronic laboratory reporting of reportable conditions to public health, produced from the same governed result tables.", "cdc-elr",
                     cat="Public Health Reporting (ELR)",
                     what="Electronic laboratory reporting of reportable conditions to public health, produced from the same governed result tables the lab reports on.",
                     users="Lab Leadership, Accreditation leads and Interface Eng.",
                     data_out=data_out(
                         batch=flow(["semi-structured"], "MBs-GBs/day (reportable results)", "Continuous / daily filing"))),
                tile("Instrument Events", "stream", "ASTM and HL7 instrument event streams over Kafka carrying analyzer results, flags and QC readings, landed as structured events.",
                     cat="Instrument Event Stream (ASTM/HL7)",
                     what="ASTM and HL7 instrument event streams over Kafka carrying analyzer results, flags and QC readings, landed as structured events for real-time operations.",
                     users="Interface Eng, Bench supervisors and Diagnostics DS.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "1-10k events/sec at peak", "Continuous (Kafka)"))),
            ]),
            "ppl": ppl2([
                biz("Lab Leadership", "Genie One",
                    "The lab CEO and COO on volume, cost per test and network capacity; the medical director on diagnostic quality and the test menu; the CFO on reimbursement, payer mix and margin per accession.",
                    [["Genie One", "Ask what a test line cost or what drove denials last month without an analyst pull."],
                     ["AI/BI", "Cost per test, turnaround and margin per accession on one certified set of Metric Views."],
                     ["Unity Catalog", "Certification and the glossary so \"billable test\" and \"TAT\" mean one thing across sites."]],
                    sub=[["Lab CEO & COO", "volume, cost per test and network capacity."],
                         ["Medical director", "diagnostic quality and the test menu."],
                         ["CFO & finance", "reimbursement, payer mix and margin per accession."]],
                    ucs=["Test Utilization", "AMR Surveillance", "Turnaround Time", "Denials & Billing"]),
                biz("Pathology", "Model Serving",
                    "Anatomic pathologists reading whole-slide images and reporting diagnoses, molecular pathology interpreting NGS and FISH assays, and cytology screening cases before sign-out.",
                    [["Pathology Viewer", "Whole-slide images pre-screened with metastasis heat maps before sign-out."],
                     ["Model Serving", "Image and molecular classifiers scored in the diagnostic path."],
                     ["MLflow", "Every diagnostic model tracked for validation and audit."]],
                    sub=[["Anatomic pathologists", "whole-slide reading and diagnostic sign-out."],
                         ["Molecular pathology", "NGS, FISH and companion-diagnostic interpretation."],
                         ["Cytology", "screening and adequacy before sign-out."]],
                    ucs=["Digital Pathology AI", "Molecular Diagnostics", "Test Utilization"]),
                biz("Lab Operations", "Lakehouse//RT",
                    "Lab operations managers on turnaround and backlog, bench supervisors on autoverification and repeat rates, and pre-analytic and phlebotomy teams on specimen quality and rejections.",
                    [["TAT Command Center", "Turnaround and backlog by bench flagged before a STAT misses target."],
                     ["Lakehouse//RT", "Live accession and instrument state at the latency a bench moves at."],
                     ["Model Serving", "Autoverification and delay models scored in the result path."]],
                    sub=[["Operations managers", "turnaround, backlog and staffing across benches."],
                         ["Bench supervisors", "autoverification and repeat rates."],
                         ["Pre-analytic & phlebotomy", "specimen quality and rejections."]],
                    ucs=["Turnaround Time", "Result Autoverify", "Critical Value Alerts", "Instrument Uptime"]),
                biz("QC & Accred", "AI/BI",
                    "QA and QC managers on Levey-Jennings and Westgard rules, accreditation leads on CLIA and CAP readiness and proficiency testing, and lab safety on competency and audit trails.",
                    [["AI/BI", "QC drift, proficiency testing and audit readiness on certified Metric Views."],
                     ["Unity Catalog", "Audit trails and lineage supporting CLIA and CAP inspection."],
                     ["Genie One", "Ask which analytes breached Westgard rules this week."]],
                    sub=[["QA & QC managers", "Levey-Jennings, Westgard rules and QC drift."],
                         ["Accreditation leads", "CLIA, CAP readiness and proficiency testing."],
                         ["Lab safety", "competency, training and audit trails."]],
                    ucs=["QC & Accreditation", "Instrument Uptime", "Result Autoverify"]),
                biz("Revenue Cycle", "AI/BI",
                    "Billing and coding on clean-claim rate and medical-necessity coding, denials management on payer denials and appeals, and payer contracting on reimbursement and prior authorization.",
                    [["Denials Workbench", "Denials triaged by root cause with the evidence to appeal assembled."],
                     ["Model Serving", "Denial-risk and medical-necessity models scored before submission."],
                     ["AI/BI", "Clean-claim rate, denial rate and net collection on certified views."]],
                    sub=[["Billing & coding", "clean-claim rate and medical-necessity coding."],
                         ["Denials management", "payer denials, appeals and write-offs."],
                         ["Payer contracting", "reimbursement and prior authorization."]],
                    ucs=["Denials & Billing", "Test Utilization", "Turnaround Time"]),
            ], [
                biz("Interface Eng", "Lakeflow",
                    "Land HL7 v2 orders and results, FHIR resources and analyzer ASTM messages through the interface engine; own the Bronze to Silver path and the pager when result feeds stall.",
                    [["Lakeflow Connect", "Managed connectors for LIS, LIMS, ERP and billing sources."],
                     ["Auto Loader", "HL7, ASTM and instrument files landed incrementally into Bronze."],
                     ["Lakewatch", "Freshness on the result and order tables the benches read all shift."]]),
                biz("Diagnostics DS", "MLflow",
                    "Whole-slide image models, autoverification and denial classifiers, and molecular interpretation models, and whether they still hold as assays and instruments change.",
                    [["Feature Store", "Specimen, patient and analyte features read identically in training and serving."],
                     ["MLflow", "Every diagnostic and operational model tracked for validation and audit."],
                     ["Model Serving", "Image, autoverification and denial models scored in the lab path."]]),
                biz("Lab App Dev", "Apps",
                    "Ship the TAT, pathology-viewer and denials applications the lab works in, hosted next to governed accession and result data.",
                    [["Apps", "Operational lab screens with no separate web tier to run or secure."],
                     ["Lakebase", "Serverless Postgres for accession workflow state and governed writes."],
                     ["Agent Bricks", "Agents that draft an appeal or a QC investigation against governed tools."]]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Leadership and QC dashboards against serverless SQL with Unity Catalog permissions enforced end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for turnaround and denial answers in the channel the lab already works in (Beta)."),
                    tile("Notebooks & IDEs", "notebook", "Pathology and data-science notebooks against governed accession, result and imaging data."),
                ]},
                {"box": "Providers & Ordering", "ic": "partner", "tiles": [
                    tile("Provider FHIR Results", "api", "Verified results returned to ordering EHRs and clinicians over HL7 FHIR from governed result tables."),
                    tile("EHR Order Interface", "connect", "Orders received from client and hospital EHRs through the interface engine into the accessioning path."),
                    tile("Ordering Portals", "globe", "Web ordering and result portals for referring physicians and outreach clients, served from governed data."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("LIS Result Writeback", "db", "Verified and autoverified results written back into the LIS so the answer reaches the reporting path.", "sunquest"),
                    tile("RCM Claim Writeback", "market", "Denial-risk flags and coding evidence written back into the RCM system so billing acts before submission.", "xifin"),
                    tile("QC Writeback", "gauge", "QC dispositions and instrument holds written back to the middleware at the bench.", "di-instrument-manager"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("CLIA & CAP Reporting", "gavel", "CLIA and CAP inspection evidence and proficiency-testing records produced from governed QC tables.", ["clia", "cap"]),
                    tile("Public Health Filing", "share", "Reportable-condition electronic lab reporting filed to public health from certified Gold results.", "cdc-elr"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Published, contracted result and utilization products discoverable in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Hospitals, health plans and registries reading live tables with no copy and no egress duplication."),
                ]},
            ], genie_spaces=[
                genie("Turnaround & Operations", "Ask about turnaround, backlog and benches at risk of missing target in plain language.",
                      feeds=["Epic Beaker LIS", "DI Instrument Manager", "Instrument Events", "TAT, utilization, QC"],
                      teams=["Lab Operations", "Operations managers", "Bench supervisors"],
                      questions=[
                          "What is turnaround time by bench against target right now?",
                          "Which STAT orders are at risk of missing turnaround?",
                          "Where is the backlog deepest across the benches?",
                          "What is the autoverification rate by analyzer today?",
                          "Which specimens were rejected and for what reason?"]),
                genie("Pathology & Diagnostics", "Explore case volumes, sign-out throughput and molecular results across pathology.",
                      feeds=["Philips IntelliSite", "Leica Aperio", "LabWare LIMS", "Conformed order, specimen, result"],
                      teams=["Pathology", "Anatomic pathologists", "Molecular pathology"],
                      questions=[
                          "How many cases are awaiting sign-out by subspecialty?",
                          "What is time to sign-out for whole-slide cases this week?",
                          "Which molecular assays have the longest turnaround?",
                          "How many cases were AI-prioritised before review?",
                          "What is the reflex-to-send-out rate by test?"]),
                genie("Revenue Cycle & Denials", "Answer clean-claim, denial and net-collection questions across the revenue cycle.",
                      feeds=["XiFin RCM", "Billing & Claims Marts", "Conformed order, specimen, result"],
                      teams=["Revenue Cycle", "Billing & coding", "Denials management"],
                      questions=[
                          "What is our clean-claim rate by payer this month?",
                          "Which denial reasons are driving the most lost revenue?",
                          "How many appealable claims are aging toward the deadline?",
                          "What is net collection by test and payer?",
                          "Which tests fail medical-necessity checks most often?"]),
                genie("QC & Compliance", "Ask about QC drift, Westgard breaches and accreditation readiness across analytes.",
                      feeds=["Bio-Rad Unity QC", "Roche cobas infinity", "Analyzer Data", "TAT, utilization, QC"],
                      teams=["QC & Accred", "QA & QC managers", "Accreditation leads"],
                      questions=[
                          "Which analytes breached Westgard rules this week?",
                          "What is the QC failure rate by instrument and analyte?",
                          "How did we perform on the last proficiency-testing round?",
                          "Which instruments are trending toward a failure?",
                          "Where is our lineage evidence weakest for CAP inspection?"]),
            ], dashboards=[
                dashboard("Turnaround & Backlog", "Turnaround, backlog and STAT compliance by bench on certified Metric Views.",
                          kpis=["Turnaround time", "Backlog by bench", "STAT compliance", "Autoverification rate", "Repeat rate"],
                          teams=["Lab Operations", "Lab Leadership", "Operations managers"]),
                dashboard("Test Utilization & Cost", "Test volume, cost per test and send-out cost for menu and utilization steering.",
                          kpis=["Test volume", "Cost per test", "Send-out cost", "Redundant orders", "Margin per accession"],
                          teams=["Lab Leadership", "Revenue Cycle", "Medical director"]),
                dashboard("Denials & Revenue", "Clean-claim rate, denial rate and net collection across the revenue cycle.",
                          kpis=["Clean-claim rate", "Denial rate", "Net collection", "Appeal success rate", "Days in AR"],
                          teams=["Revenue Cycle", "Lab Leadership", "Denials management"]),
                dashboard("QC & Accreditation", "QC failure, Westgard breaches and instrument uptime for CLIA and CAP readiness.",
                          kpis=["QC failure rate", "Westgard breaches", "Proficiency-testing outcome", "Instrument uptime", "Audit findings"],
                          teams=["QC & Accred", "Lab Operations", "Accreditation leads"]),
            ]),
        },
        "top": top_band(
            [
                app("TAT Command Center", "Turnaround & backlog", "gauge",
                    "The screen operations runs the shift from: accessions and STAT orders tracked from collection to verified result across every bench, flagging the ones that will miss target turnaround, on Databricks Apps over Lakebase."),
                app("Pathology Viewer", "Digital pathology triage", "media",
                    "Whole-slide images pre-screened with deep-learning metastasis heat maps and case context, so pathologists triage and sign out from governed imaging and result data."),
                app("Denials Workbench", "Revenue cycle", "market",
                    "Where billing sees denials triaged by root cause with the medical-necessity and coding evidence assembled to appeal, scored for denial risk before the claim goes out."),
                app("Utilization Hub", "Test utilization", "chart",
                    "Test ordering by provider, panel and guideline, flagging redundant and low-value tests so the medical director can steer the menu and reduce send-out cost."),
            ],
            [
                uc("Turnaround Time", "Operations", "gauge",
                    "Accessions tracked from collection to verified result across every bench, so the orders that will miss turnaround are moved before the STAT is late.",
                    problem="Turnaround is measured after the fact in the LIS, so a backlog on a bench or a stalled analyzer is discovered when a clinician chases a STAT, not before.",
                    who="Lab Operations",
                    how="LIS accession events and analyzer middleware feeds land in Lakehouse//RT; delay models score orders in Model Serving and the TAT Command Center flags benches that will miss target before the result is late.",
                    comps=["TAT Command Center", "Lakehouse//RT", "Epic Beaker LIS", "DI Instrument Manager", "AI/BI"],
                    stories=[["Kythera Labs builds its business on Spark Declarative Pipelines", "https://www.databricks.com/customers/kythera-labs"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Digital Pathology AI", "Pathology", "media",
                    "Whole-slide images processed at scale with deep learning to pre-screen for metastasis and prioritise cases before a pathologist signs out.",
                    problem="Whole-slide images are gigapixel and reviewed manually, so screening is slow and the hardest cases wait behind routine ones in the same queue.",
                    who="Pathology",
                    how="Slides from the digital-pathology scanners are processed with the Databricks pathology accelerator; metastasis models score tiles in Model Serving and surface heat maps in the Pathology Viewer for triage and sign-out.",
                    comps=["Pathology Viewer", "Philips IntelliSite", "Leica Aperio", "Model Serving", "MLflow", "Unity Catalog"],
                    stories=[["Digital Pathology Image Analysis solution accelerator", "https://www.databricks.com/solutions/accelerators/digital-pathology"],
                             ["Why Pathnostics chose Databricks for complex diagnostics data", "https://www.databricks.com/blog/why-pathnostics-chose-databricks-data-intelligence-platform-its-most-complex-diagnostics-data"]]),
                uc("Result Autoverify", "Operations", "zeroops",
                    "Routine results released automatically against rules and prior-result deltas, so technologists spend their time on the cases that actually need a human.",
                    problem="Every result queues for manual verification even when it is normal and consistent with history, so technologist time is spent on the routine and the abnormal waits behind it.",
                    who="Lab Operations",
                    how="Analyzer results flow through the middleware into the lakehouse; delta-check and autoverification models score each result in Model Serving so routine results release and only exceptions reach a technologist.",
                    comps=["DI Instrument Manager", "Analyzer Data", "Model Serving", "Lakehouse//RT", "Sunquest LIS"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Test Utilization", "Leadership", "chart",
                    "Ordering patterns by provider, panel and guideline, so redundant and low-value tests are steered out and send-out cost is controlled.",
                    problem="Duplicate orders, reflex tests and expensive send-outs are ordered against no consistent guideline, so cost per accession creeps and the menu is never rationalised.",
                    who="Lab Leadership",
                    how="Order, result and coding data are conformed to certified Metric Views mapped to LOINC; the Utilization Hub and Genie surface redundant and low-value ordering for the medical director to steer.",
                    comps=["Utilization Hub", "AI/BI", "Genie One", "LOINC & SNOMED", "Unity Catalog"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Denials & Billing", "Revenue cycle", "market",
                    "Claim denials predicted and triaged by root cause with the medical-necessity evidence assembled to appeal, so cash is not left on the table.",
                    problem="Denials are worked reactively across the billing system and spreadsheets, so appealable claims age past the window and the same root causes recur unmeasured.",
                    who="Revenue Cycle",
                    how="Accession, result and claim data are joined in the lakehouse; denial-risk models score claims in Model Serving before submission and the Denials Workbench assembles appeals on Lakebase.",
                    comps=["Denials Workbench", "XiFin RCM", "Model Serving", "AI/BI", "Lakebase"]),
                uc("QC & Accreditation", "Quality", "gavel",
                    "QC drift, proficiency testing and audit trails on certified data, so CLIA and CAP inspection is a query rather than a scramble.",
                    problem="QC lives in instrument middleware and spreadsheets and accreditation evidence is assembled by hand, so Westgard breaches are caught late and every inspection is a fire drill.",
                    who="QC & Accred",
                    how="QC results and proficiency testing are conformed to Gold under Unity Catalog; Levey-Jennings and Westgard monitoring runs in AI/BI with lineage that supports CLIA and CAP inspection.",
                    comps=["Bio-Rad Unity QC", "AI/BI", "Unity Catalog", "Lakeflow"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Molecular Diagnostics", "Pathology", "ontology",
                    "NGS, FISH and companion-diagnostic results interpreted and reported with the unstructured assay context pathologists need to sign out.",
                    problem="Molecular results arrive as large, semi-structured assay outputs the LIS was never built to hold, so interpretation and reporting are slow and evidence is scattered.",
                    who="Pathology",
                    how="NGS and molecular outputs land in Delta Lake alongside the LIMS record; AI Functions extract and structure assay context and interpretation models score in Model Serving for sign-out.",
                    comps=["LabWare LIMS", "AI Functions", "Model Serving", "Delta Lake", "Unity Catalog"],
                    stories=[["Why Pathnostics chose Databricks for complex diagnostics data", "https://www.databricks.com/blog/why-pathnostics-chose-databricks-data-intelligence-platform-its-most-complex-diagnostics-data"],
                             ["Real-World Evidence Solution Accelerator", "https://www.databricks.com/solutions/accelerators/real-world-evidence"]]),
                uc("Critical Value Alerts", "Operations", "stream",
                    "Critical and life-threatening results detected and routed to the ordering clinician the moment they verify, with acknowledgement closing the loop.",
                    problem="Critical values depend on a technologist reaching a clinician by phone, so a life-threatening result can wait in a queue and read-back is hard to evidence.",
                    who="Lab Operations",
                    how="Verified results stream through the interface engine into Lakehouse//RT; critical-value and early-deterioration models score in Model Serving and alerts route to the clinician over FHIR with acknowledgement tracked.",
                    comps=["Rhapsody Engine", "Lakehouse//RT", "Model Serving", "Provider FHIR Results"],
                    stories=[["MUSC detects at-risk sepsis patients from real-world data", "https://www.databricks.com/blog/2020/10/20/detecting-at-risk-patients-with-real-world-data.html"]]),
                uc("Instrument Uptime", "Engineering", "iot",
                    "Analyzer telemetry scored for drift and failure so a maintenance call is planned before an instrument goes down mid-run.",
                    problem="An analyzer failure mid-run scraps specimens and stalls a bench, and without telemetry the first signal is a failed QC or a dead instrument, not a prediction.",
                    who="QC & Accred",
                    how="Analyzer and middleware telemetry stream into the lakehouse; remaining-useful-life models score each instrument in Model Serving so service is planned before an unplanned failure.",
                    comps=["Analyzer Data", "Instrument Events", "MLflow", "Model Serving", "AI/BI"],
                    stories=[["Predictive maintenance on the Databricks Lakehouse", "https://www.databricks.com/blog/what-is-predictive-maintenance"]]),
                uc("AMR Surveillance", "Population", "zshield",
                    "Antibiotic resistance tracked across microbiology results and reported to clinicians and public health, so stewardship acts on real local patterns.",
                    problem="Resistance patterns sit in microbiology results no one aggregates, so antibiograms are annual and stewardship and public-health reporting lag the actual local trend.",
                    who="Lab Leadership",
                    how="Microbiology results are conformed with LOINC and SNOMED in the lakehouse; resistance trends are analysed in AI/BI and reported to clinicians and public health, and asked of Genie directly.",
                    comps=["LOINC & SNOMED", "Public Health Filing", "AI/BI", "Genie", "Delta Lake"],
                    stories=[["Why Pathnostics chose Databricks for complex diagnostics data", "https://www.databricks.com/blog/why-pathnostics-chose-databricks-data-intelligence-platform-its-most-complex-diagnostics-data"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
            ],
        ),
        "sources": {
            "epic-beaker": {"t": "Epic software (Beaker LIS)", "u": "https://www.epic.com/software/"},
            "sunquest": {"t": "Clinisys / Sunquest LIS", "u": "https://www.clinisys.com/"},
            "oracle-pathnet": {"t": "Oracle Health", "u": "https://www.oracle.com/health/"},
            "orchard": {"t": "Orchard Harvest LIS", "u": "https://www.orchardsoft.com/"},
            "labware": {"t": "LabWare LIMS", "u": "https://www.labware.com/"},
            "samplemanager": {"t": "Thermo Fisher lab informatics (SampleManager)", "u": "https://www.thermofisher.com/us/en/home/digital-solutions/lab-informatics.html"},
            "labvantage": {"t": "LabVantage LIMS", "u": "https://www.labvantage.com/"},
            "starlims": {"t": "STARLIMS laboratory informatics", "u": "https://www.starlims.com/"},
            "di-instrument-manager": {"t": "Data Innovations Instrument Manager", "u": "https://www.datainnovations.com/"},
            "roche-cobas": {"t": "Roche cobas instruments", "u": "https://diagnostics.roche.com/global/en/products/instruments.html"},
            "abbott-aliniq": {"t": "Abbott AlinIQ informatics", "u": "https://www.corelaboratory.abbott/int/en/offerings/brands/aliniq"},
            "philips-pathology": {"t": "Philips IntelliSite Pathology Solution", "u": "https://www.usa.philips.com/healthcare/resources/landing/philips-intellisite-pathology-solution"},
            "leica-aperio": {"t": "Leica Aperio digital pathology", "u": "https://www.leicabiosystems.com/us/digital-pathology/"},
            "sectra": {"t": "Sectra Digital Pathology Solution", "u": "https://medical.sectra.com/product/sectra-digital-pathology-solution/"},
            "paige": {"t": "Paige clinical AI pathology", "u": "https://www.paige.ai/"},
            "rhapsody": {"t": "Rhapsody integration engine", "u": "https://rhapsody.health/"},
            "mirth": {"t": "NextGen Connect (Mirth) integration engine", "u": "https://www.nextgen.com/solutions/interoperability/mirth-integration-engine"},
            "xifin": {"t": "XiFin revenue cycle management", "u": "https://www.xifin.com/"},
            "biorad-unity": {"t": "Bio-Rad Unity quality controls", "u": "https://www.bio-rad.com/en-us/category/quality-controls"},
            "loinc": {"t": "LOINC test terminology", "u": "https://loinc.org/"},
            "snomed": {"t": "SNOMED CT clinical terminology", "u": "https://www.snomed.org/"},
            "cdc-elr": {"t": "CDC Electronic Laboratory Reporting", "u": "https://www.cdc.gov/elr/"},
            "clia": {"t": "CMS CLIA program", "u": "https://www.cms.gov/medicare/quality/clinical-laboratory-improvement-amendments"},
            "cap": {"t": "CAP Laboratory Accreditation", "u": "https://www.cap.org/laboratory-improvement/accreditation"},
        },
    }
}
