import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_SEMICONDUCTORS = {
    'semiconductors': {
        "label": "Semiconductors",
        "blurb": "Fab and foundry operations: wafer manufacturing execution, yield and test analytics, design-to-silicon traceability, and supply chain resilience across the semiconductor value chain.",
        "medallion": medallion(
            "Raw fab and test feeds",
            "SECS/GEM equipment events, MES lot and step history, ATE parametric dumps and WIP snapshots, landed exactly as received so a yield excursion can always be replayed.",
            "Conformed lot, wafer, die",
            "Lots, wafers, dies and equipment resolved into single conformed entities across MES, test and ERP, with die IDs reconciled and rework genealogy stitched to one trace.",
            "Yield, cycle time, OEE",
            "Contracted products engineering runs on: yield and bin pareto by layer and tool, cycle time and WIP ageing, OEE and downtime attribution, and cost per good die.",
        ),
        "rails": {
            "src": [
                {"box": "Fab & MES", "ic": "erp", "tiles": [
                    tile("Applied E3 MES", "erp", "Manufacturing execution for wafer fabs: lot tracking, recipe management, equipment dispatch and hold/release.", "applied-e3"),
                    tile("Camstar Semiconductor", "sheet", "MES routings, BOMs, component traceability and quality holds against each lot.", "camstar"),
                    tile("camLine LineWorks", "db", "Fab APC, FDC and SPC with equipment integration: run-to-run control and tool health across the wafer line.", "brooks-pfab"),
                ]},
                {"box": "Design & IP", "ic": "sheet", "tiles": [
                    tile("Synopsys Fusion Design", "sheet", "RTL through sign-off: synthesis, place-and-route and timing closure feeding the tape-out record.", "synopsys-fusion"),
                    tile("Cadence Virtuoso", "code", "Custom and analog design: schematic, layout and LVS for IP blocks on each die.", "cadence-virtuoso"),
                    tile("Siemens Calibre", "gavel", "DRC, LVS and OPC verification against foundry rules before mask order.", "calibre"),
                ]},
                {"box": "Yield & Test", "ic": "iot", "tiles": [
                    tile("Teradyne UltraFLEX", "iot", "ATE parametric and functional test: bin maps, shmoo plots and bin history per die.", "teradyne"),
                    tile("PDF Solutions Exensio", "chart", "Yield management: defect classification, spatial signatures and excursion detection.", "pdf-exensio"),
                    tile("KLA 5D Analyzer", "stream", "Inspection and metrology: defect maps, overlay and CD measurements by tool and recipe.", "kla-5d"),
                ]},
                {"box": "Equipment & Sensors", "ic": "stream", "tiles": [
                    tile("SECS/GEM Tool Interface", "stream", "Equipment events, alarms and trace data from lithography, etch and deposition tools.", "secs-gem"),
                    tile("ASML YieldStar", "iot", "In-line overlay and CD metrology from the scanner feeding litho feedback.", "asml-yieldstar"),
                    tile("Lam Equipment Analytics", "partner", "Chamber health, RF matching and preventive maintenance signals from process tools.", "lam-analytics"),
                ]},
                {"box": "Supply & Materials", "ic": "market", "tiles": [
                    tile("SAP S/4HANA", "erp", "Procurement, inventory and cost accounting for wafers, chemicals and substrates.", "sap-s4"),
                    tile("Resilinc Supply Risk", "globe", "Multi-tier supplier mapping and disruption alerts for critical materials.", "resilinc"),
                ]},
                fed_group("Partner Foundry Marts", "Yield and capacity marts left at the foundry and queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("SEMI E134 Data Collection", "stream", "Industry data collection standard for equipment and MES events parsed on arrival.", "semi-e134"),
                tile("SECS/GEM Message Bus", "api", "Equipment host communication for remote commands, trace reports and alarms.", "secs-gem"),
                tile("OSAT Test File Exchange", "zplug", "STDF parametric files from outsourced assembly and test partners.", "stdf"),
            ]),
            "ppl": ppl2([
                biz("CEO & Fab Strategy", "Genie One", "The CEO on capacity utilisation and margin; the COO on cycle time, yield ramp and the cost of a fab excursion by product and layer.",
                    [["Genie One", "Ask what yesterday's fab output cost without booking analyst time."], ["AI/BI", "Yield, cycle time and OEE on certified Metric Views."], ["Unity Catalog", "Certification so yield means one thing across the enterprise."]],
                    sub=[["CEO", "fab capacity utilisation, margin and the return on each new fab and node."], ["COO", "cycle time, yield ramp and the cost of an excursion by product and layer."], ["VP Manufacturing", "wafer starts, output commitments and the plan behind capacity."]],
                    ucs=["Cycle Time & WIP", "Yield Excursion Detection", "Supply Risk & Allocation"]),
                biz("Fab Operations", "Lakehouse//RT", "Fab managers on WIP position, tool availability and lot disposition through each critical layer, defending cycle time and wafer starts.",
                    [["Fab Control Tower", "Live WIP and bottleneck tools on Databricks Apps over Lakebase."], ["Lakehouse//RT", "Equipment and lot state at fab-line latency."]],
                    sub=[["Fab Shift Manager", "WIP position, tool availability and hitting the day's wafer starts."], ["Dispatch & Scheduling", "lot priority, bottleneck tools and keeping the route moving."], ["Process Engineering", "recipe stability and run-to-run drift on critical layers."]],
                    ucs=["Cycle Time & WIP", "Run-to-Run Control", "Chamber Matching", "Predictive Maintenance"]),
                biz("Yield Engineering", "Model Serving", "Yield engineers on defect pareto, spatial signatures and the designed experiments that recover margin before a lot is dispositioned.",
                    [["Yield Workbench", "Bin maps and excursion history before disposition is signed."], ["Model Serving", "Defect classification and yield prediction on incoming lots."]],
                    sub=[["Yield Engineer", "defect pareto, spatial signatures and recovering margin before disposition."], ["Product & Test Engineering", "bin trends, test coverage and good-die cost per product."], ["Failure Analysis", "tracing an excursion or return to the layer, tool and process step."]],
                    ucs=["Yield Excursion Detection", "Defect Classification", "Test Optimization", "Design-Fab Feedback"]),
                biz("Supply Chain", "AI/BI", "Materials planners on substrate lead times, wafer allocation and single-source risk, trading inventory cost against line-down risk.",
                    [["AI/BI", "Inventory, consumption and supplier OTIF on certified Metric Views."], ["Genie One", "Ask which lots are at risk from a supplier delay."]],
                    sub=[["Materials Planning", "substrate and chemical lead times and buffer against line-down risk."], ["Wafer Allocation", "allocating scarce capacity and wafers against demand and priority."], ["Supplier Risk", "single-source exposure and multi-tier disruption on critical materials."]],
                    ucs=["Supply Risk & Allocation", "Cycle Time & WIP"]),
                biz("Quality & Reliability", "Lakeflow", "Quality teams on customer returns, failure-analysis correlation and qualification change controls tied back to the fab lot and test bin.",
                    [["FA Correlation Lab", "Returns tied to fab lot, test bin and assembly trace."], ["Lakeflow", "Test, MES and returns feeds conformed for quality analytics."]],
                    sub=[["Quality Engineering", "customer returns, RMA correlation and qualification change control."], ["Reliability Engineering", "failure-mode life data tied back to fab lot and test bin."], ["Customer Quality", "CoA, PPAP and reliability submissions to fabless customers."]],
                    ucs=["Customer Quality CoA", "Defect Classification", "Yield Excursion Detection"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land SECS/GEM tool events, MES lot history, ATE parametric dumps and ERP feeds; own Bronze to Silver and the pager when a yield pipeline stalls.",
                    [["Lakeflow Connect", "Managed connectors for MES, ERP and equipment host sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on SECS/GEM and test feeds."], ["Lakewatch", "Freshness on the yield tables engineering reads each shift."]],
                    sub=[["Pipeline Engineering", "SECS/GEM, MES and ATE feeds landed Bronze to Silver on time."], ["Streaming & Ingest", "equipment-host and STDF streams parsed and conformed on arrival."], ["Data Reliability", "freshness and the pager when a yield pipeline stalls mid-shift."]],
                    ucs=["Yield Excursion Detection", "Cycle Time & WIP", "Predictive Maintenance"]),
                biz("Data Scientists", "MLflow", "Defect-classification, yield-prediction, chamber-matching and test-optimisation models, and whether they still hold as processes and nodes shift.",
                    [["Feature Store", "Wafer and tool features read identically in training and serving."], ["MLflow", "Every excursion experiment tracked for audit and reproduction."], ["Model Serving", "Defect and yield models scored on incoming lots."]],
                    sub=[["Yield & Defect Modelling", "excursion, defect-classification and yield-prediction models."], ["Equipment ML", "chamber-matching and remaining-life models on tool telemetry."], ["Test Analytics", "test-time optimisation and coverage models per product."]],
                    ucs=["Defect Classification", "Chamber Matching", "Test Optimization", "Predictive Maintenance"]),
                biz("App Developers", "Apps", "Ship the Fab Control Tower, Yield Workbench and Chamber Match apps engineering runs the line from, hosted next to governed MES and test data.",
                    [["Apps", "Fab screens with no separate web tier to run or secure."], ["Lakebase", "Serverless Postgres for hold state and disposition writes."], ["Agent Bricks", "Agents that draft dispositions against governed tools."]],
                    sub=[["Apps Engineering", "the Fab Control Tower, Yield Workbench and Chamber Match apps."], ["Lakebase & Writeback", "hold state and disposition writes on serverless Postgres."], ["Agents", "agents that draft dispositions and work orders against governed tools."]],
                    ucs=["Cycle Time & WIP", "Yield Excursion Detection", "Run-to-Run Control"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Qlik / ThoughtSpot", "chart", "External BI against serverless SQL warehouses with Unity Catalog permissions end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for governed answers and yield alerts in the channel the fab works in."),
                    tile("Notebooks & IDEs", "notebook", "Engineering notebooks against governed MES, test and equipment data."),
                ]},
                {"box": "Distribution & Partners", "ic": "partner", "tiles": [
                    tile("Foundry Partner Portal", "api", "Yield summaries and lot status shared to fabless customers over Delta Sharing."),
                    tile("OSAT & Assembly Partners", "partner", "Test results and ship authorisation read by assembly partners under governed sharing."),
                    tile("Equipment OEM Feeds", "globe", "Chamber matching and maintenance recommendations exchanged with tool vendors.", "secs-gem"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("MES Hold & Release", "db", "Automated hold and release written back into MES for dispatch lists.", "applied-e3"),
                    tile("Recipe & R2R Adjust", "erp", "Run-to-run adjustments pushed to equipment hosts within approved guard bands."),
                    tile("Maintenance Work Orders", "apps", "Predicted tool removals raised as maintenance work orders on technician devices."),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Export & Trade Compliance", "gavel", "Technology node and end-use reporting from governed tables."),
                    tile("Customer Quality Reports", "share", "CoA, reliability and PPAP submissions from contracted Gold products."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Yield and traceability products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Fabless customers and OSAT partners reading live tables via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Fab Control Tower", "Live WIP state", "gauge", "Fab managers run the line from bottleneck tools, hold queues and lot disposition on Databricks Apps over Lakebase."),
             app("Yield Workbench", "Excursion analysis", "chart", "Yield engineers see bin maps, defect overlays and excursion history before lot disposition."),
             app("Chamber Match Console", "Tool health", "iot", "Chamber matching scores and drift alerts by tool and recipe before yield moves."),
             app("FA Correlation Lab", "Returns trace", "partner", "Customer returns tied to fab lot, test bin and assembly genealogy in one view.")],
            [uc("Yield Excursion Detection", "Fab quality", "chart", "Detecting yield loss by layer, tool and product before wafers complete the route.",
                problem="A yield excursion can ruin whole lots before anyone sees it, yet defect, parametric and tool data sit apart, so root cause takes weeks and the loss compounds shift after shift.",
                who="Yield Engineering",
                how="SECS/GEM, MES and ATE feeds land in Lakehouse//RT and correlate on Delta Lake; excursion models score in Model Serving and surface in the Yield Workbench before a lot is dispositioned.",
                comps=["Yield Workbench", "PDF Solutions Exensio", "Lakehouse//RT", "Model Serving", "Delta Lake"],
                stories=[["Semiconductors on the Databricks Data Intelligence Platform", "https://www.databricks.com/blog/semiconductors-data-intelligence-platform"]]),
             uc("Chamber Matching", "Equipment", "iot", "Matching chambers across a fleet on process signatures without manual tuning.",
                problem="Nominally identical chambers drift apart, so the same recipe yields differently by tool, and engineers chase the mismatch with manual golden-wafer runs that burn capacity.",
                who="Fab Operations",
                how="Chamber trace and metrology stream through SECS/GEM into Lakehouse//RT; matching models score signatures in Model Serving and flag drift in the Chamber Match Console before yield moves.",
                comps=["Chamber Match Console", "Lam Equipment Analytics", "SECS/GEM Tool Interface", "Model Serving", "Feature Store"],
                stories=[["Acond advances equipment anomaly detection with Databricks", "https://www.databricks.com/customers/acond/datasentics"]]),
             uc("Cycle Time & WIP", "Operations", "stream", "Cycle time and WIP ageing by route and bottleneck for capacity plans.",
                problem="Cycle time and WIP ageing hide in MES snapshots that refresh too slowly, so bottleneck tools and capacity risk are seen after the fact, not while there is still time to react.",
                who="CEO & Fab Strategy",
                how="MES lot and step history land through Lakeflow, conform on Delta Lake, and drive cycle-time, WIP-ageing and OEE Metric Views in AI/BI and the Fab Control Tower for capacity planning.",
                comps=["Fab Control Tower", "Applied E3 MES", "Lakeflow", "AI/BI", "Delta Lake"],
                stories=[["Applied Materials modernizes its manufacturing data foundation on Databricks", "https://www.databricks.com/blog/announcing-winners-2026-databricks-customer-awards"]]),
             uc("Defect Classification", "Metrology", "gauge", "Automated defect classification from inspection images feeding disposition rules.",
                problem="Inspection images pile up faster than engineers can classify them by hand, so defect signatures are labelled inconsistently and disposition rules lag the real failure modes.",
                who="Yield Engineering",
                how="Metrology inspection images are scored by vision models in Model Serving with features in Feature Store, feeding automated defect classes and disposition rules into the Yield Workbench.",
                comps=["Yield Workbench", "KLA 5D Analyzer", "Model Serving", "AI Functions", "Feature Store"],
                stories=[["How Corning built end-to-end ML for visual defect detection", "https://www.databricks.com/blog/2023/01/05/how-corning-built-end-end-ml-databricks-lakehouse-platform.html"]]),
             uc("Run-to-Run Control", "Process", "erp", "Closed-loop recipe adjustments within guard bands against inline metrology.",
                problem="Run-to-run adjustments rely on delayed metrology and spreadsheets, so recipe corrections arrive a lot too late and drift pushes wafers past guard bands before anyone intervenes.",
                who="Fab Operations",
                how="Inline overlay and CD metrology land in Lakehouse//RT; AI Functions compute closed-loop offsets in Model Serving and write back to equipment hosts via SECS/GEM within approved guard bands.",
                comps=["ASML YieldStar", "SECS/GEM Tool Interface", "Model Serving", "AI Functions", "Lakehouse//RT"]),
             uc("Predictive Maintenance", "Tool uptime", "iot", "Predicting tool failures from SECS/GEM traces before unplanned downtime.",
                problem="Process tools fail between planned maintenance windows, and unplanned downtime on a bottleneck tool stalls the line while the symptoms sat in trace data no one was watching.",
                who="Fab Operations",
                how="SECS/GEM trace and chamber-health signals stream into Lakehouse//RT; models tracked in MLflow score in Model Serving and raise maintenance work orders from the Chamber Match Console.",
                comps=["Chamber Match Console", "Lam Equipment Analytics", "MLflow", "Model Serving", "Lakehouse//RT"],
                stories=[["What is predictive maintenance on the Databricks Platform", "https://www.databricks.com/blog/what-is-predictive-maintenance"], ["Training 10,000 explainable anomaly-detection models for predictive maintenance", "https://www.databricks.com/blog/training-10000-anomaly-detection-models-one-billion-records-explainable-predictions"]]),
             uc("Supply Risk & Allocation", "Materials", "globe", "Multi-tier supplier risk when lead times stretch or a sub-tier fab goes offline.",
                problem="Substrate and chemical lead times swing and a single sub-tier fab can go dark, yet supplier risk and wafer allocation sit in ERP exports stale the moment they are pulled.",
                who="Supply Chain",
                how="ERP and multi-tier supplier feeds conform on Delta Lake; allocation and risk are served on certified Metric Views in AI/BI, and Genie One answers which lots a supplier delay puts at risk.",
                comps=["Resilinc Supply Risk", "SAP S/4HANA", "AI/BI", "Genie One", "Delta Lake"],
                stories=[["Mipox accelerates demand forecasting on Databricks", "https://www.databricks.com/customers/mipox"], ["Part-level demand forecasting at scale for the chip supply chain", "https://www.databricks.com/blog/part-level-demand-forecasting-scale"]]),
             uc("Test Optimization", "Cost per die", "market", "Test time and coverage trade-offs scored per product for good die cost.",
                problem="Test time is a big slice of good-die cost, yet coverage and time trade-offs are guessed per product because parametric results and escape data never sit together for analysis.",
                who="Yield Engineering",
                how="ATE parametric dumps and OSAT files conform on Delta Lake; models in Model Serving score coverage-versus-time trade-offs per product to trim test flows without losing quality.",
                comps=["Teradyne UltraFLEX", "OSAT Test File Exchange", "Model Serving", "AI Functions", "Delta Lake"]),
             uc("Design-Fab Feedback", "DTCO", "sheet", "Closing the loop from yield data back to design rules and IP revisions.",
                problem="Yield learning stays trapped in the fab, so design and IP teams revise rules on old assumptions and the design-technology loop that should close in weeks drags across nodes.",
                who="Yield Engineering",
                how="Fab yield and test data conform under Unity Catalog and join tape-out and verification records, surfaced in AI/BI so design rules and IP revisions are driven by silicon, not assumption.",
                comps=["Synopsys Fusion Design", "Siemens Calibre", "Unity Catalog", "AI/BI", "Delta Lake"]),
             uc("Customer Quality CoA", "Ship release", "product", "Certificates of analysis and ship-hold logic joined to final test gates.",
                problem="Certificates of analysis and ship-hold calls are stitched by hand from test, MES and returns systems, so releases slow and a field return is hard to trace back to its fab lot.",
                who="Quality & Reliability",
                how="Final-test gates, genealogy and returns conform under Unity Catalog in the FA Correlation Lab, and certified quality products ship to customers over Open Sharing as Data Products.",
                comps=["FA Correlation Lab", "SAP S/4HANA", "Unity Catalog", "Open Sharing", "Data Products"],
                stories=[["HP cuts consumable traceability from days to minutes with Unity Catalog", "https://www.databricks.com/customers/hp-indigo"]])],
        ),
        "sources": {
            "applied-e3": {"t": "Applied Materials E3 MES", "u": "https://www.appliedmaterials.com/us/en/products/e3.html"},
            "camstar": {"t": "Camstar Semiconductor Suite", "u": "https://plm.sw.siemens.com/en-US/opcenter/"},
            "brooks-pfab": {"t": "camLine LineWorks (Elisa IndustrIQ)", "u": "https://www.elisaindustriq.com/camline/products"},
            "synopsys-fusion": {"t": "Synopsys Fusion Design Platform", "u": "https://www.synopsys.com/implementation-and-signoff.html"},
            "cadence-virtuoso": {"t": "Cadence Virtuoso", "u": "https://www.cadence.com/en_US/home/tools/custom-ic-analog-rf-design/virtuoso-studio.html"},
            "calibre": {"t": "Siemens Calibre", "u": "https://eda.sw.siemens.com/en-US/ic/calibre-design/"},
            "teradyne": {"t": "Teradyne UltraFLEX", "u": "https://www.teradyne.com/products/test-systems/ultraflex/"},
            "pdf-exensio": {"t": "PDF Solutions Exensio", "u": "https://www.pdf.com/exensio"},
            "kla-5d": {"t": "KLA 5D Analyzer", "u": "https://www.kla.com/"},
            "secs-gem": {"t": "SECS/GEM equipment interface", "u": "https://www.semi.org/en/standards"},
            "asml-yieldstar": {"t": "ASML YieldStar metrology", "u": "https://www.asml.com/en/products/metrology-and-inspection-systems"},
            "lam-analytics": {"t": "Lam Research equipment analytics", "u": "https://www.lamresearch.com/"},
            "sap-s4": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "resilinc": {"t": "Resilinc supply risk", "u": "https://resilinc.com/"},
            "semi-e134": {"t": "SEMI E134 data collection", "u": "https://www.semi.org/en/products-services/standards"},
            "stdf": {"t": "STDF test data format", "u": "https://www.semi.org/en/products-services/standards"},
        },
    },
}
