import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_BANKING = {
    'banking': {
        "label": "Banking",
        "blurb": "Retail and commercial banking: core ledger, payments, lending, fraud, and regulatory reporting across branches and digital channels.",
        "medallion": medallion(
            "Raw core and channel logs",
            "Core banking postings, card authorizations, wire messages and CRM events landed exactly as received for audit replay.",
            "Conformed customers and accounts",
            "Customers, accounts, facilities and parties resolved into golden records across core, cards and channels.",
            "NIM, NPL, liquidity ratios",
            "Contracted products finance and risk run on: net interest margin, NPL ratio, LCR and customer profitability.",
        ),
        "rails": {
            "src": [
                {"box": "Core Banking", "ic": "erp", "tiles": [
                    tile("Temenos Transact", "erp", "Deposits, loans, GL and end-of-day across retail and commercial.", "temenos"),
                    tile("FIS Profile", "erp", "Account processing, interest accrual and regulatory extracts.", "fis-profile"),
                    tile("Finastra Fusion", "erp", "Lending origination, servicing and treasury interfaces.", "finastra"),
                ]},
                {"box": "Cards & Payments", "ic": "market", "tiles": [
                    tile("Visa DPS / Auth", "market", "Authorization, clearing and dispute messages.", "visa"),
                    tile("Mastercard Smart Data", "market", "Spend analytics and merchant category enrichment.", "mastercard"),
                    tile("SWIFT FIN Messages", "api", "Cross-border payment instructions and confirmations.", "swift"),
                ]},
                {"box": "Digital Channels", "ic": "apps", "tiles": [
                    tile("Temenos Infinity", "apps", "Mobile and web sessions, transfers and self-service events.", "temenos-infinity"),
                    tile("Salesforce FSC", "custlake", "Households, opportunities and service cases.", "sf-fsc"),
                    tile("NICE Actimize", "gavel", "AML alerts, cases and SAR workflow.", "actimize"),
                ]},
                {"box": "Risk & Finance", "ic": "chart", "tiles": [
                    tile("Moody's RiskCalc", "chart", "PD/LGD models and rating migrations for commercial names.", "moodys"),
                    tile("FIS Ambit Focus", "chart", "ALM, liquidity and interest rate risk measurement.", "fis-alm"),
                    tile("AxiomSL Reg Reporting", "gavel", "Basel, CCAR and local regulatory templates.", "axiomsl"),
                ]},
                {"box": "Open Banking", "ic": "api", "tiles": [
                    tile("Plaid Aggregation", "api", "External account verification and aggregation with consent.", "plaid"),
                    tile("Tink Open Banking", "partner", "AIS/PIS traffic and consent registry.", "tink"),
                ]},
                fed_group("Data Warehouse Mart", "Historical GL and risk marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("FICO Falcon", "gavel", "Card fraud scores and consortium intelligence.", "fico"),
                tile("LexisNexis Risk", "partner", "KYC, sanctions and adverse media screening.", "lexisnexis"),
                tile("Experian Bureau", "custlake", "Credit bureau pulls and attribute refreshes.", "experian"),
            ]),
            "ppl": ppl2([
                biz("Chief Credit Officer & CFO", "Genie One",
                    "The CEO on ROE and deposit growth; the CFO on net interest margin, cost-to-income and CET1 capital against NPL formation across the book.",
                    [["Genie One", "Ask what last quarter's NIM was by segment."], ["AI/BI", "Capital and liquidity on certified Metric Views."], ["Unity Catalog", "One customer definition across channels."]],
                    sub=[["Chief Executive Officer", "return on equity, deposit growth and the balance between growth and capital strength."], ["Chief Financial Officer", "net interest margin, cost-to-income and the certified numbers behind the results."], ["Chief Credit Officer", "portfolio credit quality, NPL formation and provisioning across the book."]],
                    ucs=["Regulatory Reporting", "Credit Early Warning", "Liquidity Forecasting"]),
                biz("Retail Banking", "AI/BI",
                    "Branch productivity, product penetration and attrition, judged on deposit and loan growth, household profitability and cross-sell.",
                    [["Branch Performance", "Household profitability by branch and RM."], ["AI/BI", "Deposit and loan growth on governed core data."]],
                    sub=[["Head of Branch Network", "branch productivity, deposit and loan growth and household profitability by region."], ["Head of Digital Banking", "mobile and web engagement, digital sales and self-service adoption."], ["Cards & Payments Lead", "card spend, interchange and fraud loss across the portfolio."]],
                    ucs=["Customer 360", "Next-Best-Product", "Collections Optimization", "Open Banking Analytics"]),
                biz("Commercial Banking", "Model Serving",
                    "Relationship profitability, covenants and limit utilization, tracked on risk-adjusted return, exposure at default and rating migration.",
                    [["RM Workbench", "Exposure and cross-sell opportunities by relationship."], ["Model Serving", "Early warning models on commercial books."]],
                    sub=[["Head of Corporate Banking", "relationship profitability and risk-adjusted return across the commercial book."], ["Relationship Managers", "exposure, covenant status and cross-sell across their named clients."], ["Credit Risk Officers", "limit utilization, rating migration and early signs of deterioration."]],
                    ucs=["Credit Early Warning", "Customer 360", "Regulatory Reporting"]),
                biz("Risk & Compliance", "Lakehouse//RT",
                    "Credit, market and operational risk with regulatory reporting, run on PD/LGD, fraud loss rate and AML alert-to-SAR conversion.",
                    [["AML Investigator", "Alert prioritization and case narrative drafting."], ["Lakehouse//RT", "Fraud scores at authorization latency."]],
                    sub=[["Chief Risk Officer", "credit, market and operational risk appetite and the loss rate across the bank."], ["Head of Financial Crime", "AML alert quality, SAR conversion and sanctions screening coverage."], ["Head of Fraud", "real-time fraud loss, false-positive rate and dispute volumes."]],
                    ucs=["Real-Time Fraud", "AML Transaction Monitoring", "Operational Loss", "Credit Early Warning"]),
                biz("Treasury & ALM", "AI/BI",
                    "Funding, liquidity buffers and hedge effectiveness, measured on LCR, NSFR and interest-rate gap under stress across the balance sheet.",
                    [["ALM Dashboard", "Gap and duration under rate scenarios."], ["AI/BI", "LCR and NSFR on certified regulatory views."]],
                    sub=[["Group Treasurer", "funding, liquidity buffers and the cost of funds across the balance sheet."], ["ALM Manager", "interest-rate gap, duration and hedge effectiveness under rate scenarios."], ["Liquidity Risk Lead", "LCR, NSFR and intraday liquidity under stress."]],
                    ucs=["Liquidity Forecasting", "Regulatory Reporting"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land core-banking postings, card-network authorizations, wire messages and market-data feeds; own Bronze to Silver and the pager when risk tables stall.",
                    [["Lakeflow Connect", "Managed connectors for core, cards and credit-bureau sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on posting and authorization feeds."], ["Lakewatch", "Freshness on the exposure and liquidity tables risk reads at open."]],
                    sub=[["Ingestion Engineers", "core-banking postings, card authorizations and wire messages landed on time."], ["Pipeline Engineers", "Bronze-to-Silver conforming and expectations on posting and auth feeds."], ["Platform Reliability", "freshness of the exposure and liquidity tables risk reads at open."]],
                    ucs=["Real-Time Fraud", "Regulatory Reporting", "Open Banking Analytics"]),
                biz("Data Scientists", "MLflow",
                    "PD/LGD credit-risk, AML transaction-monitoring, card-fraud and next-best-action models, and whether they still hold through a rate cycle.",
                    [["Feature Store", "Customer and transaction features read identically in training and serving."], ["MLflow", "Every PD and fraud model tracked for audit and reproduction."], ["Model Serving", "Fraud and PD models scored in the authorization path."]],
                    sub=[["Credit Risk Modelers", "PD, LGD and early-warning models that hold through a rate cycle."], ["Financial Crime DS", "AML and card-fraud models and keeping false positives low."], ["Marketing DS", "propensity, churn and next-best-action models on the retail book."]],
                    ucs=["Credit Early Warning", "Real-Time Fraud", "AML Transaction Monitoring", "Next-Best-Product"]),
                biz("App Developers", "Apps",
                    "Ship the limit, case-management, RM workbench and AML investigator apps risk and RMs work in, hosted next to governed customer data.",
                    [["Apps", "Risk and RM screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for limit and case-management state."], ["Agent Bricks", "Agents that draft case narratives and limit changes against governed tools."]],
                    sub=[["Full-Stack Engineers", "the limit, case-management and RM workbench screens bankers work in."], ["Agent Developers", "agents that draft case narratives and limit changes on governed tools."], ["Integration Engineers", "writeback of blocks, limits and offers into core and channels."]],
                    ucs=["AML Transaction Monitoring", "Credit Early Warning", "Collections Optimization"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Finance and risk dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for liquidity and exposure questions."),
                    tile("Notebooks & IDEs", "notebook", "Model development notebooks on governed customer data."),
                ]},
                {"box": "Partners & Networks", "ic": "partner", "tiles": [
                    tile("Card Network Files", "api", "Clearing and settlement files to Visa and Mastercard.", "visa"),
                    tile("Open Banking APIs", "api", "Account information and payment initiation to TPPs.", "tink"),
                    tile("Correspondent Banking", "globe", "SWIFT payment routing to correspondent banks.", "swift"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Limit Updates", "gauge", "Credit limits adjusted in core from early warning triggers."),
                    tile("Fraud Block Rules", "gavel", "Card blocks propagated to authorization switches.", "fico"),
                    tile("CRM Next-Best-Action", "custlake", "Offers pushed to digital channels from governed models.", "sf-fsc"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Basel III Returns", "gavel", "RWA and capital returns filed from contracted Gold tables.", "axiomsl"),
                    tile("FinCEN SAR Filing", "share", "Suspicious activity reports assembled from AML cases.", "actimize"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Customer and exposure products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Partners and regulators via governed sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Branch Performance", "Household P&L", "chart", "Deposit, loan and fee profitability by branch and relationship manager."),
             app("RM Workbench", "Commercial CRM", "custlake", "Exposure, covenant status and cross-sell pipeline on governed relationship data."),
             app("AML Investigator", "Case prioritization", "gavel", "Alerts ranked and narratives drafted against transaction graphs."),
             app("ALM Dashboard", "Liquidity gaps", "gauge", "Rate and liquidity scenarios with hedge recommendations.")],
            [uc("Real-Time Fraud", "Payments", "gavel", "Authorization decisions scored before funds leave the account.",
                problem="A stolen card or account is drained in the seconds between swipe and settlement, and overnight batch fraud checks only tell you how much you lost after the money is gone.",
                who="Risk & Compliance",
                how="Authorization messages land in Lakehouse//RT, fraud models in Model Serving score transaction features within the authorization window, and a decline returns before funds leave the account.",
                comps=["Visa DPS / Auth", "Lakehouse//RT", "Model Serving", "Feature Store", "MLflow"],
                stories=[["Coinbase scales real-time fraud detection on Databricks", "https://www.databricks.com/customers/coinbase/lakeflow"], ["Maya cuts fraud losses by up to 98%", "https://www.databricks.com/customers/maya"]]),
             uc("AML Transaction Monitoring", "Compliance", "gavel", "Suspicious patterns surfaced across channels and entities.",
                problem="Money-laundering signals are scattered across accounts, channels and entities, and rules-only monitoring buries analysts under alerts that are mostly false positives while real networks slip through.",
                who="Risk & Compliance",
                how="Transactions and KYC land under Unity Catalog, Model Serving scores alerts, and Agent Bricks agents build case files and draft SAR narratives in the AML Investigator for human sign-off.",
                comps=["AML Investigator", "NICE Actimize", "Agent Bricks", "Unity Catalog", "Model Serving"],
                stories=[["Modern BSA/AML compliance on Databricks", "https://www.databricks.com/blog/modern-bsaaml-compliance-databricks"]]),
             uc("Credit Early Warning", "Risk", "chart", "Commercial deterioration flagged before covenant breach.",
                problem="Commercial borrowers deteriorate months before a covenant breach, but early signals sit in separate risk, transaction and market systems, so managers see trouble only once it is on the books.",
                who="Commercial Banking",
                how="Exposure, rating and transaction features are engineered in Feature Store and scored by early-warning models in Model Serving, with runs tracked in MLflow and alerts surfaced in the RM Workbench.",
                comps=["RM Workbench", "Moody's RiskCalc", "Model Serving", "MLflow", "Feature Store"],
                stories=[["Techcombank runs 100+ credit risk models on Databricks", "https://www.databricks.com/customers/techcombank"], ["Capital One powers faster credit decisions", "https://www.databricks.com/customers/capital-one"]]),
             uc("Customer 360", "Retail", "custlake", "Household view across deposits, loans, cards and digital.",
                problem="A household's deposits, loans, cards and digital activity live in separate core and channel systems, so nobody sees the whole relationship and the same customer looks like a stranger in every silo.",
                who="Retail Banking",
                how="Core, card and channel feeds are resolved into golden customer and account records on Delta Lake under Unity Catalog, and the household view is served to bankers through AI/BI and Salesforce FSC.",
                comps=["Salesforce FSC", "Temenos Transact", "Unity Catalog", "Delta Lake", "AI/BI"],
                stories=[["HSBC scales customer analytics and network science", "https://www.databricks.com/customers/hsbc"], ["Siam Commercial Bank builds a single customer view", "https://www.databricks.com/customers/siam-commercial-bank"]]),
             uc("Next-Best-Product", "Marketing", "market", "Offers ranked by propensity and profitability.",
                problem="Offers go out on product-centric campaign calendars rather than what a household needs next, so conversion is low, the wrong customers are targeted and profitable cross-sell is left on the table.",
                who="Retail Banking",
                how="Propensity and profitability features in Feature Store feed ranking models in Model Serving, and next-best offers surface in Branch Performance and are pushed to Salesforce FSC.",
                comps=["Branch Performance", "Salesforce FSC", "Model Serving", "Feature Store", "AI Functions"],
                stories=[["Discovery Bank's next-best-action lifts engagement 40%", "https://www.databricks.com/customers/discovery-bank"], ["Banco Bradesco doubles conversion with next best action", "https://www.databricks.com/customers/banco-bradesco/lakeflow-declarative-pipelines"]]),
             uc("Liquidity Forecasting", "Treasury", "gauge", "Cash and collateral projections under stress scenarios.",
                problem="Treasury projects cash, collateral and deposit runoff from monthly snapshots and spreadsheets, so buffers are sized on stale positions and a funding squeeze shows up too late to hedge.",
                who="Treasury & ALM",
                how="Deposit, market and position feeds land on Delta Lake, runoff models in Model Serving project buffers under stress, and gap and LCR scenarios surface in the ALM Dashboard and AI/BI.",
                comps=["ALM Dashboard", "FIS Ambit Focus", "Model Serving", "AI/BI", "Delta Lake"],
                stories=[["How Databricks helps banks navigate interest rate changes", "https://www.databricks.com/blog/how-databricks-helps-banks-navigate-interest-rate-changes"]]),
             uc("Regulatory Reporting", "Finance", "erp", "Basel, CCAR and local returns from one governed model.",
                problem="Basel, CCAR and local returns are stitched from dozens of risk and finance systems each cycle, so reconciliation is manual, lineage is hard to prove and one restatement can trigger a finding.",
                who="Chief Credit Officer & CFO",
                how="Risk and finance data conform into governed Gold tables under Unity Catalog with full lineage, and returns are assembled for AxiomSL Reg Reporting and published as Data Products.",
                comps=["AxiomSL Reg Reporting", "Unity Catalog", "Delta Lake", "AI/BI", "Data Products"],
                stories=[["BCBS 239 compliance in the age of AI (ABN AMRO)", "https://www.databricks.com/blog/bcbs-239-compliance-age-ai-turning-regulatory-burden-strategic-advantage"]]),
             uc("Open Banking Analytics", "Digital", "api", "Consent, aggregation and payment initiation insights.",
                problem="Consent, aggregation and payment-initiation traffic from third parties arrives in fragmented API logs, so the bank cannot see how open-banking journeys perform or which partners drive value.",
                who="Retail Banking",
                how="Aggregation and consent feeds land through Lakeflow onto Delta Lake, are conformed under governance, and partner, consent and payment-initiation metrics are analyzed in AI/BI.",
                comps=["Plaid Aggregation", "Tink Open Banking", "Lakeflow", "Delta Lake", "AI/BI"],
                stories=[]),
             uc("Collections Optimization", "Lending", "people", "Treatment strategies ranked by recovery probability.",
                problem="Delinquent accounts get the same generic dunning regardless of who will actually pay, so recoveries are low, good customers are pushed away and collections cost more than they return.",
                who="Retail Banking",
                how="Servicing and behavior features in Feature Store feed recovery-probability models in Model Serving tracked in MLflow, so each account gets the treatment most likely to cure.",
                comps=["Finastra Fusion", "Model Serving", "Feature Store", "MLflow", "AI Functions"],
                stories=[["Ophelos optimizes debt collection on Databricks", "https://www.databricks.com/customers/ophelos"], ["Oakbrook builds a collections decision engine", "https://www.databricks.com/customers/oakbrook"]]),
             uc("Operational Loss", "Risk", "gavel", "Loss events captured and capitalized for AMA frameworks.",
                problem="Operational loss events are logged in scattered spreadsheets and case tools, so capital under advanced measurement is modeled on incomplete history and control failures recur unseen.",
                who="Risk & Compliance",
                how="Loss events and near-misses are captured into governed Delta Lake tables under Unity Catalog, aggregated for AMA capital, and analyzed in AI/BI and published as Data Products.",
                comps=["Unity Catalog", "Delta Lake", "AxiomSL Reg Reporting", "AI/BI", "Data Products"],
                stories=[])],
        ),
        "sources": {
            "temenos": {"t": "Temenos Transact", "u": "https://www.temenos.com/products/transact/"},
            "fis-profile": {"t": "FIS Profile", "u": "https://www.fisglobal.com/products/core-banking"},
            "finastra": {"t": "Finastra Fusion", "u": "https://www.finastra.com/solutions/lending"},
            "visa": {"t": "Visa", "u": "https://www.visa.com/"},
            "mastercard": {"t": "Mastercard", "u": "https://www.mastercard.com/"},
            "swift": {"t": "SWIFT", "u": "https://www.swift.com/"},
            "temenos-infinity": {"t": "Temenos Infinity", "u": "https://www.temenos.com/products/infinity/"},
            "sf-fsc": {"t": "Salesforce Financial Services Cloud", "u": "https://www.salesforce.com/financial-services/"},
            "actimize": {"t": "NICE Actimize", "u": "https://www.niceactimize.com/"},
            "moodys": {"t": "Moody's Analytics", "u": "https://www.moodys.com/"},
            "fis-alm": {"t": "FIS ALM", "u": "https://www.fisglobal.com/products/treasury-and-risk"},
            "axiomsl": {"t": "AxiomSL", "u": "https://www.axiomsl.com/"},
            "plaid": {"t": "Plaid", "u": "https://plaid.com/"},
            "tink": {"t": "Tink", "u": "https://tink.com/"},
            "fico": {"t": "FICO", "u": "https://www.fico.com/"},
            "lexisnexis": {"t": "LexisNexis Risk Solutions", "u": "https://risk.lexisnexis.com/"},
            "experian": {"t": "Experian", "u": "https://www.experian.com/business/"},
        },
    },
}
