import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_CLINICAL_TRIALS = {
    'clinical_trials': {
        "label": "Clinical Trials",
        "blurb": "Protocol design, site operations, patient recruitment, safety monitoring, and regulatory submissions across CROs and sponsors.",
        "medallion": medallion(
            "Raw eCRF and lab feeds",
            "EDC entries, lab results, imaging reads and safety narratives landed exactly as received for audit trail replay.",
            "Conformed subjects and visits",
            "Subjects, visits, sites and adverse events resolved across CTMS, EDC and safety systems.",
            "Enrollment, safety signals",
            "Contracted products clinical ops and medical run on: enrollment velocity, protocol deviation rate and SAE incidence.",
        ),
        "rails": {
            "src": [
                {"box": "EDC & eSource", "ic": "db", "tiles": [
                    tile("Medidata Rave EDC", "db", "Case report forms, queries and audit trails by subject.", "medidata-rave",
                         cat="Electronic Data Capture (EDC)",
                         what="Captures case report form data, edit-check queries and a per-subject audit trail across sites, the operational system of record for clinical data collection.",
                         users="Clinical Data Management, CRAs / monitors and site coordinators.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-10 GB/day per study", "Nightly extracts + intraday query cycles"),
                             stream=flow(["semi-structured"], "tens of form events/sec at peak", "Continuous CDC on eCRF saves"))),
                    tile("Veeva Vault CDMS", "db", "Unified clinical data management and remote monitoring.", "veeva-cdms",
                         cat="Clinical Data Management System (CDMS)",
                         what="Unifies data capture, cleaning and remote monitoring on one clinical data management platform so data managers work review and coding against a single subject record.",
                         users="Clinical Data Management, Clinical Programmers and central monitors.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-8 GB/day per study", "Nightly batch + query refreshes"))),
                    tile("Oracle Clinical One", "db", "Unified platform for randomization and data capture.", "oracle-clinical",
                         cat="Clinical Data Management & Randomization Platform",
                         what="Combines electronic data capture with randomization and trial supply management on one platform, so data capture and drug assignment share a subject model.",
                         users="Clinical Data Management, Clinical Supply and Biostatistics.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-6 GB/day per study", "Nightly batch extracts"),
                             stream=flow(["semi-structured"], "randomization events on demand", "Continuous at randomization"))),
                ]},
                {"box": "CTMS & Sites", "ic": "sheet", "tiles": [
                    tile("Veeva CTMS", "sheet", "Site feasibility, activation and enrollment tracking.", "veeva-ctms",
                         cat="Clinical Trial Management System (CTMS)",
                         what="Tracks site feasibility, activation milestones, monitoring visits and enrollment against plan across the study's sites and countries.",
                         users="Clinical Operations, Clinical Trial Managers and Site Management.",
                         data_out=data_out(
                             batch=flow(["structured"], "0.5-3 GB/day", "Nightly sync + intraday updates"))),
                    tile("Medidata CTMS", "people", "Monitoring visits, action items and site payments.", "medidata-ctms",
                         cat="Clinical Trial Management System (CTMS)",
                         what="Manages monitoring visit reports, action items and visit-based site payments, tying operational site activity to enrollment and quality.",
                         users="Clinical Operations, CRAs / monitors and Site payments teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "0.5-2 GB/day", "Nightly sync"))),
                    tile("Signant SmartSupplies", "product", "IRT, drug supply and depot inventory.", "signant",
                         cat="Interactive Response Technology (IRT/RTSM)",
                         what="Randomizes subjects and manages drug supply, depot inventory and resupply triggers so the right kit reaches the right site as enrollment moves.",
                         users="Clinical Supply, Clinical Operations and Depot / logistics teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "0.2-1 GB/day", "Nightly batch"),
                             stream=flow(["semi-structured"], "randomization + dispensing events", "Continuous at dosing"))),
                ]},
                {"box": "Safety & PV", "ic": "gavel", "tiles": [
                    tile("Argus Safety", "gavel", "SAE processing, MedDRA coding and expedited reporting.", "argus",
                         cat="Pharmacovigilance / Safety System",
                         what="Processes individual case safety reports, codes events to MedDRA and drives expedited (E2B) regulatory reporting for adverse events.",
                         users="Pharmacovigilance, Drug Safety Physicians and Medical Monitors.",
                         data_out=data_out(
                             batch=flow(["structured", "unstructured"], "0.5-2 GB/day cases + narratives", "Hourly / daily case intake"))),
                    tile("Veeva Vault Safety", "gavel", "Case intake, narrative generation and submissions.", "veeva-safety",
                         cat="Pharmacovigilance / Safety System",
                         what="Handles safety case intake, narrative generation and regulatory submissions on a cloud safety platform tied to the trial's adverse-event record.",
                         users="Pharmacovigilance, Drug Safety Physicians and Regulatory reporting.",
                         data_out=data_out(
                             batch=flow(["structured", "unstructured"], "0.5-2 GB/day", "Hourly / daily"))),
                    tile("WHO Drug Dictionary", "product", "Medication coding for concomitant therapies.", "who-dd",
                         cat="Drug Dictionary / Medical Coding Reference",
                         what="Reference dictionary used to code concomitant medications to a standard so drug exposure and interactions are analysable across studies.",
                         users="Clinical Data Management, Medical coders and Pharmacovigilance.",
                         data_out=data_out(
                             batch=flow(["structured"], "MBs (reference dictionary)", "Quarterly version releases"))),
                ]},
                {"box": "Labs & Imaging", "ic": "stream", "tiles": [
                    tile("LabCorp Central Lab", "stream", "Central lab results with reference ranges by visit.", "labcorp",
                         cat="Central Laboratory",
                         what="Runs the trial's central laboratory testing and returns results with reference ranges and flags per subject visit for safety and efficacy review.",
                         users="Clinical Data Management, Medical Monitors and Biostatistics.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/day", "Daily result transfers"))),
                    tile("Medidata Imaging", "iot", "DICOM reads and lesion measurements for oncology.", "medidata-imaging",
                         cat="Medical Imaging / Imaging Core Lab",
                         what="Manages DICOM image acquisition, blinded independent reads and lesion measurements (e.g. RECIST) for imaging endpoints in oncology trials.",
                         users="Imaging core lab reviewers, Medical Monitors and Biostatistics.",
                         data_out=data_out(
                             batch=flow(["unstructured", "structured"], "10-100 GB/day (DICOM)", "Per-visit uploads + read cycles"))),
                    tile("Clario eCOA", "apps", "Patient-reported outcomes and eDiary entries.", "ert-ecoa",
                         cat="Electronic Clinical Outcome Assessment (eCOA)",
                         what="Collects patient-reported outcomes, clinician assessments and eDiary entries on provisioned devices and apps for endpoint measurement.",
                         users="Clinical Operations, Biostatistics and Site coordinators.",
                         data_out=data_out(
                             batch=flow(["structured"], "0.2-1 GB/day", "Daily uploads"),
                             stream=flow(["semi-structured"], "diary entries as completed", "Continuous device sync"))),
                ]},
                {"box": "Regulatory", "ic": "share", "tiles": [
                    tile("Veeva RIM", "share", "Submissions, correspondence and health authority commitments.", "veeva-rim",
                         cat="Regulatory Information Management (RIM)",
                         what="Tracks regulatory submissions, health-authority correspondence and commitments so the submission plan and its content stay aligned across regions.",
                         users="Regulatory Affairs, Regulatory Operations and Data Management.",
                         data_out=data_out(
                             batch=flow(["structured", "unstructured"], "0.5-2 GB/day", "Nightly + submission milestones"))),
                    tile("CDISC Standards", "api", "SDTM and ADaM datasets for regulatory packages.", "cdisc",
                         cat="Clinical Data Standards (CDISC)",
                         what="Defines the SDTM and ADaM dataset standards clinical data is mapped to for a compliant, traceable regulatory submission package.",
                         users="Standards & CDISC, Clinical Programmers and Biostatistics.",
                         data_out=data_out(
                             batch=flow(["structured"], "MBs (standards + controlled terminology)", "Periodic standard releases"))),
                ]},
                fed_group("Legacy SDTM Mart", "Historical submission datasets queried in place under Unity Catalog.",
                          cat="Clinical Data Warehouse / Submission Data Mart",
                          what="Historical SDTM and ADaM submission datasets kept in the incumbent warehouse and queried in place through federation rather than copied.",
                          users="Biostatistics, Statistical Programmers and Regulatory Affairs.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical datasets", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("ClinicalTrials.gov", "api", "Public trial registry metadata for competitive intelligence.", "clinicaltrials-gov",
                     cat="Public Clinical Trial Registry",
                     what="Public registry of trial protocols, sites and status used for competitive intelligence and feasibility benchmarking.",
                     users="Clinical Operations, Feasibility and Portfolio teams.",
                     data_out=data_out(
                         batch=flow(["semi-structured"], "100s of MB (registry extracts)", "Weekly / on-demand pulls"))),
                tile("IQVIA Real World", "partner", "External control arms and epidemiology for protocol design.", "iqvia-rwe",
                     cat="Real-World Data / Evidence Provider",
                     what="Supplies real-world claims and clinical data for external control arms, epidemiology and protocol design and site targeting.",
                     users="Biostatistics, Epidemiology and Feasibility teams.",
                     data_out=data_out(
                         batch=flow(["structured"], "10-100 GB per cohort", "Periodic cohort refreshes"))),
                tile("Flatiron Oncology EHR", "custlake", "De-identified oncology records for external comparators.", "flatiron",
                     cat="Real-World Oncology Data (EHR-derived)",
                     what="De-identified, curated oncology EHR data used for external comparator arms and real-world outcomes in cancer trials.",
                     users="Biostatistics, Epidemiology and Medical & Safety.",
                     data_out=data_out(
                         batch=flow(["structured", "unstructured"], "10-50 GB per cohort", "Periodic curated refreshes"))),
            ]),
            "ppl": ppl2([
                biz("Chief Medical & Clinical Ops", "Genie One",
                    "The CMO on pipeline milestones and study risk; the VP Clinical on enrollment velocity and budget burn against lock timelines.",
                    [["Genie One", "Ask how enrollment is tracking to plan by country."], ["AI/BI", "Milestone and spend on certified Metric Views."], ["Unity Catalog", "One subject definition across EDC and safety."]],
                    sub=[
                        ["Chief Medical Officer", "pipeline milestones, study risk and the go/no-go calls on programs in flight."],
                        ["VP Clinical Operations", "enrollment velocity and budget burn against database-lock timelines."],
                        ["Head of Portfolio", "study prioritisation and the trade between speed, cost and quality."],
                    ],
                    ucs=["Enrollment Forecasting", "Site Selection", "Patient Recruitment"]),
                biz("Clinical Operations", "Lakehouse//RT",
                    "Site activation, monitoring and enrollment rescue, run on enrollment velocity, screen-failure rate and query aging by site.",
                    [["Enrollment Cockpit", "Site velocity and screen-failure drivers."], ["Lakehouse//RT", "Query aging at operational latency."]],
                    sub=[
                        ["Clinical Trial Manager", "site activation, enrollment rescue and the day-to-day study timeline."],
                        ["CRA / Monitor", "source data verification, query aging and protocol compliance by site."],
                        ["Site Management", "site feasibility, payments and screen-failure drivers."],
                    ],
                    ucs=["Enrollment Forecasting", "Site Selection", "Remote Monitoring", "Protocol Deviation Mgmt"]),
                biz("Data Management", "AI/BI",
                    "Database lock readiness, query resolution and SDTM conversion, tracked on open-query aging, data completeness and lock cycle time.",
                    [["Lock Readiness", "Critical variables and open queries by site."], ["AI/BI", "Data quality metrics on governed EDC."]],
                    sub=[
                        ["Lead Data Manager", "database-lock readiness, open-query aging and data completeness."],
                        ["Clinical Programmer", "edit checks, SDTM conversion and traceable mappings."],
                        ["Standards & CDISC", "SDTM and ADaM conformance for the submission package."],
                    ],
                    ucs=["SDTM Automation", "Remote Monitoring", "Regulatory Submissions"]),
                biz("Medical & Safety", "Model Serving",
                    "DSMB reviews, signal detection and medical monitoring, judged on SAE incidence, time-to-signal and expedited-report timeliness.",
                    [["Safety Signal Hub", "Emerging AE patterns across trials."], ["Model Serving", "Signal detection models on adverse events."]],
                    sub=[
                        ["Medical Monitor", "emerging safety signals and the DSMB review of the risk picture."],
                        ["Pharmacovigilance", "SAE case processing, expedited reporting and signal timeliness."],
                        ["Drug Safety Physician", "causality, labeling impact and the benefit-risk narrative."],
                    ],
                    ucs=["Safety Signal Detection", "Remote Monitoring", "Protocol Deviation Mgmt"]),
                biz("Biostatistics", "Apps",
                    "Interim analyses, adaptive designs and TLF production, measured on interim-look turnaround, TLF cycle time and protocol-deviation rate.",
                    [["Interim Analysis Workbench", "Controlled access to unblinded results."], ["Apps", "Statistical review apps on governed ADaM."]],
                    sub=[
                        ["Study Biostatistician", "interim looks, adaptive designs and the analysis plan."],
                        ["Statistical Programmer", "TLF production and reproducible ADaM-driven outputs."],
                        ["Quantitative Sciences", "modeling, sample-size re-estimation and design simulation."],
                    ],
                    ucs=["Adaptive Trial Design", "SDTM Automation", "Safety Signal Detection"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land EDC eCRF entries, central-lab results, imaging reads and safety narratives; own Bronze to Silver and the pager when the enrollment tables stall.",
                    [["Lakeflow Connect", "Managed connectors for EDC, CTMS and safety sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on lab and eCRF feeds."], ["Lakewatch", "Freshness on the enrollment and query tables study teams read daily."]],
                    sub=[
                        ["Ingestion Engineer", "landing EDC, central-lab, imaging and safety feeds into Bronze."],
                        ["Pipeline Owner", "Bronze-to-Silver conformance and the enrollment-table pager."],
                        ["Platform & Governance", "Unity Catalog permissions and the audit trail across sources."],
                    ],
                    ucs=["Enrollment Forecasting", "SDTM Automation", "Remote Monitoring"]),
                biz("Data Scientists", "MLflow",
                    "Enrollment-forecast, risk-based-monitoring and safety signal-detection models, and whether they still hold as sites and protocols amend.",
                    [["Feature Store", "Subject and site features read identically in training and serving."], ["MLflow", "Every enrollment and signal model tracked for audit and reproduction."], ["Model Serving", "Signal and monitoring models scored in the review path."]],
                    sub=[
                        ["Enrollment Modeler", "site and country enrollment forecasts as protocols amend."],
                        ["Safety Signal Scientist", "disproportionality and clustering on adverse events."],
                        ["RBM Analyst", "risk-based monitoring triggers from centralized review."],
                    ],
                    ucs=["Enrollment Forecasting", "Safety Signal Detection", "Remote Monitoring"]),
                biz("App Developers", "Apps",
                    "Ship the enrollment cockpit, lock readiness, safety signal hub and interim analysis apps clinical ops and biostats work in, next to governed trial data.",
                    [["Apps", "Study screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for monitoring and review state."], ["Agent Bricks", "Agents that draft narratives and query resolutions against governed tools."]],
                    sub=[
                        ["Clinical App Engineer", "the enrollment cockpit and lock-readiness screens ops work in."],
                        ["Safety App Engineer", "the safety signal hub and the case-review workflow."],
                        ["Agent Developer", "agents drafting narratives and query resolutions on governed tools."],
                    ],
                    ucs=["Enrollment Forecasting", "Safety Signal Detection", "Adaptive Trial Design"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Spotfire", "chart", "Enrollment and safety dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for enrollment status in study teams."),
                    tile("Notebooks & IDEs", "notebook", "Biostat notebooks on governed SDTM and ADaM."),
                ]},
                {"box": "Sites & CROs", "ic": "partner", "tiles": [
                    tile("Site Payment Portal", "api", "Visit-based payments released after data verification.", "medidata-ctms"),
                    tile("eConsent Platform", "apps", "Consent versions and re-consent pushed to sites.", "veeva-cdms"),
                    tile("IRT Supply Updates", "product", "Depot shipments triggered by enrollment forecasts.", "signant"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Query Auto-Resolution", "db", "Edit checks resolved back to EDC with audit trail.", "medidata-rave"),
                    tile("Safety Expedited Reports", "gavel", "E2B submissions generated from confirmed cases.", "argus"),
                    tile("Enrollment Caps", "gauge", "Country caps enforced in IRT when limits reached.", "signant"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("FDA eCTD Submissions", "share", "Regulatory packages assembled from governed datasets.", "veeva-rim"),
                    tile("DSUR/PSUR Production", "gavel", "Periodic safety reports from pooled safety data.", "veeva-safety"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Trial and safety products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Partners and regulators via governed sharing."),
                ]},
            ], genie_spaces=[
                genie("Enrollment & Site Performance", "Ask how enrollment is tracking to plan and which sites are at risk, in plain language.",
                      feeds=["Veeva CTMS", "Medidata Rave EDC", "Conformed subjects and visits", "Enrollment, safety signals"],
                      teams=["Chief Medical & Clinical Ops", "Clinical Operations", "Clinical Trial Manager"],
                      questions=[
                          "How is enrollment tracking to plan by country and site this month?",
                          "Which sites are under-enrolling and at risk of closure?",
                          "What is the screen-failure rate by site and protocol?",
                          "How long is site activation taking from selection to first patient in?",
                          "Which countries are driving the current enrollment shortfall?"]),
                genie("Safety & Pharmacovigilance", "Explore adverse events, emerging signals and expedited-reporting timeliness across trials.",
                      feeds=["Argus Safety", "Veeva Vault Safety", "WHO Drug Dictionary", "Enrollment, safety signals"],
                      teams=["Medical & Safety", "Pharmacovigilance", "Drug Safety Physician"],
                      questions=[
                          "What is the SAE incidence by product and treatment arm this quarter?",
                          "Which adverse events are showing an emerging signal across trials?",
                          "How many expedited reports are approaching their reporting deadline?",
                          "What is our time-to-signal for newly reported serious events?",
                          "Which concomitant medications co-occur most with reported events?"]),
                genie("Data Management & Quality", "Answer query-aging, completeness and lock-readiness questions across EDC and labs.",
                      feeds=["Medidata Rave EDC", "LabCorp Central Lab", "CDISC Standards", "Conformed subjects and visits"],
                      teams=["Data Management", "Lead Data Manager", "Standards & CDISC"],
                      questions=[
                          "Which sites have the oldest open queries right now?",
                          "What is data completeness on critical variables by study?",
                          "How many visits are missing or overdue by site?",
                          "Where does SDTM conformance fail validation checks?",
                          "How far are we from database-lock readiness this week?"]),
                genie("Feasibility & Site Selection", "Rank sites and geographies for the next protocol from history, registries and real-world data.",
                      feeds=["Veeva CTMS", "ClinicalTrials.gov", "IQVIA Real World", "Flatiron Oncology EHR"],
                      teams=["Clinical Operations", "Chief Medical & Clinical Ops", "Site Management"],
                      questions=[
                          "Which sites historically enroll fastest for this indication?",
                          "What is each candidate site's past data-quality track record?",
                          "How many competing trials are recruiting the same population?",
                          "What patient volume does real-world data suggest per region?",
                          "Which sites combine high enrollment with low screen-failure rates?"]),
            ], dashboards=[
                dashboard("Enrollment & Milestones", "Enrollment velocity, screen-failure and activation against the study plan on certified Metric Views.",
                          kpis=["Enrollment velocity", "Screen-failure rate", "Site activation cycle time", "Randomization rate", "Dropout rate"],
                          teams=["Chief Medical & Clinical Ops", "Clinical Operations", "Clinical Trial Manager"]),
                dashboard("Safety Surveillance", "SAE incidence, signal timeliness and expedited-report throughput across trials.",
                          kpis=["SAE incidence", "Time-to-signal", "Expedited-report timeliness", "AE rate", "Case backlog"],
                          teams=["Medical & Safety", "Pharmacovigilance", "Drug Safety Physician"]),
                dashboard("Data Quality & Lock Readiness", "Open-query aging, completeness and SDTM conformance on the path to database lock.",
                          kpis=["Open-query aging", "Data completeness", "Lock cycle time", "SDTM conformance", "Critical-variable coverage"],
                          teams=["Data Management", "Biostatistics", "Standards & CDISC"]),
                dashboard("Site Feasibility & Selection", "Historical site performance and data quality for feasibility and selection.",
                          kpis=["Historical enrollment rate", "Data-quality score", "Startup cycle time", "Screen-failure rate", "Cost per patient"],
                          teams=["Clinical Operations", "Chief Medical & Clinical Ops", "Site Management"]),
            ]),
        },
        "top": top_band(
            [app("Enrollment Cockpit", "Site velocity", "gauge", "Screening, randomization and dropout rates by site and country against plan."),
             app("Lock Readiness", "Database lock", "db", "Open queries, missing visits and critical variables blocking lock."),
             app("Safety Signal Hub", "Pharmacovigilance", "gavel", "Emerging adverse event patterns ranked for medical review."),
             app("Interim Analysis Workbench", "Unblinded access", "chart", "Controlled interim looks with full audit trail.")],
            [uc("Enrollment Forecasting", "Operations", "people", "Site and country enrollment predicted against activation curves.",
                problem="Enrollment velocity data lands on a monthly cycle, so a site that stalls is only spotted weeks later, after the slip has already pushed the read-out and the whole study timeline.",
                who="Chief Medical & Clinical Ops",
                how="CTMS and EDC feeds land through Lakeflow, and enrollment-forecast models tracked in MLflow score site and country curves into the Enrollment Cockpit against the activation plan.",
                comps=["Enrollment Cockpit", "Model Serving", "MLflow", "Feature Store", "Veeva CTMS"],
                stories=[
                    ["Clinical operations intelligence belongs on the Lakehouse", "https://www.databricks.com/blog/clinical-operations-intelligence-belongs-lakehouse"],
                    ["Clinical trials run longer than they have to. That's a patient problem.", "https://www.databricks.com/blog/clinical-trials-run-longer-they-have-thats-patient-problem"],
                ]),
             uc("Site Selection", "Feasibility", "globe", "Sites ranked by historical enrollment and data quality.",
                problem="Sites are picked from relationships and last trial's memory, so poor enrollers are chosen again and again while the feasibility signal sits unused in CTMS, registries and RWE.",
                who="Clinical Operations",
                how="Historical CTMS performance is joined to ClinicalTrials.gov and IQVIA Real World under Unity Catalog, and sites are ranked by enrollment and data-quality models scored in Model Serving.",
                comps=["IQVIA Real World", "ClinicalTrials.gov", "Model Serving", "AI/BI", "Unity Catalog"],
                stories=[
                    ["Clinical operations intelligence belongs on the Lakehouse", "https://www.databricks.com/blog/clinical-operations-intelligence-belongs-lakehouse"],
                ]),
             uc("Remote Monitoring", "Quality", "observ", "Risk-based monitoring triggers from centralized data review.",
                problem="On-site monitoring visits are periodic and expensive, so data issues and safety risks at a site surface only at the next visit, weeks after the signal first appeared in the data.",
                who="Clinical Operations",
                how="Centralized EDC and lab data land on Lakehouse//RT, and risk-based monitoring models in Model Serving raise site and query triggers reviewed in AI/BI under Unity Catalog.",
                comps=["Lakehouse//RT", "AI/BI", "Model Serving", "Medidata Rave EDC", "Unity Catalog"],
                stories=[
                    ["Clinical trials run longer than they have to. That's a patient problem.", "https://www.databricks.com/blog/clinical-trials-run-longer-they-have-thats-patient-problem"],
                ]),
             uc("Safety Signal Detection", "PV", "gavel", "Disproportionality and temporal clustering on adverse events.",
                problem="Adverse events arrive as structured cases and unstructured narratives across trials, so a real safety signal can hide in the noise until it is late enough to force a labeling change.",
                who="Medical & Safety",
                how="Case and narrative data feed disproportionality and clustering models tracked in MLflow and scored in Model Serving, surfacing ranked signals in the Safety Signal Hub for medical review.",
                comps=["Safety Signal Hub", "Model Serving", "MLflow", "Argus Safety", "Feature Store"],
                stories=[
                    ["Improving drug safety with adverse event detection using NLP", "https://www.databricks.com/blog/2022/01/17/improving-drug-safety-with-adverse-event-detection-using-nlp.html"],
                ]),
             uc("Protocol Deviation Mgmt", "Compliance", "gavel", "Deviations trended and remediated before inspection findings.",
                problem="Protocol deviations are reviewed in quarterly site assessments, so a pattern of the same avoidable deviation runs for months before anyone catches it, and inspection findings follow.",
                who="Clinical Operations",
                how="Deviation data from EDC is conformed under Unity Catalog and trended in AI/BI and Genie, with AI Functions classifying free-text so remediation starts before a finding, not after.",
                comps=["AI/BI", "Genie", "Unity Catalog", "Medidata Rave EDC", "AI Functions"],
                stories=[
                    ["Clinical trials run longer than they have to. That's a patient problem.", "https://www.databricks.com/blog/clinical-trials-run-longer-they-have-thats-patient-problem"],
                ]),
             uc("SDTM Automation", "Data Mgmt", "db", "Study data converted to SDTM with traceable mappings.",
                problem="SDTM conversion is a manual, spec-driven grind repeated per study, so mapping errors surface late, traceability is thin, and the database-lock-to-submission path is slow and fragile.",
                who="Data Management",
                how="Raw EDC data is mapped to SDTM through Lakeflow pipelines on Delta Lake, with CDISC Standards and lineage held in Unity Catalog and AI Functions drafting mappings for review.",
                comps=["CDISC Standards", "Lakeflow", "Delta Lake", "Unity Catalog", "AI Functions"],
                stories=[
                    ["Building a modern clinical trial data + AI platform", "https://www.databricks.com/blog/building-modern-clinical-trial-data-intelligence-platform"],
                ]),
             uc("Adaptive Trial Design", "Biostats", "chart", "Interim results driving sample size or arm changes.",
                problem="Interim looks need unblinded results fast and under tight access control, but the analysis data is scattered and every controlled peek is a slow, manual, audit-heavy assembly.",
                who="Biostatistics",
                how="Governed ADaM data feeds interim analyses in the Interim Analysis Workbench on Notebooks & IDEs, with MLflow and Unity Catalog holding the audit trail behind every sample-size or arm change.",
                comps=["Interim Analysis Workbench", "Notebooks & IDEs", "Unity Catalog", "AI/BI", "MLflow"],
                stories=[
                    ["Amgen modernizes analytics to speed drug development and delivery", "https://www.databricks.com/blog/2022/03/22/amgen-modernizes-analytics-with-a-unified-data-lakehouse-to-speed-drug-development-delivery.html"],
                    ["Building a modern clinical trial data + AI platform", "https://www.databricks.com/blog/building-modern-clinical-trial-data-intelligence-platform"],
                ]),
             uc("Patient Recruitment", "Digital", "custlake", "Pre-screened cohorts identified from RWE and registries.",
                problem="Roughly 80% of trials miss enrollment timelines because eligible patients are hard to find, and the EHR and registry signals that would surface them sit outside the trial systems.",
                who="Clinical Operations",
                how="De-identified EHR and registry data from Flatiron and IQVIA are conformed under Unity Catalog, and cohort models in Model Serving pre-screen eligible patients against protocol criteria.",
                comps=["Flatiron Oncology EHR", "IQVIA Real World", "Model Serving", "Unity Catalog", "AI Functions"],
                stories=[
                    ["Clinical operations intelligence belongs on the Lakehouse", "https://www.databricks.com/blog/clinical-operations-intelligence-belongs-lakehouse"],
                    ["How Regeneron is discovering new treatments with AI", "https://www.databricks.com/customers/regeneron"],
                ]),
             uc("Supply Forecasting", "IRT", "product", "Depot and site inventory against enrollment scenarios.",
                problem="Drug supply is planned against static enrollment assumptions, so depots over-stock and expire or stock out mid-study, and a supply gap can halt randomization at exactly the wrong site.",
                who="Clinical Operations",
                how="Enrollment forecasts feed supply models scored in Model Serving and tracked in MLflow, projecting depot and site inventory that drives IRT shipments from the Enrollment Cockpit.",
                comps=["Enrollment Cockpit", "Signant SmartSupplies", "Model Serving", "MLflow", "AI/BI"]),
             uc("Regulatory Submissions", "RIM", "share", "eCTD packages produced from governed clinical datasets.",
                problem="eCTD packages are assembled by hand from datasets scattered across data management, biostats and safety, so submissions are slow and every health-authority query reopens the hunt.",
                who="Data Management",
                how="Governed SDTM and ADaM products are built on Delta Lake under Unity Catalog and published to Veeva RIM and regulators as data products shared over Open Sharing with full lineage.",
                comps=["Veeva RIM", "CDISC Standards", "Unity Catalog", "Data Products", "Delta Lake"])],
        ),
        "sources": {
            "medidata-rave": {"t": "Medidata Rave EDC", "u": "https://www.medidata.com/"},
            "veeva-cdms": {"t": "Veeva Vault CDMS", "u": "https://www.veeva.com/products/vault-cdms/"},
            "oracle-clinical": {"t": "Oracle Clinical One", "u": "https://www.oracle.com/life-sciences/clinical-trials/"},
            "veeva-ctms": {"t": "Veeva CTMS", "u": "https://www.veeva.com/products/ctms/"},
            "medidata-ctms": {"t": "Medidata CTMS", "u": "https://www.medidata.com/"},
            "signant": {"t": "Signant Health", "u": "https://www.signanthealth.com/"},
            "argus": {"t": "Oracle Argus Safety", "u": "https://www.oracle.com/life-sciences/pharmacovigilance/"},
            "veeva-safety": {"t": "Veeva Vault Safety", "u": "https://www.veeva.com/products/vault-safety/"},
            "who-dd": {"t": "WHO Drug Dictionary", "u": "https://www.who-umc.org/"},
            "labcorp": {"t": "Labcorp Drug Development", "u": "https://www.labcorp.com/"},
            "medidata-imaging": {"t": "Medidata Imaging", "u": "https://www.medidata.com/"},
            "ert-ecoa": {"t": "Clario eCOA", "u": "https://clario.com/solutions/ecoa/"},
            "veeva-rim": {"t": "Veeva RIM", "u": "https://www.veeva.com/products/regulatory/"},
            "cdisc": {"t": "CDISC", "u": "https://www.cdisc.org/"},
            "clinicaltrials-gov": {"t": "ClinicalTrials.gov", "u": "https://clinicaltrials.gov/"},
            "iqvia-rwe": {"t": "IQVIA Real World Solutions", "u": "https://www.iqvia.com/solutions/real-world-evidence"},
            "flatiron": {"t": "Flatiron Health", "u": "https://flatiron.com/"},
        },
    },
}
