import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl_rail2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles instead of shared TECH_PPL."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles},
    ]


INDUSTRIES_BATCH_PAYMENTS_FINTECH = {
    'payments_fintech': {
        "label": "Payments & Fintech",
        "blurb": "Card acquiring, digital wallets, lending and banking cores: authorisation streams, fraud, KYC and merchant lifecycle across regulated payment institutions.",
        "medallion": medallion(
            "Raw auth streams",
            "Authorisation requests, settlement files, core postings, KYC decisions and merchant onboarding events, landed exactly as received so a transaction or an account opening can always be replayed as it stood.",
            "Conformed account, txn",
            "Accounts, merchants, instruments and transactions resolved into single conformed entities across core, acquirer and fraud systems, with settlement batches reconciled and device fingerprints stitched to one identity graph.",
            "Volume, loss, NIM",
            "Contracted products product and risk run on: payment volume and take rate, fraud loss and chargeback rate, and net interest margin by product.",
        ),
        "rails": {
            "src": [
                {"box": "Core & Ledger", "ic": "erp", "tiles": [
                        tile("Temenos Transact", "erp", "Deposits, loans, GL and end-of-day across retail and commercial banking.", "temenos",
                             cat="Core Banking System",
                             what="Deposits, loans, general ledger and end-of-day processing across retail and commercial banking.",
                             users="Core banking operations, finance and product.",
                             data_out=data_out(
                                 batch=flow(["structured"], "50-200 GB/day postings + EOD", "Nightly batch + intraday CDC"))),
                        tile("Mambu Core Banking", "db", "Cloud-native accounts, products and interest accrual for digital banks.", "mambu",
                             cat="Core Banking System",
                             what="Cloud-native accounts, product definitions and interest accrual for digital banks.",
                             users="Digital banking product, core operations and finance.",
                             data_out=data_out(
                                 batch=flow(["structured"], "10-50 GB/day accounts + accruals", "Continuous CDC (near real-time)"))),
                        tile("FIS Modern Banking", "erp", "Legacy core postings, statements and regulatory extracts.", "fis-core",
                             cat="Core Banking System",
                             what="Legacy core postings, statements and regulatory extracts across the deposit and loan book.",
                             users="Core banking operations, finance and regulatory reporting.",
                             data_out=data_out(
                                 batch=flow(["structured"], "50-200 GB/day postings + extracts", "Nightly batch"))),
                    ]},
                {"box": "Acquiring & Issuing", "ic": "market", "tiles": [
                        tile("Adyen Platform", "market", "Unified acquiring authorisations, settlements and dispute events.", "adyen",
                             cat="Payment Acquiring / PSP",
                             what="Unified acquiring platform carrying authorisation, settlement and dispute events across channels.",
                             users="Payments product, fraud and settlement operations.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "5-50k auth events/sec at peak", "Continuous (real-time)"),
                                 batch=flow(["structured"], "Settlement + dispute files", "Multiple settlement cycles daily"))),
                        tile("Stripe Payments", "partner", "Merchant payment intents, connect payouts and radar fraud signals.", "stripe",
                             cat="Payment Gateway / PSP",
                             what="Merchant payment intents, Connect payouts and Radar fraud signals across online payments.",
                             users="Payments product, growth and fraud.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "Payment + payout events", "Continuous (webhooks)"),
                                 batch=flow(["structured"], "Payout + reconciliation files", "Daily batch"))),
                        tile("Marqeta Card Issuing", "api", "Card programmes, spend controls and tokenisation lifecycle.", "marqeta",
                             cat="Card Issuing Processor",
                             what="Card programme management, spend controls and tokenisation lifecycle for issued cards.",
                             users="Card product, issuing operations and fraud.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "Card auth + token events", "Continuous (real-time)"),
                                 batch=flow(["structured"], "Programme + spend files", "Daily batch"))),
                    ]},
                {"box": "Fraud & Compliance", "ic": "gavel", "tiles": [
                        tile("NICE Actimize", "gauge", "AML alerts, SAR workflows and transaction monitoring rules.", "actimize",
                             cat="Financial Crime / AML Platform",
                             what="AML alert generation, SAR workflows and transaction-monitoring rules across the book.",
                             users="AML and financial crime, compliance and investigations.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "Alerts + case records", "Intraday batch"),
                                 stream=flow(["semi-structured"], "Alert events", "Continuous (near real-time)"))),
                        tile("Onfido Identity", "people", "Document verification and biometric checks at onboarding.", "onfido",
                             cat="Identity Verification (KYC)",
                             what="Document verification and biometric identity checks performed at customer and merchant onboarding.",
                             users="Onboarding, KYB and financial crime.",
                             data_out=data_out(
                                 stream=flow(["semi-structured", "unstructured"], "Verification results + documents", "Continuous (API)"))),
                        tile("AML Screening", "gavel", "Sanctions, PEP and adverse media screening on parties and merchants.", "complyadvantage",
                             cat="Sanctions & Screening Provider",
                             what="Sanctions, PEP and adverse-media screening on parties and merchants at onboarding and monitoring.",
                             users="Financial crime, compliance and onboarding.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "Screening API responses", "Continuous (API)"),
                                 batch=flow(["structured"], "Watchlist deltas", "Daily refresh"))),
                    ]},
                {"box": "Merchant & CRM", "ic": "custlake", "tiles": [
                        tile("Salesforce Fintech CRM", "custlake", "Merchant sales pipeline, onboarding cases and support history.", "sf-fintech",
                             cat="CRM Platform",
                             what="Merchant sales pipeline, onboarding cases and support history across the commercial relationship.",
                             users="Merchant sales, merchant success and onboarding.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day accounts + cases", "Nightly CDC"),
                                 stream=flow(["semi-structured"], "Activity + case events", "Continuous (API/events)"))),
                        tile("Zendesk Merchant Care", "chat", "Tickets, chat transcripts and refund disputes tied to merchant accounts.", "zendesk",
                             cat="Customer Support Platform",
                             what="Support tickets, chat transcripts and refund disputes tied to merchant accounts.",
                             users="Merchant success, support and dispute teams.",
                             data_out=data_out(
                                 batch=flow(["structured", "unstructured"], "Tickets + transcripts", "Nightly batch"),
                                 stream=flow(["semi-structured"], "Ticket events", "Continuous (webhooks)"))),
                        tile("Braze Lifecycle", "partner", "Activation and retention campaigns with delivery and conversion events.", "braze",
                             cat="Customer Engagement Platform",
                             what="Activation and retention campaigns with delivery, open and conversion events across channels.",
                             users="Growth marketing and merchant success.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "Campaign + engagement events", "Continuous (events)"))),
                    ]},
                fed_group("Card Network Mart", "Scheme reporting and interchange marts queried in place under Unity Catalog.",
                          cat="Scheme / Interchange Data Mart",
                          what="Scheme reporting and interchange marts kept in the incumbent warehouse and queried in place, giving one view of interchange and settlement.",
                          users="Settlement operations, finance and the payments business.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale interchange + settlement history", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("SWIFT ISO 20022", "api", "Cross-border payment messages parsed into structured settlement events.", "swift-iso",
                     cat="Payment Messaging Standard",
                     what="Cross-border payment messages parsed on arrival into structured settlement events.",
                     users="Settlement operations, treasury and data engineering.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "Payment messages", "Continuous (message queue)"),
                         batch=flow(["structured"], "Settlement message batches", "Multiple settlement cycles daily"))),
                tile("Visa / Mastercard BIN", "partner", "Issuer and product metadata consumed inbound for routing and fraud.", "visa-developer",
                     cat="Card Network Reference Data",
                     what="Issuer identification and product metadata consumed inbound for routing decisions and fraud enrichment.",
                     users="Payments product, routing engineering and fraud.",
                     data_out=data_out(
                         batch=flow(["structured"], "BIN + product reference", "Daily/weekly updates"))),
                tile("Open Banking Feeds", "stream", "Account aggregation and consent-based transaction imports for lending.", "open-banking",
                     cat="Open Banking Aggregation API",
                     what="Consent-based account aggregation and transaction imports used for lending and affordability.",
                     users="Lending product, credit data science and data engineering.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "Account + transaction events", "Continuous (consent-based)"))),
            ]),
            "ppl": ppl_rail2([
                biz("Payments Leadership", "Genie One", "The CEO on payment volume growth and take rate; the CFO on fraud loss and funding cost when interest rates and scheme fees move against the book.", [["Genie One", "Ask what yesterday's net payment volume was by product without waiting on finance."], ["AI/BI", "Volume, loss and margin on one certified set of Metric Views."], ["Unity Catalog", "Certification so \"volume\" means one thing across core and acquirer."]],
                    sub=[
                        ["CEO", "payment volume growth, take rate and the bet across acquiring, issuing and banking."],
                        ["CFO", "fraud loss, funding cost and net interest margin when rates and scheme fees move."],
                        ["Chief Payments Officer", "authorisation performance, scheme relationships and the cost of every basis point of decline."],
                    ],
                    ucs=["Real-Time Fraud", "Interchange Optimisation", "Liquidity Forecasting", "Payment Routing"]),
                biz("Product & Payments", "Model Serving", "Product managers on authorisation rates, routing cost and feature adoption, tracking take rate and activation across the payment products they own.", [["Payments Console", "Auth success and latency by route before a scheme change."], ["Model Serving", "Routing and fraud models scored in the auth path."], ["AI/BI", "Take rate and activation on governed definitions."]],
                    sub=[
                        ["Head of Payments Product", "authorisation success, routing cost and the roadmap for each payment product."],
                        ["Lending Product", "BNPL and working-capital limits, approval rates and portfolio risk."],
                        ["Growth PM", "activation, feature adoption and take rate across the products they own."],
                    ],
                    ucs=["Payment Routing", "Credit Underwriting", "Open Banking Lending", "Real-Time Fraud"]),
                biz("Risk & Fraud", "AI/BI", "Fraud analysts on velocity rules, chargeback rate and AML alert queues, balancing fraud loss against the false-positive decline rate on good volume.", [["Fraud Command Centre", "Device clusters and mule patterns before payouts release."], ["AI/BI", "Loss and false-positive rates on certified Metric Views."], ["Unity Catalog", "One transaction definition across acquirer and core."]],
                    sub=[
                        ["Head of Fraud", "velocity rules, fraud loss and the false-positive decline rate on good volume."],
                        ["AML / Financial Crime", "transaction monitoring, sanctions screening and the SAR filing backlog."],
                        ["Dispute & Chargeback", "representment win rate and chargeback exposure before scheme deadlines."],
                    ],
                    ucs=["Real-Time Fraud", "AML Monitoring", "Chargeback Prevention", "Merchant Onboarding"]),
                biz("Merchant Growth", "CustomerLake", "Sales and success on the onboarding funnel, merchant churn and support load, tracking activation and revenue per merchant account.", [["Merchant 360", "Onboarding status and revenue in one view."], ["CustomerLake", "Merchant segments without copying CRM elsewhere."], ["Genie One", "Ask which merchants spiked chargebacks last week."]],
                    sub=[
                        ["Merchant Sales", "the onboarding funnel, activation and revenue per merchant account."],
                        ["Merchant Success", "retention, support load and the merchants quietly routing volume elsewhere."],
                        ["Onboarding & KYB", "time-to-first-transaction and keeping bad actors out at signup."],
                    ],
                    ucs=["Merchant Onboarding", "Merchant Churn", "Chargeback Prevention"]),
                biz("Finance & Treasury", "AI/BI", "Treasury on settlement floats, liquidity and scheme fee reconciliation, watching net interest margin and interchange revenue by product.", [["Treasury Workbench", "Float and funding scenarios before month-end close."], ["AI/BI", "NIM and interchange on certified Metric Views."], ["Unity Catalog", "One settlement definition across processors."]],
                    sub=[
                        ["Group Treasurer", "settlement floats, liquidity buffers and funding cost before settlement windows."],
                        ["Head of Settlement", "scheme fee reconciliation and interchange revenue by product."],
                        ["FP&A", "net interest margin, take rate and the numbers behind the forward book."],
                    ],
                    ucs=["Liquidity Forecasting", "Interchange Optimisation", "Credit Underwriting"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land the core, acquirer, fraud and KYC feeds; own the Bronze to Silver path and the pager when an authorisation or settlement pipeline breaks.", [["Lakeflow Connect", "Managed connectors for core banking, acquirer and CRM sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on auth and settlement feeds."], ["Lakewatch", "Freshness on the volume and loss tables risk reads every morning."]],
                    sub=[
                        ["Core & Ledger Eng", "the core banking, GL and settlement feeds and the pager when a posting pipeline breaks."],
                        ["Streaming Eng", "authorisation and acquirer event streams landed at the latency fraud reads at."],
                        ["Compliance Data Eng", "KYC, sanctions and monitoring feeds under audit-grade lineage."],
                    ],
                    ucs=["Real-Time Fraud", "AML Monitoring", "Payment Routing"]),
                biz("Data Scientists", "MLflow", "Real-time fraud, credit-underwriting, routing and merchant-churn models, and whether they still hold six months after deployment in the auth path.", [["Feature Store", "Transaction and device features read identically in training and serving."], ["MLflow", "Every fraud and credit run tracked for audit and reproduction."], ["Model Serving", "Fraud and routing models scored inside the authorisation path."]],
                    sub=[
                        ["Fraud & Risk DS", "real-time fraud and velocity models and whether they hold in the auth path."],
                        ["Credit DS", "cash-flow underwriting and affordability models for lending products."],
                        ["Merchant DS", "churn, routing and interchange models scored into the commercial workflow."],
                    ],
                    ucs=["Real-Time Fraud", "Credit Underwriting", "Merchant Churn", "Open Banking Lending"]),
                biz("App Developers", "Apps", "Ship the payments console, fraud command and merchant applications product and risk teams work in, hosted next to governed transaction data.", [["Apps", "Operational screens with no separate web tier to run or secure."], ["Lakebase", "Serverless Postgres for case state and governed writes."], ["Agent Bricks", "Agents that draft a dispute response against governed tools."]],
                    sub=[
                        ["Payments App Eng", "the Payments Console and auth-health screens over governed transaction data."],
                        ["Fraud App Eng", "the Fraud Command Centre case and blocklist workflows on Lakebase."],
                        ["Merchant App Eng", "Merchant 360 onboarding and revenue screens next to governed data."],
                    ],
                    ucs=["Real-Time Fraud", "Chargeback Prevention", "Merchant Onboarding"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                        tile("Tableau / Qlik / ThoughtSpot", "chart", "External BI against serverless SQL warehouses, with Unity Catalog permissions enforced end to end."),
                        tile("Microsoft Teams", "chat", "Genie in Teams for governed answers and incident updates in the channel ops already works in (Beta)."),
                        tile("Notebooks & IDEs", "notebook", "Notebooks, VS Code and JetBrains against governed data and Genie Code."),
                    ]},
                {"box": "Platform Writeback", "ic": "opdb", "tiles": [
                        tile("Fraud Block Lists", "gauge", "Device and instrument blocks pushed to authorisation in near real time.", "actimize"),
                        tile("Merchant Limit Updates", "market", "Spend and velocity limits adjusted from governed risk scores.", "stripe"),
                        tile("CRM Case Resolution", "custlake", "Dispute outcomes written back to merchant care workflows.", "zendesk"),
                    ]},
                {"box": "Partners & Schemes", "ic": "partner", "tiles": [
                        tile("Scheme Reporting API", "api", "Interchange and compliance files served to card networks from governed settlements.", "visa-developer"),
                        tile("Bank Sponsor Sharing", "share", "Programme performance shared to BIN sponsors over Delta Sharing.", "marqeta"),
                        tile("PSP Partner Portal", "partner", "Sub-merchant metrics exchanged without nightly flat files.", "adyen"),
                    ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                        tile("AML / SAR Reporting", "gavel", "Suspicious activity metrics filed from governed transaction monitoring.", "actimize"),
                        tile("PCI & Scheme Compliance", "share", "Control evidence and attestation data from contracted Gold products."),
                    ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                        tile("Data Products", "product", "Published, contracted products discoverable in Unity Catalog Domains and shared over Open Sharing."),
                        tile("Sharing Recipients", "share", "Sponsors, auditors and partners reading live tables with no copy."),
                    ]},
            ],
            genie_spaces=[
                genie("Payments & Volume", "Ask about payment volume, take rate and authorisation performance by product in plain language.",
                      feeds=["Adyen Platform", "Stripe Payments", "Volume, loss, NIM"],
                      teams=["Payments Leadership", "Product & Payments", "Chief Payments Officer"],
                      questions=[
                          "What was net payment volume by product yesterday?",
                          "How has authorisation success rate moved this week by route?",
                          "Where is take rate strongest and weakest across products?",
                          "Which BINs or networks are driving the most declines?",
                          "How does volume growth compare to last quarter by segment?"]),
                genie("Fraud & Disputes", "Ask about fraud loss, chargebacks and alert queues across the book in plain language.",
                      feeds=["NICE Actimize", "Adyen Platform", "Conformed account, txn"],
                      teams=["Risk & Fraud", "Head of Fraud", "Dispute & Chargeback"],
                      questions=[
                          "Which merchants spiked chargebacks last week?",
                          "What is our fraud loss and false-positive rate today?",
                          "Where are device clusters or mule patterns concentrated right now?",
                          "How large is the AML alert backlog and what is ageing?",
                          "What is our representment win rate before scheme deadlines?"]),
                genie("Merchant Growth", "Ask about the onboarding funnel, merchant revenue and churn signals in plain language.",
                      feeds=["Salesforce Fintech CRM", "Zendesk Merchant Care", "Conformed account, txn"],
                      teams=["Merchant Growth", "Merchant Sales", "Merchant Success"],
                      questions=[
                          "Where do merchants drop off in the onboarding funnel?",
                          "Which merchants are quietly routing volume elsewhere?",
                          "What is revenue per merchant by segment this quarter?",
                          "Which merchants have rising support load and disputes?",
                          "What is time-to-first-transaction for new signups?"]),
                genie("Treasury & Settlement", "Ask about settlement floats, funding and interchange revenue in plain language.",
                      feeds=["SWIFT ISO 20022", "Card Network Mart", "Volume, loss, NIM"],
                      teams=["Finance & Treasury", "Group Treasurer", "Head of Settlement"],
                      questions=[
                          "What is our expected settlement float before the next window?",
                          "How much interchange revenue did each product generate this month?",
                          "Where are scheme fees diverging from reconciliation?",
                          "What funding do we need before month-end close?",
                          "How has net interest margin moved with rates this quarter?"]),
            ],
            dashboards=[
                dashboard("Payment Volume & Take Rate", "Volume, take rate and authorisation performance across products on certified Metric Views.",
                          kpis=["Payment volume", "Take rate", "Authorisation rate", "Decline rate", "Net interest margin"],
                          teams=["Payments Leadership", "Product & Payments", "Finance & Treasury"]),
                dashboard("Fraud & Chargebacks", "Fraud loss, chargebacks and alert posture across acquiring and issuing.",
                          kpis=["Fraud loss", "Chargeback rate", "False-positive rate", "Alert volume", "Representment win rate"],
                          teams=["Risk & Fraud", "Head of Fraud", "Dispute & Chargeback"]),
                dashboard("Merchant Health", "Onboarding funnel, revenue and churn across the merchant book.",
                          kpis=["Time-to-first-transaction", "Merchant activation", "Revenue per merchant", "Merchant churn", "Support load"],
                          teams=["Merchant Growth", "Merchant Sales", "Merchant Success"]),
                dashboard("Treasury & Settlement", "Float, funding and interchange revenue across settlement cycles.",
                          kpis=["Settlement float", "Funding cost", "Interchange revenue", "Liquidity buffer", "Scheme fee reconciliation"],
                          teams=["Finance & Treasury", "Group Treasurer", "Head of Settlement"]),
            ]),
        },
        "top": top_band(
            [
                app("Payments Console", "Auth health", "gauge", "Authorisation success, latency and routing on Databricks Apps over Lakebase."),
                app("Fraud Command Centre", "Loss control", "gavel", "Velocity clusters and chargeback spikes before payouts release."),
                app("Merchant 360", "Onboarding", "custlake", "Pipeline, revenue and support history for every merchant account."),
                app("Treasury Workbench", "Float & NIM", "sheet", "Settlement floats and funding scenarios before month-end close."),
            ],
            [
                uc("Real-Time Fraud", "Authorisation", "gauge", "Mule and card-testing patterns blocked before settlement funds move.",
                    problem="Card-testing and mule networks move funds inside the authorisation window, but rules engines score in isolation and by the time a batch flags the pattern the payout has already settled.",
                    who="Risk & Fraud",
                    how="Authorisation events land in Lakehouse//RT, device and velocity features are read from Lakebase, and Model Serving scores every transaction inside the Fraud Command Centre before funds move.",
                    comps=["Fraud Command Centre", "Adyen Platform", "Lakehouse//RT", "Model Serving", "Feature Store", "Lakebase"],
                    stories=[
                        ["Coinbase scales real-time fraud detection on Databricks", "https://www.databricks.com/customers/coinbase/lakeflow"],
                        ["Building real-time fraud detection with Spark Real-Time Mode and Lakebase", "https://www.databricks.com/blog/how-build-real-time-fraud-detection-using-spark-real-time-mode-and-lakebase"],
                        ["Coins.ph delivers ML-powered fraud detection in real time", "https://www.databricks.com/customers/coins-ph"],
                    ]),
                uc("Chargeback Prevention", "Disputes", "gavel", "Dispute-prone merchants and instruments surfaced before scheme deadlines.",
                    problem="Disputes surface weeks after the sale, so chargeback-prone merchants and instruments are only caught once scheme fees, fines and write-offs have already hit the acquiring book.",
                    who="Risk & Fraud",
                    how="Adyen dispute and settlement events are conformed on the platform and scored in Model Serving, surfacing at-risk merchants in the Fraud Command Centre before scheme representment deadlines.",
                    comps=["Fraud Command Centre", "Adyen Platform", "AI/BI", "Model Serving", "Unity Catalog"],
                    stories=[
                        ["Block prevents fraud and payment risk in real time", "https://www.databricks.com/customers/block/lakeflow-declarative-pipelines"],
                    ]),
                uc("Merchant Onboarding", "Growth", "partner", "KYB risk scored at signup so sales does not onboard bad actors.",
                    problem="KYB checks are stitched across identity, sanctions and document vendors by hand at signup, so sales either onboards risky merchants or loses good ones to days of manual review.",
                    who="Merchant Growth",
                    how="Onfido and AML Screening signals are scored with AI Functions against a conformed party graph, giving Merchant 360 a risk decision at signup under Unity Catalog lineage.",
                    comps=["Merchant 360", "Onfido Identity", "AML Screening", "AI Functions", "Unity Catalog"]),
                uc("Credit Underwriting", "Lending", "sheet", "Cash-flow and behaviour models for BNPL and working-capital products.",
                    problem="BNPL and working-capital limits are set from thin bureau files and stale statements, so thin-file merchants are declined and cash-flow risk is only seen after the loan is drawn.",
                    who="Product & Payments",
                    how="Open Banking and transaction features are engineered in Feature Store and scored through Model Serving, with every underwriting run tracked in MLflow for audit and reproduction.",
                    comps=["Merchant 360", "Open Banking Feeds", "Feature Store", "Model Serving", "MLflow"],
                    stories=[
                        ["Vivriti Capital scales real-time lending and underwriting", "https://www.databricks.com/customers/vivriti-capital"],
                        ["Maya's ML-powered lending disbursed $2.1B in loans", "https://www.databricks.com/customers/maya"],
                    ]),
                uc("Payment Routing", "Optimisation", "market", "Auth routes chosen for success rate and cost not static BIN tables.",
                    problem="Authorisation routes are chosen from static BIN tables, so declines and scheme costs pile up while nobody sees which acquirer or network path actually wins on a given transaction.",
                    who="Product & Payments",
                    how="Live auth outcomes stream into Lakehouse//RT, routing models score each attempt in Model Serving, and the Payments Console shows success and cost by route before a scheme change.",
                    comps=["Payments Console", "Visa / Mastercard BIN", "Model Serving", "Lakehouse//RT", "AI/BI"]),
                uc("AML Monitoring", "Compliance", "gavel", "Transaction monitoring tuned to reduce false positives without missing SARs.",
                    problem="Legacy transaction-monitoring rules fire on thresholds, burying analysts under false positives while genuinely suspicious structuring slips through and SAR deadlines are missed.",
                    who="Risk & Fraud",
                    how="NICE Actimize alerts and AML Screening signals are enriched and scored in Model Serving, so the Fraud Command Centre ranks true risk on certified data under Unity Catalog lineage.",
                    comps=["Fraud Command Centre", "NICE Actimize", "AML Screening", "Model Serving", "Unity Catalog", "AI/BI"],
                    stories=[
                        ["Modern BSA/AML compliance on Databricks", "https://www.databricks.com/blog/modern-bsaaml-compliance-databricks"],
                        ["Coins.ph powers anti-money-laundering with Databricks", "https://www.databricks.com/customers/coins-ph"],
                    ]),
                uc("Merchant Churn", "Retention", "custlake", "At-risk merchants identified from volume dips and support signals.",
                    problem="A merchant quietly routes volume to a rival for weeks before anyone notices, because volume dips, support tickets and disputes live in systems that never meet in one view.",
                    who="Merchant Growth",
                    how="CRM, support and volume signals are unified in CustomerLake and scored for churn in Model Serving, surfacing at-risk merchants in Merchant 360 before the volume walks.",
                    comps=["Merchant 360", "Salesforce Fintech CRM", "Zendesk Merchant Care", "CustomerLake", "Model Serving"],
                    stories=[
                        ["PicPay unifies data to lift engagement and cut cash-back waste", "https://www.databricks.com/customers/picpay"],
                        ["Grab builds a single consumer view with C360", "https://www.databricks.com/customers/grab"],
                    ]),
                uc("Interchange Optimisation", "Revenue", "chart", "MCC and routing choices maximising take rate within scheme rules.",
                    problem="Interchange leaks through wrong MCC coding, missed rate qualifications and suboptimal routing, and the scheme mart is too slow and siloed to show where take rate is being lost.",
                    who="Finance & Treasury",
                    how="Settlement and scheme data from the Card Network Mart are modelled in AI/BI as governed Data Products, exposing the MCC and routing choices that lift take rate within scheme rules.",
                    comps=["Treasury Workbench", "Card Network Mart", "AI/BI", "Unity Catalog", "Data Products"]),
                uc("Open Banking Lending", "Data", "api", "Aggregated account data scored for affordability with consent lineage.",
                    problem="Consent-based account data arrives as raw feeds with no lineage, so affordability decisions are hard to defend to regulators and every lender rebuilds the same categorisation.",
                    who="Product & Payments",
                    how="Open Banking and ISO 20022 feeds are conformed under Unity Catalog, then categorised and scored for affordability in Model Serving with consent lineage carried through Feature Store.",
                    comps=["Open Banking Feeds", "SWIFT ISO 20022", "Feature Store", "Model Serving", "Unity Catalog"]),
                uc("Liquidity Forecasting", "Treasury", "erp", "Settlement floats and funding needs predicted before central bank windows.",
                    problem="Settlement floats and funding needs are guessed from spreadsheets, so treasury holds costly buffers or scrambles for liquidity before scheme and central-bank settlement windows.",
                    who="Finance & Treasury",
                    how="SWIFT ISO 20022 settlement flows are modelled in Model Serving and surfaced in the Treasury Workbench, so AI/BI shows float and funding scenarios on Delta Lake before month-end close.",
                    comps=["Treasury Workbench", "SWIFT ISO 20022", "Model Serving", "AI/BI", "Delta Lake"],
                    stories=[
                        ["Airwallex powers global banking with data and AI", "https://www.databricks.com/customers/airwallex/gcp"],
                    ]),
            ],
        ),
        "sources": {
            "temenos": {"t": "Temenos Transact", "u": "https://www.temenos.com/products/transact/"},
            "mambu": {"t": "Mambu", "u": "https://www.mambu.com/"},
            "fis-core": {"t": "FIS Modern Banking Platform", "u": "https://www.fisglobal.com/en/solutions/banking-core"},
            "adyen": {"t": "Adyen", "u": "https://www.adyen.com/"},
            "stripe": {"t": "Stripe", "u": "https://stripe.com/"},
            "marqeta": {"t": "Marqeta", "u": "https://www.marqeta.com/"},
            "actimize": {"t": "NICE Actimize", "u": "https://www.niceactimize.com/"},
            "onfido": {"t": "Onfido", "u": "https://onfido.com/"},
            "complyadvantage": {"t": "ComplyAdvantage", "u": "https://complyadvantage.com/"},
            "sf-fintech": {"t": "Salesforce Financial Services Cloud", "u": "https://www.salesforce.com/financial-services/"},
            "zendesk": {"t": "Zendesk", "u": "https://www.zendesk.com/"},
            "braze": {"t": "Braze", "u": "https://www.braze.com/"},
            "swift-iso": {"t": "SWIFT ISO 20022", "u": "https://www.swift.com/standards/iso-20022"},
            "visa-developer": {"t": "Visa Developer", "u": "https://developer.visa.com/"},
            "open-banking": {"t": "Open Banking standards", "u": "https://openbanking.org.uk/"},
        },
    },
}
