import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_SPORTS_ENTERTAINMENT = {
    'sports_entertainment': {
        "label": "Sports & Entertainment",
        "blurb": "Teams, venues and media rights: ticketing and fan engagement, game-day operations, broadcast and streaming, sponsorship activation, and athlete performance analytics.",
        "medallion": medallion(
            "Raw event and fan feeds",
            "Ticketing scans, POS concessions, broadcast logs, wearable tracking and CRM interactions, landed exactly as received so a attendance or a sponsorship impression can always be replayed.",
            "Conformed fan, event, asset",
            "Fans, events, seats and media assets resolved into single conformed entities across ticketing, CRM and broadcast estates, with identity stitched across channels.",
            "Attendance, yield, engagement",
            "Contracted products commercial and operations teams run on: ticket yield by section, F&B attach rate, sponsorship ROI, streaming concurrency and churn risk by segment.",
        ),
        "rails": {
            "src": [
                {"box": "Ticketing & CRM", "ic": "erp", "tiles": [
                    tile("Ticketmaster Archtics", "erp", "Primary ticketing, seat inventory, pricing and scan data from every event.", "ticketmaster"),
                    tile("Salesforce Sports Cloud", "custlake", "Fan profiles, membership tiers, service cases and campaign responses.", "sf-sports"),
                    tile("SeatGeek Enterprise", "market", "Secondary market listings, transfer activity and dynamic pricing signals.", "seatgeek"),
                ]},
                {"box": "Venue Operations", "ic": "stream", "tiles": [
                    tile("VenueNext", "apps", "Mobile ordering, wayfinding and in-seat service for arena and stadium guests.", "venuenext"),
                    tile("Genetec Security Center", "iot", "Access control, crowd density cameras and incident logs on game day.", "genetec"),
                    tile("Catapult Sports", "iot", "GPS and IMU player tracking: load, sprint distance and injury risk flags.", "catapult"),
                ]},
                {"box": "Broadcast & OTT", "ic": "partner", "tiles": [
                    tile("Grabyo Clipping", "stream", "Live clipping, highlights and social publishing from broadcast feeds.", "grabyo"),
                    tile("Deltatre OTT Platform", "api", "Streaming concurrency, start-over and device telemetry for direct-to-consumer.", "deltatre"),
                    tile("Nielsen Sports", "chart", "TV and digital audience measurement for rights valuation.", "nielsen-sports"),
                ]},
                {"box": "Sponsorship & Ads", "ic": "market", "tiles": [
                    tile("SponsorUnited", "partner", "Sponsorship inventory, activation tracking and competitive spend intelligence.", "sponsorunited"),
                    tile("The Trade Desk Sports", "market", "Programmatic inventory across league and team digital properties.", "trade-desk"),
                    tile("UKG Workforce", "people", "Staff scheduling, time and attendance for event and concessions crews.", "ukg"),
                ]},
                fed_group("League Data Marts", "Official league statistics and schedule marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("Stats Perform Feeds", "api", "Live play-by-play, rosters and official statistics ingested for analytics.", "stats-perform"),
                tile("Social Listening APIs", "observ", "Brand mention and sentiment feeds for sponsorship and crisis monitoring."),
                tile("Rights Holder Metadata", "zplug", "Media rights windows and blackout rules from league partners.", "stats-perform"),
            ]),
            "ppl": ppl2([
                biz("Ownership & Executive", "Genie One", "The CEO on revenue per fan and matchday P&L; the COO on ingress throughput, concessions flow and the safety record across the venue.",
                    [["Genie One", "Last home stand yield without analyst delay."], ["AI/BI", "Attendance and sponsorship ROI on Metric Views."]],
                    sub=[["CEO / Team President", "revenue per fan, matchday P&L and the trade between winning and margin."], ["CFO", "gate, media and sponsorship revenue against the cost of running the venue."], ["Chief Commercial Officer", "sponsorship value, premium inventory and the growth of the fan base."]],
                    ucs=["Sponsorship ROI", "Dynamic Ticket Pricing", "Merchandise Forecast"]),
                biz("Ticketing & Pricing", "Model Serving", "Pricing analysts on dynamic seat tiers, secondary-market pressure and sell-through pace against the demand curve before and during on-sale.",
                    [["Pricing Workbench", "Demand forecast before on-sale."], ["Model Serving", "Price models in the on-sale path."]],
                    sub=[["Head of Ticketing", "sell-through pace, sections at risk and the on-sale calendar."], ["Pricing Analyst", "dynamic seat tiers and secondary-market pressure against the demand curve."], ["Yield Manager", "premium and dynamic inventory value across the season."]],
                    ucs=["Dynamic Ticket Pricing", "Secondary Market Intel", "Fan Churn Prediction"]),
                biz("Fan Engagement", "CustomerLake", "CRM teams on membership growth, churn before renewal and personalised offers scored on spend stitched across ticketing and concessions.",
                    [["Fan 360 Console", "Spend stitched across ticketing and concessions."], ["CustomerLake", "Segments without a separate CDP."]],
                    sub=[["CRM Director", "membership growth, renewals and churn before the renewal window."], ["Digital & Content", "app engagement, highlights reach and personalised offers."], ["Membership Services", "the season-ticket experience and the value each fan sees."]],
                    ucs=["Fan Churn Prediction", "OTT Personalization", "Broadcast Highlights"]),
                biz("Game-Day Ops", "Lakehouse//RT", "Venue managers and medical staff on ingress flow, queue times, player load and incidents, moving crews before a bottleneck becomes a delay.",
                    [["Game-Day Command", "Live scans and queue times on one screen."], ["Load Management Hub", "Player workload before selection."]],
                    sub=[["VP Venue Operations", "ingress throughput, concessions flow and the safety record."], ["Head of Security", "crowd density, incidents and evacuation readiness."], ["Head of Performance / Medical", "player load, injury risk and availability for selection."]],
                    ucs=["Crowd Safety Analytics", "Concessions Optimization", "Injury Risk Scoring"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land ticketing scans, POS folios, wearable tracking and CRM feeds; own Bronze to Silver and the pager when a game-day attendance table stalls.",
                    [["Lakeflow Connect", "Managed connectors for ticketing, CRM and POS sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on scan and tracking feeds."], ["Lakewatch", "Freshness on the attendance tables commercial reads on game day."]],
                    sub=[["Streaming Engineer", "scan, POS and tracking feeds landed at game-day latency."], ["Pipeline Engineer", "Bronze-to-Silver reliability and expectations on attendance tables."], ["Platform Engineer", "freshness and the pager when a game-day table stalls."]],
                    ucs=["Crowd Safety Analytics", "Concessions Optimization", "Dynamic Ticket Pricing"]),
                biz("Data Scientists", "MLflow", "Dynamic-pricing, fan-churn, injury-risk and highlight-selection models, and whether they still hold as rosters, opponents and demand shift.",
                    [["Feature Store", "Fan and athlete features read identically in training and serving."], ["MLflow", "Every pricing and load experiment tracked for audit."], ["Model Serving", "Price and risk models scored in the on-sale and coaching path."]],
                    sub=[["Pricing Scientist", "demand and dynamic-pricing models that hold across opponents."], ["Fan & Churn Scientist", "churn, propensity and offer-scoring models across channels."], ["Sports Scientist", "injury-risk and load models against wearable and tracking data."]],
                    ucs=["Dynamic Ticket Pricing", "Fan Churn Prediction", "Injury Risk Scoring"]),
                biz("App Developers", "Apps", "Ship the Game-Day Command, Pricing Workbench and Fan 360 apps commercial and venue teams work in, next to governed ticketing data.",
                    [["Apps", "Venue screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for offer and incident state writes."], ["Agent Bricks", "Agents that draft offers against governed tools."]],
                    sub=[["Apps Engineer", "the Game-Day Command, Pricing Workbench and Fan 360 screens."], ["Backend Engineer", "offer and incident state on serverless Postgres."], ["Agent Engineer", "agents that draft offers against governed ticketing tools."]],
                    ucs=["Concessions Optimization", "Dynamic Ticket Pricing", "OTT Personalization"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "League and team dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for attendance and sponsorship questions on game day."),
                    tile("Notebooks & IDEs", "notebook", "Analytics notebooks against governed ticketing and tracking data."),
                ]},
                {"box": "Fan & Partner", "ic": "partner", "tiles": [
                    tile("Mobile App Offers", "api", "Personalised upsell and parking offers served in the team app."),
                    tile("Sponsor Reporting API", "share", "Activation proof and impression delivery to sponsors over Delta Sharing."),
                    tile("Broadcaster Data Feed", "globe", "Official stats and graphics packages shared to rights holders."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Dynamic Price Holds", "market", "Price tier adjustments written back to ticketing inventory.", "ticketmaster"),
                    tile("Staff Shift Dispatch", "people", "Concessions and security shift changes pushed to crew devices.", "ukg"),
                    tile("Coaching Clip Tags", "stream", "Tagged video moments written to the coaching platform.", "second-spectrum"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("League Revenue Share", "gavel", "Gate and local revenue reports filed to the league.", "stats-perform"),
                    tile("Safety Incident Reports", "share", "Crowd and medical incidents documented from governed logs.", "genetec"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Fan and performance products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "League partners reading live attendance via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Game-Day Command", "Venue operations", "gauge", "Live ingress, concessions throughput and security incidents on Databricks Apps over Lakebase."),
             app("Pricing Workbench", "Ticket yield", "market", "Demand curves and price tiers before on-sale and throughout the sales window."),
             app("Fan 360 Console", "Engagement view", "custlake", "Ticketing, concessions and CRM activity stitched per fan segment."),
             app("Load Management Hub", "Athlete readiness", "iot", "Player workload, injury risk and selection recommendations for coaching staff.")],
            [uc("Dynamic Ticket Pricing", "Revenue", "market", "Price tiers adjusted to demand, inventory and secondary market pressure.",
                problem="Seat prices sit on static tiers and stale rules, so demand shifts, opponent draw and secondary-market pressure move faster than pricing and revenue leaks on every event.",
                who="Ticketing & Pricing",
                how="Ticketing scans, demand and resale signals land through Lakeflow, conform on Delta Lake and are scored in Model Serving, with price tiers set in the Pricing Workbench through the sales window.",
                comps=["Pricing Workbench", "Ticketmaster Archtics", "Model Serving", "Lakeflow", "Delta Lake"],
                stories=[["Stadium Analytics: increasing sports fan engagement with data and AI", "https://www.databricks.com/blog/2022/03/31/stadium-analytics-increasing-sports-fan-engagement-with-data-and-ai.html"]]),
             uc("Fan Churn Prediction", "CRM", "custlake", "Season ticket and membership churn scored before renewal windows.",
                problem="Membership and season-ticket data sits apart from concessions and app behaviour, so churn is only noticed at renewal when the fan has already decided to walk.",
                who="Fan Engagement",
                how="Ticketing, CRM and concessions signals are stitched per fan in CustomerLake, scored for churn in Model Serving and surfaced in the Fan 360 Console before the renewal window opens.",
                comps=["Fan 360 Console", "Salesforce Sports Cloud", "CustomerLake", "Model Serving", "AI/BI"],
                stories=[["NRL transforms fan experience with data", "https://www.databricks.com/customers/national-rugby-league"], ["Pumpjack Dataworks builds a fan data refinery on Databricks", "https://www.databricks.com/customers/pumpjack-dataworks"]]),
             uc("Concessions Optimization", "F&B", "product", "Stand staffing and menu mix tuned to expected attendance and weather.",
                problem="Stand staffing and menu mix are planned off last season's averages, so queues build at some counters while food is wasted at others and per-cap spend suffers on game day.",
                who="Game-Day Ops",
                how="POS folios, attendance and weather feeds conform on Delta Lake and forecast demand in Model Serving, with staffing and menu recommendations shown per stand in Game-Day Command.",
                comps=["Game-Day Command", "VenueNext", "Model Serving", "Delta Lake", "AI/BI"],
                stories=[["Stadium Analytics: increasing sports fan engagement with data and AI", "https://www.databricks.com/blog/2022/03/31/stadium-analytics-increasing-sports-fan-engagement-with-data-and-ai.html"]]),
             uc("Sponsorship ROI", "Commercial", "partner", "Activation impressions and conversions attributed to sponsor inventory.",
                problem="Sponsors want proof their logo drove attention and sales, but impressions, broadcast exposure and conversions live in separate systems, so activation value is argued rather than measured.",
                who="Ownership & Executive",
                how="Broadcast, social and CRM exposure conform under Unity Catalog and are attributed to sponsor inventory in AI/BI, with activation proof shared to sponsors as governed Data Products.",
                comps=["SponsorUnited", "Unity Catalog", "AI/BI", "Data Products", "Delta Lake"],
                stories=[["Pumpjack Dataworks builds a fan data refinery on Databricks", "https://www.databricks.com/customers/pumpjack-dataworks"]]),
             uc("Injury Risk Scoring", "Performance", "iot", "Load and biomechanical signals flagging elevated injury risk.",
                problem="Player load and biomechanical signals come off wearables in silos, so medical and coaching staff see fatigue and injury risk only after it costs a player or a result.",
                who="Game-Day Ops",
                how="Wearable and tracking feeds land in Lakehouse//RT, are engineered in Feature Store and scored for injury risk in Model Serving, with readiness shown in the Load Management Hub before selection.",
                comps=["Load Management Hub", "Catapult Sports", "Lakehouse//RT", "Feature Store", "Model Serving"],
                stories=[["LaLiga changes the world of sports with real-time streaming data", "https://www.databricks.com/customers/laliga"]]),
             uc("Broadcast Highlights", "Media", "stream", "Automated clip selection and publishing from live feeds.",
                problem="Clipping and publishing highlights is a manual scramble against the second screen, so the best moments reach social late and the audience has already moved on.",
                who="Fan Engagement",
                how="Live broadcast and play-by-play feeds land through Lakeflow and AI Functions score clip-worthy moments on Delta Lake, so highlights are selected and published from Grabyo Clipping in near real time.",
                comps=["Grabyo Clipping", "Stats Perform Feeds", "Lakeflow", "AI Functions", "Delta Lake"]),
             uc("Crowd Safety Analytics", "Operations", "gauge", "Density and ingress patterns flagged before capacity thresholds.",
                problem="Ingress crushes, density hot-spots and medical incidents are spotted by eye across dozens of cameras, so crews react after a bottleneck has already become a safety risk.",
                who="Game-Day Ops",
                how="Access-control and crowd-density feeds stream into Lakehouse//RT and are scored against density thresholds in Model Serving, alerting crews from Game-Day Command before capacity is breached.",
                comps=["Game-Day Command", "Genetec Security Center", "Lakehouse//RT", "Model Serving", "Delta Lake"]),
             uc("Secondary Market Intel", "Ticketing", "chart", "Transfer and resale activity informing primary pricing.",
                problem="Resale and transfer activity on secondary platforms signals true demand, but it arrives disconnected from primary inventory, so pricing and hold decisions are made half-blind.",
                who="Ticketing & Pricing",
                how="Secondary listings and transfer feeds land through Lakeflow, conform on Delta Lake alongside primary inventory and inform the price and hold moves surfaced in the Pricing Workbench.",
                comps=["Pricing Workbench", "SeatGeek Enterprise", "Lakeflow", "Delta Lake", "AI/BI"]),
             uc("OTT Personalization", "Streaming", "api", "Content recommendations and offers scored per viewer segment.",
                problem="Streaming viewers get generic content and offers because concurrency, device and viewing history sit apart from the CRM, so engagement and subscriber value are left on the table.",
                who="Fan Engagement",
                how="OTT telemetry and CRM data are stitched in CustomerLake and scored for recommendations in Model Serving, personalising content and offers per viewer segment in the direct-to-consumer app.",
                comps=["Deltatre OTT Platform", "CustomerLake", "Model Serving", "Feature Store", "AI/BI"],
                stories=[["Seven West Media fuels audience growth and ad revenue with AI", "https://www.databricks.com/customers/seven-west-media"], ["Empowering Swiss public media SRF with data-driven intelligence", "https://www.databricks.com/customers/srf"]]),
             uc("Merchandise Forecast", "Retail", "erp", "Event-level merch demand forecast tied to opponent and promotion.",
                problem="Event-level merch demand swings with opponent, promotion and result, but forecasts run on flat seasonal averages, so stock sells out on hot nights and sits dead on others.",
                who="Ownership & Executive",
                how="Sales, event and promotion data conform on Delta Lake and forecast per-event demand in Model Serving, with opponent and promotion features managed in Feature Store for the retail team.",
                comps=["Model Serving", "Feature Store", "Delta Lake", "AI/BI", "Data Products"])],
        ),
        "sources": {
            "ticketmaster": {"t": "Ticketmaster Archtics", "u": "https://business.ticketmaster.com/"},
            "sf-sports": {"t": "Salesforce Sports Cloud", "u": "https://www.salesforce.com/"},
            "seatgeek": {"t": "SeatGeek Enterprise", "u": "https://seatgeek.com/enterprise"},
            "venuenext": {"t": "VenueNext", "u": "https://www.venuenext.com/"},
            "genetec": {"t": "Genetec Security Center", "u": "https://www.genetec.com/"},
            "ukg": {"t": "UKG workforce management", "u": "https://www.ukg.com/"},
            "grabyo": {"t": "Grabyo", "u": "https://about.grabyo.com/"},
            "deltatre": {"t": "Deltatre OTT", "u": "https://www.deltatre.com/"},
            "nielsen-sports": {"t": "Nielsen Sports", "u": "https://www.nielsen.com/"},
            "sponsorunited": {"t": "SponsorUnited", "u": "https://www.sponsorunited.com/"},
            "trade-desk": {"t": "The Trade Desk", "u": "https://www.thetradedesk.com/"},
            "catapult": {"t": "Catapult Sports", "u": "https://www.catapult.com/"},
            "second-spectrum": {"t": "Second Spectrum", "u": "https://www.secondspectrum.com/"},
            "stats-perform": {"t": "Stats Perform", "u": "https://www.statsperform.com/"},
        },
    },
}
