import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_CONSTRUCTION = {
    'construction': {
        "label": "Construction",
        "blurb": "Capital projects, job costing, field operations, subcontractor management, and BIM coordination across general contractors and owners.",
        "medallion": medallion(
            "Raw project and field feeds",
            "Procore daily logs, ERP job costs, BIM revisions and equipment telematics landed exactly as received.",
            "Conformed projects and WBS",
            "Projects, cost codes, subcontractors and assets resolved across ERP, PM and field systems.",
            "Margin, schedule, safety",
            "Contracted products executives and PMs run on: job margin, schedule variance, RFI aging and TRIR.",
        ),
        "rails": {
            "src": [
                {"box": "Project Management", "ic": "sheet", "tiles": [
                    tile("Procore", "sheet", "RFIs, submittals, daily logs and punch lists.", "procore"),
                    tile("Autodesk Build", "apps", "Issues, checklists and field photos on BIM context.", "autodesk-build"),
                    tile("Primavera P6", "sheet", "Master schedules, critical path and earned value.", "primavera"),
                ]},
                {"box": "ERP & Job Cost", "ic": "erp", "tiles": [
                    tile("Trimble Viewpoint Vista", "erp", "Job cost, AP, payroll and equipment billing.", "viewpoint"),
                    tile("Sage 300 CRE", "erp", "Project accounting, change orders and WIP.", "sage-cre"),
                    tile("Oracle Aconex", "share", "Document control and transmittals.", "aconex"),
                ]},
                {"box": "BIM & Design", "ic": "product", "tiles": [
                    tile("Autodesk Revit", "product", "Design models, quantities and clash contexts.", "revit"),
                    tile("Navisworks", "apps", "4D simulations and clash detection runs.", "navisworks"),
                    tile("Bentley iTwin", "globe", "Digital twin synchronization for infrastructure.", "itwin"),
                ]},
                {"box": "Field & Equipment", "ic": "iot", "tiles": [
                    tile("Samsara Fleet", "iot", "Equipment location, utilization and DVIR.", "samsara"),
                    tile("United Rentals Total Control", "stream", "Rental fleet hours, utilization and geofence alerts.", "united-rentals"),
                    tile("OpenSpace", "iot", "360 site capture with progress and safety analytics.", "openspace"),
                ]},
                {"box": "Safety & Quality", "ic": "gavel", "tiles": [
                    tile("ISNetworld", "gavel", "Contractor prequalification and safety scores.", "isnetworld"),
                    tile("HammerTech", "gavel", "Site inductions, permits and incident logs.", "hammertech"),
                ]},
                fed_group("Owner Reporting Mart", "Owner KPI and portfolio marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("Dodge Construction Network", "market", "Bid opportunities and project leads by geography.", "dodge"),
                tile("IFC / COBie / BCF", "chart", "openBIM model, asset and issue exchange (buildingSMART) parsed on arrival for coordination.", "rsmeans"),
                tile("OSHA Incident Data", "gavel", "Industry injury rates for safety benchmarking.", "osha"),
            ]),
            "ppl": ppl2([
                biz("GC President & COO", "Genie One",
                    "The CEO on backlog and margin; the COO on labor productivity, schedule variance and safety, watching forecast at completion and TRIR.",
                    [["Genie One", "Ask which jobs are below margin this month."], ["AI/BI", "WIP and margin on certified Metric Views."], ["Unity Catalog", "One cost code definition across ERP and field."]],
                    sub=[
                        ["Chief Executive", "backlog, forecast at completion and the margin the board is underwriting."],
                        ["Chief Operating Officer", "labor productivity, schedule variance and the safety record across the portfolio."],
                        ["Regional VP", "job-level margin and delivery risk across the region's active work."],
                    ],
                    ucs=["WIP Forecasting", "Portfolio Benchmarking", "Earned Value Mgmt", "Safety Analytics"]),
                biz("Project Managers", "AI/BI",
                    "Schedule, budget, change orders and subcontractor performance, run on CPI, SPI, RFI aging and forecast at completion.",
                    [["Project Command", "Earned value and forecast at completion by job."], ["AI/BI", "RFI and CO aging on governed Procore data."]],
                    sub=[
                        ["Senior Project Manager", "cost, schedule and change-order exposure on the largest jobs."],
                        ["Project Engineer", "RFIs, submittals and BIM coordination keeping the field unblocked."],
                        ["Cost Controller", "CPI, SPI and forecast at completion against the budget."],
                    ],
                    ucs=["Earned Value Mgmt", "Change Order Control", "Schedule Recovery", "BIM Clash Prevention"]),
                biz("Estimating", "Model Serving",
                    "Bid pricing, risk allowances and historical productivity, judged on win rate, margin sensitivity and unit-cost variance.",
                    [["Bid Analyzer", "Win probability and margin sensitivity."], ["Model Serving", "Productivity models in the estimating path."]],
                    sub=[
                        ["Chief Estimator", "bid margin, risk allowances and the win-rate target."],
                        ["Preconstruction Lead", "trade coverage, subcontractor prequalification and scope gaps before award."],
                        ["Cost Analyst", "unit-cost benchmarks and historical productivity behind each bid."],
                    ],
                    ucs=["Subcontractor Risk", "Labor Productivity", "Portfolio Benchmarking"]),
                biz("Field Superintendents", "Lakehouse//RT",
                    "Daily production, labor hours and safety observations, tracked on units per labor hour, equipment idle time and near-miss rate.",
                    [["Field Daily Log", "Production quantities vs plan in real time."], ["Lakehouse//RT", "Equipment utilization at site latency."]],
                    sub=[
                        ["General Superintendent", "crew deployment, production rates and equipment across active sites."],
                        ["Site Superintendent", "daily production against plan and the trades on the critical path."],
                        ["Field Engineer", "layout, quantities and the as-built record feeding cost."],
                    ],
                    ucs=["Labor Productivity", "Equipment Utilization", "Schedule Recovery"]),
                biz("Safety & Quality", "Apps",
                    "Incident prevention, inspections and closeout documentation, measured on TRIR, leading-indicator closure and punch-list burndown.",
                    [["Safety Dashboard", "Leading indicators before TRIR moves."], ["Apps", "Inspection apps on governed field data."]],
                    sub=[
                        ["EHS Director", "TRIR, leading-indicator closure and the OSHA reporting record."],
                        ["Safety Manager", "site inductions, permits and near-miss follow-up in the field."],
                        ["Quality Manager", "inspections, punch-list burndown and closeout documentation."],
                    ],
                    ucs=["Safety Analytics", "Subcontractor Risk", "BIM Clash Prevention"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land Procore daily logs, ERP job costs, BIM revisions and equipment telematics; own Bronze to Silver and the pager when the WIP tables stall.",
                    [["Lakeflow Connect", "Managed connectors for ERP, project-management and field sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on cost and schedule feeds."], ["Lakewatch", "Freshness on the WIP and margin tables PMs read at month-end."]],
                    sub=[
                        ["Lead Data Engineer", "the WIP and margin pipelines PMs read at month-end close."],
                        ["Ingestion Engineer", "Procore, ERP and telematics connectors landing Bronze to Silver."],
                        ["Platform Engineer", "Unity Catalog governance and the pager when a feed stalls."],
                    ],
                    ucs=["Earned Value Mgmt", "WIP Forecasting", "Equipment Utilization"]),
                biz("Data Scientists", "MLflow",
                    "Bid win-probability, productivity-forecast and safety-leading-indicator models, and whether they still hold across a new project type and region.",
                    [["Feature Store", "Job and cost-code features read identically in training and serving."], ["MLflow", "Every bid and productivity model tracked for audit and reproduction."], ["Model Serving", "Productivity and risk models scored in the estimating path."]],
                    sub=[
                        ["ML Engineer", "productivity, risk and forecast models in the estimating and PM path."],
                        ["Applied Scientist", "bid win-probability and schedule-recovery scenario models."],
                        ["MLOps Engineer", "MLflow tracking and Model Serving for every deployed model."],
                    ],
                    ucs=["Labor Productivity", "Subcontractor Risk", "Schedule Recovery"]),
                biz("App Developers", "Apps",
                    "Ship the project command, bid analyzer, field daily log and safety dashboard apps PMs and superintendents work in, next to governed job data.",
                    [["Apps", "Field and project screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for daily-log and inspection state."], ["Agent Bricks", "Agents that draft change orders and recovery plans against governed tools."]],
                    sub=[
                        ["Full-Stack Developer", "the Project Command and Field Daily Log screens PMs and crews work in."],
                        ["Mobile Developer", "the field and inspection apps superintendents use on site."],
                        ["Agent Developer", "agents drafting change orders and recovery plans on governed data."],
                    ],
                    ucs=["Change Order Control", "Safety Analytics", "Schedule Recovery"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Portfolio dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for job status in project channels."),
                    tile("Notebooks & IDEs", "notebook", "Estimating notebooks on historical cost data."),
                ]},
                {"box": "Owners & Subs", "ic": "partner", "tiles": [
                    tile("Owner Portal", "api", "Progress photos and earned value shared to owners.", "procore"),
                    tile("Subcontractor PO", "zplug", "Committed costs and pay apps to trade partners.", "viewpoint"),
                    tile("BIM Coordination", "product", "Clash reports pushed to design teams.", "navisworks"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Change Order Routing", "sheet", "Approved COs written to ERP job cost.", "sage-cre"),
                    tile("Schedule Updates", "gauge", "Percent complete fed back to P6 activities.", "primavera"),
                    tile("Equipment Dispatch", "iot", "Fleet assignments optimized and sent to yards.", "samsara"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("OSHA Logs", "gavel", "300 logs and incident summaries filed from field data.", "osha"),
                    tile("Prevailing Wage", "share", "Certified payroll reports for public works.", "viewpoint"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Project performance products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Owners and JV partners via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Project Command", "Earned value", "gauge", "SPI, CPI and forecast at completion across the active portfolio."),
             app("Bid Analyzer", "Preconstruction", "market", "Historical productivity and risk allowances applied to new bids."),
             app("Field Daily Log", "Production tracking", "stream", "Installed quantities and labor hours vs daily plan."),
             app("Safety Dashboard", "Leading indicators", "gavel", "Observations, near-misses and training gaps before TRIR rises.")],
            [uc("Earned Value Mgmt", "Finance", "chart", "CPI and SPI integrated across ERP and schedule systems.",
                problem="CPI and SPI live in the scheduler while actual cost sits in the ERP, so earned value is rebuilt by hand in spreadsheets and is stale the moment the job moves.",
                who="Project Managers",
                how="ERP job cost and P6 progress land through Lakeflow and conform on Delta Lake under Unity Catalog, so Project Command serves one certified CPI and SPI per job.",
                comps=["Project Command", "Trimble Viewpoint Vista", "Primavera P6", "Lakeflow", "Unity Catalog", "Delta Lake"],
                stories=[
                    ["Hanwha builds an integrated data system for smarter decision making", "https://www.databricks.com/customers/hanwha-corporation"],
                ]),
             uc("Change Order Control", "Commercial", "erp", "Pending and approved COs tracked against margin impact.",
                problem="Pending change orders sit in email and PM tools while their margin impact lives in the ERP, so exposure is unknown until a CO is approved and the job has already moved.",
                who="Project Managers",
                how="Procore COs and Sage job cost conform under Unity Catalog and Project Command tracks each pending and approved CO against forecast margin before it is signed.",
                comps=["Project Command", "Procore", "Sage 300 CRE", "Unity Catalog", "AI/BI", "Delta Lake"],
                stories=[
                    ["Hanwha builds an integrated data system for smarter decision making", "https://www.databricks.com/customers/hanwha-corporation"],
                ]),
             uc("Labor Productivity", "Field", "people", "Units per labor hour benchmarked by trade and job.",
                problem="Daily production and labor hours are logged on paper and in field apps, so units per labor hour by trade is only known weeks later at cost close, too late to correct.",
                who="Field Superintendents",
                how="Field Daily Log lands production quantities and hours through Lakeflow into Delta Lake, benchmarking units per labor hour by trade and job in AI/BI at site latency.",
                comps=["Field Daily Log", "Procore", "Lakeflow", "Delta Lake", "AI/BI", "Lakehouse//RT"],
                stories=[
                    ["Novade improves construction safety and efficiency with Databricks", "https://www.databricks.com/customers/novade"],
                ]),
             uc("Equipment Utilization", "Fleet", "iot", "Owned and rented assets ranked by idle time and cost.",
                problem="Owned and rented assets scatter across yards and jobsites, so idle machines keep billing while another site waits, and no one can see true utilization by asset.",
                who="Field Superintendents",
                how="Samsara and rental telematics stream into Lakehouse//RT and are joined to jobsite geofences on Delta Lake, ranking assets by idle time and cost in the Field Daily Log.",
                comps=["Field Daily Log", "Samsara Fleet", "United Rentals Total Control", "Lakehouse//RT", "Delta Lake", "AI/BI"],
                stories=[
                    ["Maximizing equipment utilization through geospatial analytics", "https://www.databricks.com/blog/maximizing-equipment-utilization-through-geospatial-analytics"],
                    ["Trackunit eliminates construction downtime on Databricks", "https://www.databricks.com/customers/trackunit"],
                ]),
             uc("BIM Clash Prevention", "Design", "product", "Clashes resolved before they become field rework.",
                problem="Clashes between structural, mechanical and electrical models surface in the field as rework, because coordination runs in siloed BIM tools disconnected from the schedule.",
                who="Project Managers",
                how="Revit and Navisworks clash runs land under Unity Catalog and are joined to P6 activities on Delta Lake, so unresolved clashes are ranked by schedule impact in AI/BI.",
                comps=["Autodesk Revit", "Navisworks", "Primavera P6", "Unity Catalog", "Delta Lake", "AI/BI"]),
             uc("Subcontractor Risk", "Supply", "zplug", "Prequalification and performance scored before award.",
                problem="Subcontractor prequalification, safety scores and past performance sit in separate systems, so trades are awarded on price without a clear view of delivery and default risk.",
                who="Estimating",
                how="ISNetworld scores and historical performance conform on Delta Lake and feed a risk model in Model Serving, surfaced through the Bid Analyzer before a trade is awarded.",
                comps=["Bid Analyzer", "ISNetworld", "Model Serving", "Unity Catalog", "Delta Lake", "MLflow"]),
             uc("Schedule Recovery", "Planning", "sheet", "Recovery options costed when critical path slips.",
                problem="When the critical path slips, recovery options are argued in meetings without cost, so crews are added or resequenced with no view of the margin hit until it is already spent.",
                who="Project Managers",
                how="P6 progress and job cost conform on Delta Lake and recovery scenarios are costed with AI Functions in Project Command, so the cheapest path back to plan is chosen fast.",
                comps=["Project Command", "Primavera P6", "AI Functions", "Model Serving", "Delta Lake", "Unity Catalog"]),
             uc("WIP Forecasting", "Finance", "erp", "Revenue and cost at completion before month-end close.",
                problem="Work-in-progress and cost at completion are assembled manually from ERP and field data at month-end, so revenue and margin are known too late to steer the job.",
                who="GC President & COO",
                how="ERP job cost and field production conform through Lakeflow on Delta Lake, and forecast-at-completion models in Model Serving publish WIP to AI/BI before close.",
                comps=["Trimble Viewpoint Vista", "Sage 300 CRE", "Lakeflow", "Model Serving", "AI/BI", "Delta Lake"],
                stories=[
                    ["Hanwha builds an integrated data system for smarter decision making", "https://www.databricks.com/customers/hanwha-corporation"],
                ]),
             uc("Safety Analytics", "EHS", "gavel", "Leading indicators predicting recordable incidents.",
                problem="Incidents are counted after they happen, while leading indicators like near-misses and inspection gaps sit in field apps no one aggregates until TRIR has already moved.",
                who="Safety & Quality",
                how="HammerTech observations and OSHA logs conform on Delta Lake and feed leading-indicator models in Model Serving, surfaced in the Safety Dashboard before TRIR rises.",
                comps=["Safety Dashboard", "HammerTech", "OSHA Incident Data", "Model Serving", "Delta Lake", "AI/BI"],
                stories=[
                    ["Novade improves construction safety and efficiency with Databricks", "https://www.databricks.com/customers/novade"],
                ]),
             uc("Portfolio Benchmarking", "Executive", "chart", "Job performance compared across regions and types.",
                problem="Job performance is compared in slide decks built by hand, so the executive team cannot see margin, schedule and safety across regions and job types on one consistent basis.",
                who="GC President & COO",
                how="Certified job margin, schedule and safety metrics conform under Unity Catalog and are compared across regions and types in AI/BI, with Genie One answering ad hoc questions.",
                comps=["Genie One", "AI/BI", "Unity Catalog", "Data Products", "Delta Lake", "SQL Warehouses"],
                stories=[
                    ["Colas unifies data across 50 countries with Databricks", "https://www.databricks.com/customers/colas"],
                    ["Hanwha builds an integrated data system for smarter decision making", "https://www.databricks.com/customers/hanwha-corporation"],
                ])],
        ),
        "sources": {
            "procore": {"t": "Procore", "u": "https://www.procore.com/"},
            "autodesk-build": {"t": "Autodesk Build", "u": "https://construction.autodesk.com/products/autodesk-build/"},
            "primavera": {"t": "Oracle Primavera P6", "u": "https://www.oracle.com/construction-engineering/primavera-p6/"},
            "viewpoint": {"t": "Trimble Viewpoint Vista", "u": "https://www.viewpoint.com/solutions/vista"},
            "sage-cre": {"t": "Sage 300 Construction", "u": "https://www.sage.com/en-us/industry/construction/"},
            "aconex": {"t": "Oracle Aconex", "u": "https://www.oracle.com/construction-engineering/aconex/"},
            "revit": {"t": "Autodesk Revit", "u": "https://www.autodesk.com/products/revit/"},
            "navisworks": {"t": "Autodesk Navisworks", "u": "https://www.autodesk.com/products/navisworks/"},
            "itwin": {"t": "Bentley iTwin", "u": "https://www.bentley.com/software/itwin/"},
            "samsara": {"t": "Samsara", "u": "https://www.samsara.com/"},
            "united-rentals": {"t": "United Rentals Total Control", "u": "https://www.unitedrentals.com/services/online-services/total-control"},
            "openspace": {"t": "OpenSpace", "u": "https://www.openspace.ai/"},
            "isnetworld": {"t": "ISNetworld", "u": "https://www.isnetworld.com/"},
            "hammertech": {"t": "HammerTech", "u": "https://www.hammertech.com/"},
            "dodge": {"t": "Dodge Construction Network", "u": "https://www.construction.com/"},
            "rsmeans": {"t": "buildingSMART openBIM (IFC/COBie/BCF)", "u": "https://www.buildingsmart.org/"},
            "osha": {"t": "OSHA", "u": "https://www.osha.gov/"},
        },
    },
}
