import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_PAPER_PACKAGING = {
    "paper_packaging": {
        "label": "Paper & Packaging",
        "blurb": "Pulp, paper, board and packaging: mill process control and quality, converting and MES, forestry and fiber supply, order-to-cash, energy and emissions, and OTIF logistics.",
        "medallion": medallion(
            "Raw mill and order feeds",
            "DCS and historian tags from the paper machines and recovery boiler, converting-line and MES events, LIMS lab results, SAP order and shipment records and forestry scale tickets, landed exactly as received so a reel or a delay can be replayed as it stood.",
            "Conformed reel, order, asset",
            "Reels, orders, grades and machines resolved into single conformed entities across the DCS, MES, quality and ERP estates, with grade codes and units of measure reconciled and reel genealogy stitched from fiber to finished roll.",
            "OEE, yield, OTIF, emissions",
            "Contracted products the mill and commercial teams run on: OEE and downtime by machine and line, first-pass yield and grade give-away, OTIF and order cycle time, and energy intensity and Scope 1-3 emissions by tonne.",
        ),
        "rails": {
            "src": [
                {
                    "box": "Mill Process Control",
                    "ic": "compute",
                    "tiles": [
                        tile("Valmet DNA DCS", "compute", "Valmet DNA distributed control system: the system of record for paper-machine, stock-prep and recovery-boiler set-points and the process time-series behind every run.", "valmet-dna",
                             cat="Distributed Control System (DCS)",
                             what="System of record for paper-machine, stock-prep and recovery-boiler set-points and the process time-series behind every run.",
                             users="DCS operators, process engineering and Reliability.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "10-100k tags/sec", "Continuous control telemetry"))),
                        tile("ABB 800xA DCS", "compute", "ABB Ability System 800xA distributed control system running the machine drives and process areas where ABB is the incumbent control backbone.", "abb-800xa",
                             cat="Distributed Control System (DCS)",
                             what="Runs the machine drives and process areas where ABB Ability System 800xA is the incumbent control backbone.",
                             users="DCS operators, controls engineering and Reliability.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "10-100k tags/sec", "Continuous control telemetry"))),
                        tile("Honeywell Experion", "compute", "Honeywell Experion PKS process control for pulp and paper areas, carrying loop set-points, alarms and process state into the estate.", "honeywell-experion",
                             cat="Distributed Control System (DCS)",
                             what="Process control for pulp and paper areas, carrying loop set-points, alarms and process state into the estate.",
                             users="Control room operators, process engineering and Reliability.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "5-50k tags/sec", "Continuous control telemetry"))),
                        tile("AVEVA PI Historian", "iot", "AVEVA PI System process historian: the high-frequency tag store that underpins OEE, sheet-break analysis and predictive maintenance.", "avevapi",
                             cat="Process/Time-Series Historian",
                             what="High-frequency process historian tag store underpinning OEE, sheet-break analysis and predictive maintenance.",
                             users="Reliability engineering, process engineering and Data science.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "10-100k tags/sec", "Continuous historian stream"))),
                    ],
                },
                {
                    "box": "Quality & MES",
                    "ic": "gauge",
                    "tiles": [
                        tile("Valmet IQ QCS", "gauge", "Valmet IQ quality control system: scanners and profile controls for basis weight, moisture, caliper and strength across paper, board, tissue and converting.", "valmet-iq",
                             cat="Quality Control System (QCS)",
                             what="Scanner and profile controls for basis weight, moisture, caliper and strength across paper, board, tissue and converting.",
                             users="Quality, process engineering and DCS operators.",
                             data_out=data_out(
                                 stream=flow(["structured"], "1-10k measurements/sec", "Continuous scan telemetry"))),
                        tile("Kiwiplan MES", "compute", "Kiwiplan production management and scheduling for corrugated and folding-carton plants: orders, machine schedules and converting genealogy.", "kiwiplan",
                             cat="Packaging MES / Scheduling",
                             what="Production management and scheduling for corrugated and folding-carton plants: orders, machine schedules and converting genealogy.",
                             users="Converting operations, scheduling and Order-to-cash.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-8 GB/day", "Nightly + hourly deltas"),
                                 stream=flow(["semi-structured"], "hundreds of events/sec", "Continuous converting events"))),
                        tile("Greycon opt-Studio", "sheet", "Greycon trim optimisation and mill production planning: cutting patterns, trim loss and machine sequencing for roll and sheet goods.", "greycon",
                             cat="Trim Optimization / Mill Planning",
                             what="Trim optimization and mill production planning: cutting patterns, trim loss and machine sequencing for roll and sheet goods.",
                             users="Mill planning, scheduling and Supply chain.",
                             data_out=data_out(
                                 batch=flow(["structured"], "GBs (patterns + plans)", "Planning cycles + on-demand"))),
                    ],
                },
                {
                    "box": "ERP & Order-to-Cash",
                    "ic": "erp",
                    "tiles": [
                        tile("SAP S/4HANA", "erp", "The ERP of record for orders, production, inventory, procurement and finance across the pulp, paper and packaging business.", "sap",
                             cat="Enterprise ERP",
                             what="System of record for orders, production, inventory, procurement and finance across the pulp, paper and packaging business.",
                             users="Order management, procurement, planning and Finance.",
                             data_out=data_out(
                                 batch=flow(["structured"], "20-80 GB/day", "Nightly batch + hourly deltas"),
                                 stream=flow(["semi-structured"], "hundreds of postings/sec", "Continuous CDC"))),
                        tile("Amtech ERP", "erp", "Amtech corrugated and packaging ERP: order entry, scheduling, costing and shipping for box plants and sheet feeders.", "amtech",
                             cat="Packaging ERP",
                             what="Corrugated and packaging ERP for order entry, scheduling, costing and shipping across box plants and sheet feeders.",
                             users="Box plant operations, scheduling and Order-to-cash.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-8 GB/day", "Nightly + hourly deltas"))),
                        tile("Salesforce CRM", "crm", "Commercial CRM for accounts, quotes and orders across brand-owner, converter and distributor customers.", "salesforce",
                             cat="Commercial CRM",
                             what="Commercial CRM for accounts, quotes and orders across brand-owner, converter and distributor customers.",
                             users="Sales, commercial and Customer service.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-2 GB/day", "Hourly sync"),
                                 stream=flow(["semi-structured"], "tens of events/sec", "Continuous CDC"))),
                        tile("Blue Yonder TMS", "orch", "Transportation management for load building, carrier selection and delivery execution behind OTIF to the customer.", "blueyonder",
                             cat="Transportation Management (TMS)",
                             what="Transportation management for load building, carrier selection and delivery execution behind OTIF to the customer.",
                             users="Logistics, distribution and Customer service.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-4 GB/day", "Hourly + event-driven"))),
                    ],
                },
                {
                    "box": "Forestry & Fiber",
                    "ic": "globe",
                    "tiles": [
                        tile("Trimble Forestry", "globe", "Forest and fiber supply management: harvest planning, wood procurement, scaling and log-yard inventory feeding the mill's fiber line.", "trimble-forestry",
                             cat="Forestry & Fiber Supply Management",
                             what="Manages harvest planning, wood procurement, scaling and log-yard inventory feeding the mill's fiber line.",
                             users="Fiber sourcing, wood procurement and Forestry planning.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-4 GB/day", "Daily + on-delivery"))),
                        tile("Log Scaling & Weigh", "iot", "Weighbridge and scaling systems capturing wood and recovered-fiber deliveries by species, moisture and supplier at the gate.",
                             cat="Weighbridge / Scaling System",
                             what="Weighbridge and scaling systems capturing wood and recovered-fiber deliveries by species, moisture and supplier at the gate.",
                             users="Wood yard, fiber sourcing and Procurement.",
                             data_out=data_out(
                                 stream=flow(["structured"], "10s-100s of tickets/hour", "Continuous gate events"))),
                        tile("Recovered Fiber Feeds", "network", "Recovered-paper and OCC intake feeds: grades, contamination and yield for recycled containerboard and packaging furnish.",
                             cat="Recovered Fiber Intake",
                             what="Recovered-paper and OCC intake feeds capturing grades, contamination and yield for recycled containerboard and packaging furnish.",
                             users="Fiber sourcing, recycling operations and Quality.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "100s of MB/day", "Per-delivery + daily"))),
                        tile("EUDR / Fiber Trace", "gavel", "Fiber-origin and chain-of-custody records supporting EU Deforestation Regulation due diligence from forest to finished pulp.", "eudr",
                             cat="Chain-of-Custody / Compliance",
                             what="Fiber-origin and chain-of-custody records supporting EU Deforestation Regulation due diligence from forest to finished pulp.",
                             users="Sustainability, fiber sourcing and Regulatory compliance.",
                             data_out=data_out(
                                 batch=flow(["structured", "unstructured"], "100s of MB/day", "Per-consignment + daily"))),
                    ],
                },
                {
                    "box": "Energy & Maintenance",
                    "ic": "zplug",
                    "tiles": [
                        tile("IBM Maximo EAM", "orch", "Enterprise asset management: work orders, PM schedules and asset history for the machines and utilities the mill runs on.", "maximo",
                             cat="Enterprise Asset Management (EAM)",
                             what="Manages maintenance work orders, PM schedules and asset history for the machines and utilities the mill runs on.",
                             users="Reliability engineering, maintenance planning and Storeroom.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Nightly + event-driven"))),
                        tile("SAP Plant Maint", "erp", "SAP Plant Maintenance work orders and notifications where PM is run inside the ERP against the same asset master.", "sap",
                             cat="Plant Maintenance (EAM)",
                             what="Runs maintenance work orders and notifications inside the ERP against the same asset master where PM is centralized.",
                             users="Maintenance planning, reliability and Plant operations.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-4 GB/day", "Nightly batch"))),
                        tile("Recovery Boiler DCS", "compute", "Recovery boiler and power-island control data: steam, black-liquor firing and generation behind the mill's energy balance.",
                             cat="Boiler / Power-Island Control",
                             what="Recovery boiler and power-island control data: steam, black-liquor firing and generation behind the mill's energy balance.",
                             users="Energy management, boiler operations and Reliability.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "5-50k tags/sec", "Continuous control telemetry"))),
                        tile("Energy & Utilities", "gauge", "Steam, power, gas and water metering across the mill, the basis for energy intensity per tonne and emissions accounting.",
                             cat="Energy & Utility Metering",
                             what="Steam, power, gas and water metering across the mill, the basis for energy intensity per tonne and emissions accounting.",
                             users="Energy management, ESG and Finance.",
                             data_out=data_out(
                                 stream=flow(["structured"], "100s-1000s of readings/sec", "Continuous metering"))),
                    ],
                },
                fed_group("Cost & ESG Marts", "Historical cost, emissions and quality marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers.",
                          cat="Enterprise Data Warehouse",
                          what="Historical cost, emissions and quality marts kept in the incumbent warehouse and queried in place through federation instead of copied.",
                          users="Finance, ESG reporting and Executive analytics.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("OPC UA / MQTT Events", "stream", "Mill DCS, historian and converting-machine events over OPC UA and MQTT, parsed on arrival and landed as structured events.",
                     cat="OT Protocol Gateway",
                     what="Carries mill DCS, historian and converting-machine events over OPC UA and MQTT, parsed on arrival and landed as structured events.",
                     users="OT/IT integration, controls engineering and Streaming data teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "10-100k events/sec", "Continuous OT telemetry"))),
                tile("Pulp Price Indices", "market", "Pulp, containerboard and recovered-paper price benchmarks joined to orders and margin for commercial and buying decisions.",
                     cat="Commodity Price Benchmarks",
                     what="Supplies pulp, containerboard and recovered-paper price benchmarks joined to orders and margin for commercial and buying decisions.",
                     users="Commercial, buying and Margin analytics.",
                     data_out=data_out(
                         batch=flow(["structured"], "10s of MB", "Periodic price assessments"))),
                tile("Weather & Freight", "globe", "External weather and freight-rate feeds used for logistics planning, energy demand and OTIF risk.",
                     cat="External Weather & Freight Data",
                     what="Provides external weather and freight-rate feeds used for logistics planning, energy demand and OTIF risk modeling.",
                     users="Logistics, energy management and Supply chain planning.",
                     data_out=data_out(
                         batch=flow(["structured", "semi-structured"], "100s of MB/day", "Daily + intraday updates"))),
            ]),
            "ppl": ppl2([
                biz("Executive Team", "Genie One",
                    "The CEO and mill-group leadership on margin per tonne, capacity and the trade between fiber cost and energy; the CFO on unit cost and working capital tied up in reels and inventory; the COO on OEE, safety and the reliability of the machines the mill runs on.",
                    [["Genie One", "Ask what a machine or a grade cost last week, or where downtime went, without booking analyst time."],
                     ["AI/BI", "OEE, unit cost, yield and OTIF on one certified set of Metric Views."],
                     ["Unity Catalog", "Certification and the business glossary, so \"OEE\" and \"yield\" mean one thing across every mill."]],
                    sub=[["CEO & Group", "margin per tonne, capacity and the fiber-versus-energy trade."],
                         ["CFO & Finance", "unit cost and working capital tied up in reels and inventory."],
                         ["COO", "OEE, safety and machine reliability across the fleet of mills."]],
                    ucs=["OEE & Downtime", "Demand & S&OP", "Emissions & ESG", "OTIF & Logistics"]),
                biz("Mill Operations", "Lakehouse//RT",
                    "Shift managers and DCS operators running the paper machines and recovery boiler, converting and finishing on corrugator and folding-carton lines, and reliability engineering on the assets whose failure stops the machine.",
                    [["Mill Control Tower", "Live OEE, downtime and throughput by machine and line at the latency a run moves at."],
                     ["Lakehouse//RT", "DCS, historian and MES state streamed for real-time operations."],
                     ["Model Serving", "Break-risk and reliability models scored against live machine state."]],
                    sub=[["Shift & DCS operators", "the paper machine and recovery boiler on the current run."],
                         ["Converting & finishing", "corrugator and folding-carton line performance."],
                         ["Reliability eng", "the assets whose failure stops the machine."]],
                    ucs=["Predictive Maintenance", "OEE & Downtime", "Sheet Break Reduction", "Energy Optimization"]),
                biz("Process & QA", "Model Serving",
                    "Process engineers on digester, refiner and dryer set-points, quality on basis weight, moisture and strength against grade spec, and R&D and fiber on furnish, additives and new-grade development.",
                    [["Quality & Grade Cockpit", "Basis weight, moisture and defect trends against grade spec by reel."],
                     ["Model Serving", "Break-risk, defect and quality models scored inside the control loop."],
                     ["AI Functions", "Lab notes, defect images and complaints classified at scale from unstructured data."]],
                    sub=[["Process engineering", "digester, refiner and dryer set-points."],
                         ["Quality", "basis weight, moisture and strength against grade spec."],
                         ["R&D & fiber", "furnish, additives and new-grade development."]],
                    ucs=["Quality & Defect Detection", "Sheet Break Reduction", "Grade & Yield"]),
                biz("Supply Chain", "AI/BI",
                    "Demand planning and S&OP balancing orders against machine time and trim, order-to-cash and customer service on order status and claims, and logistics on warehouse, carrier and OTIF to the converter and brand owner.",
                    [["AI/BI", "Demand, order cycle time and OTIF on the definitions the commercial team already reports."],
                     ["Model Serving", "Demand and OTIF-risk models scored into planning and dispatch."],
                     ["Genie One", "Ask which orders are at risk of missing OTIF this week."]],
                    sub=[["Demand & S&OP", "orders balanced against machine time and trim."],
                         ["Order-to-cash & service", "order status, claims and credit."],
                         ["Logistics", "warehouse, carrier and OTIF to the customer."]],
                    ucs=["Demand & S&OP", "OTIF & Logistics", "Fiber & Forestry"]),
                biz("Energy & ESG", "Genie One",
                    "Energy managers on steam, power and the recovery boiler, ESG and sustainability on Scope 1-3 emissions and CSRD reporting, and fiber sourcing on wood, recovered fiber and deforestation-free supply.",
                    [["AI/BI", "Energy intensity and Scope 1-3 emissions per tonne on certified views."],
                     ["Genie One", "Ask which mill and grade drove this month's emissions and energy cost."],
                     ["Unity Catalog", "Fiber-origin and emissions lineage governed for EUDR and CSRD audit."]],
                    sub=[["Energy management", "steam, power and the recovery boiler."],
                         ["ESG & sustainability", "Scope 1-3 emissions and CSRD reporting."],
                         ["Fiber sourcing", "wood, recovered fiber and deforestation-free supply."]],
                    ucs=["Energy Optimization", "Emissions & ESG", "Fiber & Forestry"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land DCS and historian tags over OPC UA, MES and converting events, LIMS results and SAP order and shipment feeds; own the Bronze to Silver path and the pager when the mill tables stall.",
                    [["Lakeflow Connect", "Managed connectors for SAP, MES, LIMS and quality sources."],
                     ["Auto Loader", "Historian and converting-line event files landed incrementally into Bronze."],
                     ["Lakewatch", "Freshness on the OEE and order tables ops and planning read each morning."]]),
                biz("Data Scientists", "MLflow",
                    "Sheet-break, defect, remaining-useful-life and demand models off historian, LIMS and order data, and whether they still hold as grades and furnish change.",
                    [["Feature Store", "Machine, reel and grade features read identically in training and serving."],
                     ["MLflow", "Every break-risk and reliability model tracked for audit and reproduction."],
                     ["Model Serving", "Break-risk, defect and demand models scored in the operational path."]]),
                biz("App Developers", "Apps",
                    "Ship the mill-control, reliability, quality and planning applications the business works in, hosted next to governed data.",
                    [["Apps", "Operational screens with no separate web tier to run or secure."],
                     ["Lakebase", "Serverless Postgres for run-state, work orders and planning writes."],
                     ["Agent Bricks", "Agents that draft a work order or a recovery action against governed tools."]]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Power BI / Tableau", "chart", "Executive and mill dashboards against serverless SQL warehouses, with Unity Catalog permissions enforced end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for OEE, yield and OTIF answers in the channel operations and planning already work in (Beta)."),
                    tile("Notebooks & IDEs", "notebook", "Process-engineering and data-science notebooks against governed mill and quality data."),
                ]},
                {"box": "Customers & Partners", "ic": "partner", "tiles": [
                    tile("Customer & EDI Portals", "api", "Order, ASN and OTIF status served to brand owners and converters over EDI and portals."),
                    tile("Converter & 3PL Share", "share", "Converting partners and 3PLs reading live schedule, inventory and delivery tables over Open Sharing."),
                    tile("Recyclers & Fiber", "globe", "Recovered-fiber suppliers and recyclers exchanging grade, volume and quality data with the mill."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("DCS Setpoint Write", "compute", "Recommended set-points and grade targets written back toward the DCS so the answer reaches the control loop.", "valmet-dna"),
                    tile("Maximo Work Orders", "orch", "Predicted failures raised as maintenance work orders against the asset, in the system reliability already works in.", "maximo"),
                    tile("ERP Order & Trim", "erp", "Production, trim and reallocation decisions written back into the ERP so planning acts on the same numbers.", "sap"),
                ]},
                {"box": "Regulatory & ESG", "ic": "gavel", "tiles": [
                    tile("EUDR & Fiber Trace", "gavel", "Fiber chain-of-custody and due-diligence statements filed for EU Deforestation Regulation from governed forestry tables.", "eudr"),
                    tile("Emissions Reporting", "share", "Scope 1-3 emissions and CSRD disclosures produced from the same certified Gold tables the mill runs on."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Published, contracted mill, quality and supply-chain products discoverable in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Converters, brand owners and fiber partners reading live tables with no copy and no egress duplication."),
                ]},
            ], genie_spaces=[
                genie("Mill OEE & Downtime", "Ask about OEE, downtime and throughput by machine and line in plain language.",
                      feeds=["Valmet DNA DCS", "AVEVA PI Historian", "Kiwiplan MES", "OEE, yield, OTIF, emissions"],
                      teams=["Mill Operations", "Executive Team", "Shift & DCS operators"],
                      questions=[
                          "What was OEE by machine and line yesterday, and where did downtime go?",
                          "Which downtime reasons cost the most tonnes this week?",
                          "What is throughput by grade against plan right now?",
                          "Which machines had the most sheet breaks this shift?",
                          "What is unit cost by machine and grade last week?"]),
                genie("Quality & Grade", "Explore basis weight, moisture, defects and grade give-away by reel.",
                      feeds=["Valmet IQ QCS", "AVEVA PI Historian", "Greycon opt-Studio", "Conformed reel, order, asset"],
                      teams=["Process & QA", "Quality", "Process engineering"],
                      questions=[
                          "What is first-pass yield and grade give-away by grade this month?",
                          "Which reels are trending off-spec on basis weight or moisture?",
                          "Which defect types are most common by machine and grade?",
                          "Where is trim loss highest across the order book?",
                          "Which set-points correlate with the current quality drift?"]),
                genie("Supply Chain & OTIF", "Answer demand, order-cycle and OTIF-risk questions across the network.",
                      feeds=["SAP S/4HANA", "Blue Yonder TMS", "Amtech ERP", "OEE, yield, OTIF, emissions"],
                      teams=["Supply Chain", "Demand & S&OP", "Logistics"],
                      questions=[
                          "Which orders are at risk of missing OTIF this week?",
                          "What is order cycle time by grade and customer?",
                          "Where is demand outrunning available machine time and trim?",
                          "Which customers drive the most claims and short shipments?",
                          "What is forecast accuracy by grade versus last quarter?"]),
                genie("Energy & ESG", "Ask about energy intensity, emissions and fiber-origin compliance.",
                      feeds=["Recovery Boiler DCS", "Energy & Utilities", "EUDR / Fiber Trace", "OEE, yield, OTIF, emissions"],
                      teams=["Energy & ESG", "Energy management", "Fiber sourcing"],
                      questions=[
                          "What is energy intensity per tonne by mill and grade this month?",
                          "Which mill and grade drove this month's Scope 1-2 emissions?",
                          "Where can recovery-boiler and steam set-points cut energy cost?",
                          "Which fiber consignments lack complete EUDR chain-of-custody?",
                          "What is Scope 3 emissions per tonne by fiber source?"]),
            ], dashboards=[
                dashboard("Mill OEE & Downtime", "OEE, downtime pareto and throughput by machine and line on certified Metric Views.",
                          kpis=["OEE", "Downtime by reason", "Throughput", "Sheet breaks", "Unit cost"],
                          teams=["Mill Operations", "Executive Team", "Reliability eng"]),
                dashboard("Quality & Grade", "First-pass yield, grade give-away, defects and trim loss by reel.",
                          kpis=["First-pass yield", "Grade give-away", "Defect rate", "Trim loss", "Break rate"],
                          teams=["Process & QA", "Quality", "R&D & fiber"]),
                dashboard("Supply Chain & OTIF", "Demand, order cycle time and OTIF risk across the order book.",
                          kpis=["OTIF", "Order cycle time", "Forecast accuracy", "Claims rate", "Plan attainment"],
                          teams=["Supply Chain", "Demand & S&OP", "Logistics"]),
                dashboard("Energy & Emissions", "Energy intensity, Scope 1-3 emissions and fiber-origin compliance.",
                          kpis=["Energy intensity per tonne", "Scope 1-2 emissions", "Scope 3 per tonne", "Recovery-boiler efficiency", "EUDR coverage"],
                          teams=["Energy & ESG", "Energy management", "Fiber sourcing"]),
            ]),
        },
        "top": top_band(
            [
                app("Mill Control Tower", "Live OEE & downtime", "gauge",
                    "The screen the shift runs the mill from: live OEE, downtime reasons and throughput by machine and line, with energy and grade context, on Databricks Apps over Lakebase."),
                app("Reliability Watchtower", "Asset health", "iot",
                    "Asset health and predicted failures by machine and utility, so reliability plans the fix at a maintenance window instead of discovering it as a break."),
                app("Quality & Grade Cockpit", "Quality & grade", "chart",
                    "Where process and quality see basis weight, moisture, defect and break trends against grade spec by reel, before the roll ships off-spec."),
                app("S&OP & OTIF Planner", "Planning & delivery", "sheet",
                    "Demand, machine time, trim and delivery balanced in one place, flagging the orders that will miss OTIF while there is still time to move them."),
            ],
            [
                uc("OEE & Downtime", "Reliability", "gauge",
                    "Overall equipment effectiveness and downtime attacked at the machine and line, with losses attributed to the right area and shift in near real time.",
                    problem="OEE and downtime are reviewed the next morning from manual logs, so a losing shift is explained after the tonnes are gone rather than corrected while the run is live.",
                    who="Mill Operations",
                    how="DCS, historian and MES feeds stream into Lakehouse//RT; OEE and downtime are computed on certified Metric Views and surfaced live on the Mill Control Tower with break-risk scored in Model Serving.",
                    comps=["Mill Control Tower", "Lakehouse//RT", "Valmet DNA DCS", "AI/BI", "Model Serving"],
                    stories=[["Databricks: agents for production lines and in-shift OEE recovery", "https://www.databricks.com/blog/agents-production-lines-trusted-decisions-real-time"],
                             ["Multi-factory OEE solution accelerator", "https://www.databricks.com/blog/2022/11/29/solution-accelerator-multi-factory-overall-equipment-effectiveness.html"]]),
                uc("Predictive Maintenance", "Reliability", "iot",
                    "Predicting failures on dryers, rolls, pumps and drives from sensor and historian data so an unplanned break becomes a planned maintenance window.",
                    problem="An unplanned failure on a dryer or drive tears the sheet and stops the machine for hours; maintenance run on a calendar fixes healthy assets and misses the ones about to fail.",
                    who="Mill Operations",
                    how="Historian vibration and process tags feed remaining-useful-life models tracked in MLflow and scored in Model Serving; predicted failures raise Maximo work orders from the Reliability Watchtower.",
                    comps=["Reliability Watchtower", "AVEVA PI Historian", "IBM Maximo EAM", "Model Serving", "MLflow", "Lakehouse//RT"],
                    stories=[["Predictive maintenance on paper and pulp dryers (DeepIQ + Databricks)", "https://www.databricks.com/blog/2020/07/28/industrial-iot-analytics-with-deepiq-datastudio-and-databricks.html"],
                             ["Predictive maintenance on the Databricks Lakehouse", "https://www.databricks.com/blog/what-is-predictive-maintenance"]]),
                uc("Sheet Break Reduction", "Runnability", "stream",
                    "Predicting web and sheet breaks from wet-end and dryer conditions so the operator stabilises the machine before the sheet lets go.",
                    problem="A sheet break costs tens of minutes of production and a threading effort, and the conditions that cause it hide in high-frequency wet-end and dryer data no operator can watch by eye.",
                    who="Process & QA",
                    how="Historian and QCS signals are conformed and served in Lakehouse//RT; break-risk models use Feature Store features and score in Model Serving, warning the operator through the Quality & Grade Cockpit before a break.",
                    comps=["Quality & Grade Cockpit", "AVEVA PI Historian", "Model Serving", "Feature Store", "Lakehouse//RT"],
                    stories=[["Databricks for Manufacturing", "https://www.databricks.com/solutions/industries/manufacturing-industry-solutions"],
                             ["What is Overall Equipment Effectiveness (OEE)?", "https://www.databricks.com/blog/what-is-overall-equipment-effectiveness"]]),
                uc("Quality & Defect Detection", "Quality", "chart",
                    "Surface defects, holes and streaks caught with machine vision and QCS data, with root cause narrowed to the station and set-point that produced them.",
                    problem="Defects are found at inspection or by the customer, and QCS and camera data live apart from the process record, so root cause is reconstructed by hand long after the reel is made.",
                    who="Process & QA",
                    how="QCS measurements and web-inspection images are conformed on the lakehouse; computer-vision and defect models trained with MLflow score in Model Serving, and AI Functions classify defect and complaint text at scale.",
                    comps=["Quality & Grade Cockpit", "Valmet IQ QCS", "Model Serving", "AI Functions", "MLflow"],
                    stories=[["Corning: end-to-end ML and computer-vision defect detection on Databricks", "https://www.databricks.com/blog/2023/01/05/how-corning-built-end-end-ml-databricks-lakehouse-platform.html"],
                             ["Corning accelerates manufacturing quality with the Databricks Platform", "https://www.databricks.com/customers/corning-mosaic-ai"]]),
                uc("Grade & Yield", "Efficiency", "sheet",
                    "Basis-weight give-away, fiber yield and trim loss reduced by scoring the economical optimum for each grade rather than running to a safe margin.",
                    problem="Machines are run heavy to stay inside spec, giving away fiber on every tonne, while trim loss and off-quality eat yield that no single system measures end to end.",
                    who="Process & QA",
                    how="QCS, furnish and order data are conformed to certified Metric Views; give-away and trim are optimised with Greycon patterns and Model Serving recommendations surfaced in the Quality & Grade Cockpit.",
                    comps=["Quality & Grade Cockpit", "Valmet IQ QCS", "Greycon opt-Studio", "Model Serving", "AI/BI"],
                    stories=[["Databricks for Manufacturing", "https://www.databricks.com/solutions/industries/manufacturing-industry-solutions"]]),
                uc("Demand & S&OP", "Planning", "market",
                    "Demand forecast to grade and customer, balanced against machine time and trim so the mill plans what it can sell and make profitably.",
                    problem="Demand, machine capacity and trim are planned in separate tools, so the mill either builds inventory it cannot sell or misses orders it could have run, and forecast accuracy never improves.",
                    who="Supply Chain",
                    how="Order, shipment and price feeds are conformed to Gold; demand models score in Model Serving and feed the S&OP & OTIF Planner where capacity and trim are balanced on the same numbers finance reads.",
                    comps=["S&OP & OTIF Planner", "SAP S/4HANA", "Greycon opt-Studio", "Model Serving", "AI/BI"],
                    stories=[["Mondelez scales SKU demand forecasting on Databricks", "https://www.databricks.com/customers/mondelez"],
                             ["Smarter supply chains with data and AI", "https://www.databricks.com/blog/smarter-supply-chains-data-and-ai-why-its-time-rethink-inventory-management"]]),
                uc("OTIF & Logistics", "Delivery", "globe",
                    "On-time-in-full protected by predicting which orders will miss and moving production, inventory or carrier before the delivery fails.",
                    problem="OTIF is measured after the miss, when a late order or short shipment has already cost a penalty and a brand-owner escalation that no dashboard prevented.",
                    who="Supply Chain",
                    how="ERP order, warehouse and TMS feeds are joined in the lakehouse; OTIF-risk models score each order in Model Serving and the S&OP & OTIF Planner flags at-risk deliveries in time to act.",
                    comps=["S&OP & OTIF Planner", "Blue Yonder TMS", "SAP S/4HANA", "Model Serving", "AI/BI"],
                    stories=[["Barilla streamlines manufacturing and supplier OTIF on Databricks", "https://www.databricks.com/customers/barilla"],
                             ["Digital supply chain reference architecture for manufacturing", "https://www.databricks.com/resources/architectures/manufacturing-digital-supply-chain-reference-architecture"]]),
                uc("Energy Optimization", "Energy", "gauge",
                    "Steam, power and recovery-boiler operation optimised so the mill cuts its largest variable cost without putting the machine's runnability at risk.",
                    problem="Energy is the mill's largest controllable cost, but steam and power are run to habit, and the levers that would cut them sit in DCS and metering data nobody optimises together.",
                    who="Energy & ESG",
                    how="Recovery-boiler, utility and historian data are conformed to Gold; energy models score in Model Serving and recommendations are surfaced on the Mill Control Tower against production targets.",
                    comps=["Mill Control Tower", "Recovery Boiler DCS", "AVEVA PI Historian", "Model Serving", "AI/BI"],
                    stories=[["Shell optimises operations and energy with Databricks", "https://www.databricks.com/customers/shell"],
                             ["Sustainability reference architecture for manufacturing", "https://www.databricks.com/resources/architectures/sustainability-reference-architecture-for-manufacturing"]]),
                uc("Emissions & ESG", "Sustainability", "product",
                    "Scope 1-3 emissions and product carbon footprint per tonne computed from governed mill, energy and fiber data for CSRD and customer disclosure.",
                    problem="Emissions and carbon-footprint numbers are assembled by hand from energy, production and fiber systems, so CSRD and customer requests take weeks and never tie back to the audited operation.",
                    who="Energy & ESG",
                    how="Energy, production and fiber-origin data are conformed under Unity Catalog with lineage; emissions and footprint are computed to certified Gold and filed through Emissions Reporting.",
                    comps=["Emissions Reporting", "SAP S/4HANA", "Unity Catalog", "AI/BI", "Cost & ESG Marts"],
                    stories=[["How Dow built a carbon footprint ledger on Databricks", "https://www.databricks.com/blog/how-dow-built-carbon-footprint-ledger-databricks-accelerate-sustainability-scale"],
                             ["Sustainability reference architecture for manufacturing", "https://www.databricks.com/resources/architectures/sustainability-reference-architecture-for-manufacturing"]]),
                uc("Fiber & Forestry", "Supply", "network",
                    "Wood and recovered-fiber supply planned and traced from forest and recycler to the fiber line, with deforestation-free due diligence built in.",
                    problem="Fiber is the mill's largest raw-material spend and now its biggest compliance exposure; harvest, procurement and recovered-fiber data are scattered, and EUDR due diligence is a manual paper chase.",
                    who="Supply Chain",
                    how="Forestry, scaling and recovered-fiber feeds are conformed on the lakehouse; supply and quality are read in AI/BI and Genie, and fiber-origin lineage under Unity Catalog supports EUDR chain-of-custody.",
                    comps=["Trimble Forestry", "EUDR / Fiber Trace", "Unity Catalog", "AI/BI", "Genie"],
                    stories=[["Smarter supply chains with data and AI", "https://www.databricks.com/blog/smarter-supply-chains-data-and-ai-why-its-time-rethink-inventory-management"],
                             ["Digital supply chain reference architecture for manufacturing", "https://www.databricks.com/resources/architectures/manufacturing-digital-supply-chain-reference-architecture"]]),
            ],
        ),
        "sources": {
            "valmet-dna": {"t": "Valmet DNA distributed control system", "u": "https://www.valmet.com/automation/control-systems/valmet-dna/"},
            "abb-800xa": {"t": "ABB Ability System 800xA", "u": "https://new.abb.com/control-systems/system-800xa"},
            "honeywell-experion": {"t": "Honeywell Experion PKS", "u": "https://process.honeywell.com/us/en/products/control-monitoring-and-safety-systems/integrated-control-and-safety-systems/experion-pks"},
            "avevapi": {"t": "AVEVA PI System", "u": "https://www.aveva.com/en/products/aveva-pi-system/"},
            "valmet-iq": {"t": "Valmet IQ Quality Control System", "u": "https://www.valmet.com/automation/quality-management/quality-control-system-qcs/"},
            "kiwiplan": {"t": "Kiwiplan packaging MES", "u": "https://www.kiwiplan.com/"},
            "greycon": {"t": "Greycon trim optimisation and planning", "u": "https://www.greycon.com/"},
            "sap": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "amtech": {"t": "Amtech corrugated & packaging ERP", "u": "https://www.amtechsoftware.com/"},
            "salesforce": {"t": "Salesforce Manufacturing Cloud", "u": "https://www.salesforce.com/products/manufacturing-cloud/"},
            "blueyonder": {"t": "Blue Yonder transportation management", "u": "https://blueyonder.com/solutions/transportation-management"},
            "trimble-forestry": {"t": "Trimble Forestry", "u": "https://forestry.trimble.com/"},
            "maximo": {"t": "IBM Maximo asset management", "u": "https://www.ibm.com/products/maximo"},
            "eudr": {"t": "EU Deforestation Regulation (EUDR)", "u": "https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en"},
        },
    }
}
