import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_AEROSPACE_SPACE = {
    "aerospace_space": {
        "label": "Aerospace & Space",
        "blurb": "Aerospace OEMs, satellite operators and launch providers: PLM and the digital thread, MES and supply chain, MRO and fleet reliability, satellite telemetry, mission ops and earned-value program control.",
        "medallion": medallion(
            "Raw engineering and telemetry feeds",
            "CATIA and Teamcenter change orders, Opcenter and Apriso lot and process records, CCSDS satellite telemetry and ground downlink, engine and test-stand streams, Deltek cost and schedule actuals, landed exactly as received so a design change or a telemetry pass can be replayed as it stood.",
            "Conformed program, part, vehicle",
            "Programs, parts, serial numbers, satellites and engines resolved into single conformed entities across PLM, MES, MRO and mission systems, with the as-designed, as-planned and as-built configurations reconciled and every serial stitched from component to flight.",
            "EVM, yield, fleet reliability",
            "Contracted products the program and operations teams run on: earned-value cost and schedule variance by control account, first-pass yield and OEE by line, satellite and fleet reliability by vehicle, and anomaly and removal rates by subsystem.",
        ),
        "rails": {
            "src": [
                {
                    "box": "PLM & Engineering",
                    "ic": "dev",
                    "tiles": [
                        tile("CATIA / 3DEXPERIENCE", "dev", "Dassault Systèmes design and MBSE backbone: the system of record for CAD, requirements and the model-based definition of the vehicle.", "catia"),
                        tile("Siemens Teamcenter", "erp", "PLM for BOM, requirements, change orders and configuration management where Teamcenter is the incumbent digital thread.", "teamcenter"),
                        tile("PTC Windchill", "dev", "Product lifecycle management for design data, change control and the as-designed configuration on programs standardised on Windchill.", "windchill"),
                        tile("Ansys Simulation", "compute", "Structural, thermal and CFD simulation results and reduced-order models validated against physical test.", "ansys"),
                    ],
                },
                {
                    "box": "Manufacturing & ERP",
                    "ic": "erp",
                    "tiles": [
                        tile("Siemens Opcenter MES", "compute", "Manufacturing execution: electronic work instructions, as-built records, genealogy and in-line quality on the pulse line.", "opcenter"),
                        tile("DELMIA Apriso", "compute", "MES for production, quality and traceability across discrete aerostructures and assembly where Apriso is the incumbent.", "apriso"),
                        tile("SAP S/4HANA", "erp", "The ERP of record for procurement, inventory, production orders and finance across the aerospace and space business.", "sap"),
                        tile("AVEVA PI Historian", "iot", "Process and test historian: equipment, engine and test-stand time-series underpinning SPC, OEE and anomaly detection.", "avevapi"),
                    ],
                },
                {
                    "box": "Program & EVM",
                    "ic": "sheet",
                    "tiles": [
                        tile("Deltek Cobra EVM", "sheet", "Earned-value management: the cost and schedule performance baseline, control accounts and variance the customer contract is measured against.", "cobra"),
                        tile("Oracle Primavera P6", "sheet", "Integrated master schedule: activities, critical path and resource loading across the program and its suppliers.", "primavera"),
                        tile("Deltek Costpoint", "erp", "Government-contracting ERP for project accounting, timekeeping and DCAA-compliant cost tracking on defense and space programs.", "costpoint"),
                    ],
                },
                {
                    "box": "Satellite & Ground",
                    "ic": "stream",
                    "tiles": [
                        tile("Kratos OpenSpace", "stream", "Software-defined satellite ground system: telemetry, tracking and command and the orchestration of the ground segment.", "kratos"),
                        tile("Ansys STK", "globe", "Systems Tool Kit: orbit, coverage and mission analysis, the reference for where a satellite is and what it can see.", "stk"),
                        tile("CCSDS Telemetry", "stream", "Space-standard telemetry and command frames from the spacecraft, decommutated on arrival and landed as structured events.", "ccsds"),
                        tile("GMV Ground Segment", "network", "Flight dynamics and satellite control ground software feeding orbit, health and manoeuvre state into the estate.", "gmv"),
                    ],
                },
                {
                    "box": "MRO & Reliability",
                    "ic": "orch",
                    "tiles": [
                        tile("IFS Maintenix", "orch", "Aviation maintenance of record: work orders, component lifing, service bulletins and the reliability history against each serial.", "maintenix"),
                        tile("Engine Health Monitor", "iot", "On-wing engine condition monitoring: vibration, temperature and performance parameters streamed from the delivered fleet."),
                        tile("Test & Flight Data", "iot", "Flight-test, DFDR and test-stand instrumentation, the ground truth for qualification, reliability and anomaly investigation."),
                    ],
                },
                fed_group("EVM & Cost Marts", "Historical earned-value, cost and program marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers."),
            ],
            "ing": ing_rail([
                tile("Ground Station Feeds", "stream", "Telemetry, tracking and command downlink from KSAT and teleport networks, parsed on arrival and landed as CCSDS frames and structured events.", "ksat"),
                tile("Supplier EDI / Ariba", "api", "Supplier EDI, advance-ship-notice and purchase-order messages from the extended supply base exchanged through SAP Ariba and integration hubs.", "ariba"),
                tile("Test & Telemetry Bus", "stream", "MQTT and Kafka topics carrying engine, test-stand and satellite telemetry, landed incrementally as structured events."),
            ]),
            "ppl": ppl2([
                biz("Program Leaders", "Genie One",
                    "Program directors on cost, schedule and earned-value performance across the portfolio; the CFO and finance on contract margin, cost of quality and cash across programs; the chief engineer on technical performance, risk and design maturity.",
                    [["Program Cockpit", "Cost, schedule and earned-value variance on a program at a glance before the monthly review."],
                     ["AI/BI", "EVM, supplier risk and quality escapes on one certified set of Metric Views."],
                     ["Genie One", "Ask what drove this month's cost variance without waiting on a controls analyst."]],
                    sub=[["Program directors", "cost, schedule and earned-value performance across the portfolio."],
                         ["CFO & finance", "contract margin, cost of quality and cash across programs."],
                         ["Chief engineer", "technical performance, risk and design maturity."]],
                    ucs=["Program EVM & Risk", "Supply Chain Risk", "Digital Thread"]),
                biz("Eng & Design", "AI/BI",
                    "Systems engineering on requirements and design maturity in the digital thread, structural, thermal and CFD analysts validating models against test, and MBSE teams keeping CATIA, Teamcenter and Windchill in one coherent thread.",
                    [["Digital Thread View", "Requirements traced to as-designed and as-built with no manual reconciliation."],
                     ["MLflow", "Simulation surrogate and reliability models tracked for design reviews and audit."],
                     ["Unity Catalog", "Requirements, CAD and change control governed with lineage across the estate."]],
                    sub=[["Systems engineering", "requirements and design maturity in the digital thread."],
                         ["Simulation & analysis", "structural, thermal and CFD models validated against test."],
                         ["Design & MBSE", "CATIA, Teamcenter and Windchill kept in one coherent thread."]],
                    ucs=["Digital Thread", "Simulation & Test", "Geospatial Intelligence"]),
                biz("Mfg & Quality", "Lakehouse//RT",
                    "Production and assembly on rate, takt and station performance, quality and MRB on nonconformance and first-pass yield, and supply chain on part availability and supplier quality across the extended aerospace supply base.",
                    [["Yield & MRB Cockpit", "Station yield and nonconformance flagged before a unit is at risk."],
                     ["Lakehouse//RT", "Live MES and historian state at the latency a pulse line moves at."],
                     ["Model Serving", "Defect and supplier-risk models scored against in-line inspection."]],
                    sub=[["Production & assembly", "rate, takt and station performance on the line."],
                         ["Quality & MRB", "nonconformance, MRB disposition and first-pass yield."],
                         ["Supply chain", "part availability and supplier quality across the supply base."]],
                    ucs=["MES Yield & Quality", "Supply Chain Risk", "Predictive Maintenance"]),
                biz("Mission & Fleet", "Lakehouse//RT",
                    "Mission operations on satellite health, orbits and anomaly response, the ground segment on telemetry, tracking and command across the constellation, and fleet reliability on engine and airframe health across the delivered fleet.",
                    [["Mission Control", "Satellite health and anomalies triaged from live telemetry in one cockpit."],
                     ["Lakehouse//RT", "Constellation telemetry at the latency an anomaly has to be caught at."],
                     ["Model Serving", "Anomaly and remaining-useful-life models scored in the operational path."]],
                    sub=[["Mission operations", "satellite health, orbits and anomaly response."],
                         ["Ground segment", "telemetry, tracking and command across the constellation."],
                         ["Fleet reliability", "engine and airframe health across the delivered fleet."]],
                    ucs=["Satellite Telemetry", "Anomaly Detection", "Predictive Maintenance", "Geospatial Intelligence"]),
                biz("Compliance & Sec", "Unity Catalog",
                    "Export and ITAR control over technical data and licensing, compliance and audit on AS9100, DO-178C and contract terms, and security over controlled unclassified information and who may see which part of the program.",
                    [["Unity Catalog", "Row, column and tag policy so controlled technical data reaches only cleared people."],
                     ["AI Functions", "Export markings and control classifications inferred across documents at scale."],
                     ["Genie One", "Ask who accessed a controlled dataset this quarter without a manual audit pull."]],
                    sub=[["Export & ITAR", "controlled technical data and export licensing."],
                         ["Compliance & audit", "AS9100, DO-178C and contract compliance."],
                         ["Security", "controlled unclassified information and access."]],
                    ucs=["ITAR & Export Control", "Program EVM & Risk", "Digital Thread"]),
            ], [
                biz("Telemetry Eng", "Lakeflow",
                    "Land satellite, engine and test telemetry over CCSDS, MQTT and Kafka, PLM and MES feeds and the ground-network downlink; own the Bronze to Silver path and the pager when the telemetry tables stall.",
                    [["Lakeflow Connect", "Managed connectors for PLM, ERP, MES and program-controls sources."],
                     ["Zerobus", "Gigabytes of engine and test telemetry pushed straight to the lakehouse with no message bus."],
                     ["Lakewatch", "Freshness on the mission and fleet tables ops reads every pass."]]),
                biz("Sim & ML Eng", "MLflow",
                    "Anomaly detection, remaining-useful-life, simulation surrogate and demand models, and whether they still hold as vehicles, orbits and processes change.",
                    [["Feature Store", "Vehicle, engine and telemetry features read identically in training and serving."],
                     ["MLflow", "Every anomaly and RUL model tracked for design review, audit and reproduction."],
                     ["Model Serving", "Anomaly and RUL models scored in the mission and fleet path."]]),
                biz("Mission App Dev", "Apps",
                    "Ship the mission-ops, program and fleet-health applications the business works in, hosted next to governed data with governed writes back to the ground system.",
                    [["Apps", "Mission, program and fleet screens with no separate web tier to run or secure."],
                     ["Lakebase", "Serverless Postgres for command state, anomaly triage and program actions."],
                     ["Agent Bricks", "Agents that draft an anomaly response or a work order against governed tools."]]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Program, engineering and mission dashboards against serverless SQL with Unity Catalog permissions enforced end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for governed answers from the lakehouse, and program and anomaly updates in the channel the team already works in (Beta)."),
                    tile("Notebooks & IDEs", "notebook", "Engineering and data-science notebooks, VS Code and JetBrains against governed program and telemetry data."),
                ]},
                {"box": "Partners & Suppliers", "ic": "partner", "tiles": [
                    tile("Supplier Sharing", "share", "Tier-1 and component suppliers reading live demand, quality and forecast tables over Delta Sharing rather than nightly file exchange."),
                    tile("Prime & Gov Sharing", "globe", "Primes, subcontractors and government customers reading contracted program data over governed sharing with no egress copy."),
                    tile("Digital Twin Exchange", "share", "As-built configuration and telemetry-fed digital twins shared to operators and MRO partners as live products."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Teamcenter Writeback", "erp", "Configuration and change decisions written back into the PLM so the answer reaches the system engineering works in.", "teamcenter"),
                    tile("MES Disposition", "compute", "Lot hold, release and rework decisions written back to the MES at the station.", "opcenter"),
                    tile("Maintenix Work Orders", "orch", "Predicted component removals and service actions raised in the MRO system against the serial.", "maintenix"),
                ]},
                {"box": "Mission & Ground", "ic": "stream", "tiles": [
                    tile("Commanding Writeback", "stream", "Anomaly responses and manoeuvre plans written back to the ground system so the decision reaches the spacecraft.", "kratos"),
                    tile("Ground Ops Portal", "gauge", "Satellite health, contact schedule and anomaly state served to mission controllers on Databricks Apps."),
                    tile("Constellation Ops", "network", "Cross-fleet reliability and coverage served to constellation operators from certified Gold products."),
                ]},
                {"box": "Compliance & Reporting", "ic": "gavel", "tiles": [
                    tile("EVM / CPR Reporting", "sheet", "Contract Performance Reports and earned-value submissions filed to the customer from the same governed cost and schedule tables.", "cobra"),
                    tile("ITAR & Export Filing", "gavel", "Export-control markings, license usage and technical-data-access records produced from governed tables under Unity Catalog."),
                    tile("AS9100 Compliance", "gavel", "Quality, airworthiness and first-article records assembled for AS9100 and airworthiness audit from certified Gold."),
                ]},
            ]),
        },
        "top": top_band(
            [
                app("Mission Control", "Satellite mission ops", "gauge",
                    "The cockpit mission controllers run a pass from: satellite health, contact schedule and anomalies from live CCSDS telemetry, with responses drafted and written back to the ground system, on Databricks Apps over Lakebase."),
                app("Program Cockpit", "EVM & schedule", "sheet",
                    "Earned-value cost and schedule variance by control account against the integrated master schedule, so a program manager sees the overrun forming before the monthly review, not after."),
                app("Fleet Health Watch", "Fleet reliability", "iot",
                    "Engine and airframe health and predicted removals by serial, so reliability engineering plans the change at a base overnight instead of discovering it on wing."),
                app("Digital Thread View", "Requirements to as-built", "network",
                    "Where systems engineering traces a requirement from CATIA and Teamcenter through to the as-built serial and its test evidence, on the same governed data the whole program reads."),
            ],
            [
                uc("Predictive Maintenance", "Reliability", "iot",
                    "Predicting engine and component removal from on-wing telemetry and defect history so an unplanned removal becomes a planned shop visit.",
                    problem="An unplanned engine or component removal grounds a vehicle and cascades through the fleet. Removals need predicting from actual condition, not a calendar, so the fix becomes a planned base visit.",
                    who="Mission & Fleet",
                    how="Engine condition, historian and Maintenix defect history feed remaining-useful-life models tracked in MLflow and scored in Model Serving; predicted removals raise work orders from the Fleet Health Watch.",
                    comps=["Fleet Health Watch", "Engine Health Monitor", "AVEVA PI Historian", "MLflow", "Model Serving", "IFS Maintenix"],
                    stories=[["Rolls-Royce keeps its engines running on Databricks", "https://www.databricks.com/customers/rolls-royce"],
                             ["Collins Aerospace transforms data into value with Databricks", "https://www.databricks.com/customers/collins-aerospace"]]),
                uc("Satellite Telemetry", "Mission ops", "stream",
                    "Billions of rows of live satellite telemetry ingested and served at low latency so operations dashboards and anomaly checks keep up with the pass.",
                    problem="Constellation telemetry arrives faster than legacy ground software can land and query it, so mission dashboards lag the pass and a second serving layer has to be maintained alongside the data platform.",
                    who="Mission & Fleet",
                    how="CCSDS frames and ground-station downlink stream through Zerobus into Lakehouse//RT; operations dashboards and anomaly checks run directly on the live tables with no separate serving system.",
                    comps=["Mission Control", "CCSDS Telemetry", "Ground Station Feeds", "Lakehouse//RT", "Zerobus", "Kratos OpenSpace"],
                    stories=[["Zerobus Ingest for telemetry and IoT at scale", "https://www.databricks.com/blog/announcing-public-preview-zerobus-ingest"]]),
                uc("Anomaly Detection", "Mission ops", "observ",
                    "Emerging spacecraft and engine anomalies detected across telemetry before they become a failure or a lost contact.",
                    problem="Anomaly signal hides across thousands of telemetry parameters; by the time a trend clears a manual review the spacecraft or engine is already degraded or lost.",
                    who="Mission & Fleet",
                    how="Telemetry is conformed to Gold; anomaly-detection models score emerging trends in Model Serving and surface them to mission and reliability teams from Mission Control before they become failures.",
                    comps=["Mission Control", "CCSDS Telemetry", "Model Serving", "Lakehouse//RT", "AI Functions"],
                    stories=[["Rolls-Royce monitors engines in real time on Databricks", "https://www.databricks.com/customers/rolls-royce"]]),
                uc("Digital Thread", "Engineering", "network",
                    "Requirements, CAD, change orders and the as-built configuration stitched so a design decision is traceable from requirement to serial.",
                    problem="Requirements, CAD, change orders and the as-built record live in CATIA, Teamcenter and Windchill separately, so tracing a requirement to the serial that flew is a manual reconciliation across systems.",
                    who="Eng & Design",
                    how="PLM, requirements and MES feeds are conformed in Silver under Unity Catalog; the Digital Thread View traces a requirement from design to the as-built serial and its test evidence with lineage.",
                    comps=["CATIA / 3DEXPERIENCE", "Siemens Teamcenter", "PTC Windchill", "Unity Catalog", "Digital Thread View", "Delta Lake"],
                    stories=[["Databricks for Manufacturing", "https://www.databricks.com/solutions/industries/manufacturing-industry-solutions"]]),
                uc("Simulation & Test", "Engineering", "compute",
                    "Simulation results and physical test data joined so models are validated against test and surrogate models cut the next analysis cycle.",
                    problem="Simulation output and flight- and rig-test data never meet, so validating a model against test is a manual export and each design iteration waits on another full analysis run.",
                    who="Eng & Design",
                    how="Ansys simulation output and test-stand and flight telemetry are conformed in the lakehouse; surrogate and reliability models trained in MLflow are validated against test and read from the Feature Store.",
                    comps=["Ansys Simulation", "Test & Flight Data", "Test & Telemetry Bus", "MLflow", "Feature Store", "AVEVA PI Historian"],
                    stories=[["Joby Aviation powers real-time telemetry with Databricks", "https://www.databricks.com/customers/joby/lakeflow-connect"]]),
                uc("MES Yield & Quality", "Manufacturing", "gauge",
                    "First-pass yield and nonconformance attacked at the station with in-line defect scoring rather than at final inspection.",
                    problem="First-pass yield and scrap are reviewed after the unit, so a drifting process is caught at final inspection or in qualification instead of at the station where it can still be fixed.",
                    who="Mfg & Quality",
                    how="MES, historian and inspection data are conformed to certified Metric Views; defect and yield models score in-line in Model Serving and the Yield & MRB Cockpit flags units at risk before disposition.",
                    comps=["Siemens Opcenter MES", "DELMIA Apriso", "AVEVA PI Historian", "Model Serving", "AI/BI"],
                    stories=[["Joby Aviation optimizes manufacturing with Databricks", "https://www.databricks.com/customers/joby/lakeflow-connect"]]),
                uc("Supply Chain Risk", "Supply chain", "network",
                    "Supplier and component exposure scored so a shortage or a bad lot is moved before it stops a build or reaches a vehicle.",
                    problem="Single-source components and opaque supplier quality across a deep aerospace supply base mean a shortage or a nonconformance is discovered at the line, after it has already stopped a build.",
                    who="Mfg & Quality",
                    how="ERP, supplier EDI and MES feeds are joined in the lakehouse; risk models score supplier and component exposure in Model Serving so buffers and qualifications are moved before a shortage lands.",
                    comps=["SAP S/4HANA", "Supplier EDI / Ariba", "Genie", "Model Serving", "AI/BI"],
                    stories=[["Supply chain and distribution optimization on Databricks", "https://www.databricks.com/solutions/accelerators/supply-chain-distribution-optimization"]]),
                uc("Program EVM & Risk", "Program", "sheet",
                    "Earned-value cost and schedule variance surfaced by control account so an overrun is seen forming, not reported after the fact.",
                    problem="Cost, schedule and technical performance live in Deltek and Primavera separately, so earned-value variance is assembled by hand for the monthly review, long after the overrun could have been acted on.",
                    who="Program Leaders",
                    how="Cobra cost actuals, Primavera schedule and Costpoint accounting are conformed to Gold; the Program Cockpit surfaces earned-value variance by control account on the same certified definitions the customer report is filed from.",
                    comps=["Program Cockpit", "Deltek Cobra EVM", "Oracle Primavera P6", "Deltek Costpoint", "AI/BI", "EVM & Cost Marts"],
                    stories=[["Databricks for Federal Government", "https://www.databricks.com/solutions/industries/federal-government"]]),
                uc("ITAR & Export Control", "Compliance", "gavel",
                    "Controlled technical data governed so export-controlled information reaches only cleared people and every access is auditable.",
                    problem="Export-controlled technical data is scattered across engineering and program systems, so proving that only cleared, licensed people saw ITAR-controlled data is a manual, error-prone audit.",
                    who="Compliance & Sec",
                    how="Technical data is governed under Unity Catalog with row, column and tag policy; AI Functions infer export markings across documents and access is auditable from the ITAR & Export Filing tables.",
                    comps=["Unity Catalog", "AI Functions", "Genie", "Siemens Teamcenter", "ITAR & Export Filing"],
                    stories=[["Databricks for Federal Government", "https://www.databricks.com/solutions/industries/federal-government"]]),
                uc("Geospatial Intelligence", "Space data", "globe",
                    "Earth-observation imagery and downlinked geospatial data turned into analytics products joined to the rest of the estate.",
                    problem="Earth-observation and downlinked geospatial data sit in specialist pipelines that never join cleanly to business data, so imagery-derived insight takes weeks and cannot be shared as a governed product.",
                    who="Mission & Fleet",
                    how="Downlinked imagery and geospatial data are processed with spatial SQL and H3 on the lakehouse; analytics products are scored in Model Serving and published over Open Sharing to customers and analysts.",
                    comps=["AI/BI", "Delta Lake", "Model Serving", "Open Sharing", "Ground Station Feeds"],
                    stories=[["Geospatial unbounded: spatial SQL, AI/BI maps and sharing", "https://www.databricks.com/blog/geospatial-unbounded-spatial-sql-ga-aibi-maps-delta-sharing-and-iceberg-v3"],
                             ["Nousot and Xcel Energy: AI and geospatial intelligence", "https://www.databricks.com/blog/nousot-and-xcel-energy-harnessing-ai-and-geospatial-intelligence-natural-disaster-mitigation"]]),
            ],
        ),
        "sources": {
            "catia": {"t": "Dassault CATIA / 3DEXPERIENCE", "u": "https://www.3ds.com/products/catia"},
            "teamcenter": {"t": "Siemens Teamcenter PLM", "u": "https://plm.sw.siemens.com/en-US/teamcenter/"},
            "windchill": {"t": "PTC Windchill PLM", "u": "https://www.ptc.com/en/products/windchill"},
            "ansys": {"t": "Ansys structural simulation", "u": "https://www.ansys.com/products/structures"},
            "stk": {"t": "Ansys STK (Systems Tool Kit)", "u": "https://www.ansys.com/products/missions/ansys-stk"},
            "opcenter": {"t": "Siemens Opcenter Execution MES", "u": "https://plm.sw.siemens.com/en-US/opcenter/"},
            "apriso": {"t": "DELMIA Apriso MES", "u": "https://www.3ds.com/products/delmia/apriso"},
            "sap": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "avevapi": {"t": "AVEVA PI System", "u": "https://www.aveva.com/en/products/aveva-pi-system/"},
            "cobra": {"t": "Deltek Cobra earned value management", "u": "https://www.deltek.com/en/products/project-and-portfolio-management/cobra"},
            "primavera": {"t": "Oracle Primavera P6", "u": "https://www.oracle.com/construction-engineering/primavera-p6/"},
            "costpoint": {"t": "Deltek Costpoint ERP", "u": "https://www.deltek.com/en/products/erp/costpoint"},
            "kratos": {"t": "Kratos OpenSpace ground platform", "u": "https://www.kratosspace.com/virtual-ground/platform"},
            "ccsds": {"t": "CCSDS space data standards", "u": "https://public.ccsds.org/default.aspx"},
            "gmv": {"t": "GMV space ground systems", "u": "https://www.gmv.com/en/sectors/space"},
            "maintenix": {"t": "IFS Maintenix aviation MRO", "u": "https://www.ifs.com/industries/aerospace-and-defense"},
            "ksat": {"t": "KSAT ground network services", "u": "https://www.ksat.no/ground-network-services/"},
            "ariba": {"t": "SAP Ariba spend management", "u": "https://www.sap.com/products/spend-management/ariba.html"},
        },
    }
}
