import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_SHIPPING_PORTS = {
    'shipping_ports': {
        "label": "Shipping & Ports",
        "blurb": "Port and terminal operations: vessel scheduling, berth and crane allocation, cargo handling, customs clearance, and landside logistics across container and bulk terminals.",
        "medallion": medallion(
            "Raw port and vessel feeds",
            "TOS moves, AIS position reports, berth plans, customs declarations and gate transactions, landed exactly as received so a dwell time or a crane move can always be replayed.",
            "Conformed vessel, visit, unit",
            "Vessels, port calls, containers and bills of lading resolved into single conformed entities across TOS, PCS and carrier systems, with voyage legs stitched to one visit.",
            "Throughput, dwell, crane rate",
            "Contracted products terminal and port authority teams run on: crane moves per hour, truck turnaround, vessel berth productivity, container dwell and demurrage exposure.",
        ),
        "rails": {
            "src": [
                {"box": "Terminal Operating", "ic": "erp", "tiles": [
                    tile("Navis N4 TOS", "erp", "Terminal operating system: vessel plans, yard slots, crane dispatch and gate transactions.", "navis-n4",
                         cat="Terminal Operating System (TOS)",
                         what="Holds the system-of-record for vessel stow plans, yard slots, crane dispatch and gate transactions, emitting the move events every terminal KPI is built on.",
                         users="Terminal Operations, Berth Planners and Yard Controllers.",
                         data_out=data_out(
                             batch=flow(["structured"], "10-40 GB/day", "Hourly batch + end-of-shift"),
                             stream=flow(["semi-structured"], "hundreds-thousands of moves/sec at peak", "Continuous move events"))),
                    tile("CyberLogitec OPUS", "db", "Container yard inventory, equipment control and rail loading for multi-modal terminals.", "cyberlogitec",
                         cat="Terminal Operating System (TOS)",
                         what="Manages container yard inventory, equipment control and rail loading for multi-modal terminals, the source of stack and rehandle state.",
                         users="Terminal Operations, Yard Controllers and Intermodal Planners.",
                         data_out=data_out(
                             batch=flow(["structured"], "5-20 GB/day", "Hourly batch"),
                             stream=flow(["semi-structured"], "hundreds of events/sec", "Continuous yard events"))),
                    tile("SAP TM for Ports", "sheet", "Landside transport orders, appointment scheduling and carrier billing.", "sap-tm",
                         cat="Transportation Management System (TMS)",
                         what="Handles landside transport orders, appointment scheduling and carrier billing, feeding rail and truck movement into terminal planning.",
                         users="Landside Logistics, Intermodal Planners and Commercial & Tariffs teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "2-8 GB/day", "Nightly batch + hourly deltas"))),
                ]},
                {"box": "Vessel & Traffic", "ic": "stream", "tiles": [
                    tile("Port Community System", "api", "Berth requests, pilot orders and customs pre-arrival messages exchanged with carriers.", "pcs",
                         cat="Port Community System (PCS)",
                         what="Exchanges berth requests, pilot orders and customs pre-arrival messages between carriers, agents and the port, the shared operating picture for a call.",
                         users="Terminal Operations, Harbour Master and Customs & Security teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens-hundreds of messages/sec", "Continuous message flow"))),
                    tile("AIS Vessel Tracking", "globe", "Position, ETA and anchorage queue for every vessel approaching the port.", "ais",
                         cat="Vessel Position (AIS)",
                         what="Broadcasts vessel position, speed, ETA and anchorage queue for every ship approaching the port, the ground truth for arrival timing.",
                         users="Terminal Operations, Berth Planners and Harbour Master.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of position reports/sec", "Continuous (seconds-minutes)"))),
                    tile("MarineTraffic API", "partner", "Historical track, port calls and congestion signals for schedule planning.", "marinetraffic",
                         cat="Maritime Data Provider",
                         what="Provides historical vessel tracks, port-call history and congestion signals used to plan schedules and validate declared ETAs.",
                         users="Terminal Operations, Berth Planners and ETA & Dwell Modelers.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "1-5 GB/day", "Hourly / daily API pulls"))),
                ]},
                {"box": "Cargo & Customs", "ic": "gavel", "tiles": [
                    tile("Descartes Customs", "gavel", "Import and export declarations, duty calculation and hold status from customs brokers.", "descartes-customs",
                         cat="Customs & Trade Compliance",
                         what="Processes import and export declarations, duty calculation and hold status from customs brokers, driving pre-arrival clearance and holds.",
                         users="Customs & Security, Customs Compliance and Landside Logistics teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "1-4 GB/day", "Hourly + on-demand"))),
                    tile("CargoWise One", "market", "Freight forwarding, house bills and milestone events for containerised cargo.", "cargowise",
                         cat="Freight Forwarding Platform",
                         what="Runs freight-forwarding operations, house bills and milestone events for containerised cargo, joining forwarder detail to terminal units.",
                         users="Commercial & Tariffs, Customs Compliance and forwarder account teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "1-5 GB/day", "Daily + milestone events"))),
                    tile("INTTRA eBL", "product", "Electronic bills of lading and booking confirmations from ocean carriers.", "inttra",
                         cat="Electronic Bill of Lading Network",
                         what="Carries electronic bills of lading and booking confirmations from ocean carriers, the documentary basis for cargo release and DG declarations.",
                         users="Customs & Security, DG Officers and documentation teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Continuous documents / daily batch"))),
                ]},
                {"box": "Equipment & Yard", "ic": "iot", "tiles": [
                    tile("Kalmar Insight", "iot", "RTG and STS crane telemetry, spreader cycles and fuel burn by shift.", "kalmar-tv",
                         cat="Crane & Equipment Telemetry",
                         what="Streams RTG and STS crane telemetry, spreader cycles and fuel burn by shift, the source of crane productivity and emissions data.",
                         users="Terminal Operations, Shift Managers and Environmental reporting teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of readings/sec", "Continuous equipment telemetry"))),
                    tile("Identec RFID Gates", "stream", "Automated gate OCR, RFID and chassis identification at in-gate and out-gate.", "identec",
                         cat="Gate Automation & OCR",
                         what="Captures automated gate OCR, RFID and chassis identification at in-gate and out-gate, decomposing truck turnaround into stages.",
                         users="Landside Logistics, Gate Managers and Yard Controllers.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens-hundreds of gate events/sec", "Continuous gate transactions"))),
                    tile("SICK Yard Automation", "partner", "Automated straddle carrier and AGV position for high-throughput yards.", "sick-yard",
                         cat="Yard Automation Sensors",
                         what="Reports automated straddle carrier and AGV position and status for high-throughput yards, feeding equipment balance and safety analytics.",
                         users="Terminal Operations, Yard Controllers and automation engineering teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of position events/sec", "Continuous (seconds)"))),
                ]},
                {"box": "Finance & Tariffs", "ic": "market", "tiles": [
                    tile("Jade Master Terminal", "erp", "Storage, handling and demurrage invoices reconciled against actual moves.", "oracle-port",
                         cat="Terminal Billing & Revenue",
                         what="Generates storage, handling and demurrage invoices reconciled against actual crane and gate moves, the source of billed-versus-actual revenue.",
                         users="Commercial & Tariffs, Revenue Assurance and Finance teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-4 GB/day", "Daily billing cycles"))),
                    tile("Tideworks Mainsail", "chart", "Published tariffs, rebates and contract rates applied to each service event.", "hph-tariff",
                         cat="Tariff & Rate Management",
                         what="Maintains published tariffs, rebates and contract rates applied to each service event, the pricing reference behind revenue leakage analysis.",
                         users="Commercial & Tariffs, Tariff Managers and Key Account Managers.",
                         data_out=data_out(
                             batch=flow(["structured"], "MBs-GBs (rates + events)", "Daily rate refresh"))),
                ]},
                fed_group("Carrier Schedule Marts", "Vessel schedules and capacity marts left with carriers and queried in place under Unity Catalog.",
                          cat="Carrier Schedule Warehouse",
                          what="Carrier-side vessel schedule and capacity marts kept with the lines and queried in place through federation rather than copied into the terminal.",
                          users="Terminal Operations, Berth Planners and Commercial & Tariffs analysts.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("UN/EDIFACT COPRAR / CODECO", "stream", "COPRAR and CODECO vessel and gate moves and IFTMIN and IFTSTA transport messages from shipping lines, parsed on arrival.", "edifact",
                     cat="EDI Transaction Messages",
                     what="Carries COPRAR/CODECO vessel and gate moves and IFTMIN/IFTSTA transport messages from shipping lines, parsed on arrival and matched to units.",
                     users="Terminal Operations, Customs Compliance and Integration Engineers.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "tens-hundreds of messages/sec", "Continuous message flow"))),
                tile("Port Authority AIS Feed", "api", "Real-time berth occupancy and pilot boarding events from the port authority.", "pcs",
                     cat="Port Authority Data Feed",
                     what="Provides real-time berth occupancy and pilot-boarding events from the port authority, aligning the terminal to harbour-wide movement.",
                     users="Terminal Operations, Harbour Master and Berth Planners.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "tens of events/sec", "Continuous (near real-time)"))),
                tile("Customs Single Window", "gavel", "Government clearance status and inspection results consumed inbound.", "descartes-customs",
                     cat="Government Single Window",
                     what="Consumes government clearance status and inspection results inbound, the authoritative signal for whether a box may be released.",
                     users="Customs & Security, Customs Compliance and Port Security teams.",
                     data_out=data_out(
                         batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Hourly + event-driven"))),
            ]),
            "ppl": ppl2([
                biz("Port Director Office", "Genie One", "The port director on throughput and revenue per call; the COO on berth productivity, truck queues and the terminal's demurrage exposure.",
                    [["Genie One", "Ask what yesterday's vessel productivity cost without analyst delay."], ["AI/BI", "Crane rate and dwell on certified Metric Views."], ["Unity Catalog", "One definition of dwell across terminal and finance."]],
                    sub=[
                        ["Port Director", "throughput, revenue per call and the port's standing against neighbouring gateways."],
                        ["Chief Operating Officer", "berth productivity, truck queues and the terminal's demurrage exposure each shift."],
                        ["Harbour Master", "vessel safety, berth allocation and traffic through the approach channel."],
                    ],
                    ucs=["Berth Productivity", "Tariff & Storage Revenue", "Vessel ETA Reliability", "Environmental Reporting"]),
                biz("Terminal Operations", "Lakehouse//RT", "Berth planners and shift managers on crane allocation, yard density and vessel cut-off, defending crane moves per hour on the stow plan.",
                    [["Berth Planner", "Live berth and crane plan against AIS ETA and yard capacity."], ["Lakehouse//RT", "Gate and crane state at terminal-line latency."]],
                    sub=[
                        ["Berth Planner", "the berth and crane plan against AIS ETA, stow and yard capacity."],
                        ["Shift Manager", "crane moves per hour and gang deployment across the working shift."],
                        ["Yard Controller", "slot density, rehandles and equipment balance across the stacks."],
                    ],
                    ucs=["Berth Productivity", "Crane Sequencing", "Vessel ETA Reliability", "Container Dwell"]),
                biz("Commercial & Tariffs", "AI/BI", "Tariff managers on contract compliance, rebate accuracy and storage revenue leakage where free-dwell days slip past the billed clock.",
                    [["AI/BI", "Handling revenue and demurrage on certified views."], ["Genie One", "Ask which customers exceed free dwell this week."]],
                    sub=[
                        ["Tariff Manager", "contract rates, rebate accuracy and storage revenue leakage on free-dwell days."],
                        ["Key Account Manager", "line and shipper agreements and volume commitments per service."],
                        ["Revenue Assurance", "billed moves reconciled to the actual crane and gate events."],
                    ],
                    ucs=["Tariff & Storage Revenue", "Container Dwell", "Berth Productivity"]),
                biz("Landside Logistics", "Model Serving", "Truck appointment and rail planners on gate queues and intermodal handoff, matching slots to yard density before demurrage accrues.",
                    [["Gate Optimizer", "Appointment slots scored against yard density and cut-off."], ["Model Serving", "Dwell prediction models before demurrage accrues."]],
                    sub=[
                        ["Gate Manager", "truck appointment slots, gate queues and turnaround time at the terminal."],
                        ["Intermodal Planner", "rail consist, train windows and the yard-to-ramp handoff."],
                        ["Drayage Coordinator", "carrier slot compliance and container availability at pickup."],
                    ],
                    ucs=["Gate Turnaround", "Container Dwell", "Intermodal Rail Load"]),
                biz("Customs & Security", "Lakeflow", "Compliance teams on customs holds, inspection outcomes and dangerous-goods declarations validated against stow position and segregation.",
                    [["Customs Hold Console", "Declaration status and inspection outcomes in one governed view."], ["Lakeflow", "PCS and customs feeds conformed for compliance analytics."]],
                    sub=[
                        ["Customs Compliance", "declaration status, holds and inspection outcomes before cargo lands."],
                        ["DG Officer", "dangerous-goods segregation, stow position and hazmat documentation."],
                        ["Port Security", "ISPS access control, seals and screening across the terminal perimeter."],
                    ],
                    ucs=["Customs Clearance", "Dangerous Goods", "Container Dwell"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land TOS moves, AIS position reports, PCS messages and customs feeds; own Bronze to Silver and the pager when a dwell or crane table breaks.",
                    [["Lakeflow Connect", "Managed connectors for TOS, PCS and carrier sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on AIS and gate feeds."], ["Lakewatch", "Freshness on the dwell tables the berth desk reads each shift."]],
                    sub=[
                        ["Ingestion Engineer", "TOS moves, AIS position reports, PCS and customs feeds landed on arrival."],
                        ["Pipeline Engineer", "Bronze-to-Silver conformance and expectations on the dwell and crane tables."],
                        ["Platform SRE", "the pager when a dwell or crane table the berth desk reads breaks."],
                    ],
                    ucs=["Berth Productivity", "Container Dwell", "Vessel ETA Reliability", "Customs Clearance"]),
                biz("Data Scientists", "MLflow", "Dwell-prediction, vessel-ETA, crane-sequencing and gate-turnaround models, and whether they still hold as schedules and yard density shift.",
                    [["Feature Store", "Vessel and yard features read identically in training and serving."], ["MLflow", "Every ETA and dwell experiment tracked for audit."], ["Model Serving", "Dwell and ETA models scored on approaching calls."]],
                    sub=[
                        ["ETA & Dwell Modeler", "vessel-ETA and container-dwell models as schedules and yard density shift."],
                        ["Optimisation Scientist", "crane-sequencing and berth-allocation under twin-lift and rehandle limits."],
                        ["MLOps Engineer", "feature parity and drift on the ETA and dwell models in production."],
                    ],
                    ucs=["Container Dwell", "Vessel ETA Reliability", "Crane Sequencing", "Gate Turnaround"]),
                biz("App Developers", "Apps", "Ship the Berth Planner, Gate Optimizer and Yard Density apps terminal teams work in, hosted next to governed TOS and AIS data.",
                    [["Apps", "Terminal screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for appointment and dispatch writes."], ["Agent Bricks", "Agents that draft crane sequences against governed tools."]],
                    sub=[
                        ["Full-Stack Engineer", "the Berth Planner, Gate Optimizer and Yard Density screens teams work in."],
                        ["Backend Engineer", "appointment and dispatch writes on serverless Postgres next to governed data."],
                        ["Agent Developer", "agents that draft crane sequences against governed terminal tools."],
                    ],
                    ucs=["Berth Productivity", "Gate Turnaround", "Container Dwell"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Terminal KPI dashboards on serverless SQL with Unity Catalog permissions."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for berth and dwell questions in the operations channel."),
                    tile("Notebooks & IDEs", "notebook", "Operations notebooks against governed TOS and AIS data."),
                ]},
                {"box": "Carrier & Landside", "ic": "partner", "tiles": [
                    tile("Vessel Schedule API", "api", "Berth windows and crane availability shared to shipping lines over Delta Sharing."),
                    tile("Trucker Appointment Portal", "apps", "Gate slots and container availability pushed to drayage carriers."),
                    tile("Rail Ramp Partners", "globe", "Outbound train consist and loading status shared to intermodal operators."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("TOS Crane Dispatch", "db", "Optimised crane sequences written back to the TOS dispatch list.", "navis-n4"),
                    tile("Gate Appointment Release", "stream", "Appointment capacity adjustments pushed to the truck portal."),
                    tile("Yard Rehandle Orders", "apps", "Rehandle tasks dispatched to yard equipment operators."),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Port Authority KPIs", "gavel", "Throughput and environmental metrics filed to the port authority.", "pcs"),
                    tile("Customs Audit Trail", "share", "Declaration and inspection evidence from contracted Gold products."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Terminal performance products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Carriers and shippers reading live dwell and berth data via Delta Sharing."),
                ]},
            ], genie_spaces=[
                genie("Berth & Vessel Operations", "Ask about crane productivity, berth idle time and vessel arrival reliability.",
                      feeds=["Navis N4 TOS", "Kalmar Insight", "AIS Vessel Tracking", "Throughput, dwell, crane rate"],
                      teams=["Terminal Operations", "Berth Planner", "Shift Manager"],
                      questions=[
                          "What were crane moves per hour by vessel and berth on the last shift?",
                          "How much berth idle time did we lose to plan versus execution today?",
                          "Which approaching vessels have the least reliable declared ETA?",
                          "What is the anchorage queue and expected berthing order right now?",
                          "Which cranes show the highest fuel burn per move this week?"]),
                genie("Container Dwell & Yard", "Explore dwell days, demurrage exposure and yard density across the stacks.",
                      feeds=["CyberLogitec OPUS", "Identec RFID Gates", "Descartes Customs", "Conformed vessel, visit, unit"],
                      teams=["Landside Logistics", "Yard Controller", "Terminal Operations"],
                      questions=[
                          "Which containers are about to breach free-dwell and accrue demurrage?",
                          "What is average container dwell by line and cargo type this month?",
                          "Which yard blocks are most congested and driving rehandles?",
                          "How many units are held by customs and blocking their slots?",
                          "What is our demurrage exposure by customer right now?"]),
                genie("Gate & Landside Flow", "Answer truck turnaround, gate queue and intermodal handoff questions.",
                      feeds=["Identec RFID Gates", "SAP TM for Ports", "Navis N4 TOS", "Throughput, dwell, crane rate"],
                      teams=["Landside Logistics", "Gate Manager", "Intermodal Planner"],
                      questions=[
                          "What is average truck turnaround time by gate and hour today?",
                          "Which stage of the gate process is the current bottleneck?",
                          "How does appointment compliance compare to actual arrivals?",
                          "Which rail consists are at risk of going out light this window?",
                          "What is drayage carrier slot compliance this week?"]),
                genie("Tariff & Revenue Assurance", "Ask about handling and storage revenue, rebates and billed-versus-actual moves.",
                      feeds=["Jade Master Terminal", "Tideworks Mainsail", "Navis N4 TOS", "Throughput, dwell, crane rate"],
                      teams=["Commercial & Tariffs", "Tariff Manager", "Revenue Assurance"],
                      questions=[
                          "Where do billed moves diverge from actual crane and gate events?",
                          "Which customers exceeded free dwell but were not billed storage?",
                          "How much storage and demurrage revenue did we bill this month?",
                          "Which rebate tiers are customers close to triggering?",
                          "What is revenue per vessel call by line this quarter?"]),
            ], dashboards=[
                dashboard("Vessel & Berth Productivity", "Crane moves per hour, berth utilisation and vessel ETA reliability.",
                          kpis=["Crane moves per hour", "Berth utilisation", "Berth idle time", "Vessel ETA accuracy", "Gang productivity"],
                          teams=["Terminal Operations", "Port Director Office", "Berth Planner"]),
                dashboard("Container Dwell & Demurrage", "Dwell days, demurrage exposure and yard density across the terminal.",
                          kpis=["Container dwell", "Demurrage exposure", "Yard density", "Rehandle rate", "Customs hold count"],
                          teams=["Landside Logistics", "Yard Controller", "Commercial & Tariffs"]),
                dashboard("Gate Turnaround & Intermodal", "Truck turnaround, gate queues and rail loading performance.",
                          kpis=["Truck turnaround", "Gate queue length", "Appointment compliance", "Rail utilisation", "Drayage slot compliance"],
                          teams=["Landside Logistics", "Gate Manager", "Intermodal Planner"]),
                dashboard("Tariff & Storage Revenue", "Handling and storage revenue reconciled to actual moves with leakage.",
                          kpis=["Handling revenue", "Storage revenue", "Revenue leakage", "Rebate accuracy", "Revenue per call"],
                          teams=["Commercial & Tariffs", "Tariff Manager", "Revenue Assurance"]),
            ]),
        },
        "top": top_band(
            [app("Berth Planner", "Vessel scheduling", "gauge", "Berth and crane plans scored against AIS ETA, yard density and labour availability."),
             app("Gate Optimizer", "Truck appointments", "stream", "Appointment slots and gate lanes matched to yard capacity and vessel cut-off."),
             app("Yard Density Map", "Slot utilisation", "iot", "Live yard occupancy and rehandle risk before the vessel gang lands."),
             app("Customs Hold Console", "Clearance status", "gavel", "Declaration holds, inspections and release milestones in one operations view.")],
            [uc("Berth Productivity", "Vessel ops", "gauge", "Crane moves per hour and berth idle time attributed to plan versus execution.",
                problem="Crane rate and berth idle time live in TOS and crane logs separately, so a shift that loses productivity to plan versus execution is only reconstructed next day, after the vessel sailed.",
                who="Terminal Operations",
                how="Navis N4 TOS moves and Kalmar Insight equipment telemetry land through Lakeflow and conform on Delta Lake, so berth productivity is attributed to plan versus execution and read in the Berth Planner.",
                comps=["Berth Planner", "Navis N4 TOS", "Kalmar Insight", "Lakeflow", "Delta Lake", "AI/BI"],
                stories=[
                    ["PTP gains real-time operational insights with Databricks Lakehouse", "https://www.tigeranalytics.com/perspectives/case-study/delivering-real-time-operational-insights-for-ptp-with-databricks-lakehouse/"],
                    ["From raw shipping data to real-time predictions on Databricks", "https://community.databricks.com/t5/technical-blog/from-raw-shipping-data-to-real-time-predictions-in-one-platform/ba-p/153713"],
                ]),
             uc("Container Dwell", "Yard ops", "db", "Dwell days and demurrage exposure predicted before free time expires.",
                problem="Free-dwell clocks tick across thousands of boxes at once, so by the time a spreadsheet flags the units about to breach, demurrage has accrued and the yard is congested with stale containers.",
                who="Landside Logistics",
                how="Gate, TOS and customs events feed dwell features scored in Model Serving, and predicted breaches surface in the Yard Density Map so operators clear boxes before free time expires.",
                comps=["Yard Density Map", "Model Serving", "Identec RFID Gates", "Descartes Customs", "Feature Store", "Delta Lake"],
                stories=[
                    ["Kotahi improves container movement visibility with Azure Databricks", "https://www.databricks.com/customers/kotahi"],
                ]),
             uc("Gate Turnaround", "Landside", "stream", "Truck visit duration decomposed by queue, OCR and yard handoff.",
                problem="Truck visit time blends queueing, OCR read failures and yard handoff delays, but the causes sit buried in gate and TOS logs, so drivers wait and appointment capacity is set by rule of thumb.",
                who="Landside Logistics",
                how="Identec gate OCR and TOS handoff events land through Lakeflow and are decomposed on Delta Lake, so the Gate Optimizer matches appointment slots to real turnaround by queue, OCR and yard stage.",
                comps=["Gate Optimizer", "Identec RFID Gates", "Navis N4 TOS", "Lakeflow", "Delta Lake", "AI/BI"]),
             uc("Crane Sequencing", "Equipment", "iot", "Crane work lists optimised for twin-lift and minimum rehandle.",
                problem="Crane work lists are built by hand against the stow plan, so twin-lift chances are missed and avoidable rehandles pile up, dragging moves per hour down when the berth window is tightest.",
                who="Terminal Operations",
                how="Stow, yard-slot and crane telemetry are conformed on Delta Lake and optimised with Model Serving, and the sequence is written back to the Navis N4 TOS dispatch list for the gang to work.",
                comps=["Berth Planner", "Navis N4 TOS", "Kalmar Insight", "Model Serving", "Delta Lake", "Apache Spark"]),
             uc("Vessel ETA Reliability", "Planning", "globe", "AIS-derived ETA accuracy scored against declared schedules.",
                problem="Carrier-declared ETAs drift by hours against what AIS actually shows, so berths and gangs are planned to a schedule already wrong, and the terminal absorbs the idle time or the scramble.",
                who="Terminal Operations",
                how="AIS Vessel Tracking and MarineTraffic history feed ETA models tracked in MLflow and scored in Model Serving, so the Berth Planner ranks declared schedules against a live AIS-derived arrival.",
                comps=["Berth Planner", "AIS Vessel Tracking", "MarineTraffic API", "Model Serving", "MLflow", "Lakehouse//RT"],
                stories=[
                    ["From raw shipping data to real-time predictions on Databricks", "https://community.databricks.com/t5/technical-blog/from-raw-shipping-data-to-real-time-predictions-in-one-platform/ba-p/153713"],
                ]),
             uc("Customs Clearance", "Compliance", "gavel", "Pre-arrival screening and hold resolution before cargo lands.",
                problem="Declarations, holds and inspections arrive from brokers and the single window on their own clocks, so a box can reach the quay still held and the desk learns only when discharge stalls.",
                who="Customs & Security",
                how="Descartes and Customs Single Window feeds conform through Lakeflow into the Customs Hold Console, so pre-arrival screening and hold resolution happen on one governed view before cargo lands.",
                comps=["Customs Hold Console", "Descartes Customs", "Customs Single Window", "Lakeflow", "Unity Catalog", "AI/BI"],
                stories=[
                    ["Hapag-Lloyd uses Databricks to enhance audit and compliance efficiency", "https://www.databricks.com/customers/hapag-lloyd"],
                ]),
             uc("Intermodal Rail Load", "Rail", "partner", "Train loading plans matched to vessel discharge and yard slots.",
                problem="Rail load plans are built before the vessel finishes discharge, so when the box mix or yard position shifts the train works from stale lists, wagons go out light and ramp slots are wasted.",
                who="Landside Logistics",
                how="TOS discharge events and SAP TM rail orders conform on Delta Lake, so load plans in the Gate Optimizer are matched to actual discharge and yard slots and shared to the ramp over Open Sharing.",
                comps=["Gate Optimizer", "SAP TM for Ports", "Navis N4 TOS", "Delta Lake", "Open Sharing", "AI/BI"]),
             uc("Tariff & Storage Revenue", "Commercial", "market", "Handling and storage charges reconciled to actual moves.",
                problem="Handling and storage charges bill from the TOS, but rebates, contract rates and free-dwell exceptions live in other systems, so revenue leaks wherever billed and actual moves diverge.",
                who="Commercial & Tariffs",
                how="Jade Master Terminal and Tideworks Mainsail data conform on Delta Lake and reconcile to actual crane and gate events, so handling and storage revenue is verified on certified AI/BI views.",
                comps=["Jade Master Terminal", "Tideworks Mainsail", "Navis N4 TOS", "Delta Lake", "AI/BI", "Unity Catalog"],
                stories=[
                    ["Hafnia modernizes maritime operations with Lakebase", "https://www.databricks.com/customers/hafnia/lakebase"],
                ]),
             uc("Dangerous Goods", "Safety", "gavel", "DG declarations validated against stow position and segregation rules.",
                problem="DG declarations are checked against stow position and segregation rules by hand, so a mis-declared or wrongly stowed hazardous box can reach the yard, caught only at inspection.",
                who="Customs & Security",
                how="INTTRA eBL and PCS declarations conform through Lakeflow and are validated against stow position on Delta Lake, so segregation breaches surface in the Customs Hold Console before the box is worked.",
                comps=["Customs Hold Console", "INTTRA eBL", "Port Community System", "Lakeflow", "Delta Lake", "Unity Catalog"]),
             uc("Environmental Reporting", "ESG", "chart", "Emissions and noise metrics reported to port authority programs.",
                problem="Emissions, energy and noise metrics for port-authority programs are stitched by hand from crane fuel, vessel AIS and equipment telemetry each cycle, so numbers arrive late and untraced.",
                who="Port Director Office",
                how="AIS, crane fuel and equipment telemetry conform on Delta Lake with Unity Catalog lineage, so emissions metrics are computed once and reported to port-authority programs from certified AI/BI products.",
                comps=["AIS Vessel Tracking", "Kalmar Insight", "Unity Catalog", "Delta Lake", "AI/BI", "Data Products"],
                stories=[
                    ["Leveraging ESG data to operationalize sustainability with Databricks", "https://www.databricks.com/blog/2020/11/11/leveraging-esg-data-to-operationalize-sustainability.html"],
                ])],
        ),
        "sources": {
            "navis-n4": {"t": "Navis N4 terminal operating system", "u": "https://www.navis.com/products/navis-n4"},
            "cyberlogitec": {"t": "CyberLogitec OPUS Terminal", "u": "https://www.cyberlogitec.com/"},
            "sap-tm": {"t": "SAP Transportation Management", "u": "https://www.sap.com/products/scm/transportation-logistics.html"},
            "pcs": {"t": "Port community systems", "u": "https://www.ipcsa.international/"},
            "ais": {"t": "Automatic Identification System", "u": "https://www.imo.org/en/OurWork/Safety/Pages/AIS.aspx"},
            "marinetraffic": {"t": "MarineTraffic", "u": "https://www.marinetraffic.com/"},
            "descartes-customs": {"t": "Descartes customs compliance", "u": "https://www.descartes.com/"},
            "cargowise": {"t": "CargoWise One", "u": "https://www.cargowise.com/"},
            "inttra": {"t": "INTTRA eBL platform", "u": "https://www.inttra.com/"},
            "kalmar-tv": {"t": "Kalmar Insight", "u": "https://www.kalmarglobal.com/parts-services/kalmar-insight/"},
            "identec": {"t": "Identec Solutions", "u": "https://www.identecsolutions.com/"},
            "sick-yard": {"t": "SICK logistics automation", "u": "https://www.sick.com/"},
            "oracle-port": {"t": "Jade Master Terminal TOS", "u": "https://www.jadelogistics-asia.com/products/master-terminal"},
            "hph-tariff": {"t": "Tideworks Mainsail TOS", "u": "https://tideworks.com/mainsail/"},
            "edifact": {"t": "UN/EDIFACT messaging", "u": "https://unece.org/trade/uncefact/introducing-unedifact"},
        },
    },
}
