import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_SPORTS_ENTERTAINMENT = {
    'sports_entertainment': {
        "label": "Sports & Entertainment",
        "blurb": "Teams, venues and media rights: ticketing and fan engagement, game-day operations, broadcast and streaming, sponsorship activation, and athlete performance analytics.",
        "medallion": medallion(
            "Raw event and fan feeds",
            "Ticketing scans, POS concessions, broadcast logs, wearable tracking and CRM interactions, landed exactly as received so a attendance or a sponsorship impression can always be replayed.",
            "Conformed fan, event, asset",
            "Fans, events, seats and media assets resolved into single conformed entities across ticketing, CRM and broadcast estates, with identity stitched across channels.",
            "Attendance, yield, engagement",
            "Contracted products commercial and operations teams run on: ticket yield by section, F&B attach rate, sponsorship ROI, streaming concurrency and churn risk by segment.",
        ),
        "rails": {
            "src": [
                {"box": "Ticketing & CRM", "ic": "erp", "tiles": [
                    tile("Ticketmaster Archtics", "erp", "Primary ticketing, seat inventory, pricing and scan data from every event.", "ticketmaster",
                         cat="Primary Ticketing System",
                         what="System-of-record for primary ticketing: seat inventory, pricing, sales and gate-scan data from every event.",
                         users="Ticketing, Pricing and Game-day operations teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-10 GB/day sales + scans", "Nightly + intraday deltas"),
                             stream=flow(["semi-structured"], "thousands of scans/sec at ingress", "Continuous on event day"))),
                    tile("Salesforce Marketing Cloud", "custlake", "Fan profiles, membership tiers, service cases and campaign responses.", "sf-sports",
                         cat="CRM & Marketing Platform",
                         what="Holds fan profiles, membership tiers, service cases and campaign responses used for engagement and retention.",
                         users="Fan engagement, CRM and Membership services teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/day", "Hourly / nightly sync"),
                             stream=flow(["semi-structured"], "tens of events/sec", "Continuous (engagement events)"))),
                    tile("SeatGeek Enterprise", "market", "Secondary market listings, transfer activity and dynamic pricing signals.", "seatgeek",
                         cat="Secondary Ticketing Marketplace",
                         what="Supplies secondary-market listings, transfer activity and dynamic-pricing signals that reveal true demand.",
                         users="Ticketing, Pricing analysts and Yield management teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "sub-GB to 2 GB/day", "Hourly listing + transfer feeds"))),
                ]},
                {"box": "Venue Operations", "ic": "stream", "tiles": [
                    tile("VenueNext", "apps", "Mobile ordering, wayfinding and in-seat service for arena and stadium guests.", "venuenext",
                         cat="Venue Experience & Mobile Ordering",
                         what="Runs mobile ordering, wayfinding and in-seat service, emitting concessions and guest-flow events on game day.",
                         users="Game-day operations, Concessions and Guest experience teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds-thousands of orders/sec at peak", "Continuous on event day"))),
                    tile("Genetec Security Center", "iot", "Access control, crowd density cameras and incident logs on game day.", "genetec",
                         cat="Physical Security & Access Control",
                         what="Provides access control, crowd-density camera analytics and incident logs used for crowd-safety monitoring.",
                         users="Security, Game-day operations and Safety teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "thousands of events/sec at peak", "Continuous on event day"))),
                    tile("Catapult Sports", "iot", "GPS and IMU player tracking: load, sprint distance and injury risk flags.", "catapult",
                         cat="Athlete Performance Tracking (GPS/IMU)",
                         what="Captures GPS and IMU athlete-tracking data for training load, sprint distance and injury-risk signals.",
                         users="Sports science, Medical and Coaching staff.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "high-frequency samples per athlete", "Continuous during sessions"),
                             batch=flow(["structured"], "GBs per session", "Post-session uploads"))),
                ]},
                {"box": "Broadcast & OTT", "ic": "partner", "tiles": [
                    tile("Grabyo Clipping", "stream", "Live clipping, highlights and social publishing from broadcast feeds.", "grabyo",
                         cat="Live Video Clipping & Publishing",
                         what="Clips and publishes live highlights from broadcast feeds to social and digital channels in near real time.",
                         users="Digital & content, Social media and Broadcast teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured", "unstructured"], "high-bitrate clips + metadata", "Continuous during broadcast"))),
                    tile("Deltatre OTT Platform", "api", "Streaming concurrency, start-over and device telemetry for direct-to-consumer.", "deltatre",
                         cat="OTT Streaming Platform",
                         what="Delivers direct-to-consumer streaming and emits concurrency, start-over and device telemetry for engagement.",
                         users="Direct-to-consumer, Digital product and Audience teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens of thousands of events/sec at peak", "Continuous during streams"))),
                    tile("Nielsen Sports", "chart", "TV and digital audience measurement for rights valuation.", "nielsen-sports",
                         cat="Audience Measurement",
                         what="Measures TV and digital audiences used to value media rights and sponsorship exposure.",
                         users="Media rights, Sponsorship and Commercial strategy teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "GBs of audience panels", "Daily / weekly measurement"))),
                ]},
                {"box": "Sponsorship & Ads", "ic": "market", "tiles": [
                    tile("SponsorUnited", "partner", "Sponsorship inventory, activation tracking and competitive spend intelligence.", "sponsorunited",
                         cat="Sponsorship Intelligence Platform",
                         what="Tracks sponsorship inventory, activation delivery and competitive spend intelligence across the market.",
                         users="Commercial, Sponsorship sales and Partnership teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "GBs of deals + activations", "Daily / weekly"))),
                    tile("The Trade Desk", "market", "Programmatic inventory across league and team digital properties.", "trade-desk",
                         cat="Programmatic Advertising (DSP)",
                         what="Buys and reports programmatic ad inventory across league and team digital properties.",
                         users="Digital advertising, Media and Commercial teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "1-5 GB/day impressions + conversions", "Hourly / daily"))),
                    tile("UKG Workforce", "people", "Staff scheduling, time and attendance for event and concessions crews.", "ukg",
                         cat="Workforce Management",
                         what="Schedules event and concessions crews and records time and attendance for game-day staffing.",
                         users="Venue operations, Concessions and HR teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "sub-GB/day", "Hourly punch + schedule sync"))),
                ]},
                fed_group("League Data Marts", "Official league statistics and schedule marts queried in place under Unity Catalog.",
                          cat="League Statistics Data Warehouse",
                          what="Official league statistics and schedule marts kept at the league and queried in place through federation.",
                          users="Analytics, Broadcast and Commercial teams.",
                          data_out=data_out(
                              batch=flow(["structured"], "GB-scale reference marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("Stats Perform Feeds", "api", "Live play-by-play, rosters and official statistics ingested for analytics.", "stats-perform",
                     cat="Sports Data Feed",
                     what="Delivers live play-by-play, rosters and official statistics used for analytics, highlights and broadcast graphics.",
                     users="Analytics, Broadcast and Content teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "hundreds of events/sec during games", "Continuous during events"))),
                tile("Social Listening APIs", "observ", "Brand mention and sentiment feeds for sponsorship and crisis monitoring.",
                     cat="Social Listening & Sentiment",
                     what="Aggregates brand mentions and sentiment across social platforms for sponsorship value and crisis monitoring.",
                     users="Sponsorship, Communications and Digital teams.",
                     data_out=data_out(
                         batch=flow(["semi-structured", "unstructured"], "GBs of posts + sentiment", "Continuous / hourly"))),
                tile("Rights Holder Metadata", "zplug", "Media rights windows and blackout rules from league partners.", "stats-perform",
                     cat="Media Rights Metadata",
                     what="Supplies media-rights windows and blackout rules from league partners that govern where content may air.",
                     users="Media rights, Broadcast operations and Legal teams.",
                     data_out=data_out(
                         batch=flow(["structured"], "sub-GB", "On schedule updates"))),
            ]),
            "ppl": ppl2([
                biz("Ownership & Executive", "Genie One", "The CEO on revenue per fan and matchday P&L; the COO on ingress throughput, concessions flow and the safety record across the venue.",
                    [["Genie One", "Last home stand yield without analyst delay."], ["AI/BI", "Attendance and sponsorship ROI on Metric Views."]],
                    sub=[["CEO / Team President", "revenue per fan, matchday P&L and the trade between winning and margin."], ["CFO", "gate, media and sponsorship revenue against the cost of running the venue."], ["Chief Commercial Officer", "sponsorship value, premium inventory and the growth of the fan base."]],
                    ucs=["Sponsorship ROI", "Dynamic Ticket Pricing", "Merchandise Forecast"]),
                biz("Ticketing & Pricing", "Model Serving", "Pricing analysts on dynamic seat tiers, secondary-market pressure and sell-through pace against the demand curve before and during on-sale.",
                    [["Pricing Workbench", "Demand forecast before on-sale."], ["Model Serving", "Price models in the on-sale path."]],
                    sub=[["Head of Ticketing", "sell-through pace, sections at risk and the on-sale calendar."], ["Pricing Analyst", "dynamic seat tiers and secondary-market pressure against the demand curve."], ["Yield Manager", "premium and dynamic inventory value across the season."]],
                    ucs=["Dynamic Ticket Pricing", "Secondary Market Intel", "Fan Churn Prediction"]),
                biz("Fan Engagement", "CustomerLake", "CRM teams on membership growth, churn before renewal and personalised offers scored on spend stitched across ticketing and concessions.",
                    [["Fan 360 Console", "Spend stitched across ticketing and concessions."], ["CustomerLake", "Segments without a separate CDP."]],
                    sub=[["CRM Director", "membership growth, renewals and churn before the renewal window."], ["Digital & Content", "app engagement, highlights reach and personalised offers."], ["Membership Services", "the season-ticket experience and the value each fan sees."]],
                    ucs=["Fan Churn Prediction", "OTT Personalization", "Broadcast Highlights"]),
                biz("Game-Day Ops", "Lakehouse//RT", "Venue managers and medical staff on ingress flow, queue times, player load and incidents, moving crews before a bottleneck becomes a delay.",
                    [["Game-Day Command", "Live scans and queue times on one screen."], ["Load Management Hub", "Player workload before selection."]],
                    sub=[["VP Venue Operations", "ingress throughput, concessions flow and the safety record."], ["Head of Security", "crowd density, incidents and evacuation readiness."], ["Head of Performance / Medical", "player load, injury risk and availability for selection."]],
                    ucs=["Crowd Safety Analytics", "Concessions Optimization", "Injury Risk Scoring"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land ticketing scans, POS folios, wearable tracking and CRM feeds; own Bronze to Silver and the pager when a game-day attendance table stalls.",
                    [["Lakeflow Connect", "Managed connectors for ticketing, CRM and POS sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on scan and tracking feeds."], ["Lakewatch", "Freshness on the attendance tables commercial reads on game day."]],
                    sub=[["Streaming Engineer", "scan, POS and tracking feeds landed at game-day latency."], ["Pipeline Engineer", "Bronze-to-Silver reliability and expectations on attendance tables."], ["Platform Engineer", "freshness and the pager when a game-day table stalls."]],
                    ucs=["Crowd Safety Analytics", "Concessions Optimization", "Dynamic Ticket Pricing"]),
                biz("Data Scientists", "MLflow", "Dynamic-pricing, fan-churn, injury-risk and highlight-selection models, and whether they still hold as rosters, opponents and demand shift.",
                    [["Feature Store", "Fan and athlete features read identically in training and serving."], ["MLflow", "Every pricing and load experiment tracked for audit."], ["Model Serving", "Price and risk models scored in the on-sale and coaching path."]],
                    sub=[["Pricing Scientist", "demand and dynamic-pricing models that hold across opponents."], ["Fan & Churn Scientist", "churn, propensity and offer-scoring models across channels."], ["Sports Scientist", "injury-risk and load models against wearable and tracking data."]],
                    ucs=["Dynamic Ticket Pricing", "Fan Churn Prediction", "Injury Risk Scoring"]),
                biz("App Developers", "Apps", "Ship the Game-Day Command, Pricing Workbench and Fan 360 apps commercial and venue teams work in, next to governed ticketing data.",
                    [["Apps", "Venue screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for offer and incident state writes."], ["Agent Bricks", "Agents that draft offers against governed tools."]],
                    sub=[["Apps Engineer", "the Game-Day Command, Pricing Workbench and Fan 360 screens."], ["Backend Engineer", "offer and incident state on serverless Postgres."], ["Agent Engineer", "agents that draft offers against governed ticketing tools."]],
                    ucs=["Concessions Optimization", "Dynamic Ticket Pricing", "OTT Personalization"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "League and team dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for attendance and sponsorship questions on game day."),
                    tile("Notebooks & IDEs", "notebook", "Analytics notebooks against governed ticketing and tracking data."),
                ]},
                {"box": "Fan & Partner", "ic": "partner", "tiles": [
                    tile("Mobile App Offers", "api", "Personalised upsell and parking offers served in the team app."),
                    tile("Sponsor Reporting API", "share", "Activation proof and impression delivery to sponsors over Delta Sharing."),
                    tile("Broadcaster Data Feed", "globe", "Official stats and graphics packages shared to rights holders."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Dynamic Price Holds", "market", "Price tier adjustments written back to ticketing inventory.", "ticketmaster"),
                    tile("Staff Shift Dispatch", "people", "Concessions and security shift changes pushed to crew devices.", "ukg"),
                    tile("Coaching Clip Tags", "stream", "Tagged video moments written to the coaching platform.", "second-spectrum"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("League Revenue Share", "gavel", "Gate and local revenue reports filed to the league.", "stats-perform"),
                    tile("Safety Incident Reports", "share", "Crowd and medical incidents documented from governed logs.", "genetec"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Fan and performance products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "League partners reading live attendance via Delta Sharing."),
                ]},
            ], genie_spaces=[
                genie("Ticketing & Pricing", "Ask about sell-through pace, seat yield and secondary-market pressure in plain language.",
                      feeds=["Ticketmaster Archtics", "SeatGeek Enterprise", "Attendance, yield, engagement"],
                      teams=["Ticketing & Pricing", "Head of Ticketing", "Pricing Analyst"],
                      questions=[
                          "What was ticket yield by section for the last home stand?",
                          "Which sections are behind sell-through pace for the next event?",
                          "How much secondary-market pressure is building against face value?",
                          "Which events are pricing below the demand curve right now?",
                          "What is average net effective ticket price by opponent this season?"]),
                genie("Fan 360 & Engagement", "Explore fan profiles, membership churn and engagement stitched across channels.",
                      feeds=["Salesforce Marketing Cloud", "VenueNext", "Deltatre OTT Platform", "Conformed fan, event, asset"],
                      teams=["Fan Engagement", "CRM Director", "Membership Services"],
                      questions=[
                          "What is the total spend of this fan across tickets, concessions and merch?",
                          "Which season-ticket members are at churn risk before renewal?",
                          "Which fans are highly engaged on OTT but have never attended in person?",
                          "What is streaming concurrency and churn by content type?",
                          "Which segments respond best to the current personalised offer?"]),
                genie("Game-Day Operations", "Answer questions on ingress flow, concessions throughput and crowd safety.",
                      feeds=["VenueNext", "Genetec Security Center", "Ticketmaster Archtics", "Attendance, yield, engagement"],
                      teams=["Game-Day Ops", "VP Venue Operations", "Head of Security"],
                      questions=[
                          "How is ingress throughput tracking against target right now?",
                          "Which gates and concourses have the longest queues today?",
                          "Which concession stands are at risk of running out during peak?",
                          "Where are crowd-density hot spots approaching capacity thresholds?",
                          "How many incidents have been logged this event and of what type?"]),
                genie("Sponsorship & Media", "Ask about activation delivery, audience reach and sponsorship ROI.",
                      feeds=["SponsorUnited", "Nielsen Sports", "Stats Perform Feeds", "Attendance, yield, engagement"],
                      teams=["Ownership & Executive", "Chief Commercial Officer", "Fan Engagement"],
                      questions=[
                          "Which sponsors are under-delivering against contracted impressions?",
                          "What is the audience reach of last week's broadcast by segment?",
                          "How does sponsorship ROI compare across activation types?",
                          "Which digital properties drive the most sponsor conversions?",
                          "What premium inventory remains unsold for upcoming events?"]),
            ], dashboards=[
                dashboard("Attendance & Ticket Yield", "Attendance, sell-through and seat yield on certified Metric Views.",
                          kpis=["Attendance", "Sell-through rate", "Ticket yield per section", "Net effective rate", "No-show rate"],
                          teams=["Ownership & Executive", "Ticketing & Pricing", "Fan Engagement"]),
                dashboard("Fan Engagement & Churn", "Membership growth, churn risk and OTT engagement across channels.",
                          kpis=["Membership growth", "Churn risk", "Streaming concurrency", "Per-cap spend", "Offer conversion"],
                          teams=["Fan Engagement", "CRM Director", "Digital & Content"]),
                dashboard("Game-Day Operations", "Ingress flow, concessions throughput and safety incidents on event day.",
                          kpis=["Ingress throughput", "Queue time", "Concessions per cap", "Crowd density", "Incident count"],
                          teams=["Game-Day Ops", "VP Venue Operations", "Head of Security"]),
                dashboard("Sponsorship & Media ROI", "Activation delivery, audience reach and sponsorship return.",
                          kpis=["Sponsorship ROI", "Impressions delivered", "Audience reach", "Activation completion", "Premium inventory sold"],
                          teams=["Ownership & Executive", "Chief Commercial Officer", "Fan Engagement"]),
            ]),
        },
        "top": top_band(
            [app("Game-Day Command", "Venue operations", "gauge", "Live ingress, concessions throughput and security incidents on Databricks Apps over Lakebase."),
             app("Pricing Workbench", "Ticket yield", "market", "Demand curves and price tiers before on-sale and throughout the sales window."),
             app("Fan 360 Console", "Engagement view", "custlake", "Ticketing, concessions and CRM activity stitched per fan segment."),
             app("Load Management Hub", "Athlete readiness", "iot", "Player workload, injury risk and selection recommendations for coaching staff.")],
            [uc("Dynamic Ticket Pricing", "Revenue", "market", "Price tiers adjusted to demand, inventory and secondary market pressure.",
                problem="Seat prices sit on static tiers and stale rules, so demand shifts, opponent draw and secondary-market pressure move faster than pricing and revenue leaks on every event.",
                who="Ticketing & Pricing",
                how="Ticketing scans, demand and resale signals land through Lakeflow, conform on Delta Lake and are scored in Model Serving, with price tiers set in the Pricing Workbench through the sales window.",
                comps=["Pricing Workbench", "Ticketmaster Archtics", "Model Serving", "Lakeflow", "Delta Lake"],
                stories=[["Stadium Analytics: increasing sports fan engagement with data and AI", "https://www.databricks.com/blog/2022/03/31/stadium-analytics-increasing-sports-fan-engagement-with-data-and-ai.html"]]),
             uc("Fan Churn Prediction", "CRM", "custlake", "Season ticket and membership churn scored before renewal windows.",
                problem="Membership and season-ticket data sits apart from concessions and app behaviour, so churn is only noticed at renewal when the fan has already decided to walk.",
                who="Fan Engagement",
                how="Ticketing, CRM and concessions signals are stitched per fan in CustomerLake, scored for churn in Model Serving and surfaced in the Fan 360 Console before the renewal window opens.",
                comps=["Fan 360 Console", "Salesforce Marketing Cloud", "CustomerLake", "Model Serving", "AI/BI"],
                stories=[["NRL transforms fan experience with data", "https://www.databricks.com/customers/national-rugby-league"], ["Pumpjack Dataworks builds a fan data refinery on Databricks", "https://www.databricks.com/customers/pumpjack-dataworks"]]),
             uc("Concessions Optimization", "F&B", "product", "Stand staffing and menu mix tuned to expected attendance and weather.",
                problem="Stand staffing and menu mix are planned off last season's averages, so queues build at some counters while food is wasted at others and per-cap spend suffers on game day.",
                who="Game-Day Ops",
                how="POS folios, attendance and weather feeds conform on Delta Lake and forecast demand in Model Serving, with staffing and menu recommendations shown per stand in Game-Day Command.",
                comps=["Game-Day Command", "VenueNext", "Model Serving", "Delta Lake", "AI/BI"],
                stories=[["Stadium Analytics: increasing sports fan engagement with data and AI", "https://www.databricks.com/blog/2022/03/31/stadium-analytics-increasing-sports-fan-engagement-with-data-and-ai.html"]]),
             uc("Sponsorship ROI", "Commercial", "partner", "Activation impressions and conversions attributed to sponsor inventory.",
                problem="Sponsors want proof their logo drove attention and sales, but impressions, broadcast exposure and conversions live in separate systems, so activation value is argued rather than measured.",
                who="Ownership & Executive",
                how="Broadcast, social and CRM exposure conform under Unity Catalog and are attributed to sponsor inventory in AI/BI, with activation proof shared to sponsors as governed Data Products.",
                comps=["SponsorUnited", "Unity Catalog", "AI/BI", "Data Products", "Delta Lake"],
                stories=[["Pumpjack Dataworks builds a fan data refinery on Databricks", "https://www.databricks.com/customers/pumpjack-dataworks"]]),
             uc("Injury Risk Scoring", "Performance", "iot", "Load and biomechanical signals flagging elevated injury risk.",
                problem="Player load and biomechanical signals come off wearables in silos, so medical and coaching staff see fatigue and injury risk only after it costs a player or a result.",
                who="Game-Day Ops",
                how="Wearable and tracking feeds land in Lakehouse//RT, are engineered in Feature Store and scored for injury risk in Model Serving, with readiness shown in the Load Management Hub before selection.",
                comps=["Load Management Hub", "Catapult Sports", "Lakehouse//RT", "Feature Store", "Model Serving"],
                stories=[["LaLiga changes the world of sports with real-time streaming data", "https://www.databricks.com/customers/laliga"]]),
             uc("Broadcast Highlights", "Media", "stream", "Automated clip selection and publishing from live feeds.",
                problem="Clipping and publishing highlights is a manual scramble against the second screen, so the best moments reach social late and the audience has already moved on.",
                who="Fan Engagement",
                how="Live broadcast and play-by-play feeds land through Lakeflow and AI Functions score clip-worthy moments on Delta Lake, so highlights are selected and published from Grabyo Clipping in near real time.",
                comps=["Grabyo Clipping", "Stats Perform Feeds", "Lakeflow", "AI Functions", "Delta Lake"]),
             uc("Crowd Safety Analytics", "Operations", "gauge", "Density and ingress patterns flagged before capacity thresholds.",
                problem="Ingress crushes, density hot-spots and medical incidents are spotted by eye across dozens of cameras, so crews react after a bottleneck has already become a safety risk.",
                who="Game-Day Ops",
                how="Access-control and crowd-density feeds stream into Lakehouse//RT and are scored against density thresholds in Model Serving, alerting crews from Game-Day Command before capacity is breached.",
                comps=["Game-Day Command", "Genetec Security Center", "Lakehouse//RT", "Model Serving", "Delta Lake"]),
             uc("Secondary Market Intel", "Ticketing", "chart", "Transfer and resale activity informing primary pricing.",
                problem="Resale and transfer activity on secondary platforms signals true demand, but it arrives disconnected from primary inventory, so pricing and hold decisions are made half-blind.",
                who="Ticketing & Pricing",
                how="Secondary listings and transfer feeds land through Lakeflow, conform on Delta Lake alongside primary inventory and inform the price and hold moves surfaced in the Pricing Workbench.",
                comps=["Pricing Workbench", "SeatGeek Enterprise", "Lakeflow", "Delta Lake", "AI/BI"]),
             uc("OTT Personalization", "Streaming", "api", "Content recommendations and offers scored per viewer segment.",
                problem="Streaming viewers get generic content and offers because concurrency, device and viewing history sit apart from the CRM, so engagement and subscriber value are left on the table.",
                who="Fan Engagement",
                how="OTT telemetry and CRM data are stitched in CustomerLake and scored for recommendations in Model Serving, personalising content and offers per viewer segment in the direct-to-consumer app.",
                comps=["Deltatre OTT Platform", "CustomerLake", "Model Serving", "Feature Store", "AI/BI"],
                stories=[["Seven West Media fuels audience growth and ad revenue with AI", "https://www.databricks.com/customers/seven-west-media"], ["Empowering Swiss public media SRF with data-driven intelligence", "https://www.databricks.com/customers/srf"]]),
             uc("Merchandise Forecast", "Retail", "erp", "Event-level merch demand forecast tied to opponent and promotion.",
                problem="Event-level merch demand swings with opponent, promotion and result, but forecasts run on flat seasonal averages, so stock sells out on hot nights and sits dead on others.",
                who="Ownership & Executive",
                how="Sales, event and promotion data conform on Delta Lake and forecast per-event demand in Model Serving, with opponent and promotion features managed in Feature Store for the retail team.",
                comps=["Model Serving", "Feature Store", "Delta Lake", "AI/BI", "Data Products"])],
        ),
        "sources": {
            "ticketmaster": {"t": "Ticketmaster Archtics", "u": "https://business.ticketmaster.com/"},
            "sf-sports": {"t": "Salesforce Marketing Cloud", "u": "https://www.salesforce.com/products/marketing-cloud/overview/"},
            "seatgeek": {"t": "SeatGeek Enterprise", "u": "https://seatgeek.com/enterprise"},
            "venuenext": {"t": "VenueNext", "u": "https://www.venuenext.com/"},
            "genetec": {"t": "Genetec Security Center", "u": "https://www.genetec.com/"},
            "ukg": {"t": "UKG workforce management", "u": "https://www.ukg.com/"},
            "grabyo": {"t": "Grabyo", "u": "https://about.grabyo.com/"},
            "deltatre": {"t": "Deltatre OTT", "u": "https://www.deltatre.com/"},
            "nielsen-sports": {"t": "Nielsen Sports", "u": "https://www.nielsen.com/"},
            "sponsorunited": {"t": "SponsorUnited", "u": "https://www.sponsorunited.com/"},
            "trade-desk": {"t": "The Trade Desk", "u": "https://www.thetradedesk.com/"},
            "catapult": {"t": "Catapult Sports", "u": "https://www.catapult.com/"},
            "second-spectrum": {"t": "Second Spectrum", "u": "https://www.secondspectrum.com/"},
            "stats-perform": {"t": "Stats Perform", "u": "https://www.statsperform.com/"},
        },
    },
}
