import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_BANKING = {
    'banking': {
        "label": "Banking",
        "blurb": "Retail and commercial banking: core ledger, payments, lending, fraud, and regulatory reporting across branches and digital channels.",
        "medallion": medallion(
            "Raw core and channel logs",
            "Core banking postings, card authorizations, wire messages and CRM events landed exactly as received for audit replay.",
            "Conformed customers and accounts",
            "Customers, accounts, facilities and parties resolved into golden records across core, cards and channels.",
            "NIM, NPL, liquidity ratios",
            "Contracted products finance and risk run on: net interest margin, NPL ratio, LCR and customer profitability.",
        ),
        "rails": {
            "src": [
                {"box": "Core Banking", "ic": "erp", "tiles": [
                    tile("Temenos Transact", "erp", "Deposits, loans, GL and end-of-day across retail and commercial.", "temenos",
                         cat="Core Banking System",
                         what="Holds the system-of-record ledger for deposits, loans and the general ledger, and runs the end-of-day cycle that posts interest, fees and balances.",
                         users="Core banking operations, retail and commercial product teams, and Finance for the general ledger.",
                         data_out=data_out(
                             batch=flow(["structured"], "50-200 GB/day", "End-of-day batch + hourly deltas"),
                             stream=flow(["semi-structured"], "0.5-3k postings/sec at peak", "Continuous CDC (near real-time)"))),
                    tile("FIS Profile", "erp", "Account processing, interest accrual and regulatory extracts.", "fis-profile",
                         cat="Core Banking System",
                         what="Processes retail and commercial accounts, accrues interest and produces the regulatory and statement extracts the back office depends on.",
                         users="Deposit operations, Finance and Regulatory reporting teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "20-80 GB/day", "Nightly batch extracts"))),
                    tile("Fiserv DNA", "erp", "US core account processing: deposits, loans and GL on Fiserv DNA and Premier.", "finastra",
                         cat="Core Banking System",
                         what="US community and regional bank core platform covering deposits, loans and the GL, with real-time posting on the DNA architecture.",
                         users="Core operations and branch systems teams at US community and regional banks.",
                         data_out=data_out(
                             batch=flow(["structured"], "10-60 GB/day", "Nightly batch"),
                             stream=flow(["semi-structured"], "hundreds of events/sec", "Continuous CDC"))),
                ]},
                {"box": "Cards & Payments", "ic": "market", "tiles": [
                    tile("Visa DPS / Auth", "market", "Authorization, clearing and dispute messages.", "visa",
                         cat="Card Authorization & Clearing",
                         what="Carries the real-time card authorization decisions and the clearing and dispute (chargeback) messages that settle them.",
                         users="Fraud, Cards & Payments operations and Dispute/chargeback teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "5-30 GB/day clearing files", "Multiple settlement cycles daily"),
                             stream=flow(["semi-structured"], "2-10k auths/sec at peak", "Continuous (sub-second)"))),
                    tile("Mastercard Smart Data", "market", "Commercial-card expense and spend analytics with merchant category enrichment.", "mastercard",
                         cat="Commercial Card Spend Analytics",
                         what="Enriches commercial-card transactions with merchant, category and tax detail for expense management and spend analytics.",
                         users="Commercial Banking, Corporate card program managers and client Finance teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "1-5 GB/day", "Daily feed"))),
                    tile("SWIFT FIN Messages", "api", "Cross-border payment instructions and confirmations.", "swift",
                         cat="Interbank Messaging Network",
                         what="Standardized MT/MX financial messages for cross-border payments, confirmations and correspondent-bank instructions.",
                         users="Payments operations, Treasury and Correspondent banking teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "50-500 msgs/sec", "Continuous message flow"))),
                ]},
                {"box": "Digital Channels", "ic": "apps", "tiles": [
                    tile("Temenos Infinity", "apps", "Mobile and web sessions, transfers and self-service events.", "temenos-infinity",
                         cat="Digital Banking Platform",
                         what="Runs the mobile and web banking experience and emits the clickstream, transfer and self-service events behind digital journeys.",
                         users="Digital Banking, Product and Marketing analytics teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "5-20k events/sec at peak", "Continuous clickstream"))),
                    tile("Salesforce FSC", "custlake", "Households, opportunities and service cases.", "sf-fsc",
                         cat="Banking CRM",
                         what="Financial Services CRM holding household and relationship models, opportunities and service cases across channels.",
                         users="Retail and Commercial relationship managers, and Service teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/day", "Hourly / nightly sync"),
                             stream=flow(["semi-structured"], "tens of events/sec", "Continuous CDC"))),
                    tile("NICE Actimize", "gavel", "AML alerts, cases and SAR workflow.", "actimize",
                         cat="Financial Crime / AML Platform",
                         what="Generates AML transaction-monitoring alerts, manages investigation cases and drives the SAR filing workflow.",
                         users="Financial crime investigators, AML compliance and Fraud operations.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "2-8 GB/day alerts + cases", "Hourly"))),
                ]},
                {"box": "Risk & Finance", "ic": "chart", "tiles": [
                    tile("Moody's RiskCalc", "chart", "PD/LGD models and rating migrations for commercial names.", "moodys",
                         cat="Credit Risk Model Library",
                         what="Provides probability-of-default and loss-given-default models and rating migrations for commercial and corporate exposures.",
                         users="Credit risk modelers, Commercial credit officers and Regulatory capital teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "GBs (reference + scores)", "Daily / monthly refresh"))),
                    tile("FIS Ambit Focus", "chart", "ALM, liquidity and interest rate risk measurement.", "fis-alm",
                         cat="Asset & Liability Management System",
                         what="Measures balance-sheet interest-rate risk, liquidity and funding under scenarios for asset-liability management.",
                         users="Treasury, ALM and Liquidity risk teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "5-20 GB/day positions", "Daily + scenario runs"))),
                    tile("Nasdaq AxiomSL Reg Reporting", "gavel", "Basel, CCAR and local regulatory templates.", "axiomsl",
                         cat="Regulatory Reporting Platform",
                         what="Assembles Basel, CCAR and local regulatory returns from risk and finance data with full lineage and validation.",
                         users="Regulatory reporting, Finance and Risk control teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "10-40 GB/reporting cycle", "Daily / monthly / quarterly cycles"))),
                ]},
                {"box": "Open Banking", "ic": "api", "tiles": [
                    tile("Plaid Aggregation", "api", "External account verification and aggregation with consent.", "plaid",
                         cat="Account Aggregation Provider",
                         what="Connects to external accounts with customer consent to verify ownership and aggregate balances and transactions.",
                         users="Digital Banking, Lending origination and Personal financial management teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "100s of API calls/sec", "Continuous (API / webhook)"))),
                    tile("Tink Open Banking", "partner", "AIS/PIS traffic and consent registry.", "tink",
                         cat="Open Banking Platform",
                         what="Handles account-information and payment-initiation traffic under PSD2 with a consent registry for third-party access.",
                         users="Open banking, Payments and Compliance teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "100s-1000s of events/sec", "Continuous (API)"))),
                ]},
                fed_group("Data Warehouse Mart", "Historical GL and risk marts queried in place under Unity Catalog.",
                          cat="Enterprise Data Warehouse",
                          what="Legacy general-ledger and risk marts kept in the incumbent warehouse and queried in place through federation instead of being copied.",
                          users="Finance, Risk and Regulatory reporting analysts.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("FICO Falcon", "gavel", "Card fraud scores and consortium intelligence.", "fico",
                     cat="Card Fraud Scoring",
                     what="Scores card transactions for fraud in real time using consortium models and returns a risk score to the authorization path.",
                     users="Fraud operations and Card risk teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "2-10k scores/sec at peak", "Continuous (sub-second)"))),
                tile("LexisNexis Risk", "partner", "KYC, sanctions and adverse media screening.", "lexisnexis",
                     cat="KYC & Screening Provider",
                     what="Provides identity verification, sanctions and adverse-media screening used at onboarding and in ongoing due diligence.",
                     users="Financial crime compliance, KYC/onboarding and Sanctions teams.",
                     data_out=data_out(
                         batch=flow(["structured", "semi-structured"], "1-4 GB/day", "Daily + on-demand"))),
                tile("Experian Bureau", "custlake", "Credit bureau pulls and attribute refreshes.", "experian",
                     cat="Credit Bureau",
                     what="Supplies credit reports, scores and attribute refreshes used in lending decisions and portfolio monitoring.",
                     users="Lending, Credit risk and Collections teams.",
                     data_out=data_out(
                         batch=flow(["structured"], "1-3 GB/day", "Daily + on-demand pulls"))),
            ]),
            "ppl": ppl2([
                biz("Chief Credit Officer & CFO", "Genie One",
                    "The CEO on ROE and deposit growth; the CFO on net interest margin, cost-to-income and CET1 capital against NPL formation across the book.",
                    [["Genie One", "Ask what last quarter's NIM was by segment."], ["AI/BI", "Capital and liquidity on certified Metric Views."], ["Unity Catalog", "One customer definition across channels."]],
                    sub=[["Chief Executive Officer", "return on equity, deposit growth and the balance between growth and capital strength."], ["Chief Financial Officer", "net interest margin, cost-to-income and the certified numbers behind the results."], ["Chief Credit Officer", "portfolio credit quality, NPL formation and provisioning across the book."]],
                    ucs=["Regulatory Reporting", "Credit Early Warning", "Liquidity Forecasting"]),
                biz("Retail Banking", "AI/BI",
                    "Branch productivity, product penetration and attrition, judged on deposit and loan growth, household profitability and cross-sell.",
                    [["Branch Performance", "Household profitability by branch and RM."], ["AI/BI", "Deposit and loan growth on governed core data."]],
                    sub=[["Head of Branch Network", "branch productivity, deposit and loan growth and household profitability by region."], ["Head of Digital Banking", "mobile and web engagement, digital sales and self-service adoption."], ["Cards & Payments Lead", "card spend, interchange and fraud loss across the portfolio."]],
                    ucs=["Customer 360", "Next-Best-Product", "Collections Optimization", "Open Banking Analytics"]),
                biz("Commercial Banking", "Model Serving",
                    "Relationship profitability, covenants and limit utilization, tracked on risk-adjusted return, exposure at default and rating migration.",
                    [["RM Workbench", "Exposure and cross-sell opportunities by relationship."], ["Model Serving", "Early warning models on commercial books."]],
                    sub=[["Head of Corporate Banking", "relationship profitability and risk-adjusted return across the commercial book."], ["Relationship Managers", "exposure, covenant status and cross-sell across their named clients."], ["Credit Risk Officers", "limit utilization, rating migration and early signs of deterioration."]],
                    ucs=["Credit Early Warning", "Customer 360", "Regulatory Reporting"]),
                biz("Risk & Compliance", "Lakehouse//RT",
                    "Credit, market and operational risk with regulatory reporting, run on PD/LGD, fraud loss rate and AML alert-to-SAR conversion.",
                    [["AML Investigator", "Alert prioritization and case narrative drafting."], ["Lakehouse//RT", "Fraud scores at authorization latency."]],
                    sub=[["Chief Risk Officer", "credit, market and operational risk appetite and the loss rate across the bank."], ["Head of Financial Crime", "AML alert quality, SAR conversion and sanctions screening coverage."], ["Head of Fraud", "real-time fraud loss, false-positive rate and dispute volumes."]],
                    ucs=["Real-Time Fraud", "AML Transaction Monitoring", "Operational Loss", "Credit Early Warning"]),
                biz("Treasury & ALM", "AI/BI",
                    "Funding, liquidity buffers and hedge effectiveness, measured on LCR, NSFR and interest-rate gap under stress across the balance sheet.",
                    [["ALM Dashboard", "Gap and duration under rate scenarios."], ["AI/BI", "LCR and NSFR on certified regulatory views."]],
                    sub=[["Group Treasurer", "funding, liquidity buffers and the cost of funds across the balance sheet."], ["ALM Manager", "interest-rate gap, duration and hedge effectiveness under rate scenarios."], ["Liquidity Risk Lead", "LCR, NSFR and intraday liquidity under stress."]],
                    ucs=["Liquidity Forecasting", "Regulatory Reporting"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land core-banking postings, card-network authorizations, wire messages and market-data feeds; own Bronze to Silver and the pager when risk tables stall.",
                    [["Lakeflow Connect", "Managed connectors for core, cards and credit-bureau sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on posting and authorization feeds."], ["Lakewatch", "Freshness on the exposure and liquidity tables risk reads at open."]],
                    sub=[["Ingestion Engineers", "core-banking postings, card authorizations and wire messages landed on time."], ["Pipeline Engineers", "Bronze-to-Silver conforming and expectations on posting and auth feeds."], ["Platform Reliability", "freshness of the exposure and liquidity tables risk reads at open."]],
                    ucs=["Real-Time Fraud", "Regulatory Reporting", "Open Banking Analytics"]),
                biz("Data Scientists", "MLflow",
                    "PD/LGD credit-risk, AML transaction-monitoring, card-fraud and next-best-action models, and whether they still hold through a rate cycle.",
                    [["Feature Store", "Customer and transaction features read identically in training and serving."], ["MLflow", "Every PD and fraud model tracked for audit and reproduction."], ["Model Serving", "Fraud and PD models scored in the authorization path."]],
                    sub=[["Credit Risk Modelers", "PD, LGD and early-warning models that hold through a rate cycle."], ["Financial Crime DS", "AML and card-fraud models and keeping false positives low."], ["Marketing DS", "propensity, churn and next-best-action models on the retail book."]],
                    ucs=["Credit Early Warning", "Real-Time Fraud", "AML Transaction Monitoring", "Next-Best-Product"]),
                biz("App Developers", "Apps",
                    "Ship the limit, case-management, RM workbench and AML investigator apps risk and RMs work in, hosted next to governed customer data.",
                    [["Apps", "Risk and RM screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for limit and case-management state."], ["Agent Bricks", "Agents that draft case narratives and limit changes against governed tools."]],
                    sub=[["Full-Stack Engineers", "the limit, case-management and RM workbench screens bankers work in."], ["Agent Developers", "agents that draft case narratives and limit changes on governed tools."], ["Integration Engineers", "writeback of blocks, limits and offers into core and channels."]],
                    ucs=["AML Transaction Monitoring", "Credit Early Warning", "Collections Optimization"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Finance and risk dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for liquidity and exposure questions."),
                    tile("Notebooks & IDEs", "notebook", "Model development notebooks on governed customer data."),
                ]},
                {"box": "Partners & Networks", "ic": "partner", "tiles": [
                    tile("Card Network Files", "api", "Clearing and settlement files to Visa and Mastercard.", "visa"),
                    tile("Open Banking APIs", "api", "Account information and payment initiation to TPPs.", "tink"),
                    tile("Correspondent Banking", "globe", "SWIFT payment routing to correspondent banks.", "swift"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Limit Updates", "gauge", "Credit limits adjusted in core from early warning triggers."),
                    tile("Fraud Block Rules", "gavel", "Card blocks propagated to authorization switches.", "fico"),
                    tile("CRM Next-Best-Action", "custlake", "Offers pushed to digital channels from governed models.", "sf-fsc"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Basel III Returns", "gavel", "RWA and capital returns filed from contracted Gold tables.", "axiomsl"),
                    tile("FinCEN SAR Filing", "share", "Suspicious activity reports assembled from AML cases.", "actimize"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Customer and exposure products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Partners and regulators via governed sharing."),
                ]},
            ], genie_spaces=[
                genie("Fraud & Financial Crime", "Ask about fraud losses, alert quality and AML case backlogs in plain language.",
                      feeds=["Visa DPS / Auth", "NICE Actimize", "FICO Falcon", "Conformed customers and accounts"],
                      teams=["Risk & Compliance", "Head of Fraud", "AML Investigators"],
                      questions=[
                          "What is our card fraud loss rate this month versus last?",
                          "Which alert types have the worst false-positive rate right now?",
                          "How many AML cases are open past their SLA, and for which segments?",
                          "Which merchant categories are driving the most confirmed fraud?",
                          "What is the alert-to-SAR conversion rate by investigator team?"]),
                genie("Credit Risk", "Explore portfolio credit quality, early-warning signals and provisioning across the book.",
                      feeds=["Moody's RiskCalc", "Experian Bureau", "Conformed customers and accounts", "NIM, NPL, liquidity ratios"],
                      teams=["Commercial Banking", "Chief Credit Officer & CFO", "Credit Risk Officers"],
                      questions=[
                          "Which commercial names moved to a worse rating band this quarter?",
                          "What is our NPL ratio by segment and region?",
                          "Which exposures are approaching a covenant breach?",
                          "How has expected loss changed since last month and why?",
                          "Which borrowers show the strongest early-warning deterioration signals?"]),
                genie("Customer 360", "Answer household and relationship questions across deposits, loans, cards and digital.",
                      feeds=["Salesforce FSC", "Temenos Transact", "Temenos Infinity", "Conformed customers and accounts"],
                      teams=["Retail Banking", "Relationship Managers", "Marketing & Sales"],
                      questions=[
                          "What is the total relationship value of this household across all products?",
                          "Which customers hold only one product but look like cross-sell candidates?",
                          "What is deposit and loan growth by branch and relationship manager?",
                          "Which digitally-active customers have never been offered a card?",
                          "What is attrition risk for our top-decile households?"]),
                genie("Treasury & Liquidity", "Ask about funding, liquidity buffers and rate risk under stress.",
                      feeds=["FIS Ambit Focus", "SWIFT FIN Messages", "NIM, NPL, liquidity ratios"],
                      teams=["Treasury & ALM", "Group Treasurer", "Liquidity Risk Lead"],
                      questions=[
                          "What is our LCR and NSFR today, and the trend this quarter?",
                          "How does the interest-rate gap look under a +200bp shock?",
                          "What is projected deposit runoff under the stress scenario?",
                          "Which currencies show the tightest intraday liquidity?",
                          "How effective are our current hedges against rate moves?"]),
            ], dashboards=[
                dashboard("Capital & Liquidity", "Basel capital ratios, LCR and NSFR on certified regulatory Metric Views.",
                          kpis=["CET1 ratio", "LCR", "NSFR", "RWA", "Interest-rate gap"],
                          teams=["Chief Credit Officer & CFO", "Treasury & ALM", "Regulatory Reporting"]),
                dashboard("Fraud & AML Operations", "Fraud loss, alert volumes, false-positive rates and SAR throughput.",
                          kpis=["Fraud loss rate", "Alert volume", "False-positive rate", "Alert-to-SAR conversion", "Dispute volume"],
                          teams=["Risk & Compliance", "Head of Fraud", "Head of Financial Crime"]),
                dashboard("Retail Growth & Cross-Sell", "Deposit and loan growth, product penetration and household profitability.",
                          kpis=["Deposit growth", "Loan growth", "Products per household", "Cross-sell rate", "Household profitability"],
                          teams=["Retail Banking", "Marketing & Sales", "Head of Branch Network"]),
                dashboard("Credit Portfolio Quality", "NPL formation, rating migration and expected loss across the book.",
                          kpis=["NPL ratio", "Rating migration", "Expected loss", "PD/LGD trend", "Coverage ratio"],
                          teams=["Commercial Banking", "Credit Risk Officers", "Chief Credit Officer & CFO"]),
            ]),
        },
        "top": top_band(
            [app("Branch Performance", "Household P&L", "chart", "Deposit, loan and fee profitability by branch and relationship manager."),
             app("RM Workbench", "Commercial CRM", "custlake", "Exposure, covenant status and cross-sell pipeline on governed relationship data."),
             app("AML Investigator", "Case prioritization", "gavel", "Alerts ranked and narratives drafted against transaction graphs."),
             app("ALM Dashboard", "Liquidity gaps", "gauge", "Rate and liquidity scenarios with hedge recommendations.")],
            [uc("Real-Time Fraud", "Payments", "gavel", "Authorization decisions scored before funds leave the account.",
                problem="A stolen card or account is drained in the seconds between swipe and settlement, and overnight batch fraud checks only tell you how much you lost after the money is gone.",
                who="Risk & Compliance",
                how="Authorization messages land in Lakehouse//RT, fraud models in Model Serving score transaction features within the authorization window, and a decline returns before funds leave the account.",
                comps=["Visa DPS / Auth", "Lakehouse//RT", "Model Serving", "Feature Store", "MLflow"],
                stories=[["Coinbase scales real-time fraud detection on Databricks", "https://www.databricks.com/customers/coinbase/lakeflow"], ["Maya cuts fraud losses by up to 98%", "https://www.databricks.com/customers/maya"]]),
             uc("AML Transaction Monitoring", "Compliance", "gavel", "Suspicious patterns surfaced across channels and entities.",
                problem="Money-laundering signals are scattered across accounts, channels and entities, and rules-only monitoring buries analysts under alerts that are mostly false positives while real networks slip through.",
                who="Risk & Compliance",
                how="Transactions and KYC land under Unity Catalog, Model Serving scores alerts, and Agent Bricks agents build case files and draft SAR narratives in the AML Investigator for human sign-off.",
                comps=["AML Investigator", "NICE Actimize", "Agent Bricks", "Unity Catalog", "Model Serving"],
                stories=[["Modern BSA/AML compliance on Databricks", "https://www.databricks.com/blog/modern-bsaaml-compliance-databricks"]]),
             uc("Credit Early Warning", "Risk", "chart", "Commercial deterioration flagged before covenant breach.",
                problem="Commercial borrowers deteriorate months before a covenant breach, but early signals sit in separate risk, transaction and market systems, so managers see trouble only once it is on the books.",
                who="Commercial Banking",
                how="Exposure, rating and transaction features are engineered in Feature Store and scored by early-warning models in Model Serving, with runs tracked in MLflow and alerts surfaced in the RM Workbench.",
                comps=["RM Workbench", "Moody's RiskCalc", "Model Serving", "MLflow", "Feature Store"],
                stories=[["Techcombank runs 100+ credit risk models on Databricks", "https://www.databricks.com/customers/techcombank"], ["Capital One powers faster credit decisions", "https://www.databricks.com/customers/capital-one"]]),
             uc("Customer 360", "Retail", "custlake", "Household view across deposits, loans, cards and digital.",
                problem="A household's deposits, loans, cards and digital activity live in separate core and channel systems, so nobody sees the whole relationship and the same customer looks like a stranger in every silo.",
                who="Retail Banking",
                how="Core, card and channel feeds are resolved into golden customer and account records on Delta Lake under Unity Catalog, and the household view is served to bankers through AI/BI and Salesforce FSC.",
                comps=["Salesforce FSC", "Temenos Transact", "Unity Catalog", "Delta Lake", "AI/BI"],
                stories=[["HSBC scales customer analytics and network science", "https://www.databricks.com/customers/hsbc"], ["Siam Commercial Bank builds a single customer view", "https://www.databricks.com/customers/siam-commercial-bank"]]),
             uc("Next-Best-Product", "Marketing", "market", "Offers ranked by propensity and profitability.",
                problem="Offers go out on product-centric campaign calendars rather than what a household needs next, so conversion is low, the wrong customers are targeted and profitable cross-sell is left on the table.",
                who="Retail Banking",
                how="Propensity and profitability features in Feature Store feed ranking models in Model Serving, and next-best offers surface in Branch Performance and are pushed to Salesforce FSC.",
                comps=["Branch Performance", "Salesforce FSC", "Model Serving", "Feature Store", "AI Functions"],
                stories=[["Discovery Bank's next-best-action lifts engagement 40%", "https://www.databricks.com/customers/discovery-bank"], ["Banco Bradesco doubles conversion with next best action", "https://www.databricks.com/customers/banco-bradesco/lakeflow-declarative-pipelines"]]),
             uc("Liquidity Forecasting", "Treasury", "gauge", "Cash and collateral projections under stress scenarios.",
                problem="Treasury projects cash, collateral and deposit runoff from monthly snapshots and spreadsheets, so buffers are sized on stale positions and a funding squeeze shows up too late to hedge.",
                who="Treasury & ALM",
                how="Deposit, market and position feeds land on Delta Lake, runoff models in Model Serving project buffers under stress, and gap and LCR scenarios surface in the ALM Dashboard and AI/BI.",
                comps=["ALM Dashboard", "FIS Ambit Focus", "Model Serving", "AI/BI", "Delta Lake"],
                stories=[["How Databricks helps banks navigate interest rate changes", "https://www.databricks.com/blog/how-databricks-helps-banks-navigate-interest-rate-changes"]]),
             uc("Regulatory Reporting", "Finance", "erp", "Basel, CCAR and local returns from one governed model.",
                problem="Basel, CCAR and local returns are stitched from dozens of risk and finance systems each cycle, so reconciliation is manual, lineage is hard to prove and one restatement can trigger a finding.",
                who="Chief Credit Officer & CFO",
                how="Risk and finance data conform into governed Gold tables under Unity Catalog with full lineage, and returns are assembled for Nasdaq AxiomSL Reg Reporting and published as Data Products.",
                comps=["Nasdaq AxiomSL Reg Reporting", "Unity Catalog", "Delta Lake", "AI/BI", "Data Products"],
                stories=[["BCBS 239 compliance in the age of AI (ABN AMRO)", "https://www.databricks.com/blog/bcbs-239-compliance-age-ai-turning-regulatory-burden-strategic-advantage"]]),
             uc("Open Banking Analytics", "Digital", "api", "Consent, aggregation and payment initiation insights.",
                problem="Consent, aggregation and payment-initiation traffic from third parties arrives in fragmented API logs, so the bank cannot see how open-banking journeys perform or which partners drive value.",
                who="Retail Banking",
                how="Aggregation and consent feeds land through Lakeflow onto Delta Lake, are conformed under governance, and partner, consent and payment-initiation metrics are analyzed in AI/BI.",
                comps=["Plaid Aggregation", "Tink Open Banking", "Lakeflow", "Delta Lake", "AI/BI"],
                stories=[]),
             uc("Collections Optimization", "Lending", "people", "Treatment strategies ranked by recovery probability.",
                problem="Delinquent accounts get the same generic dunning regardless of who will actually pay, so recoveries are low, good customers are pushed away and collections cost more than they return.",
                who="Retail Banking",
                how="Servicing and behavior features in Feature Store feed recovery-probability models in Model Serving tracked in MLflow, so each account gets the treatment most likely to cure.",
                comps=["Fiserv DNA", "Model Serving", "Feature Store", "MLflow", "AI Functions"],
                stories=[["Ophelos optimizes debt collection on Databricks", "https://www.databricks.com/customers/ophelos"], ["Oakbrook builds a collections decision engine", "https://www.databricks.com/customers/oakbrook"]]),
             uc("Operational Loss", "Risk", "gavel", "Loss events captured and capitalized for AMA frameworks.",
                problem="Operational loss events are logged in scattered spreadsheets and case tools, so capital under advanced measurement is modeled on incomplete history and control failures recur unseen.",
                who="Risk & Compliance",
                how="Loss events and near-misses are captured into governed Delta Lake tables under Unity Catalog, aggregated for AMA capital, and analyzed in AI/BI and published as Data Products.",
                comps=["Unity Catalog", "Delta Lake", "Nasdaq AxiomSL Reg Reporting", "AI/BI", "Data Products"],
                stories=[])],
        ),
        "sources": {
            "temenos": {"t": "Temenos Transact", "u": "https://www.temenos.com/products/transact/"},
            "fis-profile": {"t": "FIS Profile", "u": "https://www.fisglobal.com/products/core-banking"},
            "finastra": {"t": "Fiserv DNA", "u": "https://www.fiserv.com/"},
            "visa": {"t": "Visa", "u": "https://www.visa.com/"},
            "mastercard": {"t": "Mastercard", "u": "https://www.mastercard.com/"},
            "swift": {"t": "SWIFT", "u": "https://www.swift.com/"},
            "temenos-infinity": {"t": "Temenos Infinity", "u": "https://www.temenos.com/products/infinity/"},
            "sf-fsc": {"t": "Salesforce Financial Services Cloud", "u": "https://www.salesforce.com/financial-services/"},
            "actimize": {"t": "NICE Actimize", "u": "https://www.niceactimize.com/"},
            "moodys": {"t": "Moody's Analytics", "u": "https://www.moodys.com/"},
            "fis-alm": {"t": "FIS ALM", "u": "https://www.fisglobal.com/products/treasury-and-risk"},
            "axiomsl": {"t": "Nasdaq AxiomSL", "u": "https://www.nasdaq.com/solutions/fintech/nasdaq-axiomsl/regulatory-reporting"},
            "plaid": {"t": "Plaid", "u": "https://plaid.com/"},
            "tink": {"t": "Tink", "u": "https://tink.com/"},
            "fico": {"t": "FICO", "u": "https://www.fico.com/"},
            "lexisnexis": {"t": "LexisNexis Risk Solutions", "u": "https://risk.lexisnexis.com/"},
            "experian": {"t": "Experian", "u": "https://www.experian.com/business/"},
        },
    },
}
