import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_RAIL_TRANSIT = {
    "rail_transit": {
        "label": "Rail & Transit",
        "blurb": "Freight railroads and passenger transit: rolling-stock and track maintenance, signaling and PTC, network dispatch, fare collection and ridership, scheduling and safety reporting.",
        "medallion": medallion(
            "Raw operational feeds",
            "PTC and signaling event logs, AVL and GPS position pings, AFC tap and ticketing transactions, Maximo and SAP work orders, wayside detector and track-geometry readings, and GTFS-RT trip updates, landed exactly as received so a delay code or a fare can always be replayed as it stood.",
            "Conformed train, asset, trip",
            "Trains, rolling-stock and track assets, and scheduled trips resolved into single conformed entities across the signaling, dispatch, maintenance and fare estates, with station and stop codes reconciled and multi-leg journeys stitched to one trip.",
            "OTP, availability, ridership",
            "Contracted products the operations and commercial teams run on: on-time performance and delay attribution by cause, asset availability and mean distance between failures, ridership and farebox recovery by line, and energy per train-kilometre.",
        ),
        "rails": {
            "src": [
                {"box": "Asset & Maintenance", "ic": "erp", "tiles": [
                    tile("IBM Maximo", "erp", "Enterprise asset management for rolling stock and infrastructure: work orders, component lifing, defect history and maintenance planning against every asset.", cite=["maximo"]),
                    tile("SAP EAM", "erp", "Plant maintenance and enterprise asset management where SAP is the incumbent, feeding the same asset, work-order and spares entities.", cite=["sap-eam"]),
                    tile("Bentley AssetWise", "db", "Linear and infrastructure asset management: track, structures and signaling assets, their condition and their inspection and renewal history.", cite=["assetwise"]),
                ]},
                {"box": "Signaling & Control", "ic": "network", "tiles": [
                    tile("Wabtec I-ETMS PTC", "network", "Interoperable positive train control: on-board and back-office enforcement of movement authority, the source of exceedance and enforcement events.", cite=["ptc"]),
                    tile("Siemens Trainguard", "network", "CBTC and automatic train control for mass transit, the moving-block signaling basis for headway, throughput and energy-optimised driving.", cite=["trainguard"]),
                    tile("Alstom Signalling", "iot", "Interlockings, ETCS and wayside signaling, the source of route setting, occupancy and aspect state across the network.", cite=["alstom-sig"]),
                ]},
                {"box": "Dispatch & Network Ops", "ic": "stream", "tiles": [
                    tile("RailConnect TMS", "stream", "Wabtec transportation management: train sheets, crew calling, waybills and movement authority, the operational backbone of a freight railroad.", cite=["wabtec"]),
                    tile("Alstom Iconis", "gauge", "Integrated traffic management and control centre: dispatcher decisions, conflict detection and network-wide movement supervision.", cite=["alstom-sig"]),
                    tile("AVL / GPS Telemetry", "iot", "Automatic vehicle location and GPS pings from locomotives and transit vehicles, the ground truth for position, speed and run adherence."),
                ]},
                {"box": "Fare & Ridership", "ic": "market", "tiles": [
                    tile("Cubic AFC", "market", "Automated fare collection: gates, validators, account-based ticketing and the tap transactions that measure ridership and revenue.", cite=["cubic"]),
                    tile("INIT", "partner", "Fare collection and CAD/AVL for public transit: ticketing, vehicle location and passenger counting on one integrated estate.", cite=["init"]),
                    tile("Scheidt & Bachmann", "product", "Fare collection and ticketing systems: validators, ticket vending and the back office that reconciles fares to revenue.", cite=["scheidt"]),
                ]},
                {"box": "Scheduling & Sensors", "ic": "sheet", "tiles": [
                    tile("GIRO HASTUS", "sheet", "Transit scheduling and crew rostering: timetables, blocking, runcutting and rosters, the plan the operation is measured against.", cite=["hastus"]),
                    tile("GTFS / GTFS-RT", "stream", "General Transit Feed Specification static schedules and real-time trip updates, the open standard for stops, trips and live arrivals.", cite=["gtfs"]),
                    tile("Wayside Detectors", "iot", "Hot bearing, wheel-impact and dragging-equipment detectors along the track, catching a failing axle before it becomes a derailment.", cite=["hotbox"]),
                    tile("Track Geometry", "iot", "Track-geometry inspection car runs measuring gauge, alignment and cant, the basis for slow orders and renewal planning.", cite=["trackgeo"]),
                ]},
                fed_group("Cost & Revenue Marts", "Finance, farebox recovery and subsidy marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers."),
            ],
            "ing": ing_rail([
                tile("Mobile Ticketing", "api", "Account-based and mobile ticketing platforms carrying purchases and validations inbound, joined to AFC taps for ridership and revenue.", cite=["masabi"]),
                tile("Weather & Geo", "globe", "Weather, geospatial and land-use feeds joined to movement and demand for delay, energy and ridership analysis."),
                tile("IoT Event Streams", "stream", "Existing Kafka or event-hub topics carrying AVL, sensor and PTC events, landed generically as structured events."),
            ]),
            "ppl": ppl2([
                biz("Executive Team", "Genie One",
                    "The CEO on network reliability, the capital program and the trade between growth and cost; the CFO on farebox recovery, subsidy and cost per train-kilometre; the Chief Operating Officer on on-time performance, disruption cost and the safety record.",
                    [
                        ["Genie One", "Ask what yesterday's punctuality or asset availability was, without booking analyst time."],
                        ["AI/BI", "On-time performance, ridership, asset availability and cost per train-km on one certified set of Metric Views."],
                        ["Unity Catalog", "Certification and the glossary so \"on time\" and \"availability\" mean one thing across the network."],
                    ],
                    sub=[
                        ["CEO", "network reliability, the capital program and the safety record."],
                        ["CFO & Finance", "farebox recovery, subsidy and cost per train-kilometre."],
                        ["Chief Operating Officer", "on-time performance, disruption cost and asset availability."],
                    ],
                    ucs=["Delay Prediction", "Predictive Maintenance", "Ridership Forecast", "Network Dispatch Opt"]),
                biz("Network Ops", "Lakehouse//RT",
                    "Dispatchers and network controllers running a live railroad; crew control repairing rosters when the operation moves; passenger information teams keeping riders accurately informed through disruption.",
                    [
                        ["Dispatch Cockpit", "Movement and dispatch decisions costed across trains, crews and infrastructure together."],
                        ["Lakehouse//RT", "Live network state at the latency a train movement moves at."],
                        ["Model Serving", "Delay-probability and conflict-resolution models scored inside the operational path."],
                    ],
                    sub=[
                        ["Dispatchers", "train movement, conflicts and network control from the control centre."],
                        ["Crew control", "roster repair and duty-limit compliance when the operation moves."],
                        ["Passenger information", "real-time arrivals and disruption messaging to riders."],
                    ],
                    ucs=["Delay Prediction", "Network Dispatch Opt", "Energy & Traction Opt", "Crew & Scheduling", "Live Passenger Info"]),
                biz("Fleet & Assets", "Model Serving",
                    "Rolling-stock and infrastructure engineers on predicted component removals, track condition and the Maximo work orders raised against the fleet and network they already run.",
                    [
                        ["Asset Health Watch", "Predicted component and track failures raised as work orders before they strand a train."],
                        ["MLflow", "Remaining-useful-life and defect models tracked for audit and reproduction."],
                        ["Model Serving", "Removal and defect models scored against live sensor and inspection data."],
                    ],
                    sub=[
                        ["Rolling-stock engineering", "component lifing and predicted removals across the fleet."],
                        ["Infrastructure & track", "track geometry, structures and wayside asset condition."],
                    ],
                    ucs=["Predictive Maintenance", "Track Inspection", "Energy & Traction Opt"]),
                biz("Revenue & Fares", "AI/BI",
                    "Revenue and ridership teams on farebox recovery, demand and fares; fare collection teams on AFC integrity, reconciliation and revenue protection.",
                    [
                        ["Ridership Studio", "Ridership, origin-destination demand and farebox recovery on certified definitions."],
                        ["AI/BI", "Demand, ridership and revenue on the same definitions the executive team reads."],
                        ["Feature Store", "Demand and revenue features defined once and read identically in training and serving."],
                    ],
                    sub=[
                        ["Revenue & demand", "ridership forecasting, fares and farebox recovery."],
                        ["Fare collection", "AFC integrity, reconciliation and revenue protection."],
                    ],
                    ucs=["Ridership Forecast", "Revenue Protection", "Live Passenger Info"]),
                biz("Safety & Reg", "Unity Catalog",
                    "Safety and compliance teams on signaling and PTC event analysis, incident investigation and the punctuality, safety and emissions reporting filed with the authority.",
                    [
                        ["Safety Insights", "Signaling, PTC and incident events analysed for precursors before they become events."],
                        ["Unity Catalog", "Governed, auditable safety and regulatory tables with lineage end to end."],
                        ["AI Functions", "Incident reports and inspection notes classified and summarised at scale."],
                    ],
                    sub=[
                        ["Safety assurance", "precursor analysis on signaling, PTC and near-miss data."],
                        ["Regulatory reporting", "punctuality, safety and emissions submissions to the authority."],
                    ],
                    ucs=["Safety Event Analytics", "Track Inspection", "Predictive Maintenance"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land the EAM, signaling and PTC, AVL, AFC and GTFS-RT feeds; own the Bronze to Silver path and the pager when a pipeline breaks.",
                    [
                        ["Lakeflow Connect", "Managed connectors for Maximo, SAP and the AFC and scheduling systems."],
                        ["Lakeflow Designer", "Declarative pipelines with expectations on movement, sensor and tap feeds."],
                        ["Lakewatch", "Freshness on the tables dispatch and revenue teams read every morning."],
                    ],
                    sub=[
                        ["Ingestion engineers", "EAM, AFC and scheduling feeds into Bronze."],
                        ["Streaming engineers", "AVL, PTC and GTFS-RT events into Lakehouse//RT."],
                        ["Platform & governance", "Unity Catalog permissions and pipeline SLAs."],
                    ],
                    ucs=["Delay Prediction", "Predictive Maintenance", "Network Dispatch Opt"]),
                biz("Data Scientists", "MLflow",
                    "Delay-probability, remaining-useful-life, demand and energy-optimisation models, and whether they still hold six months after deployment.",
                    [
                        ["Feature Store", "Features defined once and read identically in training and serving."],
                        ["MLflow", "Every run tracked for audit and reproduction."],
                        ["Model Serving", "Delay, RUL and demand models scored in the operational path."],
                    ],
                    sub=[
                        ["Reliability modelers", "remaining-useful-life on sensor and defect history."],
                        ["Ops & demand modelers", "delay-probability and ridership demand models."],
                        ["MLOps", "tracking and serving models in the operational path."],
                    ],
                    ucs=["Predictive Maintenance", "Delay Prediction", "Ridership Forecast"]),
                biz("App Developers", "Apps",
                    "Ship the dispatch, asset-health, ridership and safety applications the railroad works in, hosted next to governed data.",
                    [
                        ["Apps", "Operational screens with no separate web tier to run or secure."],
                        ["Lakebase", "Serverless Postgres for dispatch decisions and work-order writes."],
                        ["Agent Bricks", "Agents that draft a recovery plan or work order against governed tools."],
                    ],
                    sub=[
                        ["Operational app developers", "dispatch, asset-health and ridership screens."],
                        ["Backend & Lakebase", "dispatch and work-order state with governed writes."],
                        ["Agent developers", "recovery-plan and work-order drafting agents."],
                    ],
                    ucs=["Network Dispatch Opt", "Predictive Maintenance"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "External BI against serverless SQL warehouses, with Unity Catalog permissions enforced end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for Unity Catalog-governed answers from the lakehouse, and delay and disruption updates in the channel the operation already works in (Beta)."),
                    tile("Notebooks & IDEs", "notebook", "Notebooks, VS Code and JetBrains against governed data and Genie Code."),
                ]},
                {"box": "Riders & Partners", "ic": "partner", "tiles": [
                    tile("GTFS-RT Open Feeds", "share", "Live arrivals and disruption published as GTFS-RT to journey planners and rider apps from the same predictions the operation runs on.", cite=["gtfs"]),
                    tile("Delta Sharing", "share", "Neighbouring operators, authorities and infrastructure owners reading live schedule and disruption state rather than nightly file exchange."),
                    tile("Journey Planner APIs", "api", "Trip planning and arrival APIs served to rider apps and third-party mobility platforms."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Maximo Work Orders", "erp", "Predicted component and track removals raised as maintenance work orders against the asset, in the system engineering already works in.", cite=["maximo"]),
                    tile("Dispatch Writeback", "db", "Recovery and movement decisions written back into the dispatch and TMS estate so the answer reaches the controller's screen."),
                    tile("Crew & Field Mobile", "apps", "Roster changes, standby calls and inspection tasks pushed to the devices crew and field teams actually carry."),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Safety Submissions", "gavel", "Punctuality, safety and incident reporting to the rail safety authority, produced from the same governed tables the railroad runs on.", cite=["fra"]),
                    tile("Energy & ESG Report", "share", "Traction energy and emissions accounting and the network's sustainability reporting, filed from contracted Gold products."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Published, contracted products discoverable in Unity Catalog Domains and shared over Open Sharing."),
                    tile("Sharing Recipients", "share", "Lessors, maintenance partners and infrastructure owners reading live tables with no copy and no egress duplication."),
                ]},
            ]),
        },
        "top": top_band([
            app("Dispatch Cockpit", "Network control", "gauge",
                "The screen dispatchers run a live railroad from: movement conflicts, delay probability and recovery options costed across trains, crews and infrastructure, on Databricks Apps over Lakebase."),
            app("Asset Health Watch", "Fleet & track health", "iot",
                "Component and track condition and predicted failures by asset, so engineering plans the fix at a depot overnight instead of stranding a train in service."),
            app("Ridership Studio", "Demand & revenue", "market",
                "Where revenue and ridership analysts see origin-destination demand, farebox recovery and the revenue at risk on a line before a service or fare change."),
            app("Safety Insights", "Safety & compliance", "gavel",
                "Signaling, PTC and incident events surfaced with precursor scoring, and the regulatory submissions produced from the same governed tables the railroad runs on."),
        ], [
            uc("Predictive Maintenance", "Rolling stock", "iot",
               "Predicting component removal from sensor, telematics and defect history so a failure in service becomes a planned depot visit.",
               problem="A traction motor or door fault discovered in service cancels trains and cascades across the diagram. Removals need predicting from actual condition, not a calendar, so the fix becomes a planned depot visit.",
               who="Fleet & Assets",
               how="Fleet telematics, sensor and Maximo defect history feed remaining-useful-life models tracked in MLflow and scored in Model Serving; predicted removals raise work orders from Asset Health Watch.",
               comps=["Asset Health Watch", "IBM Maximo", "MLflow", "Model Serving", "Wayside Detectors"],
               stories=[
                   ["Hitachi: predictive maintenance on railway overhead lines", "https://www.databricks.com/customers/hitachi"],
                   ["Predictive maintenance on the Databricks Lakehouse", "https://www.databricks.com/blog/what-is-predictive-maintenance"],
               ]),
            uc("Track Inspection", "Infrastructure", "gauge",
               "Turning track-geometry and wayside inspection data into defect predictions so a rail or bearing fault is caught before it becomes a slow order or a derailment risk.",
               problem="Track and structures are inspected on a fixed cycle; a geometry defect or a hot bearing that develops between inspections is found late, forcing an emergency slow order or worse.",
               who="Fleet & Assets",
               how="Track-geometry runs, wayside detector readings and inspection notes are conformed in Delta Lake; defect and severity models score each segment through Model Serving and AI Functions triages the backlog.",
               comps=["Track Geometry", "Wayside Detectors", "Model Serving", "AI Functions", "Asset Health Watch"],
               stories=[
                   ["ARTC unifies 8,500km of rail network data on Databricks", "https://www.databricks.com/customers/artc"],
                   ["Sporveien: analysing Oslo metro operations on Databricks", "https://www.databricks.com/blog/2017/06/14/analyzing-metro-operations-using-apache-spark.html"],
               ]),
            uc("Delay Prediction", "Punctuality", "stream",
               "Predicting where the network will run late from live movement, signaling and knock-on effects, so controllers intervene before the delay propagates.",
               problem="On-time performance is lost to knock-on delay that propagates faster than a controller can see it. Explained after the fact it is a report; predicted, it is a decision.",
               who="Network Ops",
               how="AVL, signaling and GTFS-RT feeds stream into Lakehouse//RT; delay-probability models score each service through Model Serving and surface in the Dispatch Cockpit and AI/BI.",
               comps=["Dispatch Cockpit", "Lakehouse//RT", "Model Serving", "GTFS / GTFS-RT", "AI/BI"],
               stories=[
                   ["BKK transforms Budapest city mobility with Databricks", "https://www.databricks.com/blog/driving-budapest-forward-how-bkk-uses-databricks-transform-city-mobility"],
               ]),
            uc("Network Dispatch Opt", "Movement planning", "network",
               "Optimising train movements, meets and passes across a congested network so throughput and reliability rise without new track.",
               problem="On a single-track or congested network, meet-and-pass and dispatch decisions made locally leave capacity and reliability on the table that a network-wide view would recover.",
               who="Network Ops",
               how="Movement, TMS and infrastructure feeds are conformed and served in Lakehouse//RT; movement-optimisation models are scored through Model Serving and actioned from the Dispatch Cockpit on Lakebase.",
               comps=["Dispatch Cockpit", "RailConnect TMS", "Model Serving", "Lakehouse//RT", "Lakebase"],
               stories=[
                   ["J.B. Hunt builds its transportation network on Databricks", "https://www.databricks.com/customers/jbhunt"],
                   ["A major freight railroad scales pipelines with Genie Code", "https://www.databricks.com/blog/how-major-freight-railroad-scaled-pipeline-creation-genie-code"],
               ]),
            uc("Ridership Forecast", "Demand", "market",
               "Forecasting ridership and origin-destination demand from AFC taps, schedules and events so service and capacity match how people actually travel.",
               problem="Service and capacity are planned on last year's timetable while demand shifts with events, seasons and land use. Overcrowding and empty trains are both the same missing forecast.",
               who="Revenue & Fares",
               how="AFC tap and ridership data are conformed with schedule and event feeds; demand models score each line and time band through Model Serving and Feature Store, explored in Ridership Studio.",
               comps=["Ridership Studio", "Cubic AFC", "Model Serving", "AI/BI", "Feature Store"],
               stories=[
                   ["BKK transforms Budapest city mobility with Databricks", "https://www.databricks.com/blog/driving-budapest-forward-how-bkk-uses-databricks-transform-city-mobility"],
                   ["Grab unifies transport data with C360 on Databricks", "https://www.databricks.com/customers/grab"],
               ]),
            uc("Energy & Traction Opt", "Cost & emissions", "chart",
               "Cutting traction energy and emissions through driving-style, timetable and route decisions scored against live speed and load data.",
               problem="Traction energy is a top controllable cost and emissions line, yet driving-style and timetable decisions are made without the speed, gradient and load data that would optimise them.",
               who="Network Ops",
               how="AVL, speed and load data are conformed to Gold; energy-optimisation recommendations are scored in Model Serving and reconciled against the network's sustainability reporting.",
               comps=["AVL / GPS Telemetry", "Model Serving", "AI/BI", "Lakeflow"],
               stories=[
                   ["BKK optimises route performance and energy with Databricks", "https://www.databricks.com/blog/driving-budapest-forward-how-bkk-uses-databricks-transform-city-mobility"],
               ]),
            uc("Crew & Scheduling", "Planning", "people",
               "Building legal, low-cost crew rosters and repairing them when the operation moves, without tipping a crew into a duty-hours breach.",
               problem="Legal, low-cost rosters must hold under duty-hours rules and then be repaired the moment the operation moves, without ever running a crew past their limits.",
               who="Network Ops",
               how="HASTUS roster and duty state is conformed and served in Lakehouse//RT; disruption models flag crews nearing limits so rosters are repaired before they break.",
               comps=["GIRO HASTUS", "Model Serving", "Lakehouse//RT", "AI/BI"],
               stories=[
                   ["BKK: dynamic scheduling and capacity on Databricks", "https://www.databricks.com/blog/driving-budapest-forward-how-bkk-uses-databricks-transform-city-mobility"],
               ]),
            uc("Safety Event Analytics", "Safety", "gavel",
               "Mining signaling, PTC and incident data for the precursors that precede a SPAD or a collision, so the risk is retired before it becomes an event.",
               problem="Signaling exceedances, PTC enforcements and near-misses hold the precursors of the next serious event, but scattered across systems they are counted after the fact rather than acted on.",
               who="Safety & Reg",
               how="PTC, signaling and incident feeds are governed in Unity Catalog and analysed in Delta Lake; AI Functions classifies incident narratives and Safety Insights surfaces precursor patterns.",
               comps=["Safety Insights", "Wabtec I-ETMS PTC", "AI Functions", "Unity Catalog", "Delta Lake"],
               stories=[
                   ["Hitachi makes railways safer with AI on Databricks", "https://www.databricks.com/customers/hitachi"],
               ]),
            uc("Live Passenger Info", "Rider experience", "chat",
               "Turning live movement and prediction into accurate arrivals and disruption messaging pushed to riders through open feeds and journey planners.",
               problem="Riders judge a service on whether the arrival board is right. When real-time prediction lags the actual train, trust in the whole network erodes.",
               who="Network Ops",
               how="GTFS-RT and AVL feeds stream into Lakehouse//RT; predicted arrivals are published through GTFS-RT open feeds to journey planners and surfaced in AI/BI.",
               comps=["GTFS / GTFS-RT", "Lakehouse//RT", "GTFS-RT Open Feeds", "AI/BI"],
               stories=[
                   ["Grab unifies transport data with C360 on Databricks", "https://www.databricks.com/customers/grab"],
                   ["BKK transforms Budapest city mobility with Databricks", "https://www.databricks.com/blog/driving-budapest-forward-how-bkk-uses-databricks-transform-city-mobility"],
               ]),
            uc("Revenue Protection", "Fare integrity", "market",
               "Detecting fare evasion, AFC leakage and reconciliation gaps so revenue that is being earned actually lands.",
               problem="Fare revenue leaks through evasion, mis-taps and reconciliation gaps between the AFC estate and the general ledger, and the leakage is invisible until an audit finds it.",
               who="Revenue & Fares",
               how="AFC tap, gate and reconciliation data are joined in the lakehouse; evasion and anomaly models score patterns through Model Serving and AI Functions flags reconciliation breaks in Ridership Studio.",
               comps=["Ridership Studio", "Cubic AFC", "Model Serving", "AI Functions", "Scheidt & Bachmann"]),
        ]),
        "sources": {
            "maximo": {"t": "IBM Maximo Application Suite", "u": "https://www.ibm.com/products/maximo"},
            "sap-eam": {"t": "SAP Enterprise Asset Management", "u": "https://www.sap.com/products/scm/asset-management-eam.html"},
            "assetwise": {"t": "Bentley AssetWise", "u": "https://www.bentley.com/software/assetwise/"},
            "ptc": {"t": "Positive Train Control (I-ETMS)", "u": "https://en.wikipedia.org/wiki/Positive_train_control"},
            "trainguard": {"t": "Siemens Mobility Trainguard CBTC", "u": "https://www.mobility.siemens.com/global/en/portfolio/rail-infrastructure/mass-transit/communications-based-train-control-system.html"},
            "alstom-sig": {"t": "Alstom signalling solutions", "u": "https://www.alstom.com/our-solutions/signalling"},
            "wabtec": {"t": "Wabtec (RailConnect TMS)", "u": "https://en.wikipedia.org/wiki/Wabtec"},
            "cubic": {"t": "Cubic Transportation Systems", "u": "https://www.cubic.com/transportation"},
            "init": {"t": "INIT transit fare collection and ITS", "u": "https://www.initse.com/enus/"},
            "scheidt": {"t": "Scheidt & Bachmann fare collection", "u": "https://www.scheidt-bachmann.de/en/fare-collection-systems/"},
            "hastus": {"t": "GIRO HASTUS scheduling", "u": "https://www.giro.ca/en-us/our-solutions/hastus-software/"},
            "gtfs": {"t": "General Transit Feed Specification", "u": "https://gtfs.org/"},
            "hotbox": {"t": "Hot box / wayside detectors", "u": "https://en.wikipedia.org/wiki/Hot_box"},
            "trackgeo": {"t": "Track geometry car", "u": "https://en.wikipedia.org/wiki/Track_geometry_car"},
            "masabi": {"t": "Masabi mobile ticketing", "u": "https://www.masabi.com/"},
            "fra": {"t": "US Federal Railroad Administration", "u": "https://railroads.dot.gov/"},
        },
    }
}
