import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_ECOMMERCE = {
    'ecommerce': {
        "label": "E-Commerce",
        "blurb": "Digital commerce: catalog, orders, fulfillment, personalization, and marketplace operations across DTC and marketplace channels.",
        "medallion": medallion(
            "Raw clickstream and orders",
            "Web events, OMS orders, payment captures and WMS shipments landed exactly as received.",
            "Conformed customers and orders",
            "Customers, sessions, orders and SKUs resolved across storefront, OMS and fulfillment.",
            "Conversion, AOV, LTV",
            "Contracted products growth and ops run on: conversion rate, AOV, repeat rate and fulfillment SLA.",
        ),
        "rails": {
            "src": [
                {"box": "Commerce Platform", "ic": "apps", "tiles": [
                    tile("Shopify Plus", "apps", "Catalog, carts, checkouts and customer accounts.", "shopify-ec"),
                    tile("Salesforce Commerce Cloud", "partner", "B2C and B2B storefronts with promotions.", "sfcc"),
                    tile("Adobe Commerce", "product", "Magento catalog, pricing and multi-site config.", "adobe-commerce"),
                ]},
                {"box": "OMS & Payments", "ic": "erp", "tiles": [
                    tile("Manhattan Active Omni", "erp", "Order orchestration, promising and returns.", "manhattan"),
                    tile("Stripe Payments", "market", "Payment intents, disputes and payout reconciliation.", "stripe"),
                    tile("Adyen Platform", "partner", "Global acquiring, risk and settlement.", "adyen"),
                ]},
                {"box": "Fulfillment & WMS", "ic": "stream", "tiles": [
                    tile("ShipBob WMS", "stream", "Pick, pack and carrier manifests.", "shipbob"),
                    tile("Flexport Logistics", "globe", "Inbound containers, customs and drayage.", "flexport"),
                    tile("Narvar Post-Purchase", "partner", "Tracking, returns and WISMO experiences.", "narvar"),
                ]},
                {"box": "Marketing & CRM", "ic": "custlake", "tiles": [
                    tile("Klaviyo", "custlake", "Email, SMS and lifecycle segments.", "klaviyo"),
                    tile("Braze", "partner", "Cross-channel campaigns and canvas journeys.", "braze"),
                    tile("Google Analytics 4", "observ", "Session, funnel and attribution events.", "ga4"),
                ]},
                {"box": "Marketplaces", "ic": "market", "tiles": [
                    tile("Amazon Seller Central", "market", "Marketplace orders, fees and advertising.", "amazon-sc"),
                    tile("eBay Managed Payments", "partner", "Third-party marketplace transactions.", "ebay"),
                ]},
                fed_group("Finance Revenue Mart", "Revenue recognition marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("Similarweb Digital", "observ", "Competitive traffic and channel mix benchmarks.", "similarweb"),
                tile("Jungle Scout", "market", "Marketplace share and keyword intelligence.", "jungle-scout"),
                tile("ShipStation Rates", "api", "Carrier rate shopping and delivery promises.", "shipstation"),
            ]),
            "ppl": ppl2([
                biz("CEO & Growth CFO", "Genie One",
                    "The CEO on GMV and contribution margin; the CMO on CAC and LTV, watching conversion rate, AOV and repeat rate by channel.",
                    [["Genie One", "Ask what yesterday's conversion rate was by channel."], ["AI/BI", "Revenue and margin on certified Metric Views."], ["Unity Catalog", "One customer ID across storefront and CRM."]],
                    sub=[
                        ["CEO", "GMV, contribution margin and the growth-versus-profit trade across channels."],
                        ["Growth CFO", "cash, CAC payback and the margin behind every discount and promotion."],
                        ["Chief Marketing Officer", "blended CAC, LTV-to-CAC and return on ad spend across paid and owned."],
                    ],
                    ucs=["Personalization", "Dynamic Pricing", "LTV Segmentation", "Fraud Prevention"]),
                biz("Growth Marketing", "Model Serving",
                    "Paid acquisition, SEO and lifecycle campaigns, judged on blended CAC, LTV-to-CAC and return on ad spend against payback period by channel.",
                    [["Attribution Hub", "Multi-touch credit across paid and owned."], ["Model Serving", "Propensity models in the campaign path."]],
                    sub=[
                        ["Paid Acquisition", "blended CAC, ROAS and payback period by channel and campaign."],
                        ["Lifecycle & CRM", "email, SMS and push journeys judged on repeat rate and retention."],
                        ["SEO & Content", "organic traffic, landing-page conversion and content-driven discovery."],
                    ],
                    ucs=["Personalization", "Cart Abandonment", "LTV Segmentation"]),
                biz("Merchandising", "AI/BI",
                    "Assortment, pricing, bundles and on-site search relevance, tracked on attach rate, gross margin and competitive price gap.",
                    [["Pricing Workbench", "Elasticity and competitive price gaps."], ["AI/BI", "Basket and attach rate on governed orders."]],
                    sub=[
                        ["Category Managers", "assortment, gross margin and attach rate by category."],
                        ["Pricing & Promotions", "elasticity, competitive price gap and promotion lift."],
                        ["Site Search & Discovery", "on-site search relevance and conversion from query to cart."],
                    ],
                    ucs=["Dynamic Pricing", "Search Relevance", "Marketplace Sync"]),
                biz("Operations", "Lakehouse//RT",
                    "Fulfillment SLA, inventory and returns processing, run on on-time delivery, fill rate and cost to serve per order.",
                    [["Fulfillment Command", "Promise vs actual delivery by node."], ["Lakehouse//RT", "Inventory ATP at cart latency."]],
                    sub=[
                        ["Fulfillment Ops", "on-time delivery, fill rate and cost to serve per order."],
                        ["Inventory Planning", "available-to-promise accuracy and safety stock across nodes."],
                        ["Returns & Reverse Logistics", "return rate, processing cost and restock speed."],
                    ],
                    ucs=["Inventory ATP", "Fulfillment Network", "Returns Optimization"]),
                biz("Customer Experience", "Apps",
                    "Support, reviews and loyalty program health, measured on CSAT, NPS and repeat purchase against return rate and contact rate by cohort.",
                    [["CX Console", "CSAT, NPS and repeat purchase by cohort."], ["Apps", "Support tools on governed order history."]],
                    sub=[
                        ["Customer Support", "contact rate, first-contact resolution and CSAT by channel."],
                        ["Loyalty & Retention", "repeat purchase, NPS and program engagement by cohort."],
                        ["Reviews & Community", "review volume, sentiment and their lift on conversion."],
                    ],
                    ucs=["Returns Optimization", "Cart Abandonment", "LTV Segmentation"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land web clickstream, OMS orders, payment captures and WMS shipments; own Bronze to Silver and the pager when the revenue and ATP tables stall.",
                    [["Lakeflow Connect", "Managed connectors for commerce, OMS and payment sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on clickstream and order feeds."], ["Lakewatch", "Freshness on the revenue and conversion tables growth reads at standup."]],
                    sub=[
                        ["Ingestion Engineers", "clickstream, OMS, payment and WMS connectors landing on time."],
                        ["Pipeline Owners", "Bronze-to-Silver reliability and the revenue and ATP table SLAs."],
                        ["Platform On-Call", "freshness and the pager when conversion or inventory tables stall."],
                    ],
                    ucs=["Inventory ATP", "Fraud Prevention", "Marketplace Sync"]),
                biz("Data Scientists", "MLflow",
                    "Recommendation, propensity, dynamic-pricing and checkout-fraud models, and whether they still hold across a peak season and channel mix shift.",
                    [["Feature Store", "Customer and session features read identically in training and serving."], ["MLflow", "Every recommendation and fraud model tracked for audit and reproduction."], ["Model Serving", "Recommendation and fraud models scored in the checkout path."]],
                    sub=[
                        ["Recommendation & Ranking", "recommender and search-ranking models and their conversion lift."],
                        ["Pricing & Propensity", "elasticity, propensity and lifetime-value models across the mix."],
                        ["Fraud & Risk", "checkout-fraud models and how they hold through peak season."],
                    ],
                    ucs=["Personalization", "Dynamic Pricing", "Fraud Prevention", "Search Relevance"]),
                biz("App Developers", "Apps",
                    "Ship the attribution hub, pricing workbench, fulfillment command and CX console apps growth and operations work in, next to governed order data.",
                    [["Apps", "Growth and operations screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for cart-recovery and inventory-hold state."], ["Agent Bricks", "Agents that draft pricing and recovery moves against governed tools."]],
                    sub=[
                        ["App Engineers", "the attribution, pricing, fulfillment and CX consoles growth and ops work in."],
                        ["Backend & State", "cart-recovery and inventory-hold state on serverless Postgres."],
                        ["Agent Builders", "agents that draft pricing and recovery moves against governed tools."],
                    ],
                    ucs=["Cart Abandonment", "Dynamic Pricing", "Fulfillment Network"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Looker", "chart", "Growth and ops dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for daily revenue in growth standups."),
                    tile("Notebooks & IDEs", "notebook", "Analyst notebooks on governed clickstream."),
                ]},
                {"box": "Channels & Partners", "ic": "partner", "tiles": [
                    tile("Marketplace Listings", "api", "Inventory and price sync to Amazon and eBay.", "amazon-sc"),
                    tile("3PL Status Feed", "stream", "Shipment events shared to Narvar and Klaviyo.", "narvar"),
                    tile("Affiliate Networks", "partner", "Commission and attribution to partners.", "braze"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Dynamic Pricing", "market", "Price updates pushed to commerce and marketplaces.", "sfcc"),
                    tile("Cart Recovery", "custlake", "Abandonment sequences triggered from session data.", "klaviyo"),
                    tile("Inventory Holds", "stream", "ATP reservations released or extended in OMS.", "manhattan"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Sales Tax Filing", "gavel", "Jurisdiction filings from governed transaction data."),
                    tile("PCI Scope Reports", "share", "Cardholder data environment attestations."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Customer and order products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Brand partners via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Attribution Hub", "Marketing mix", "chart", "Multi-touch attribution across paid, owned and marketplace channels."),
             app("Pricing Workbench", "Elasticity", "market", "Price gaps and elasticity scenarios before changes go live."),
             app("Fulfillment Command", "Delivery SLA", "gauge", "Promise vs actual ship and delivery by node and carrier."),
             app("CX Console", "Customer health", "custlake", "CSAT, returns and repeat rate by cohort and segment.")],
            [uc("Personalization", "Growth", "custlake", "Product recommendations and content ranked per visitor.",
                problem="Every visitor sees the same merchandising, so relevant products stay buried and conversion leaks, and the signals to rank per shopper sit split across web, CRM and order systems.",
                who="Growth Marketing",
                how="Clickstream and order features are engineered in Feature Store and scored through Model Serving in the storefront path, so recommendations rank per visitor at page latency.",
                comps=["Model Serving", "Feature Store", "MLflow", "AI Functions", "Klaviyo"],
                stories=[
                    ["Flaconi delivers real-time recommendations that lift conversion", "https://www.databricks.com/customers/flaconi"],
                    ["Myntra powers personalized shopping for 70M monthly users", "https://www.databricks.com/customers/myntra"],
                ]),
             uc("Cart Abandonment", "Lifecycle", "apps", "Recovery sequences timed to session behavior.",
                problem="Most carts are abandoned and recovery fires on a fixed timer that ignores intent, so shoppers are nagged or missed and the session context that would time the nudge is already gone.",
                who="Growth Marketing",
                how="Live session and cart state land in Lakebase and Lakehouse//RT, and propensity scores from Model Serving trigger recovery journeys in Klaviyo and Braze at the right moment.",
                comps=["Lakebase", "Lakehouse//RT", "Model Serving", "Klaviyo", "Braze"],
                stories=[
                    ["Pandora scales personalized email recommendations across markets", "https://www.databricks.com/customers/pandora"],
                ]),
             uc("Dynamic Pricing", "Merchandising", "market", "Prices adjusted to elasticity and competitive signals.",
                problem="Prices are set on cost-plus rules and stale competitor checks, so margin leaks on some SKUs and demand is left on the table on others while true elasticity goes unmeasured.",
                who="Merchandising",
                how="Demand, inventory and competitive signals feed elasticity models in Pricing Workbench, scored with Model Serving and pushed to the storefront and marketplaces.",
                comps=["Pricing Workbench", "Model Serving", "AI Functions", "Delta Lake", "Unity Catalog"],
                stories=[
                    ["Seven ways AI reshapes retail pricing and operations", "https://www.databricks.com/blog/top-7-ways-ai-retail-enhances-customer-experience-and-operations"],
                ]),
             uc("Inventory ATP", "Operations", "stream", "Available-to-promise accurate at add-to-cart.",
                problem="Available-to-promise is computed from a nightly snapshot, so the cart shows stock that is already gone and oversells trigger cancellations, split shipments and refunds.",
                who="Operations",
                how="OMS and WMS events stream through Zerobus into Lakehouse//RT, and Fulfillment Command serves an ATP position accurate at add-to-cart across every node.",
                comps=["Fulfillment Command", "Lakehouse//RT", "Zerobus", "Manhattan Active Omni", "Delta Lake"],
                stories=[
                    ["Walgreens right-sizes inventory across 9,000 stores on Databricks", "https://www.databricks.com/customers/walgreens"],
                ]),
             uc("Fraud Prevention", "Payments", "gavel", "Checkout fraud scored before capture.",
                problem="Checkout fraud and chargebacks eat margin, but rules-only screening blocks good customers and misses new patterns, and the score has to land before capture in milliseconds.",
                who="CEO & Growth CFO",
                how="Per-card velocity features are served from Lakebase and scored by Model Serving in the checkout path, with every model tracked in MLflow for audit and dispute defense.",
                comps=["Model Serving", "Feature Store", "MLflow", "Lakebase", "Stripe Payments"],
                stories=[
                    ["Real-time fraud detection with Spark Real-Time Mode and Lakebase", "https://www.databricks.com/blog/how-build-real-time-fraud-detection-using-spark-real-time-mode-and-lakebase"],
                ]),
             uc("Search Relevance", "Discovery", "observ", "Query understanding and ranking tuned to conversion.",
                problem="On-site search misreads intent and synonyms, so shoppers land on empty or irrelevant results and bounce, and merchandisers cannot see which queries quietly lose the sale.",
                who="Merchandising",
                how="Query and catalog embeddings in AI Search rank results with Model Serving, and AI/BI surfaces zero-result and low-conversion queries merchandisers tune against.",
                comps=["AI Search", "Model Serving", "AI Functions", "Feature Store", "AI/BI"]),
             uc("Returns Optimization", "CX", "partner", "Return reasons analyzed to reduce preventable volume.",
                problem="Returns are processed blind to why they happen, so preventable returns from sizing, defects or misleading detail keep recurring and reverse-logistics cost climbs every season.",
                who="Customer Experience",
                how="Return reasons, reviews and order history are conformed on Delta Lake and analysed with AI Functions in the CX Console, feeding fixes back to detail pages and sizing.",
                comps=["CX Console", "AI Functions", "Narvar Post-Purchase", "Delta Lake", "AI/BI"]),
             uc("Marketplace Sync", "Channels", "globe", "Listings, fees and ads optimized across marketplaces.",
                problem="Listings, fees, inventory and ad spend live in each marketplace console, so price and stock drift out of sync, buy-box is lost and true per-channel profit is never clear.",
                who="Merchandising",
                how="Amazon and eBay order, fee and ad feeds land through Lakeflow onto Delta Lake, and AI/BI reconciles price, stock and margin per channel into a single sync view.",
                comps=["Amazon Seller Central", "eBay Managed Payments", "Lakeflow", "Delta Lake", "AI/BI"]),
             uc("LTV Segmentation", "CRM", "custlake", "Cohorts scored for retention and upsell campaigns.",
                problem="Campaigns target broad lists because lifetime value is guessed from last purchase, so budget chases one-time buyers while high-value cohorts get the same generic offer.",
                who="Growth Marketing",
                how="Purchase, engagement and margin features in Feature Store drive LTV and churn models in Model Serving, and Klaviyo activates the scored cohorts for retention and upsell.",
                comps=["Model Serving", "Feature Store", "MLflow", "Klaviyo", "AI/BI"],
                stories=[
                    ["Skechers lifts CTR 324% and cuts acquisition cost with segmentation", "https://www.databricks.com/customers/skechers"],
                ]),
             uc("Fulfillment Network", "Logistics", "stream", "Orders routed to the lowest-cost node meeting SLA.",
                problem="Orders route on static warehouse rules, so shipments travel farther than needed, split across nodes and miss the promise date while carrier and labor cost creep up.",
                who="Operations",
                how="Inventory, carrier-rate and demand signals are scored in Model Serving and served through Fulfillment Command, routing each order to the lowest-cost node that still meets SLA.",
                comps=["Fulfillment Command", "Model Serving", "Manhattan Active Omni", "ShipBob WMS", "Delta Lake"])],
        ),
        "sources": {
            "shopify-ec": {"t": "Shopify Plus", "u": "https://www.shopify.com/plus"},
            "sfcc": {"t": "Salesforce Commerce Cloud", "u": "https://www.salesforce.com/commerce/"},
            "adobe-commerce": {"t": "Adobe Commerce", "u": "https://business.adobe.com/products/magento/magento-commerce.html"},
            "manhattan": {"t": "Manhattan Associates", "u": "https://www.manh.com/"},
            "stripe": {"t": "Stripe", "u": "https://stripe.com/"},
            "adyen": {"t": "Adyen", "u": "https://www.adyen.com/"},
            "shipbob": {"t": "ShipBob", "u": "https://www.shipbob.com/"},
            "flexport": {"t": "Flexport", "u": "https://www.flexport.com/"},
            "narvar": {"t": "Narvar", "u": "https://corp.narvar.com/"},
            "klaviyo": {"t": "Klaviyo", "u": "https://en.wikipedia.org/wiki/Klaviyo"},
            "braze": {"t": "Braze", "u": "https://www.braze.com/"},
            "ga4": {"t": "Google Analytics 4", "u": "https://marketingplatform.google.com/about/analytics/"},
            "amazon-sc": {"t": "Amazon Seller Central", "u": "https://sellercentral.amazon.com/"},
            "ebay": {"t": "eBay", "u": "https://www.ebay.com/"},
            "similarweb": {"t": "Similarweb", "u": "https://www.similarweb.com/"},
            "jungle-scout": {"t": "Jungle Scout", "u": "https://www.junglescout.com/"},
            "shipstation": {"t": "ShipStation", "u": "https://www.shipstation.com/"},
        },
    },
}
