import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_PHARMACY_PBM = {
    "pharmacy_pbm": {
        "label": "Pharmacy & PBM",
        "blurb": "Retail, mail and specialty pharmacies and the pharmacy benefit managers behind them: claims adjudication, formulary and rebate management, prior authorization, 340B, dispensing and adherence.",
        "medallion": medallion(
            "Raw claims and Rx feeds",
            "NCPDP claim transactions and reversals, dispensing and e-prescribing records, manufacturer rebate contracts, 340B accumulations and wholesaler invoices, landed exactly as received so a claim or a rebate can always be replayed as it stood.",
            "Conformed claim, member, drug",
            "Claims, members, prescribers and drugs resolved into single conformed entities across the adjudication, dispensing and rebate estates, with NDC, GPI and NPI reconciled and every fill stitched to member, plan and drug.",
            "Net cost, adherence, rebate",
            "Contracted products the clinical and finance teams run on: net cost and rebate accrual per claim, medication adherence by drug and cohort, generic dispensing rate, and pharmacy network and specialty performance.",
        ),
        "rails": {
            "src": [
                {
                    "box": "Pharmacy Systems",
                    "ic": "erp",
                    "tiles": [
                        tile("McKesson EnterpriseRx", "erp", "Enterprise pharmacy management for chains: the system of record for prescriptions, dispensing workflow, patient profiles and third-party billing.", "enterpriserx",
                             cat="Pharmacy Management System",
                             what="System of record for chain pharmacies: prescriptions, dispensing workflow, patient profiles and third-party billing, emitting fill, patient and billing records.",
                             users="Pharmacy Ops, retail pharmacy operations and inventory teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "10-50 GB/day", "Nightly batch + intraday deltas"),
                                 stream=flow(["semi-structured"], "hundreds of fills/sec at peak", "Continuous (dispensing events)"))),
                        tile("PioneerRx", "erp", "Independent and specialty pharmacy management: e-prescribing, workflow, inventory and point-of-sale for the dispensing pharmacy.", "pioneerrx",
                             cat="Pharmacy Management System",
                             what="Manages independent and specialty pharmacy e-prescribing, workflow, inventory and point-of-sale, feeding fill, inventory and patient data.",
                             users="Pharmacy Ops, mail & specialty and inventory teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day", "Nightly batch"),
                                 stream=flow(["semi-structured"], "tens of fills/sec", "Continuous (dispensing events)"))),
                        tile("Epic Willow", "product", "Health-system pharmacy: inpatient and outpatient dispensing, order verification and medication management inside the EHR.", "willow",
                             cat="Health-System Pharmacy System",
                             what="Runs health-system inpatient and outpatient dispensing, order verification and medication management inside the EHR, emitting dispensing and medication records.",
                             users="Pharmacy Ops, health-system pharmacy and inventory teams.",
                             data_out=data_out(
                                 batch=flow(["structured", "unstructured"], "5-20 GB/day incl. med records", "Nightly batch"))),
                        tile("FrameworkLTC", "erp", "Long-term-care pharmacy management: batch and cycle fills, facility billing and eMAR integration for LTC pharmacies.", "frameworkltc",
                             cat="Long-Term-Care Pharmacy System",
                             what="Manages long-term-care batch and cycle fills, facility billing and eMAR integration, emitting cycle-fill, facility and billing records.",
                             users="Pharmacy Ops, LTC pharmacy operations and facility-billing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Cycle-fill batches"))),
                    ],
                },
                {
                    "box": "Claims & Adjudication",
                    "ic": "market",
                    "tiles": [
                        tile("SS&C RxClaim", "market", "PBM claims adjudication: real-time NCPDP claim processing, benefit and formulary application and pharmacy payment.", "rxclaim",
                             cat="PBM Claims Adjudication Engine",
                             what="Adjudicates PBM claims in real time: NCPDP claim processing, benefit and formulary application and pharmacy payment, emitting adjudicated claim lines.",
                             users="PBM Leadership, Network Pricing and Clinical & UM teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "20-80 GB/day", "Daily claims cycle + intraday deltas"),
                                 stream=flow(["semi-structured"], "2-10k claims/sec at peak", "Continuous (real-time adjudication)"))),
                        tile("Gainwell Rx", "market", "State Medicaid pharmacy benefit administration and point-of-sale claim processing for fee-for-service and single-PBM programs.", "argus",
                             cat="Medicaid Pharmacy Benefit System",
                             what="Administers state Medicaid pharmacy benefits and point-of-sale claim processing for fee-for-service and single-PBM programs, emitting POS claim records.",
                             users="PBM Leadership, Trust & Comply and regulatory-affairs teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Daily claims cycle"),
                                 stream=flow(["semi-structured"], "hundreds of claims/sec at peak", "Continuous (POS)"))),
                        tile("NCPDP Claims", "stream", "Real-time NCPDP Telecommunication D.0 claim and reversal transactions from the pharmacy point of sale, the ground truth for every fill.", "ncpdp",
                             cat="Pharmacy Claim Transaction Standard",
                             what="Carries real-time NCPDP Telecommunication D.0 claim and reversal transactions from the pharmacy point of sale, the ground truth for every fill.",
                             users="Claims Data Eng, PBM Leadership and Trust & Comply teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "2-10k transactions/sec at peak", "Continuous (point-of-sale)"))),
                        tile("Surescripts Rx", "api", "E-prescribing, medication history and eligibility across the Surescripts network into the pharmacy and PBM estate.", "surescripts",
                             cat="E-Prescribing Network",
                             what="Carries e-prescribing, medication history and eligibility across the Surescripts network into the pharmacy and PBM estate.",
                             users="Clinical & UM, Pharmacy Ops and Claims Data Eng teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds of messages/sec at peak", "Continuous (network)"))),
                    ],
                },
                {
                    "box": "Formulary & Pricing",
                    "ic": "sheet",
                    "tiles": [
                        tile("First Databank FDB", "db", "Drug knowledge and pricing: AWP, drug identifiers and clinical screening, the reference claims are adjudicated against.", "fdb",
                             cat="Drug Knowledge & Pricing Database",
                             what="Supplies drug knowledge and pricing, AWP, drug identifiers and clinical screening, the reference claims are adjudicated against.",
                             users="Network Pricing, Clinical & UM and pricing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "GBs (drug reference + pricing)", "Weekly / on release"))),
                        tile("Medi-Span", "db", "Wolters Kluwer drug pricing and clinical data used for AWP, MAC and drug-interaction screening.", "medispan",
                             cat="Drug Knowledge & Pricing Database",
                             what="Provides drug pricing and clinical data used for AWP, MAC and drug-interaction screening across the estate.",
                             users="Network Pricing, pricing & MAC and Clinical & UM teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "GBs (drug reference + pricing)", "Weekly / on release"))),
                        tile("Model N Rebates", "market", "Revenue and rebate management: manufacturer rebate contracts, formulary rebate accrual and payment reconciliation.", "modeln",
                             cat="Rebate & Revenue Management System",
                             what="Manages manufacturer rebate contracts, formulary rebate accrual and payment reconciliation, emitting contract, accrual and payment records.",
                             users="PBM Leadership, chief trade officer and finance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day contracts + accruals", "Daily + rebate cycle"))),
                        tile("MMIT Formulary", "sheet", "Formulary status, coverage and restriction data across plans and payers for formulary and market-access analytics.", "mmit",
                             cat="Formulary & Market-Access Data",
                             what="Supplies formulary status, coverage and restriction data across plans and payers for formulary and market-access analytics.",
                             users="Clinical & UM, P&T committee and market-access teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB refresh", "Periodic formulary refresh"))),
                    ],
                },
                {
                    "box": "Specialty, PA & 340B",
                    "ic": "partner",
                    "tiles": [
                        tile("CoverMyMeds", "partner", "Electronic prior authorization and patient access: PA requests, determinations and specialty enrollment across payers.", "covermymeds",
                             cat="Electronic Prior Authorization Platform",
                             what="Runs electronic prior authorization and patient access: PA requests, determinations and specialty enrollment across payers.",
                             users="Clinical & UM, utilization management and Pharmacy Ops teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured", "unstructured"], "tens of PA requests/sec at peak", "Continuous (portal / API)"))),
                        tile("CareMetx Hub", "partner", "Specialty hub services: benefit verification, enrollment, copay and adherence for specialty and limited-distribution drugs.", "caremetx",
                             cat="Specialty Pharmacy Hub",
                             what="Provides specialty hub services: benefit verification, enrollment, copay and adherence for specialty and limited-distribution drugs.",
                             users="Pharmacy Ops, mail & specialty and clinical-pharmacy teams.",
                             data_out=data_out(
                                 batch=flow(["structured", "unstructured"], "1-4 GB/day enrollment + status", "Daily feed"))),
                        tile("Trisus 340B", "gavel", "Craneware 340B split-billing and compliance: eligibility, accumulation and replenishment for covered entities.", "trisus",
                             cat="340B Compliance Platform",
                             what="Runs 340B split-billing and compliance: eligibility, accumulation and replenishment for covered entities, emitting accumulation and eligibility records.",
                             users="Pharmacy Ops, 340B compliance and audit teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day accumulations", "Daily split-billing cycle"))),
                        tile("Macro Helix 340B", "gavel", "340B Architect split-billing and program management where Macro Helix is the covered entity's compliance platform.", "macrohelix",
                             cat="340B Compliance Platform",
                             what="Runs 340B Architect split-billing and program management where Macro Helix is the covered entity's compliance platform.",
                             users="Pharmacy Ops, 340B compliance and audit teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day accumulations", "Daily split-billing cycle"))),
                    ],
                },
                {
                    "box": "Wholesale & Dispensing",
                    "ic": "compute",
                    "tiles": [
                        tile("Cencora Supply", "storage", "Pharmaceutical wholesale: drug orders, invoices, chargebacks and DSCSA serialization from the primary distributor.", "cencora",
                             cat="Pharmaceutical Wholesale Distributor",
                             what="Supplies pharmaceutical wholesale feeds: drug orders, invoices, chargebacks and DSCSA serialization from the primary distributor.",
                             users="Pharmacy Ops, inventory and 340B compliance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day orders + invoices", "Daily EDI cycle"))),
                        tile("McKesson Supply", "storage", "Wholesale distribution feeds: purchase orders, acquisition cost and 340B replenishment from the distributor.", "mckesson",
                             cat="Pharmaceutical Wholesale Distributor",
                             what="Provides wholesale distribution feeds: purchase orders, acquisition cost and 340B replenishment from the distributor.",
                             users="Pharmacy Ops, inventory and 340B compliance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day orders + invoices", "Daily EDI cycle"))),
                        tile("ScriptPro Robotics", "iot", "Central-fill and in-pharmacy dispensing automation: robotic fill counts, vial data and dispensing throughput.", "scriptpro",
                             cat="Pharmacy Dispensing Automation",
                             what="Runs central-fill and in-pharmacy dispensing automation, emitting robotic fill counts, vial data and dispensing throughput.",
                             users="Pharmacy Ops, dispensing operations and inventory teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds of fill events/sec at peak", "Continuous (dispensing telemetry)"))),
                        tile("Parata Systems", "iot", "High-volume dispensing and pouch-packaging automation feeding fill, inventory and adherence-packaging data.", "parata",
                             cat="Pharmacy Dispensing Automation",
                             what="Runs high-volume dispensing and pouch-packaging automation, feeding fill, inventory and adherence-packaging data.",
                             users="Pharmacy Ops, mail & specialty and inventory teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds of fill events/sec at peak", "Continuous (dispensing telemetry)"))),
                    ],
                },
                fed_group("Rebate & Claims Marts", "Historical adjudicated-claims, rebate accrual and DIR marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers.",
                          cat="Claims & Rebate Data Warehouse",
                          what="Historical adjudicated-claims, rebate accrual and DIR marts kept where they are and queried in place through federation instead of being copied.",
                          users="PBM Leadership, finance and Network Pricing teams.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("Surescripts Network", "api", "E-prescribing, eligibility and medication-history transactions across the Surescripts network, landed as structured events.", "surescripts",
                     cat="E-Prescribing Network",
                     what="Carries e-prescribing, eligibility and medication-history transactions across the Surescripts network, landed as structured events.",
                     users="Claims Data Eng, Clinical & UM and Pharmacy Ops teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "hundreds of messages/sec at peak", "Continuous (network)"))),
                tile("X12 & NCPDP Feeds", "stream", "834 enrollment, 270/271 eligibility and NCPDP claim events parsed on arrival and landed as structured records.", "ncpdp",
                     cat="EDI Enrollment & Claims Feed",
                     what="Parses 834 enrollment, 270/271 eligibility and NCPDP claim events on arrival and lands them as structured records.",
                     users="Claims Data Eng, eligibility and enrollment teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "hundreds of transactions/sec at peak", "Continuous EDI feed"))),
                tile("Wholesaler EDI", "stream", "852, 856 and 810 order, shipment and invoice EDI from distributors reconciled against dispensing and 340B.",
                     cat="Supply Chain EDI Feed",
                     what="Carries 852, 856 and 810 order, shipment and invoice EDI from distributors, reconciled against dispensing and 340B accumulation.",
                     users="Claims Data Eng, inventory and 340B compliance teams.",
                     data_out=data_out(
                         batch=flow(["semi-structured"], "1-5 GB/day EDI", "Daily EDI cycle"))),
            ]),
            "ppl": ppl2([
                biz("PBM Leadership", "Genie One",
                    "The CEO on book-of-business growth and client retention; the CFO on rebate economics and net cost trend; the chief trade officer on manufacturer rebate contracts and formulary value.",
                    [["Genie One", "Ask what a client's net cost per claim was last month, or where rebate leaked, without a analyst pull."],
                     ["AI/BI", "Net cost, rebate accrual and generic dispensing rate on one certified set of Metric Views."],
                     ["Unity Catalog", "Certification and the glossary so \"net cost\" and \"rebate\" mean one thing across the PBM."]],
                    sub=[["CEO", "book-of-business growth and client retention."],
                         ["CFO", "rebate economics and net cost trend across the book."],
                         ["Chief trade officer", "manufacturer rebate contracts and formulary value."]],
                    ucs=["Rebate Optimization", "Formulary Management", "Network Performance", "MAC & Drug Pricing"]),
                biz("Clinical & UM", "Model Serving",
                    "The P&T committee on formulary decisions, clinical pharmacists on medication therapy and adherence, and utilization management on prior-authorization policy and step therapy.",
                    [["Model Serving", "Adherence and prior-auth models scored inside the clinical and PA path."],
                     ["AI Functions", "Prior-auth documents and clinical notes classified at scale from unstructured text."],
                     ["AI/BI", "Adherence, PA turnaround and formulary compliance on governed, certified views."]],
                    sub=[["P&T committee", "formulary decisions and therapeutic class review."],
                         ["Clinical pharmacy", "medication therapy management and adherence."],
                         ["Utilization mgmt", "prior-authorization policy and step therapy."]],
                    ucs=["Prior Auth Automation", "Medication Adherence", "Formulary Management"]),
                biz("Network Pricing", "AI/BI",
                    "Network contracting on pharmacy reimbursement, the pricing team on MAC lists and AWP, and underwriting on client pricing guarantees and effective rate.",
                    [["AI/BI", "MAC competitiveness, network spread and guarantee attainment on certified views."],
                     ["Model Serving", "MAC and reimbursement models scored against acquisition cost and claim volume."],
                     ["Genie One", "Ask which drugs are underwater on the current MAC list this week."]],
                    sub=[["Network contracting", "pharmacy reimbursement and network design."],
                         ["Pricing & MAC", "MAC list maintenance and AWP benchmarking."],
                         ["Underwriting", "client pricing guarantees and effective rate."]],
                    ucs=["MAC & Drug Pricing", "Network Performance", "Rebate Optimization"]),
                biz("Pharmacy Ops", "Lakehouse//RT",
                    "Retail pharmacy operations on dispensing workflow and throughput, mail and specialty on fulfillment and patient support, and inventory on stock, replenishment and 340B accumulation.",
                    [["Dispensing Cockpit", "Fill volume, wait time and out-of-stock risk flagged before a patient is turned away."],
                     ["Lakehouse//RT", "Live dispensing and inventory state at the latency a pharmacy moves at."],
                     ["Model Serving", "Demand and replenishment models scored against fill and wholesaler data."]],
                    sub=[["Retail pharmacy ops", "dispensing workflow and throughput."],
                         ["Mail & specialty", "fulfillment and specialty patient support."],
                         ["Inventory", "stock, replenishment and 340B accumulation."]],
                    ucs=["Specialty Pharmacy", "Dispensing & Inventory", "340B Compliance"]),
                biz("Trust & Comply", "Unity Catalog",
                    "Program integrity on fraud, waste and abuse, regulatory affairs on Medicare Part D and CMS reporting, and audit on pharmacy audit exposure and DIR reconciliation.",
                    [["Model Serving", "Fraud, waste and abuse models scored across claims, prescriber and pharmacy behaviour."],
                     ["Unity Catalog", "Fine-grained governance and lineage over PHI supporting HIPAA and CMS audit."],
                     ["AI/BI", "FWA exposure, Part D metrics and DIR reconciliation on governed, certified views."]],
                    sub=[["Program integrity", "fraud, waste and abuse investigation."],
                         ["Regulatory affairs", "Medicare Part D and CMS reporting."],
                         ["Audit", "pharmacy audit exposure and DIR reconciliation."]],
                    ucs=["Fraud, Waste & Abuse", "340B Compliance", "Medication Adherence"]),
            ], [
                biz("Claims Data Eng", "Lakeflow",
                    "Land NCPDP claims and reversals, eligibility and enrollment, Surescripts and wholesaler EDI; own the Bronze to Silver path and the pager when the claims tables stall.",
                    [["Lakeflow Connect", "Managed connectors for RxClaim, dispensing, rebate and eligibility sources."],
                     ["Auto Loader", "NCPDP claim and EDI files landed incrementally into Bronze."],
                     ["Lakewatch", "Freshness on the claims and rebate tables finance reads every morning."]]),
                biz("Pharmacy DS", "MLflow",
                    "Adherence, fraud-waste-abuse, prior-auth prediction and demand models, and whether they still hold six months after deployment as formularies and networks change.",
                    [["Feature Store", "Member, drug and claim features read identically in training and serving."],
                     ["MLflow", "Every adherence and FWA model tracked for audit and reproduction."],
                     ["Model Serving", "Adherence and anomaly models scored in the clinical and claims path."]]),
                biz("Health App Dev", "Apps",
                    "Ship the prior-auth, rebate, adherence and dispensing applications the pharmacy and PBM work in, hosted next to governed PHI.",
                    [["Apps", "Operational screens with no separate web tier to run or secure."],
                     ["Lakebase", "Serverless Postgres for PA and dispensing state with governed writes."],
                     ["Agent Bricks", "Agents that draft a prior-auth decision against governed tools."]]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Executive and clinical dashboards against serverless SQL with Unity Catalog permissions enforced end to end."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for net-cost and adherence answers in the channel clinical and finance already work in."),
                    tile("Notebooks & IDEs", "notebook", "Notebooks and IDEs against governed claims, drug and member data."),
                ]},
                {"box": "Payers & Partners", "ic": "partner", "tiles": [
                    tile("Plan Sponsor Portal", "globe", "Net cost, utilization and guarantee attainment shared to plan sponsors and consultants over governed access."),
                    tile("Manufacturer Share", "share", "Rebate-eligible utilization and market data shared to manufacturers over Delta Sharing without a copy."),
                    tile("Provider Exchange", "api", "Medication history and adherence signal exchanged with prescribers and health systems over HL7 FHIR."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Adjudication Writeback", "market", "MAC updates and coverage decisions written back into the adjudication engine so the answer reaches the claim path.", "rxclaim"),
                    tile("PA Determinations", "gavel", "Prior-authorization determinations written back into the PA workflow prescribers and pharmacies work in.", "covermymeds"),
                    tile("Dispensing Queue", "apps", "Adherence outreach and replenishment tasks pushed to the dispensing and mail-order queue."),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("CMS Part D Reporting", "gavel", "Medicare Part D, PDE and star-ratings reporting produced from the same governed tables the PBM runs on."),
                    tile("DIR & Rebate Filing", "share", "Direct and indirect remuneration and rebate reconciliation filed from contracted Gold products."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Published, contracted claims and rebate products discoverable in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Plan sponsors, manufacturers and covered entities reading live tables with no copy and no egress duplication."),
                ]},
            ], genie_spaces=[
                genie("Rebate & Net Cost", "Ask about net cost per claim, rebate accrual and where rebate is leaking in plain language.",
                      feeds=["Model N Rebates", "SS&C RxClaim", "Net cost, adherence, rebate", "Rebate & Claims Marts"],
                      teams=["PBM Leadership", "Chief trade officer", "CFO"],
                      questions=[
                          "What was net cost per claim by client last month?",
                          "Where is rebate leaking against the manufacturer contracts?",
                          "How is generic dispensing rate trending by client?",
                          "Which drugs contribute most to net cost trend this quarter?",
                          "What is rebate accrual versus payment reconciliation by contract?"]),
                genie("Clinical & Adherence", "Explore adherence, prior-auth turnaround and formulary compliance across the book.",
                      feeds=["NCPDP Claims", "MMIT Formulary", "CoverMyMeds", "Net cost, adherence, rebate"],
                      teams=["Clinical & UM", "P&T committee", "Clinical pharmacy"],
                      questions=[
                          "Which members are at highest risk of non-adherence right now?",
                          "What is proportion-of-days-covered by therapeutic class?",
                          "Where is prior-auth turnaround exceeding target?",
                          "How does formulary compliance vary by plan and drug?",
                          "Which step-therapy policies drive the most appeals?"]),
                genie("Network & Pricing", "Answer MAC competitiveness, network spread and guarantee-attainment questions.",
                      feeds=["SS&C RxClaim", "First Databank FDB", "Medi-Span", "Conformed claim, member, drug"],
                      teams=["Network Pricing", "Pricing & MAC", "Network contracting"],
                      questions=[
                          "Which drugs are underwater on the current MAC list this week?",
                          "What is network spread by pharmacy and drug class?",
                          "Where are client guarantees at risk of not being attained?",
                          "How does effective rate compare to the contracted guarantee?",
                          "Which pharmacies drive the most reimbursement variance?"]),
                genie("Integrity & Compliance", "Ask about fraud, waste and abuse, 340B compliance and DIR reconciliation.",
                      feeds=["NCPDP Claims", "Trisus 340B", "Gainwell Rx", "Conformed claim, member, drug"],
                      teams=["Trust & Comply", "Program integrity", "Audit"],
                      questions=[
                          "Which prescribers show aberrant billing patterns this quarter?",
                          "Where are duplicate 340B discounts at risk across entities?",
                          "What is our FWA exposure by claim category?",
                          "How does DIR reconciliation compare to accrual?",
                          "Which pharmacies show the highest audit exposure?"]),
            ], dashboards=[
                dashboard("Rebate & Net Cost", "Net cost per claim, rebate accrual and generic dispensing rate on certified Metric Views.",
                          kpis=["Net cost per claim", "Rebate accrual", "Generic dispensing rate", "Rebate leakage", "Net cost trend"],
                          teams=["PBM Leadership", "Chief trade officer", "CFO"]),
                dashboard("Adherence & Clinical", "Adherence, prior-auth turnaround and formulary compliance across the book.",
                          kpis=["Proportion of days covered", "Adherence rate", "PA turnaround", "Formulary compliance", "Step-therapy adherence"],
                          teams=["Clinical & UM", "Clinical pharmacy", "Utilization mgmt"]),
                dashboard("Network & Pricing", "MAC competitiveness, network spread, guarantee attainment and effective rate.",
                          kpis=["MAC competitiveness", "Network spread", "Guarantee attainment", "Effective rate", "Underwater drug rate"],
                          teams=["Network Pricing", "Pricing & MAC", "Underwriting"]),
                dashboard("Integrity & Compliance", "FWA exposure, recoveries, 340B compliance and DIR reconciliation.",
                          kpis=["FWA exposure", "Recovery", "340B compliance rate", "DIR reconciliation", "Part D metrics"],
                          teams=["Trust & Comply", "Program integrity", "Audit"]),
            ]),
        },
        "top": top_band(
            [
                app("Rebate Cockpit", "Rebate & net cost", "market",
                    "Where the trade and finance teams see rebate accrual, formulary value and net cost per claim by client and drug, on Databricks Apps over Lakebase."),
                app("PA Assistant", "Prior authorization", "agents",
                    "Prior-authorization requests triaged and drafted against formulary and clinical policy, assembling evidence from claims and prescriber notes with Agent Bricks."),
                app("Adherence Monitor", "Medication adherence", "gauge",
                    "Members scored on refill and adherence risk so outreach reaches non-adherent patients before a gap becomes a gap in care."),
                app("FWA Investigator", "Program integrity", "zshield",
                    "Claims, prescriber and pharmacy behaviour scored for fraud, waste and abuse so special investigations work the highest-value cases first."),
            ],
            [
                uc("Rebate Optimization", "Revenue", "market",
                    "Manufacturer rebate accrual and formulary value reconciled per claim so net cost is understood before the invoice, not after.",
                    problem="Rebate contracts, formulary tiers and adjudicated claims sit in separate systems, so rebate leakage and net cost per client are reconstructed by hand quarters after the money moved.",
                    who="PBM Leadership",
                    how="Model N rebate contracts and RxClaim adjudication are conformed in the lakehouse; accrual and net cost are scored per claim in Model Serving and read in the Rebate Cockpit on certified Metric Views.",
                    comps=["Rebate Cockpit", "Model N Rebates", "SS&C RxClaim", "AI/BI", "Model Serving", "Rebate & Claims Marts"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Prior Auth Automation", "Clinical", "gavel",
                    "Prior-authorization requests triaged, evidence assembled and routine approvals drafted so patients wait hours, not days.",
                    problem="Prior authorization is a manual, fax-and-portal process; requests queue for days while clinicians reassemble the same claims, prescriber and formulary evidence by hand.",
                    who="Clinical & UM",
                    how="CoverMyMeds PA requests and Surescripts data land in the lakehouse; text models classify and draft determinations in Model Serving and Agent Bricks, with the PA Assistant writing decisions back.",
                    comps=["PA Assistant", "CoverMyMeds", "Surescripts Rx", "Agent Bricks", "AI Functions", "Model Serving"],
                    stories=[["Orizon automates claims and denials with data and AI", "https://www.databricks.com/customers/orizon/mosaic-ai"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Medication Adherence", "Clinical", "gauge",
                    "Members scored on refill and adherence risk so outreach reaches non-adherent patients before the gap widens.",
                    problem="Non-adherence drives avoidable cost and worse outcomes, but the refill and claims signal that predicts it is scattered and reviewed too late to intervene.",
                    who="Clinical & UM",
                    how="Fill and claims history feed proportion-of-days-covered and risk models in Model Serving; the Adherence Monitor targets outreach to the members most likely to lapse.",
                    comps=["Adherence Monitor", "NCPDP Claims", "Model Serving", "AI/BI", "Feature Store"],
                    stories=[["CVS Health improves medication adherence with Databricks", "https://www.databricks.com/customers/cvs-health"]]),
                uc("Formulary Management", "Clinical", "sheet",
                    "Formulary tiers and coverage decisions evaluated on utilization, rebate value and clinical evidence together.",
                    problem="Formulary decisions weigh clinical evidence, rebate value and utilization that live in different systems, so a tier change's true net-cost effect is hard to see before it ships.",
                    who="Clinical & UM",
                    how="MMIT formulary status and FDB drug data are conformed with utilization and rebate on the lakehouse; scenarios are explored in AI/BI and Genie on the definitions the P&T committee reads.",
                    comps=["MMIT Formulary", "First Databank FDB", "AI/BI", "Unity Catalog", "Genie One"],
                    stories=[["IQVIA and Databricks enable healthcare data collaboration", "https://www.databricks.com/blog/future-healthcare-relies-data-collaboration-how-iqvia-and-databricks-lakehouse-enable-better"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("MAC & Drug Pricing", "Pricing", "chart",
                    "MAC lists and reimbursement tuned against acquisition cost and AWP so drugs are neither underwater nor overpaid.",
                    problem="MAC lists drift against acquisition cost and AWP, leaving drugs underwater for pharmacies or overpaid for clients, and every list refresh is a slow manual reconciliation.",
                    who="Network Pricing",
                    how="FDB and Medi-Span pricing and RxClaim adjudication are conformed to Gold; MAC and reimbursement models score competitiveness in Model Serving and write updates back to the adjudication engine.",
                    comps=["First Databank FDB", "Medi-Span", "SS&C RxClaim", "Model Serving", "AI/BI", "Lakeflow"],
                    stories=[["Abacus Insights unifies healthcare data on Databricks", "https://www.databricks.com/customers/abacus-insights"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Network Performance", "Network", "network",
                    "Pharmacy network spread, guarantee attainment and effective rate read on one certified set of definitions.",
                    problem="Network spread and client guarantee attainment are computed in spreadsheets from claims exports, so effective rate is known too late to renegotiate or correct.",
                    who="Network Pricing",
                    how="Adjudicated claims and contract terms are conformed to certified Metric Views; network spread and guarantee attainment are read in AI/BI and Genie and shared to plan sponsors.",
                    comps=["SS&C RxClaim", "AI/BI", "Genie One", "Unity Catalog", "Plan Sponsor Portal"],
                    stories=[["Walgreens builds an intelligent pharmacy data platform", "https://www.databricks.com/customers/walgreens"],
                             ["Abacus Insights unifies healthcare data on Databricks", "https://www.databricks.com/customers/abacus-insights"]]),
                uc("Specialty Pharmacy", "Specialty", "partner",
                    "Specialty patient journeys from hub enrollment through fill and adherence assembled into one view for support and outcomes.",
                    problem="Specialty patients move across hub, benefit verification, specialty pharmacy and clinical support systems that never meet, so enrollment stalls and adherence risk is invisible.",
                    who="Pharmacy Ops",
                    how="CareMetx hub, dispensing and clinical feeds are conformed on the lakehouse; adherence and abandonment models score each patient in Model Serving for proactive specialty support.",
                    comps=["CareMetx Hub", "PioneerRx", "Model Serving", "Lakehouse//RT", "AI/BI"],
                    stories=[["Walgreens delivers personalized care at the point of care", "https://www.databricks.com/customers/walgreens"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Dispensing & Inventory", "Operations", "iot",
                    "Demand forecasting and replenishment across the pharmacy network so the right drug is on the shelf without dead stock.",
                    problem="Out-of-stocks turn patients away while overstock ties up cash and risks expiry, and forecasts made per store miss the demand that moves across the network.",
                    who="Pharmacy Ops",
                    how="Dispensing, wholesaler and fill-automation feeds stream into Lakehouse//RT; demand and replenishment models in Model Serving right-size inventory and drive the dispensing queue.",
                    comps=["ScriptPro Robotics", "Parata Systems", "Cencora Supply", "Lakehouse//RT", "Model Serving", "Dispensing Queue"],
                    stories=[["Walgreens optimizes pharmacy supply chain with Databricks", "https://www.databricks.com/customers/walgreens"]]),
                uc("340B Compliance", "Compliance", "gavel",
                    "340B eligibility, accumulation and split-billing reconciled continuously so every discounted claim holds up under audit.",
                    problem="340B eligibility, accumulation and duplicate-discount prevention span dispensing, TPA and claims feeds, so compliance is a reactive audit scramble rather than continuous monitoring.",
                    who="Pharmacy Ops",
                    how="Trisus and Macro Helix split-billing, dispensing and wholesaler data are conformed under Unity Catalog; eligibility and duplicate-discount checks run continuously with lineage for audit.",
                    comps=["Trisus 340B", "Macro Helix 340B", "McKesson Supply", "Unity Catalog", "AI/BI"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Fraud, Waste & Abuse", "Integrity", "zshield",
                    "Claims, prescriber and pharmacy behaviour scored for fraud, waste and abuse so investigations chase the highest-value cases.",
                    problem="Rules engines catch known schemes but miss evolving behaviour like prescriber collusion and phantom billing, and manual review queues overwhelm special investigations with false positives.",
                    who="Trust & Comply",
                    how="Adjudicated claims, prescriber and pharmacy data are conformed on the lakehouse; anomaly and peer-comparison models score behaviour in Model Serving and route explainable cases to the FWA Investigator.",
                    comps=["FWA Investigator", "NCPDP Claims", "Model Serving", "AI Functions", "AI/BI", "MLflow"],
                    stories=[["Orizon reduces waste and protects patients with AI", "https://www.databricks.com/customers/orizon/mosaic-ai"],
                             ["Real-time fraud prevention on Databricks", "https://www.databricks.com/blog/bringing-real-time-fraud-prevention-government-benefits"]]),
            ],
        ),
        "sources": {
            "enterpriserx": {"t": "McKesson Pharmacy Systems", "u": "https://www.mckesson.com/pharmacy-management/"},
            "pioneerrx": {"t": "PioneerRx pharmacy software", "u": "https://www.pioneerrx.com/"},
            "willow": {"t": "Epic (Willow pharmacy)", "u": "https://www.epic.com/software/"},
            "frameworkltc": {"t": "SoftWriters FrameworkLTC", "u": "https://www.softwriters.com/"},
            "rxclaim": {"t": "SS&C Health (RxClaim)", "u": "https://www.ssctech.com/"},
            "argus": {"t": "Gainwell Rx Medicaid pharmacy", "u": "https://www.gainwelltechnologies.com/solutions/pharmacy-solutions/"},
            "ncpdp": {"t": "NCPDP standards", "u": "https://www.ncpdp.org/"},
            "surescripts": {"t": "Surescripts network", "u": "https://surescripts.com/"},
            "fdb": {"t": "First Databank (FDB)", "u": "https://www.fdbhealth.com/"},
            "medispan": {"t": "Wolters Kluwer Medi-Span", "u": "https://www.wolterskluwer.com/en/solutions/medi-span"},
            "modeln": {"t": "Model N revenue management", "u": "https://www.modeln.com/"},
            "mmit": {"t": "MMIT formulary data", "u": "https://www.mmitnetwork.com/"},
            "covermymeds": {"t": "CoverMyMeds prior authorization", "u": "https://www.covermymeds.com/"},
            "caremetx": {"t": "CareMetx specialty hub", "u": "https://www.caremetx.com/"},
            "trisus": {"t": "Craneware Trisus 340B", "u": "https://www.craneware.com/"},
            "macrohelix": {"t": "Macro Helix 340B Architect", "u": "https://www.macrohelix.com/"},
            "cencora": {"t": "Cencora pharmaceutical distribution", "u": "https://www.cencora.com/"},
            "mckesson": {"t": "McKesson distribution", "u": "https://www.mckesson.com/"},
            "scriptpro": {"t": "ScriptPro pharmacy automation", "u": "https://www.scriptpro.com/"},
            "parata": {"t": "Parata dispensing systems", "u": "https://www.parata.com/"},
        },
    }
}
