import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_WHOLESALE_DISTRIBUTION = {
    "wholesale_distribution": {
        "label": "Wholesale & Distribution",
        "blurb": "B2B wholesale and distribution: demand and inventory planning, warehouse and transport execution, EDI trading, dynamic pricing, rebates, and multi-channel commerce across branch networks.",
        "medallion": medallion(
            "Raw ERP, WMS, EDI feeds",
            "Orders, shipments and invoices from the ERP, WMS pick and putaway events, TMS movements and inbound EDI transactions, landed exactly as received so a short-ship or a price can always be replayed as it stood.",
            "Conformed customer, SKU, order",
            "Customers, SKUs, suppliers and orders resolved into single conformed entities across the ERP, WMS, CRM and commerce estates, with ship-to and bill-to hierarchies reconciled and EDI trading partners matched.",
            "Fill-rate, margin, forecast",
            "Contracted products the commercial and operations teams run on: fill rate and OTIF by customer and branch, gross-to-net margin after rebates, inventory turns, and SKU-location demand forecasts.",
        ),
        "rails": {
            "src": [
                {
                    "box": "ERP & Finance",
                    "ic": "erp",
                    "tiles": [
                        tile("SAP S/4HANA", "erp", "Orders, inventory, procurement and finance for large distributors; the system of record for the order-to-cash and procure-to-pay flow.", "sap",
                             cat="Enterprise Resource Planning (ERP)",
                             what="Holds the system-of-record for order-to-cash and procure-to-pay across large distributors, the source of orders, inventory, purchasing and finance.",
                             users="Finance & Rebates, Supply Chain & Ops and Sales & Commercial teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "20-100 GB/day", "Nightly batch + hourly deltas"),
                                 stream=flow(["semi-structured"], "hundreds of postings/sec", "Continuous CDC"))),
                        tile("Infor Distribution", "erp", "CloudSuite Distribution ERP purpose-built for wholesale distributors: inventory, pricing and warehouse operations.", "infor",
                             cat="Distribution ERP",
                             what="Purpose-built distribution ERP covering inventory, pricing and warehouse operations for wholesale distributors.",
                             users="Supply Chain & Ops, Category & Merch and Finance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "10-40 GB/day", "Nightly batch + hourly deltas"))),
                        tile("Epicor Prophet 21", "erp", "Distribution ERP widely run by mid-market wholesalers for order management, inventory and branch operations.", "epicor",
                             cat="Distribution ERP",
                             what="Mid-market distribution ERP for order management, inventory and branch operations, the operational backbone of many wholesalers.",
                             users="Supply Chain & Ops, Sales & Commercial and Branch operations teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-25 GB/day", "Nightly batch"))),
                        tile("Oracle NetSuite", "erp", "Cloud ERP for distributors covering order management, inventory, procurement and financials.", "netsuite",
                             cat="Cloud ERP",
                             what="Cloud ERP covering order management, inventory, procurement and financials for distributors running on a SaaS backbone.",
                             users="Finance & Rebates, Supply Chain & Ops and Sales & Commercial teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-25 GB/day", "Hourly / nightly sync"))),
                    ],
                },
                {
                    "box": "Warehouse (WMS)",
                    "ic": "store",
                    "tiles": [
                        tile("Manhattan Active WMS", "store", "Warehouse management for picking, putaway, slotting and labour across the DC network, the source of execution events.", "manhattan",
                             cat="Warehouse Management System (WMS)",
                             what="Runs picking, putaway, slotting and labour across the DC network, the source of execution move events behind fill rate and productivity.",
                             users="Supply Chain & Ops, Warehouse operations and Data Engineers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "10-40 GB/day", "Hourly batch"),
                                 stream=flow(["semi-structured"], "hundreds of moves/sec at peak", "Continuous move events"))),
                        tile("Blue Yonder WMS", "store", "Warehouse management and fulfilment orchestration across distribution centres and branch stock.", "blueyonder",
                             cat="Warehouse Management System (WMS)",
                             what="Orchestrates warehouse management and fulfilment across distribution centres and branch stock, feeding order and shipment execution state.",
                             users="Supply Chain & Ops and Warehouse operations teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-25 GB/day", "Hourly batch + intraday deltas"))),
                        tile("Körber WMS", "store", "Körber Supply Chain warehouse management for wave planning, inventory moves and labour in the DC.", "korber",
                             cat="Warehouse Management System (WMS)",
                             what="Handles wave planning, inventory moves and labour in the DC, emitting the task and move events behind slotting and labour analytics.",
                             users="Supply Chain & Ops and Warehouse operations teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day", "Hourly batch"))),
                    ],
                },
                {
                    "box": "Transport & Logistics",
                    "ic": "stream",
                    "tiles": [
                        tile("Oracle OTM", "stream", "Oracle Transportation Management: route planning, carrier selection, freight rating and settlement across the network.", "oracle-otm",
                             cat="Transportation Management System (TMS)",
                             what="Plans routes, selects carriers, rates freight and settles across the network, the source of movement and landed-cost data.",
                             users="Supply Chain & Ops, Transport & logistics and Finance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch + hourly deltas"))),
                        tile("project44", "iot", "Real-time transportation visibility: in-transit tracking, ETAs and exception alerts across carriers.", "project44",
                             cat="Real-Time Transportation Visibility",
                             what="Provides in-transit tracking, ETAs and exception alerts across carriers, the live status feed behind the OTIF control tower.",
                             users="Supply Chain & Ops, Transport & logistics and Customer service teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds-thousands of events/sec", "Continuous (API / webhook)"))),
                        tile("FourKites", "iot", "Supply chain visibility platform tracking loads and shipments end to end for proactive exception handling.", "fourkites",
                             cat="Real-Time Transportation Visibility",
                             what="Tracks loads and shipments end to end for proactive exception handling, feeding predictive ETA and dwell into service analytics.",
                             users="Supply Chain & Ops, Transport & logistics and Warehouse operations teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds-thousands of events/sec", "Continuous (API / webhook)"))),
                    ],
                },
                {
                    "box": "EDI & B2B Commerce",
                    "ic": "api",
                    "tiles": [
                        tile("SPS Commerce EDI", "api", "Retail and distribution EDI network carrying purchase orders, ASNs and invoices between trading partners.", "sps",
                             cat="EDI / B2B Network",
                             what="Carries purchase orders, ASNs and invoices between trading partners across the retail and distribution community, the B2B document backbone.",
                             users="Supply Chain & Ops, Category & Merch and Integration Engineers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Multiple daily batches"),
                                 stream=flow(["semi-structured"], "tens-hundreds of documents/sec", "Continuous document flow"))),
                        tile("TrueCommerce EDI", "api", "EDI and B2B integration network for order, shipment and invoice documents across the trading community.", "truecommerce",
                             cat="EDI / B2B Network",
                             what="EDI and B2B integration network for order, shipment and invoice documents across the trading community, joined to orders for status and audit.",
                             users="Supply Chain & Ops, Sales & Commercial and Integration Engineers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-3 GB/day", "Multiple daily batches"))),
                        tile("SAP Commerce Cloud", "product", "B2B commerce and punchout catalogs: contract pricing, availability and reorder for buyer procurement systems.", "sap-commerce",
                             cat="B2B Commerce Platform",
                             what="Serves B2B commerce and punchout catalogs with contract pricing, availability and reorder to buyer procurement systems, emitting web and order events.",
                             users="Sales & Commercial, Inside sales & e-commerce and Commercial App Devs.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Hourly sync"),
                                 stream=flow(["semi-structured"], "hundreds of events/sec at peak", "Continuous clickstream / orders"))),
                    ],
                },
                {
                    "box": "Pricing & CRM",
                    "ic": "market",
                    "tiles": [
                        tile("Vendavo Pricing", "market", "B2B price management and margin optimisation: price guidance, deal scoring and rebate administration.", "vendavo",
                             cat="B2B Price Management",
                             what="Manages B2B pricing and margin optimisation with price guidance, deal scoring and rebate administration, the source of contract and quote pricing.",
                             users="Sales & Commercial, Finance & Rebates and Pricing & Demand Sci teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Daily price + rebate refresh"))),
                        tile("PROS Pricing", "market", "AI-driven price optimisation and CPQ for distribution, feeding willingness-to-pay and quote guidance.", "pros",
                             cat="Price Optimization & CPQ",
                             what="Provides AI-driven price optimisation and CPQ, feeding willingness-to-pay and quote guidance into the sales and commerce path.",
                             users="Sales & Commercial, Pricing & Demand Sci and Inside sales teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-3 GB/day", "Daily + on-demand quote scoring"))),
                        tile("Salesforce Sales Cloud", "crm", "Accounts, opportunities and quotes for field, inside and account-management sales teams.", "salesforce",
                             cat="Sales CRM",
                             what="Holds accounts, opportunities and quotes for field, inside and account-management teams, the relationship view behind churn and cross-sell.",
                             users="Sales & Commercial, Sales leadership and Account management teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Hourly / nightly sync"),
                                 stream=flow(["semi-structured"], "tens of events/sec", "Continuous CDC"))),
                    ],
                },
                fed_group(
                    "Finance & Rebate Mart",
                    "Rebate, chargeback and margin marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers.",
                    cat="Finance Data Warehouse",
                    what="Rebate, chargeback and margin marts kept in the incumbent warehouse and queried in place through federation, avoiding a second copy of the audited numbers.",
                    users="Finance & Rebates, CFO & controllers and Rebate & pricing admin analysts.",
                    data_out=data_out(
                        batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)")),
                ),
            ],
            "ing": ing_rail(
                [
                    tile("Dun & Bradstreet", "partner", "Firmographics, corporate hierarchies and credit signals for customer onboarding and credit risk.", "dnb",
                         cat="Firmographic & Credit Data",
                         what="Supplies firmographics, corporate hierarchies and credit signals used to onboard customers and assess credit and counterparty risk.",
                         users="Finance & Rebates, Credit & AR and Sales & Commercial teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "0.5-2 GB/day", "Weekly + on-demand refresh"))),
                    tile("Circana POS", "chart", "Downstream point-of-sale and market data for demand sensing across categories and channels.", "circana",
                         cat="POS & Market Data",
                         what="Provides downstream point-of-sale and market data for demand sensing across categories and channels, feeding forecast and assortment decisions.",
                         users="Category & Merch, Pricing & Demand Sci and Merchandising teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/week", "Weekly syndicated feed"))),
                    tile("DAT Freight Rates", "market", "Spot and contract freight rate benchmarks for carrier negotiation and landed-cost analysis.", "dat",
                         cat="Freight Rate Benchmarks",
                         what="Publishes spot and contract freight-rate benchmarks used for carrier negotiation and landed-cost analysis.",
                         users="Supply Chain & Ops, Transport & logistics and Finance teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "MBs", "Daily / weekly rate benchmarks"))),
                ]
            ),
            "ppl": ppl2(
                [
                    biz("Executive Office", "Genie One",
                        "The CEO and COO on revenue growth, branch productivity and the working capital tied up in inventory; the strategy office on which categories, branches and customers to expand or exit.",
                        [["Genie One", "Ask what last month's gross margin was by branch and category without booking analyst time."],
                         ["AI/BI", "Revenue, fill rate, margin and inventory turns on one certified set of Metric Views."],
                         ["Unity Catalog", "Certification and the business glossary, so \"margin\" and \"service level\" mean one thing across the business."]],
                        sub=[["CEO & COO", "revenue growth, branch productivity and the trade between service and working capital."],
                             ["Strategy & M&A", "which categories, branches and customers to expand, acquire or exit."]],
                        ucs=["Margin & Mix Analytics", "Demand Forecasting", "Dynamic B2B Pricing", "Fill-Rate & OTIF"]),
                    biz("Sales & Commercial", "Model Serving",
                        "Field sales, inside sales and account management growing wallet share across the customer base, defending price and catching accounts before they drift away.",
                        [["Model Serving", "Churn, cross-sell and next-best-order scored in the rep's account view."],
                         ["Pricing Cockpit", "Quote and contract price guidance held to margin floors at the point of sale."],
                         ["AI/BI", "Pipeline, win rate and share of wallet on governed customer data."]],
                        sub=[["Sales leadership", "territory targets, rep productivity and share of wallet."],
                             ["Account management", "retention, cross-sell and contract renewals on key accounts."],
                             ["Inside sales & e-commerce", "conversion and basket size across the branch and web channels."]],
                        ucs=["Dynamic B2B Pricing", "Churn & Cross-Sell", "B2B Personalization"]),
                    biz("Category & Merch", "AI/BI",
                        "Category managers and merchandisers deciding assortment, supplier terms and private-label mix, judged on category margin, in-stock rate and supplier performance.",
                        [["AI/BI", "Category margin, assortment productivity and supplier scorecards on certified views."],
                         ["Demand Forecasting", "SKU-location demand signals feeding assortment and buy decisions."],
                         ["Genie One", "Ask which SKUs are dead stock or which suppliers slipped on lead time."]],
                        sub=[["Category managers", "assortment, pricing architecture and private-label mix."],
                             ["Merchandising", "planograms, promotions and new-product introductions."],
                             ["Vendor management", "supplier terms, rebates and lead-time performance."]],
                        ucs=["Demand Forecasting", "Supplier Scorecards", "Margin & Mix Analytics"]),
                    biz("Supply Chain & Ops", "Lakehouse//RT",
                        "Planning, warehouse and transport teams moving product from supplier to branch to customer at the promised service level and the lowest landed cost.",
                        [["Inventory Command", "Replenishment and safety-stock recommendations by SKU and location."],
                         ["Lakehouse//RT", "Live warehouse and in-transit state at the latency the operation moves at."],
                         ["OTIF Control Tower", "Orders at risk of missing the promised delivery flagged before they ship."]],
                        sub=[["Demand & supply planning", "forecast, replenishment and safety-stock policy."],
                             ["Warehouse operations", "picking, putaway and slotting across the DC network."],
                             ["Transport & logistics", "route, carrier and last-mile execution to branch and customer."]],
                        ucs=["Inventory Optimization", "Fill-Rate & OTIF", "Route & Logistics", "Demand Forecasting"]),
                    biz("Finance & Rebates", "AI/BI",
                        "The CFO's office running margin, cash and the rebate and chargeback programs that make or break net profit in a thin-margin distribution business.",
                        [["AI/BI", "Net margin after rebates and chargebacks on certified Metric Views."],
                         ["Rebate Manager", "Supplier rebate accruals and customer chargebacks tracked to contract terms."],
                         ["Genie One", "Ask which rebate tiers are at risk of being missed this quarter."]],
                        sub=[["CFO & controllers", "gross-to-net margin, cash and inventory valuation."],
                             ["Rebate & pricing admin", "supplier rebate accruals and customer chargeback claims."],
                             ["Credit & AR", "customer credit exposure and collections across the book."]],
                        ucs=["Rebate & Chargeback", "Margin & Mix Analytics", "Churn & Cross-Sell"]),
                ],
                [
                    biz("Supply Chain Data Eng", "Lakeflow",
                        "Land the SAP, Infor and Epicor ERP, Manhattan and Blue Yonder WMS, TMS and EDI feeds; own the Bronze to Silver path and the pager when replenishment tables stall.",
                        [["Lakeflow Connect", "Managed connectors for the ERP, WMS and SaaS commerce sources."],
                         ["Lakeflow Designer", "Declarative pipelines with expectations on order, shipment and EDI feeds."],
                         ["Lakewatch", "Freshness on the inventory and fill-rate tables ops reads every morning."]],
                        sub=[["Ingestion Engineers", "the SAP, Infor and Epicor ERP, WMS, TMS and EDI order feeds landed on time."],
                             ["Pipeline Engineers", "the Bronze-to-Silver path and expectations on order, shipment and EDI feeds."],
                             ["Platform Reliability", "freshness of the fill-rate and margin tables ops and finance read every morning."]]),
                    biz("Pricing & Demand Sci", "MLflow",
                        "Demand-forecast, price-elasticity, churn and inventory-optimisation models built from POS, order and Vendavo and PROS data, and whether they still hold as the network shifts.",
                        [["Feature Store", "Customer, SKU and location features read identically in training and serving."],
                         ["MLflow", "Every forecast and pricing model tracked for audit and reproduction."],
                         ["Model Serving", "Price, demand and churn models scored in the quote and replenishment path."]],
                        sub=[["Forecasting Scientists", "demand and price-elasticity models across SKU-location and customer."],
                             ["Optimization Scientists", "inventory and safety-stock models under service and working-capital limits."],
                             ["MLOps", "every forecast and pricing model tracked for audit and reproduction."]]),
                    biz("Commercial App Devs", "Apps",
                        "Ship the inventory command, pricing cockpit, OTIF tower and rebate applications the commercial and operations teams work in, hosted next to governed data.",
                        [["Apps", "Operational screens with no separate web tier to run or secure."],
                         ["Lakebase", "Serverless Postgres for quote, replenishment and rebate-claim state."],
                         ["Agent Bricks", "Agents that draft a reorder or a price quote against governed tools."]],
                        sub=[["Frontend Engineers", "the inventory command, pricing cockpit and OTIF tower screens teams work in."],
                             ["Backend Engineers", "Lakebase state for quote, replenishment and rebate-claim writeback."],
                             ["Agent Builders", "agents that draft a reorder or a price quote against governed tools."]]),
                ],
            ),
            "cons": cons_rail(
                [
                    {
                        "box": "BI & Productivity",
                        "ic": "chart",
                        "from": "bi",
                        "tiles": [
                            tile("Tableau / Power BI", "chart", "Executive and branch dashboards against serverless SQL warehouses, with Unity Catalog permissions enforced end to end."),
                            tile("Microsoft Teams", "chat", "Genie in Teams for margin and fill-rate answers in the channel the commercial team already works in (Beta)."),
                            tile("Notebooks & IDEs", "notebook", "Analyst notebooks, VS Code and JetBrains against governed order and inventory data."),
                        ],
                    },
                    {
                        "box": "Customer & Supplier",
                        "ic": "partner",
                        "tiles": [
                            tile("Customer & Punchout", "api", "Contract pricing, availability and reorder guidance served to buyer procurement and punchout catalogs.", "sap-commerce"),
                            tile("Supplier Portals", "partner", "Forecasts, scorecards and replenishment signals shared to suppliers over Delta Sharing rather than spreadsheets."),
                            tile("EDI Outbound", "stream", "Purchase orders, ASNs and invoices pushed back to trading partners through the EDI network.", "sps"),
                        ],
                    },
                    {
                        "box": "Operational Writeback",
                        "ic": "opdb",
                        "tiles": [
                            tile("ERP Replenishment", "erp", "Reorder points and purchase-order suggestions written back into the ERP so the buy reaches the procurement path.", "sap"),
                            tile("WMS Slotting", "store", "Slotting and wave recommendations written to the warehouse system operations already works in.", "manhattan"),
                            tile("Price & Quote Sync", "market", "Contract prices and quote guidance written back to CRM and commerce at the point of sale.", "vendavo"),
                        ],
                    },
                    {
                        "box": "Regulatory & Reporting",
                        "ic": "gavel",
                        "tiles": [
                            tile("Trade & Tax Compliance", "gavel", "Sales-and-use tax, customs and controlled-product reporting produced from the same governed tables the business runs on."),
                            tile("Financial Reporting", "share", "Rebate, margin and inventory-valuation reporting filed from contracted Gold products."),
                        ],
                    },
                    {
                        "box": "Published Products",
                        "ic": "product",
                        "tiles": [
                            tile("Data Products", "product", "Published, contracted products discoverable in Unity Catalog Domains and shared over OpenSharing."),
                            tile("Sharing Recipients", "share", "Suppliers, carriers and buying groups reading live tables with no copy and no egress duplication."),
                        ],
                    },
                ],
                genie_spaces=[
                    genie("Inventory & Fill-Rate", "Ask about stock positions, fill rate and orders at risk of missing OTIF.",
                          feeds=["SAP S/4HANA", "Manhattan Active WMS", "project44", "Fill-rate, margin, forecast"],
                          teams=["Supply Chain & Ops", "Demand & supply planning", "Warehouse operations"],
                          questions=[
                              "Which SKU-locations are about to stock out on current demand?",
                              "What is fill rate by customer and branch this week?",
                              "Which open orders are at risk of missing OTIF today?",
                              "Where is working capital tied up in slow-moving inventory?",
                              "Which SKUs are dead stock across the branch network?"]),
                    genie("Margin & Rebates", "Explore gross-to-net margin, rebate accruals and chargeback exposure.",
                          feeds=["SAP S/4HANA", "Vendavo Pricing", "Finance & Rebate Mart", "Fill-rate, margin, forecast"],
                          teams=["Finance & Rebates", "CFO & controllers", "Rebate & pricing admin"],
                          questions=[
                              "What is gross-to-net margin by customer and category this month?",
                              "Which supplier rebate tiers are at risk of being missed this quarter?",
                              "Which customer chargebacks look invalid and worth disputing?",
                              "Which customers and SKUs are loss-making after rebates?",
                              "How much earned rebate is still uncaptured against contract terms?"]),
                    genie("Sales & Customer Growth", "Answer share-of-wallet, churn and cross-sell questions across the account base.",
                          feeds=["Salesforce Sales Cloud", "SAP Commerce Cloud", "SAP S/4HANA", "Conformed customer, SKU, order"],
                          teams=["Sales & Commercial", "Account management", "Inside sales & e-commerce"],
                          questions=[
                              "Which accounts are drifting and reducing order frequency?",
                              "Where is the biggest cross-sell whitespace by account?",
                              "What is share of wallet on our top 100 customers?",
                              "Which reps are below target on productivity this quarter?",
                              "How is the B2B web channel converting versus the branch?"]),
                    genie("Demand & Supplier Performance", "Ask about SKU-location demand forecasts and supplier lead-time reliability.",
                          feeds=["Circana POS", "SPS Commerce EDI", "SAP S/4HANA", "Fill-rate, margin, forecast"],
                          teams=["Category & Merch", "Vendor management", "Demand & supply planning"],
                          questions=[
                              "Which SKU-locations have the least accurate forecast right now?",
                              "Which suppliers are slipping on lead time versus commitment?",
                              "How does forecast bias vary by category and season?",
                              "Which suppliers have the worst fill rate on our purchase orders?",
                              "Where should assortment change based on demand signals?"]),
                ],
                dashboards=[
                    dashboard("Fill-Rate & Service", "Fill rate, OTIF and orders at risk across customers and branches.",
                              kpis=["Fill rate", "OTIF", "Orders at risk", "Backorder rate", "Perfect order rate"],
                              teams=["Supply Chain & Ops", "Executive Office", "Demand & supply planning"]),
                    dashboard("Margin & Rebate Recovery", "Gross-to-net margin, rebate accruals and chargeback exposure.",
                              kpis=["Gross-to-net margin", "Rebate accrual", "Chargeback exposure", "Margin leakage", "Net profit"],
                              teams=["Finance & Rebates", "CFO & controllers", "Executive Office"]),
                    dashboard("Inventory & Working Capital", "Inventory turns, dead stock and working capital by SKU and branch.",
                              kpis=["Inventory turns", "Days on hand", "Dead stock value", "Working capital", "Stockout rate"],
                              teams=["Supply Chain & Ops", "Category & Merch", "Finance & Rebates"]),
                    dashboard("Sales & Customer Health", "Share of wallet, churn risk and cross-sell across the account base.",
                              kpis=["Share of wallet", "Churn risk", "Cross-sell rate", "Win rate", "Order frequency"],
                              teams=["Sales & Commercial", "Account management", "Inside sales & e-commerce"]),
                ],
            ),
        },
        "top": top_band(
            [
                app("Inventory Command", "Replenishment", "gauge",
                    "Replenishment, safety-stock and dead-stock recommendations by SKU and branch, so buyers reorder on predicted demand instead of a fixed reorder point, on Databricks Apps over Lakebase."),
                app("Pricing Cockpit", "Quote guidance", "market",
                    "Where sales and pricing see the margin floor, competitor context and win probability on a quote before a contract price is agreed."),
                app("OTIF Control Tower", "Service levels", "stream",
                    "Live order and shipment state against the promised delivery date, flagging the orders that will miss on-time-in-full before they leave the dock."),
                app("Rebate Manager", "Margin recovery", "gavel",
                    "Supplier rebate accruals and customer chargeback claims tracked to contract terms, so earned rebates are captured and invalid chargebacks are disputed."),
            ],
            [
                uc("Demand Forecasting", "Planning", "chart",
                    "SKU-location demand forecasts across a long-tail catalog and a branch network, blending sell-through, order history, seasonality and promotions.",
                    problem="A distributor forecasts hundreds of thousands of SKU-location pairs on a spreadsheet cadence, so slow movers overstock and fast movers stock out between refreshes.",
                    who="Category & Merch",
                    how="Order, POS and promotion feeds are conformed to Gold; fine-grained forecasts are trained in MLflow and scored per SKU-location, feeding replenishment and buy decisions.",
                    comps=["Demand Forecasting", "Model Serving", "SAP S/4HANA", "AI/BI", "Feature Store"],
                    stories=[["Demand Forecasting at Scale on Databricks", "https://www.databricks.com/solutions/accelerators/demand-forecasting"],
                             ["Mondelez scales model experimentation on Databricks", "https://www.databricks.com/customers/mondelez"]]),
                uc("Inventory Optimization", "Working capital", "store",
                    "Safety-stock, reorder-point and assortment decisions tuned to service-level targets and the cash tied up in inventory across every branch.",
                    problem="Inventory is set by static min-max rules per branch, so millions in working capital sit in the wrong SKUs while service levels still miss on the ones that matter.",
                    who="Supply Chain & Ops",
                    how="Forecasts and lead-time variability feed multi-echelon optimisation in Model Serving; recommendations surface in the Inventory Command app and write back to the ERP.",
                    comps=["Inventory Command", "Model Serving", "Manhattan Active WMS", "Lakehouse//RT", "MLflow"],
                    stories=[["Supply Chain Distribution Optimization", "https://www.databricks.com/solutions/accelerators/supply-chain-distribution-optimization"]]),
                uc("Dynamic B2B Pricing", "Revenue", "market",
                    "Contract and quote prices set per customer, product and volume against cost, competitor context and willingness to pay rather than a static price book.",
                    problem="Thousands of negotiated contract prices drift from cost, so margin leaks quietly on renewals and reps discount to the floor without knowing where the floor is.",
                    who="Sales & Commercial",
                    how="Vendavo and PROS pricing data are conformed in the lakehouse; elasticity and win-probability models score each quote through Model Serving behind the Pricing Cockpit.",
                    comps=["Pricing Cockpit", "Vendavo Pricing", "PROS Pricing", "Model Serving", "AI/BI"],
                    stories=[["Databricks for Retail and Consumer Goods", "https://www.databricks.com/solutions/industries/retail-industry-solutions"]]),
                uc("Churn & Cross-Sell", "Growth", "custlake",
                    "Predicting which accounts are drifting and which product lines they should be buying, scored against the order history the CRM and ERP already hold.",
                    problem="A distributor loses accounts quietly: orders taper for months before anyone notices, and cross-sell whitespace sits unworked because no one scores it.",
                    who="Sales & Commercial",
                    how="Order and CRM history are activated through CustomerLake; churn and next-best-order models are scored in Model Serving and served into the rep's account view.",
                    comps=["Feature Store", "Model Serving", "Salesforce Sales Cloud", "CustomerLake", "AI/BI"],
                    stories=[["Calculate Customer Lifetime Value", "https://www.databricks.com/solutions/accelerators/customer-lifetime-value"]]),
                uc("Fill-Rate & OTIF", "Service", "gauge",
                    "On-time-in-full attacked before the miss: order, inventory and shipment state joined so an at-risk line is caught while it can still be expedited.",
                    problem="Fill-rate and OTIF are reported after the customer is short-shipped, when the only options left are an apology and a credit.",
                    who="Supply Chain & Ops",
                    how="Order, inventory and shipment feeds stream into Lakehouse//RT; the OTIF Control Tower flags orders that will miss the promised date so ops can expedite or substitute.",
                    comps=["OTIF Control Tower", "Lakehouse//RT", "Manhattan Active WMS", "Oracle OTM", "AI/BI"],
                    stories=[["Supply Chain Distribution Optimization", "https://www.databricks.com/solutions/accelerators/supply-chain-distribution-optimization"]]),
                uc("Supplier Scorecards", "Sourcing", "sheet",
                    "Supplier performance measured on lead-time reliability, fill rate, quality and rebate compliance across every purchase order, not just the last complaint.",
                    problem="Supplier reviews run on anecdote and the loudest incident, because lead-time and fill data live in the ERP and never get turned into a scorecard.",
                    who="Category & Merch",
                    how="Purchase-order, receipt and EDI feeds are conformed to Gold; supplier scorecards are published as certified Metric Views and shared back to suppliers over Delta Sharing.",
                    comps=["AI/BI", "SAP S/4HANA", "SPS Commerce EDI", "Unity Catalog", "Genie One"],
                    stories=[["Unilever: GenAI powers smarter operations", "https://www.databricks.com/customers/unilever"]]),
                uc("Route & Logistics", "Logistics", "stream",
                    "Delivery routes, carrier choice and last-mile execution optimised across the branch and DC network to cut freight cost and hit the delivery window.",
                    problem="Routes and carrier assignments are planned in silos per branch, so trucks run half-empty, freight spend climbs and delivery windows slip.",
                    who="Supply Chain & Ops",
                    how="Order, shipment and TMS feeds are conformed; route and load plans are generated in Model Serving and executed from the OTIF Control Tower against live in-transit state.",
                    comps=["OTIF Control Tower", "Oracle OTM", "project44", "Model Serving", "Lakehouse//RT"],
                    stories=[["Scalable Route Generation on Databricks", "https://www.databricks.com/solutions/accelerators/scalable-route-generation"]]),
                uc("Rebate & Chargeback", "Margin", "gavel",
                    "Supplier rebate accruals earned and customer chargebacks validated to contract terms, so net margin reflects the money actually owed and owing.",
                    problem="Rebates and chargebacks are reconciled in spreadsheets against contracts no one can find, so earned rebates go uncaptured and invalid chargebacks go unpaid.",
                    who="Finance & Rebates",
                    how="Contract terms, purchase and sales history are conformed in the lakehouse; the Rebate Manager app tracks accruals and disputes on Lakebase with governed writes.",
                    comps=["Rebate Manager", "SAP S/4HANA", "AI/BI", "Lakebase", "Unity Catalog"]),
                uc("B2B Personalization", "E-commerce", "product",
                    "Search, product discovery and reorder guidance on the B2B web and punchout channels, tuned to the contract catalog and buying pattern of each account.",
                    problem="A distributor's e-commerce search buries the right part in a multi-million-SKU catalog, so buyers call the branch and the digital channel underperforms.",
                    who="Sales & Commercial",
                    how="Catalog and order history feed retrieval and recommendation models scored in Model Serving; personalised search and reorder lists serve into the commerce and punchout channels.",
                    comps=["Pricing Cockpit", "CustomerLake", "Model Serving", "SAP Commerce Cloud", "AI/BI"],
                    stories=[["Grainger: GenAI product discovery across 2.5M SKUs", "https://www.databricks.com/customers/grainger"],
                             ["Recommendation Engines for Personalization", "https://www.databricks.com/solutions/accelerators/recommendation-engines"]]),
                uc("Margin & Mix Analytics", "Profitability", "chart",
                    "Gross-to-net margin decomposed by customer, product, branch and channel, so the business sees where mix, price and cost move the P&L.",
                    problem="Margin is reported at the top line, so the loss-making customers and SKUs hide inside a healthy average until a bad quarter exposes them.",
                    who="Finance & Rebates",
                    how="Sales, cost and rebate data are conformed to certified Metric Views; margin and mix are explored in AI/BI and Genie on the same definitions the executive team reads.",
                    comps=["AI/BI", "Unity Catalog", "Genie One", "SAP S/4HANA", "Vendavo Pricing"],
                    stories=[["Reckitt on Databricks", "https://www.databricks.com/customers/reckitt"],
                             ["Ahold Delhaize on Databricks", "https://www.databricks.com/customers/ahold-delhaize"]]),
            ],
        ),
        "sources": {
            "sap": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "infor": {"t": "Infor CloudSuite Distribution", "u": "https://www.infor.com/industries/distribution"},
            "epicor": {"t": "Epicor Prophet 21", "u": "https://www.epicor.com/en-us/erp-systems/prophet-21/"},
            "netsuite": {"t": "Oracle NetSuite ERP", "u": "https://www.netsuite.com/portal/products/erp.shtml"},
            "manhattan": {"t": "Manhattan Active Warehouse Management", "u": "https://www.manh.com/products/warehouse-management"},
            "blueyonder": {"t": "Blue Yonder Warehouse Management", "u": "https://blueyonder.com/solutions/warehouse-management"},
            "korber": {"t": "Körber Supply Chain Software", "u": "https://www.koerber-supplychain.com/"},
            "oracle-otm": {"t": "Oracle Transportation Management", "u": "https://www.oracle.com/scm/logistics/transportation-management/"},
            "project44": {"t": "project44 Visibility", "u": "https://www.project44.com/"},
            "fourkites": {"t": "FourKites Supply Chain Visibility", "u": "https://www.fourkites.com/"},
            "sps": {"t": "SPS Commerce EDI", "u": "https://www.spscommerce.com/"},
            "truecommerce": {"t": "TrueCommerce EDI", "u": "https://www.truecommerce.com/"},
            "sap-commerce": {"t": "SAP Commerce Cloud", "u": "https://www.sap.com/products/crm/e-commerce-platforms.html"},
            "vendavo": {"t": "Vendavo Pricing", "u": "https://www.vendavo.com/"},
            "pros": {"t": "PROS Pricing", "u": "https://pros.com/"},
            "salesforce": {"t": "Salesforce Sales Cloud", "u": "https://www.salesforce.com/products/sales-cloud/overview/"},
            "dnb": {"t": "Dun & Bradstreet", "u": "https://www.dnb.com/"},
            "circana": {"t": "Circana (IRI/NPD)", "u": "https://www.circana.com/"},
            "dat": {"t": "DAT Freight & Analytics", "u": "https://www.dat.com/"},
        },
    }
}
