import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_APPAREL_FASHION = {
    'apparel_fashion': {
        "label": "Apparel & Fashion",
        "blurb": "Seasonal collections, omnichannel retail, demand sensing, and sustainable sourcing across design, manufacturing, and direct-to-consumer channels.",
        "medallion": medallion(
            "Raw style and sales feeds",
            "POS, e-commerce, PLM and factory WIP events landed exactly as received so a markdown or a allocation can be replayed.",
            "Conformed styles and channels",
            "Styles, SKUs, stores and digital channels resolved into single entities across ERP, PLM and commerce platforms.",
            "Sell-through, margin, OTB",
            "Contracted products merchandising and finance run on: sell-through rate, full-price sell-through, OTB and margin by collection.",
        ),
        "rails": {
            "src": [
                {"box": "PLM & Design", "ic": "product", "tiles": [
                    tile("Centric PLM", "product", "Style masters, BOMs, colorways and sample approvals through development.", "centric-plm"),
                    tile("Adobe Substance", "apps", "Material libraries and 3D render assets linked to style records.", "adobe-substance"),
                    tile("CLO 3D", "apps", "Digital samples and fit iterations before physical proto.", "clo-3d"),
                ]},
                {"box": "ERP & Supply", "ic": "erp", "tiles": [
                    tile("Infor CloudSuite Fashion", "erp", "Seasonal collections, purchasing and factory allocations.", "infor-fashion"),
                    tile("SAP S/4HANA Retail", "erp", "Inventory, allocation and financial close for multi-brand houses.", "sap-retail"),
                    tile("Blue Yonder WMS", "stream", "Warehouse execution, pick paths and store replenishment.", "blue-yonder-wms"),
                ]},
                {"box": "Commerce & POS", "ic": "market", "tiles": [
                    tile("Shopify Plus", "partner", "DTC orders, returns and customer profiles across owned sites.", "shopify"),
                    tile("Salesforce Commerce Cloud", "partner", "Omnichannel carts, promotions and clienteling data.", "sf-commerce"),
                    tile("Oracle Xstore POS", "market", "Store transactions, associates and endless aisle lookups.", "oracle-xstore"),
                ]},
                {"box": "Manufacturing", "ic": "zplug", "tiles": [
                    tile("Lectra Fashion", "zplug", "Marker making, cutting room and factory KPIs.", "lectra"),
                    tile("Gerber Technology", "iot", "Spreading, cutting and unit production tracking.", "gerber"),
                    tile("Fast React Plan", "sheet", "Factory capacity, T&A calendars and critical path.", "fast-react"),
                ]},
                {"box": "Sustainability", "ic": "gavel", "tiles": [
                    tile("Higg Index MSI", "gavel", "Material sustainability scores and facility social audits.", "higg"),
                    tile("Textile Exchange", "partner", "Preferred fiber certifications and chain of custody.", "textile-exchange"),
                ]},
                fed_group("Wholesale Partner Mart", "Department store sell-in and chargeback marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("Edited Retail Intel", "market", "Competitor pricing, assortment and markdown signals by market.", "edited"),
                tile("WGSN Trend Forecast", "ztarget", "Macro trends, color and silhouette forecasts for line planning.", "wgsn"),
                tile("Open Supply Hub", "globe", "Factory disclosure and supplier mapping for due diligence.", "opensupplyhub"),
            ]),
            "ppl": ppl2([
                biz("Brand President & CFO", "Genie One",
                    "The CEO on brand heat and wholesale sell-in; the CFO on gross margin, full-price sell-through and inventory ownership.",
                    [["Genie One", "Ask what last collection's full-price sell-through was."], ["AI/BI", "Margin and OTB on certified Metric Views."], ["Unity Catalog", "One SKU definition across channels."]],
                    sub=[
                        ["Brand President / CEO", "brand heat, wholesale sell-in and the health of the full-price business."],
                        ["CFO", "gross margin, full-price sell-through and the cash tied up in inventory ownership."],
                        ["Financial Planning", "OTB budgets, markdown liability and the season's margin bridge."],
                    ],
                    ucs=["Inventory Right-Sizing", "Wholesale Chargebacks", "Markdown Optimization"]),
                biz("Merchandising", "AI/BI",
                    "Assortment breadth, depth, pricing and markdown cadence by door and channel, judged on sell-through rate, weeks of supply and GMROI.",
                    [["Allocation Optimizer", "Size curves and door profiles before allocation locks."], ["AI/BI", "Sell-through and WOS on governed POS."]],
                    sub=[
                        ["Buyers", "assortment breadth and depth and the sell-through of every style they bought."],
                        ["Merchandise Planners", "pricing, markdown cadence and GMROI by door and channel."],
                        ["Trading", "weeks of supply and in-season reaction on the styles moving now."],
                    ],
                    ucs=["Markdown Optimization", "Demand Sensing", "Size Curve Optimization"]),
                biz("Planning & Allocation", "Model Serving",
                    "Open-to-buy, size curves and replenishment against demand forecasts, balancing receipt plans, in-stock rate and markdown liability.",
                    [["OTB Workbench", "Receipt plans against sell-through scenarios."], ["Model Serving", "Demand forecasts in the allocation path."]],
                    sub=[
                        ["Demand Planners", "the forecast per style and door and how fast it moves with the trend."],
                        ["Allocators", "size curves, receipt plans and the in-stock rate at each door."],
                        ["Replenishment", "weeks of supply and refill timing against markdown liability."],
                    ],
                    ucs=["Demand Sensing", "Size Curve Optimization", "Omnichannel Fulfillment", "Inventory Right-Sizing"]),
                biz("Sourcing & Production", "Lakehouse//RT",
                    "Factory capacity, time-and-action risk and cost negotiations, tracked on on-time delivery, WIP by PO and landed cost per unit.",
                    [["Factory Tracker", "WIP and delay risk by PO and factory."], ["Lakehouse//RT", "Production milestones at operational latency."]],
                    sub=[
                        ["Sourcing Managers", "landed cost per unit and the factory negotiation behind it."],
                        ["Production / T&A", "on-time delivery, WIP by PO and the critical-path calendar."],
                        ["Product Development", "fit, sample approvals and the path from design to proto."],
                    ],
                    ucs=["Factory Risk Monitoring", "3D Sample Reduction", "Sustainable Sourcing"]),
                biz("Digital & CRM", "Apps",
                    "Clienteling, loyalty and personalization across stores and DTC, measured on repeat rate, clienteled revenue and conversion.",
                    [["Clienteling App", "Associate recommendations on governed customer profiles."], ["Apps", "Store apps hosted next to governed data."]],
                    sub=[
                        ["Ecommerce", "DTC conversion, on-site personalization and the owned-site funnel."],
                        ["CRM & Loyalty", "repeat rate, clienteled revenue and lifetime value across channels."],
                        ["Retail Store Ops", "associate clienteling and endless-aisle lookups on the floor."],
                    ],
                    ucs=["Clienteling & CRM", "Omnichannel Fulfillment", "Demand Sensing"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land POS, e-commerce, PLM style masters and factory WIP; own Bronze to Silver and the pager when the sell-through tables merchandisers trade on stall.",
                    [["Lakeflow Connect", "Managed connectors for ERP, PLM and commerce sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on POS and production feeds."], ["Lakewatch", "Freshness on the sell-through tables the trading room reads every morning."]],
                    sub=[
                        ["Ingestion Engineers", "managed connectors for ERP, PLM, POS and commerce feeds."],
                        ["Pipeline Engineers", "Bronze-to-Silver reliability and expectations on the sell-through tables."],
                        ["Platform / SRE", "the pager when the trading-room tables stall before market open."],
                    ],
                    ucs=["Demand Sensing", "Omnichannel Fulfillment", "Factory Risk Monitoring"]),
                biz("Data Scientists", "MLflow",
                    "Short-lifecycle demand-sensing, size-curve and markdown-optimisation models, and whether they still hold across a new season's assortment.",
                    [["Feature Store", "Style and door features read identically in training and serving."], ["MLflow", "Every demand and markdown model tracked for audit and reproduction."], ["Model Serving", "Demand and markdown models scored in the allocation path."]],
                    sub=[
                        ["Demand Scientists", "short-lifecycle demand-sensing and size-curve models per season."],
                        ["Pricing Scientists", "markdown-optimisation and price-elasticity models that hold through the season."],
                        ["MLOps", "training-to-serving parity and whether last season's model still holds."],
                    ],
                    ucs=["Demand Sensing", "Markdown Optimization", "Size Curve Optimization"]),
                biz("App Developers", "Apps",
                    "Ship the OTB workbench, allocation optimizer, factory tracker and clienteling apps merchandising and stores work in, next to governed style data.",
                    [["Apps", "Operational and store screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for allocation and clienteling state."], ["Agent Bricks", "Agents that draft receipt and markdown moves against governed tools."]],
                    sub=[
                        ["Full-Stack Engineers", "the OTB, allocation and factory screens merchandising works in."],
                        ["Store App Engineers", "the clienteling and endless-aisle app on the sales floor."],
                        ["Agent Engineers", "agents that draft receipt and markdown moves against governed tools."],
                    ],
                    ucs=["Clienteling & CRM", "Markdown Optimization", "Inventory Right-Sizing"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Looker", "chart", "Merchandising and finance dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for sell-through and OTB in the trading room."),
                    tile("Notebooks & IDEs", "notebook", "Planning notebooks against governed style and sales data."),
                ]},
                {"box": "Wholesale & Retail", "ic": "partner", "tiles": [
                    tile("EDI 850/856 ASN", "api", "Wholesale orders and advance ship notices to department store partners."),
                    tile("Endless Aisle API", "partner", "Store lookups against central inventory for clienteling.", "oracle-xstore"),
                    tile("Marketplace Feeds", "globe", "Assortment and inventory synced to Zalando and Farfetch.", "shopify"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Allocation Releases", "stream", "Door-level allocations pushed to WMS before pick waves."),
                    tile("Price & Markdown", "market", "Markdown recommendations written to POS and commerce.", "sf-commerce"),
                    tile("Factory PO Updates", "zplug", "Revised quantities and dates sent to vendor portals.", "fast-react"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("EU DPP Readiness", "gavel", "Digital product passport attributes assembled from PLM and supply chain."),
                    tile("Modern Slavery Reports", "share", "Supplier audit status filed from governed facility data.", "higg"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Style and sell-through products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Wholesale partners reading inventory via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("OTB Workbench", "Receipt planning", "sheet", "Open-to-buy scenarios by collection before purchase orders are released."),
             app("Allocation Optimizer", "Door profiles", "market", "Size curves and door-level allocation against demand and constraints."),
             app("Factory Tracker", "Production WIP", "zplug", "PO milestones, delay risk and air-freight decisions before launch windows slip."),
             app("Clienteling App", "Store associate", "custlake", "Recommendations and endless aisle on governed customer and inventory data.")],
            [uc("Demand Sensing", "Planning", "chart", "Short-lifecycle forecasts updated from POS and digital signals.",
                problem="Fashion sells out or gets marked down before anyone reads the signal, and forecasts built on last year's like-for-like miss the trend and the weather, so the buy is wrong the moment the season turns.",
                who="Planning & Allocation",
                how="POS and e-commerce signals land through Lakeflow onto Delta Lake, and demand-sensing models tracked in MLflow score through Model Serving into the OTB Workbench so plans move weekly, not seasonally.",
                comps=["OTB Workbench", "Shopify Plus", "Model Serving", "MLflow", "Lakeflow", "Delta Lake"],
                stories=[
                    ["ABFRL forecasts trends, demand and pricing on Databricks", "https://www.databricks.com/customers/aditya-birla-fashion-and-retail-ltd"],
                    ["Prada Group tailors their AI strategy with forecasting models", "https://www.databricks.com/customers/prada-group"],
                ]),
             uc("Size Curve Optimization", "Allocation", "product", "Size profiles tuned by door cluster and sell-through.",
                problem="Size curves are set once at the chain level, so popular sizes stock out while the odd sizes pile into markdown, and door-level demand and returns never feed back into the next allocation.",
                who="Planning & Allocation",
                how="Sell-through and returns by door cluster are conformed on Delta Lake, scored with Model Serving off Feature Store, and the Allocation Optimizer sets size profiles before allocation locks.",
                comps=["Allocation Optimizer", "Oracle Xstore POS", "Model Serving", "Feature Store", "Delta Lake"],
                stories=[
                    ["ABFRL scales ML to store-level SKU assortment and allocation", "https://www.databricks.com/customers/aditya-birla-fashion-and-retail-ltd"],
                ]),
             uc("Markdown Optimization", "Pricing", "market", "Markdown timing and depth maximizing margin recovery.",
                problem="Markdowns are taken on a calendar rather than on evidence, so margin walks out the door: too deep too early on styles that would have sold, too late on the ones that never will.",
                who="Merchandising",
                how="Sell-through, inventory and price-elasticity features on Delta Lake feed markdown models in Model Serving, with recommendations written back to POS and commerce and watched in AI/BI.",
                comps=["Model Serving", "Salesforce Commerce Cloud", "AI/BI", "Delta Lake", "MLflow"],
                stories=[
                    ["ABFRL builds an in-season markdown recommendation model", "https://www.databricks.com/customers/aditya-birla-fashion-and-retail-ltd"],
                ]),
             uc("Factory Risk Monitoring", "Sourcing", "zplug", "T&A delays flagged before launch dates are missed.",
                problem="A slipped fabric date or a stalled cut cascades into a missed launch window, but time-and-action status lives in factory emails and spreadsheets, so the risk is seen only once the order is already late.",
                who="Sourcing & Production",
                how="PLM milestones and factory WIP land through Lakeflow onto Delta Lake at operational latency in Lakehouse//RT, and the Factory Tracker flags delay risk by PO before air-freight is forced.",
                comps=["Factory Tracker", "Fast React Plan", "Centric PLM", "Lakehouse//RT", "Lakeflow", "Delta Lake"]),
             uc("Sustainable Sourcing", "ESG", "gavel", "Preferred materials and audited factories scored at style level.",
                problem="Buyers pick materials and factories with no live view of sustainability scores or audit status, so ESG claims and due-diligence rules are reconciled after the buy instead of shaping it.",
                who="Sourcing & Production",
                how="Higg material scores and factory disclosures are conformed under Unity Catalog and joined to style records, scored at style level and read in AI/BI so sourcing sees the ESG picture before commitment.",
                comps=["Higg Index MSI", "Open Supply Hub", "Unity Catalog", "AI/BI", "Delta Lake"]),
             uc("Omnichannel Fulfillment", "Operations", "stream", "Ship-from-store and BOPIS against unified inventory.",
                problem="Store and warehouse stock sit in separate systems, so ship-from-store and BOPIS promise inventory that isn't there and cancel orders a nearby store could have filled.",
                who="Planning & Allocation",
                how="POS, e-commerce and WMS feeds are unified on Delta Lake in near real time through Lakehouse//RT, exposing one governed inventory position that fulfilment routing and store Apps read.",
                comps=["Blue Yonder WMS", "Shopify Plus", "Lakehouse//RT", "Delta Lake", "Apps"]),
             uc("Clienteling & CRM", "Retail", "custlake", "High-value customers recognized in every channel.",
                problem="A shopper is a loyalty number in-store, an email in DTC and a cookie online, so associates cannot recognise the high-value customer in front of them and personalization stays generic.",
                who="Digital & CRM",
                how="Store, DTC and loyalty identities are resolved on Delta Lake under Unity Catalog into CustomerLake profiles, and the Clienteling App serves associate recommendations over Lakebase.",
                comps=["Clienteling App", "Salesforce Commerce Cloud", "CustomerLake", "Unity Catalog", "Lakebase"],
                stories=[
                    ["Skechers personalizes experiences for every customer", "https://www.databricks.com/customers/skechers"],
                    ["MUSINSA uses data to inspire smart fashion choices", "https://www.databricks.com/customers/musinsa"],
                    ["Myntra delivers personalized shopping experiences", "https://www.databricks.com/customers/myntra"],
                ]),
             uc("Wholesale Chargebacks", "Finance", "erp", "Deductions reconciled to shipment and compliance data.",
                problem="Department stores deduct for late, short or non-compliant shipments, and disputing a chargeback means matching it by hand to the PO, ASN and routing rules across systems, so most are written off.",
                who="Brand President & CFO",
                how="Shipment, order and compliance data are conformed on Delta Lake and reconciled in AI/BI against the Wholesale Partner Mart, surfacing which deductions are valid and which to dispute.",
                comps=["Wholesale Partner Mart", "SAP S/4HANA Retail", "AI/BI", "Delta Lake", "Unity Catalog"]),
             uc("3D Sample Reduction", "Design", "apps", "Physical samples replaced by digital fit approval.",
                problem="Every style spins up multiple physical protos shipped between design and factories, adding weeks and cost to the calendar and a material footprint the sustainability targets can no longer absorb.",
                who="Sourcing & Production",
                how="3D samples and material libraries from CLO 3D and Adobe Substance are governed as assets under Unity Catalog beside PLM style records, so fit is approved digitally before a physical proto is cut.",
                comps=["CLO 3D", "Adobe Substance", "Centric PLM", "Unity Catalog", "Delta Lake"]),
             uc("Inventory Right-Sizing", "Finance", "chart", "WOS targets by category before excess ownership builds.",
                problem="Excess inventory ties up cash and forces end-of-season markdown, but weeks-of-supply is read on a lag from stale reports, so overbuys are visible only once the ownership is already on the books.",
                who="Brand President & CFO",
                how="Sell-through and on-hand across channels are conformed on Delta Lake into certified Metric Views, so weeks-of-supply by category is watched in AI/BI and Genie One before excess builds.",
                comps=["Infor CloudSuite Fashion", "AI/BI", "Genie One", "Delta Lake", "Unity Catalog"],
                stories=[
                    ["ABFRL anticipates the right product mix and quantities on Databricks", "https://www.databricks.com/customers/aditya-birla-fashion-and-retail-ltd"],
                ])],
        ),
        "sources": {
            "centric-plm": {"t": "Centric PLM", "u": "https://www.centricsoftware.com/"},
            "adobe-substance": {"t": "Adobe Substance 3D", "u": "https://www.adobe.com/products/substance3d.html"},
            "clo-3d": {"t": "CLO 3D", "u": "https://www.clo3d.com/"},
            "infor-fashion": {"t": "Infor CloudSuite Fashion", "u": "https://www.infor.com/industries/fashion"},
            "sap-retail": {"t": "SAP S/4HANA Retail", "u": "https://www.sap.com/industries/retail.html"},
            "blue-yonder-wms": {"t": "Blue Yonder WMS", "u": "https://blueyonder.com/solutions/warehouse-management"},
            "shopify": {"t": "Shopify Plus", "u": "https://www.shopify.com/plus"},
            "sf-commerce": {"t": "Salesforce Commerce Cloud", "u": "https://www.salesforce.com/commerce/"},
            "oracle-xstore": {"t": "Oracle Xstore", "u": "https://www.oracle.com/retail/"},
            "lectra": {"t": "Lectra", "u": "https://www.lectra.com/"},
            "gerber": {"t": "Gerber Technology", "u": "https://gerbertechnology.com/"},
            "fast-react": {"t": "Fast React", "u": "https://www.fastreact.com/"},
            "higg": {"t": "Higg Index", "u": "https://higg.com/"},
            "textile-exchange": {"t": "Textile Exchange", "u": "https://textileexchange.org/"},
            "edited": {"t": "Edited", "u": "https://edited.com/"},
            "wgsn": {"t": "WGSN", "u": "https://www.wgsn.com/"},
            "opensupplyhub": {"t": "Open Supply Hub", "u": "https://www.opensupplyhub.org/"},
        },
    },
}
