import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_ADVERTISING = {
    'advertising': {
        "label": "Advertising",
        "blurb": "Media buying, campaign delivery, audience targeting, brand safety, and cross-channel attribution across linear, digital, and retail media.",
        "medallion": medallion(
            "Raw ad server and partner logs",
            "Impression, click, conversion and spend events from DSPs, ad servers and clean rooms, landed exactly as received so a bid or a view can be replayed for audit.",
            "Conformed campaigns and audiences",
            "Campaigns, line items, creatives and audience segments resolved into single entities across platforms, with identity graphs stitched and frequency caps reconciled.",
            "ROAS, reach and attribution",
            "Contracted products the media and finance teams run on: ROAS and CPA by channel, incremental lift, reach and frequency, and brand safety incident rates.",
        ),
        "rails": {
            "src": [
                {
                    "box": "Ad Platforms & DSP",
                    "ic": "market",
                    "tiles": [
                        tile(
                            "Google Campaign Manager",
                            "erp",
                            "Campaign trafficking, creative rotation and delivery reporting across display and video inventory.",
                            "google-cm360",
                            cat="Ad Server / Campaign Management",
                            what="Campaign trafficking, creative rotation and delivery reporting across display and video inventory.",
                            users="Ad operations and Media planning teams.",
                            data_out=data_out(
                                batch=flow(["structured", "semi-structured"], "5-50 GB/day delivery logs", "Hourly"),
                                stream=flow(["semi-structured"], "1-10k impression events/sec", "Continuous")),
                        ),
                        tile(
                            "The Trade Desk",
                            "market",
                            "Programmatic buying, audience segments and bid stream across open web and CTV.",
                            "trade-desk",
                            cat="Demand-Side Platform (DSP)",
                            what="Programmatic buying, audience segments and bid stream across open web and CTV.",
                            users="Programmatic trading and Performance marketing teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "5-20 GB/day spend + delivery", "Hourly"),
                                stream=flow(["semi-structured"], "50k-500k bid events/sec", "Continuous")),
                        ),
                        tile(
                            "Meta Ads Manager",
                            "partner",
                            "Paid social campaigns, creative variants and conversion events from Meta properties.",
                            "meta-ads",
                            cat="Paid Social Platform",
                            what="Paid social campaigns, creative variants and conversion events from Meta properties.",
                            users="Paid social and Performance marketing teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "1-5 GB/day", "Hourly"),
                                stream=flow(["semi-structured"], "100s of conversion events/sec", "Continuous")),
                        ),
                        tile(
                            "Amazon Ads",
                            "product",
                            "Sponsored products, brands and display across retail media networks.",
                            "amazon-ads",
                            cat="Retail Media Network",
                            what="Sponsored products, brands and display across retail media networks.",
                            users="Retail media and Commerce marketing teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "1-10 GB/day", "Daily")),
                        ),
                    ],
                },
                {
                    "box": "SSP & Inventory",
                    "ic": "stream",
                    "tiles": [
                        tile(
                            "Google Ad Manager",
                            "stream",
                            "Publisher ad serving, yield management and direct-sold inventory for owned media.",
                            "google-ad-manager",
                            cat="Publisher Ad Server / SSP",
                            what="Publisher ad serving, yield management and direct-sold inventory for owned media.",
                            users="Publisher yield and Ad operations teams.",
                            data_out=data_out(
                                stream=flow(["semi-structured"], "10-100k ad requests/sec", "Continuous")),
                        ),
                        tile(
                            "Magnite SSP",
                            "market",
                            "Supply-side auction data, deal IDs and publisher yield across CTV and open web.",
                            "magnite",
                            cat="Supply-Side Platform (SSP)",
                            what="Supply-side auction data, deal IDs and publisher yield across CTV and open web.",
                            users="Publisher yield and Programmatic teams.",
                            data_out=data_out(
                                stream=flow(["semi-structured"], "50k-500k auction events/sec", "Continuous")),
                        ),
                        tile(
                            "Index Exchange",
                            "api",
                            "Header bidding and private marketplace bid requests for premium inventory.",
                            "index-exchange",
                            cat="Ad Exchange / Header Bidding",
                            what="Header bidding and private marketplace bid requests for premium inventory.",
                            users="Programmatic and Publisher yield teams.",
                            data_out=data_out(
                                stream=flow(["semi-structured"], "50k-500k bid requests/sec", "Continuous")),
                        ),
                    ],
                },
                {
                    "box": "CRM & Identity",
                    "ic": "custlake",
                    "tiles": [
                        tile(
                            "Salesforce Marketing Cloud",
                            "custlake",
                            "Email, journey orchestration and first-party audience lists for activation.",
                            "sf-marketing-cloud",
                            cat="Marketing Automation",
                            what="Email, journey orchestration and first-party audience lists for activation.",
                            users="CRM marketing and Audience operations teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "0.5-2 GB/day", "Hourly"),
                                stream=flow(["semi-structured"], "tens of engagement events/sec", "Continuous")),
                        ),
                        tile(
                            "Adobe Experience Platform",
                            "custlake",
                            "Real-time customer profiles, segments and consent state for cross-channel targeting.",
                            "adobe-aep",
                            cat="Customer Data Platform (CDP)",
                            what="Real-time customer profiles, segments and consent state for cross-channel targeting.",
                            users="Audience operations and Performance marketing teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "1-5 GB/day profiles + segments", "Hourly"),
                                stream=flow(["semi-structured"], "100s-1000s of profile events/sec", "Continuous")),
                        ),
                        tile(
                            "LiveRamp RampID",
                            "partner",
                            "Identity resolution and onboarding for privacy-safe audience matching.",
                            "liveramp",
                            cat="Identity Resolution",
                            what="Identity resolution and onboarding for privacy-safe audience matching.",
                            users="Audience operations and Data science teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "1-10 GB/day identity graphs", "Daily")),
                        ),
                    ],
                },
                {
                    "box": "Measurement & Safety",
                    "ic": "chart",
                    "tiles": [
                        tile(
                            "Nielsen ONE",
                            "chart",
                            "Cross-media reach and frequency measurement across linear and digital.",
                            "nielsen-one",
                            cat="Audience Measurement / Ratings",
                            what="Cross-media reach and frequency measurement across linear and digital.",
                            users="Media planning and Investment teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "1-5 GB/day panel + ratings", "Daily")),
                        ),
                        tile(
                            "IAS Brand Safety",
                            "gavel",
                            "Viewability, invalid traffic and brand suitability scoring on every impression.",
                            "ias",
                            cat="Ad Verification / Brand Safety",
                            what="Viewability, invalid traffic and brand suitability scoring on every impression.",
                            users="Brand safety and Ad verification teams.",
                            data_out=data_out(
                                stream=flow(["semi-structured"], "10-100k verification events/sec", "Continuous")),
                        ),
                        tile(
                            "AppsFlyer MMP",
                            "observ",
                            "Mobile attribution, SKAdNetwork postbacks and fraud signals.",
                            "appsflyer",
                            cat="Mobile Measurement Partner (MMP)",
                            what="Mobile attribution, SKAdNetwork postbacks and fraud signals.",
                            users="Performance marketing and Fraud operations teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "0.5-2 GB/day", "Hourly"),
                                stream=flow(["semi-structured"], "100s-1000s of postbacks/sec", "Continuous")),
                        ),
                        tile(
                            "Kantar Brand Lift",
                            "ztarget",
                            "Survey-based brand lift studies tied to exposed and control cohorts.",
                            "kantar",
                            cat="Brand Lift / Survey Measurement",
                            what="Survey-based brand lift studies tied to exposed and control cohorts.",
                            users="Brand and Marketing analytics teams.",
                            data_out=data_out(
                                batch=flow(["structured"], "0.1-0.5 GB/day survey results", "Daily")),
                        ),
                    ],
                },
                {
                    "box": "Creative & DAM",
                    "ic": "product",
                    "tiles": [
                        tile(
                            "Bynder DAM",
                            "product",
                            "Creative assets, rights metadata and version history for trafficking.",
                            "bynder",
                            cat="Digital Asset Management (DAM)",
                            what="Creative assets, rights metadata and version history for trafficking.",
                            users="Creative operations and Ad operations teams.",
                            data_out=data_out(
                                batch=flow(["semi-structured", "unstructured"], "0.5-3 GB/day assets + metadata", "Daily")),
                        ),
                        tile(
                            "Celtra Creative",
                            "apps",
                            "Dynamic creative optimization variants and performance by element.",
                            "celtra",
                            cat="Creative Management / DCO",
                            what="Dynamic creative optimization variants and performance by element.",
                            users="Creative operations and Performance marketing teams.",
                            data_out=data_out(
                                batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Hourly")),
                        ),
                    ],
                },
                fed_group(
                    "Finance & Billing Mart",
                    "Agency billing, rebates and client invoicing marts left in place and queried under Unity Catalog.",
                    cat="Finance Data Warehouse",
                    what="Agency billing, rebates and client invoicing marts kept in existing warehouses and queried in place through federation.",
                    users="Finance, Billing and Rebate teams.",
                    data_out=data_out(
                        batch=flow(["structured"], "TB-scale billing history", "Queried on demand (federated)")),
                ),
            ],
            "ing": ing_rail(
                [
                    tile(
                        "IAB Tech Lab OpenRTB",
                        "api",
                        "Bid request and response logs from programmatic exchanges, parsed into structured auction events.",
                        "iab-openrtb",
                        cat="Programmatic Auction Logs (OpenRTB)",
                        what="Bid request and response logs from programmatic exchanges, parsed into structured auction events.",
                        users="Programmatic trading and Data science teams.",
                        data_out=data_out(
                            stream=flow(["semi-structured"], "100k-1M bid events/sec", "Continuous")),
                    ),
                    tile(
                        "LiveRamp Data Clean Room",
                        "partner",
                        "Privacy-safe overlap and attribution queries against retailer and publisher partners.",
                        "liveramp-cleanroom",
                        cat="Data Clean Room",
                        what="Privacy-safe overlap and attribution queries against retailer and publisher partners.",
                        users="Audience operations and Measurement teams.",
                        data_out=data_out(
                            batch=flow(["structured"], "1-10 GB/day overlap results", "Daily")),
                    ),
                    tile(
                        "Comscore Campaign Ratings",
                        "chart",
                        "Digital campaign delivery and demographic composition for guaranteed buys.",
                        "comscore",
                        cat="Digital Audience Measurement",
                        what="Digital campaign delivery and demographic composition for guaranteed buys.",
                        users="Media planning and Investment teams.",
                        data_out=data_out(
                            batch=flow(["structured"], "0.5-3 GB/day", "Daily")),
                    ),
                ]
            ),
            "ppl": ppl2(
                [
                    biz("CMO & CFO Office", "Genie One",
                        "The CMO on brand share, working-media ratio and ROAS by channel; the CFO on agency fee efficiency and cost per acquisition.",
                        [["Genie One", "Ask what last quarter's ROAS was by channel without booking analyst time."],
                         ["AI/BI", "Reach, frequency and ROAS on certified Metric Views."],
                         ["Unity Catalog", "One definition of spend and conversion across platforms."]],
                        sub=[
                            ["CMO", "brand share, working-media ratio and whether ROAS is improving quarter on quarter."],
                            ["CFO", "agency fee efficiency, cost per acquisition and where working media is leaking."],
                            ["VP Marketing Analytics", "one certified read on spend, reach and conversion across every platform."],
                        ],
                        ucs=["Cross-Channel Attribution", "Brand Lift Measurement", "Agency Reconciliation"]),
                    biz("Media Planning", "AI/BI",
                        "Channel mix, flighting and budget allocation across linear, digital and retail media, judged on reach, effective CPM and incremental lift.",
                        [["Media Mix Model", "Scenario planning on incremental lift by channel."],
                         ["AI/BI", "Reach curves and budget pacing on governed data."]],
                        sub=[
                            ["Media Planning Director", "the channel mix and flighting that hit reach and lift at the lowest effective CPM."],
                            ["Investment Lead", "upfront commitments, guarantees and the trade between reach and frequency."],
                            ["Retail Media Strategist", "where retail media budget moves sales versus subsidising the retailer."],
                        ],
                        ucs=["Frequency Management", "Retail Media Activation", "Cross-Channel Attribution"]),
                    biz("Performance Marketing", "Model Serving",
                        "Bid management, audience targeting and creative testing across programmatic and paid social, held to CPA, ROAS and viewability targets.",
                        [["Bid Optimizer", "Real-time bid adjustments against CPA and ROAS targets."],
                         ["Model Serving", "Conversion propensity scored in the bid path."]],
                        sub=[
                            ["Programmatic Trader", "bid modifiers, pacing and viewability against CPA and ROAS targets."],
                            ["Paid Social Lead", "creative testing and audience matching across Meta and social channels."],
                            ["Audience Ops", "segment build, suppression and privacy-safe matching for activation."],
                        ],
                        ucs=["Programmatic Bid Optimization", "Audience Propensity", "Creative DCO"]),
                    biz("Brand Safety", "Lakehouse//RT",
                        "Suitability monitoring, invalid-traffic filtering and blocklists, tracked on IVT rate, viewability and brand-safety incident rate.",
                        [["Brand Safety Console", "Incidents flagged before scale is reached."],
                         ["Lakehouse//RT", "Live suitability scores at auction latency."]],
                        sub=[
                            ["Brand Safety Lead", "suitability, blocklists and keeping the brand off unsafe inventory."],
                            ["Ad Verification Analyst", "viewability, IVT rate and the incidents that reach scale."],
                            ["Fraud Operations", "spoofed inventory and bot traffic before it bills or skews models."],
                        ],
                        ucs=["Fraud & IVT Detection", "Programmatic Bid Optimization"]),
                    biz("Finance & Billing", "AI/BI",
                        "Agency reconciliation, makegoods and client billing, watching over-pacing, rebate accruals and margin on booked media.",
                        [["AI/BI", "Spend reconciliation and variance to plan."],
                         ["Genie One", "Ask which campaigns are over-pacing without a finance pull."]],
                        sub=[
                            ["Billing Manager", "client invoicing, makegoods and reconciling delivery to the IO."],
                            ["Rebate Analyst", "agency rebate accruals and volume commitments across platforms."],
                            ["Revenue Controller", "over-pacing, margin on booked media and variance to plan."],
                        ],
                        ucs=["Agency Reconciliation", "Cross-Channel Attribution"]),
                ],
                [
                    biz("Data Engineers", "Lakeflow",
                        "Land the DSP bid stream, ad-server impression logs, clean-room overlaps and CRM audiences; own Bronze to Silver and the pager when pacing tables stall.",
                        [["Lakeflow Connect", "Managed connectors for ad servers, DSPs and SaaS marketing sources."],
                         ["Lakeflow Designer", "Declarative pipelines with expectations on impression and conversion feeds."],
                         ["Lakewatch", "Freshness on the pacing tables planners refresh through the day."]],
                        sub=[
                            ["Pipeline Engineer", "Bronze-to-Silver on the bid stream, impression logs and CRM audiences."],
                            ["Streaming Ingest", "the DSP and ad-server feeds that must not drop during a flight."],
                            ["DataOps On-call", "the pager when the pacing tables planners refresh all day stall."],
                        ],
                        ucs=["Programmatic Bid Optimization", "Cross-Channel Attribution", "Privacy-Safe Clean Rooms"]),
                    biz("Data Scientists", "MLflow",
                        "Bid-optimisation, conversion-propensity, lookalike and media-mix models, and whether they still hold once cookies deprecate and channels shift.",
                        [["Feature Store", "Audience and context features read identically in training and the bidder."],
                         ["MLflow", "Every bid and lift experiment tracked for audit and reproduction."],
                         ["Model Serving", "Bid and propensity models scored inside the auction path."]],
                        sub=[
                            ["Bid & Propensity Modeler", "conversion propensity and bid models that hold in the auction."],
                            ["Media Mix Scientist", "incremental lift and budget allocation across channels."],
                            ["MLOps", "reproducible training and serving as cookies deprecate and channels shift."],
                        ],
                        ucs=["Programmatic Bid Optimization", "Audience Propensity", "Brand Lift Measurement"]),
                    biz("App Developers", "Apps",
                        "Ship the campaign command, audience-studio and brand-safety apps the media and finance teams work in, hosted next to governed delivery data.",
                        [["Apps", "Pacing and audience screens with no separate web tier to secure."],
                         ["Lakebase", "Serverless Postgres for pacing state and blocklist writes."],
                         ["Agent Bricks", "Agents that draft budget shifts against governed tools."]],
                        sub=[
                            ["Full-stack App Dev", "the pacing, audience and brand-safety screens teams work in."],
                            ["Frontend Engineer", "fast, governed views over delivery and audience data."],
                            ["Platform DevOps", "hosting apps next to governed data with no separate web tier."],
                        ],
                        ucs=["Fraud & IVT Detection", "Audience Propensity", "Agency Reconciliation"]),
                ],
            ),
            "cons": cons_rail(
                [
                    {
                        "box": "BI & Productivity",
                        "ic": "chart",
                        "from": "bi",
                        "tiles": [
                            tile(
                                "Tableau / Power BI",
                                "chart",
                                "Executive and client dashboards against serverless SQL with Unity Catalog permissions.",
                            ),
                            tile(
                                "Microsoft Teams",
                                "chat",
                                "Genie in Teams for campaign performance answers in the channel planners already work in.",
                            ),
                            tile(
                                "Notebooks & IDEs",
                                "notebook",
                                "Analyst notebooks and IDEs against governed audience and delivery data.",
                            ),
                        ],
                    },
                    {
                        "box": "Activation & Partners",
                        "ic": "partner",
                        "tiles": [
                            tile(
                                "DSP Bid Stream API",
                                "api",
                                "Optimized audiences and bid modifiers pushed back to The Trade Desk and DV360.",
                                "trade-desk",
                            ),
                            tile(
                                "Retail Media Partners",
                                "partner",
                                "Audience segments shared to Amazon, Walmart and Instacart via clean room.",
                                "amazon-ads",
                            ),
                            tile(
                                "Publisher PMP Deals",
                                "globe",
                                "Private marketplace packages activated from unified audience definitions.",
                            ),
                        ],
                    },
                    {
                        "box": "Operational Writeback",
                        "ic": "opdb",
                        "tiles": [
                            tile(
                                "Budget Pacing Alerts",
                                "gauge",
                                "Flight-level pacing adjustments written to trafficking systems before overspend.",
                            ),
                            tile(
                                "Creative Trafficking",
                                "product",
                                "Winning creative variants pushed to ad servers for rotation.",
                                "google-cm360",
                            ),
                            tile(
                                "Blocklist Updates",
                                "gavel",
                                "Publisher and placement blocks synced to DSPs after safety incidents.",
                                "ias",
                            ),
                        ],
                    },
                    {
                        "box": "Regulatory & Reporting",
                        "ic": "gavel",
                        "tiles": [
                            tile(
                                "Ad Transparency Reports",
                                "gavel",
                                "Political and issue ad disclosures filed from governed delivery tables.",
                            ),
                            tile(
                                "Client Delivery Reports",
                                "share",
                                "Guaranteed and bonus delivery reconciled for agency client billing.",
                            ),
                        ],
                    },
                    {
                        "box": "Published Products",
                        "ic": "product",
                        "tiles": [
                            tile(
                                "Data Products",
                                "product",
                                "Audience and performance products published in Unity Catalog Domains.",
                            ),
                            tile(
                                "Sharing Recipients",
                                "share",
                                "Agency and brand partners reading live tables via Delta Sharing.",
                            ),
                        ],
                    },
                ],
                genie_spaces=[
                    genie("Campaign Performance", "Ask about spend, delivery and ROAS across every active flight in plain language.",
                          feeds=["Google Campaign Manager", "The Trade Desk", "Meta Ads Manager", "ROAS, reach and attribution"],
                          teams=["Performance Marketing", "Media Planning", "Data Scientists"],
                          questions=[
                              "Which flights will miss their guarantee before the IO closes?",
                              "What is ROAS by channel this quarter versus last?",
                              "Which campaigns are over-pacing right now?",
                              "Where is working media leaking across platforms?",
                              "Which creatives are driving the best CPA this week?"]),
                    genie("Audience & Identity", "Explore segments, overlap and match rates on governed first-party data.",
                          feeds=["Adobe Experience Platform", "LiveRamp RampID", "LiveRamp Data Clean Room", "Conformed campaigns and audiences"],
                          teams=["Performance Marketing", "Media Planning", "Data Engineers"],
                          questions=[
                              "What is our match rate with each retail media partner?",
                              "Which lookalike segments convert best right now?",
                              "How much audience overlap exists across our top campaigns?",
                              "Which segments should be suppressed to cut waste?",
                              "What consent state applies to each activation audience?"]),
                    genie("Brand Safety & Fraud", "Answer viewability, IVT and suitability questions on live delivery data.",
                          feeds=["IAS Brand Safety", "IAB Tech Lab OpenRTB", "AppsFlyer MMP", "ROAS, reach and attribution"],
                          teams=["Brand Safety", "Performance Marketing", "Data Scientists"],
                          questions=[
                              "What is our invalid-traffic rate by exchange today?",
                              "Which placements breached brand-suitability thresholds?",
                              "Where is viewability below the campaign floor?",
                              "Which publishers show spoofed-inventory patterns?",
                              "What spend is exposed to unsafe inventory right now?"]),
                    genie("Finance & Reconciliation", "Ask about pacing, makegoods and margin against contracted IO terms.",
                          feeds=["Finance & Billing Mart", "Google Campaign Manager", "Comscore Campaign Ratings", "ROAS, reach and attribution"],
                          teams=["Finance & Billing", "CMO & CFO Office", "Media Planning"],
                          questions=[
                              "Which campaigns are over-pacing against the IO?",
                              "What makegood liability is accruing this quarter?",
                              "How do agency rebate accruals compare to plan?",
                              "Where is margin leaking on booked media?",
                              "What is variance to plan by client this month?"]),
                ],
                dashboards=[
                    dashboard("Campaign Performance", "Spend, delivery and ROAS across every active flight on certified views.",
                              kpis=["ROAS", "CPA", "Delivery vs guarantee", "Pacing", "Working-media ratio"],
                              teams=["Performance Marketing", "Media Planning", "CMO & CFO Office"]),
                    dashboard("Attribution & Reach", "Cross-channel attribution, reach and frequency on governed identity graphs.",
                              kpis=["Multi-touch credit", "Reach", "Frequency", "Incremental lift", "Cross-channel CPA"],
                              teams=["CMO & CFO Office", "Media Planning", "Data Scientists"]),
                    dashboard("Brand Safety & Quality", "Viewability, IVT and suitability on live delivery data.",
                              kpis=["Viewability", "IVT rate", "Brand-safety incidents", "Suitability score", "Blocked spend"],
                              teams=["Brand Safety", "Performance Marketing", "Data Scientists"]),
                    dashboard("Finance & Reconciliation", "Pacing, makegoods and margin reconciled to contracted IO terms.",
                              kpis=["Over-pacing", "Makegood liability", "Rebate accruals", "Margin on booked media", "Variance to plan"],
                              teams=["Finance & Billing", "CMO & CFO Office", "App Developers"]),
                ],
            ),
        },
        "top": top_band(
            [
                app(
                    "Campaign Command Center",
                    "Cross-channel pacing",
                    "gauge",
                    "Live spend, delivery and ROAS across every active flight, flagging flights that will miss guarantee before the IO closes.",
                ),
                app(
                    "Audience Studio",
                    "Segment builder",
                    "custlake",
                    "First-party segments composed from CRM, web and retail signals, ready for activation.",
                ),
                app(
                    "Brand Safety Console",
                    "Suitability monitoring",
                    "gavel",
                    "Incidents surfaced by severity with one-click blocklist propagation to buying platforms.",
                ),
                app(
                    "Media Mix Workbench",
                    "Channel planning",
                    "chart",
                    "Incremental lift scenarios by channel before the annual plan is locked.",
                ),
            ],
            [
                uc(
                    "Cross-Channel Attribution",
                    "Measurement",
                    "chart",
                    "Credit assigned across linear, digital and retail touchpoints using governed identity graphs.",
                    problem="Every platform claims the same conversion, so credit is double-counted and last-click still wins, and no one sees the true contribution of each touch across linear, digital and retail.",
                    who="CMO & CFO Office",
                    how="Impression, click and conversion events land through Lakeflow, identity is resolved on a governed graph, and multi-touch credit is scored in Model Serving and read in the Campaign Command Center.",
                    comps=["Campaign Command Center", "LiveRamp RampID", "Unity Catalog", "AI/BI", "Model Serving"],
                    stories=[
                        ["Comcast Advertising powers ad campaign success with predictive insights", "https://www.databricks.com/customers/comcast/databricks-apps"],
                        ["Publicis Groupe delivers real-time personalized campaigns", "https://www.databricks.com/customers/publicis-groupe"],
                    ],
                ),
                uc(
                    "Programmatic Bid Optimization",
                    "Performance",
                    "market",
                    "Bids adjusted in real time against CPA, ROAS and incrementality targets.",
                    problem="Bids are set on stale rules and yesterday's reports, so budget floods low-value inventory and CPA and ROAS targets slip while the auction has already moved on.",
                    who="Performance Marketing",
                    how="OpenRTB bid logs stream into Lakehouse//RT, propensity features come from Feature Store, and bid modifiers are scored in Model Serving and pushed to The Trade Desk in the auction path.",
                    comps=["The Trade Desk", "IAB Tech Lab OpenRTB", "Model Serving", "Lakehouse//RT", "Feature Store"],
                    stories=[
                        ["The Trade Desk scales contextual targeting NLP with Databricks", "https://www.databricks.com/customers/thetradedesk/data-science"],
                        ["Agentic AI and the future of advertising", "https://www.databricks.com/blog/agentic-ai-and-future-advertising-why-next-frontier-runs-unified-data"],
                    ],
                ),
                uc(
                    "Audience Propensity",
                    "Targeting",
                    "custlake",
                    "Lookalike and suppression audiences scored from first-party and partner signals.",
                    problem="First-party signals sit in disconnected CRM, web and loyalty stores, so lookalike and suppression audiences are built from stale exports and miss the people most likely to convert.",
                    who="Performance Marketing",
                    how="CRM and web signals conform on Delta Lake, features land in Feature Store, and propensity and lookalike models scored in Model Serving compose segments in the Audience Studio for activation.",
                    comps=["Audience Studio", "Adobe Experience Platform", "LiveRamp RampID", "Feature Store", "Model Serving"],
                    stories=[
                        ["Conde Nast unifies data for personalized experiences", "https://www.databricks.com/customers/conde_nast"],
                        ["Publicis Groupe delivers real-time personalized campaigns", "https://www.databricks.com/customers/publicis-groupe"],
                    ],
                ),
                uc(
                    "Brand Lift Measurement",
                    "Brand",
                    "ztarget",
                    "Exposed versus control cohorts tied to survey lift and delivery logs.",
                    problem="Exposed and control cohorts are stitched by hand from survey vendors and delivery logs, so brand lift lands weeks late and cannot be tied cleanly to who actually saw the campaign.",
                    who="CMO & CFO Office",
                    how="Delivery logs and survey panels conform under Unity Catalog, exposed versus control cohorts are matched, and lift is estimated in Model Serving and read in the Media Mix Workbench.",
                    comps=["Media Mix Workbench", "Kantar Brand Lift", "Nielsen ONE", "Model Serving", "AI/BI"],
                ),
                uc(
                    "Frequency Management",
                    "Reach",
                    "stream",
                    "Cross-platform frequency caps enforced before waste accumulates.",
                    problem="Each platform caps frequency only against its own impressions, so the same household is hit far past the point of return and spend is wasted on people already saturated.",
                    who="Media Planning",
                    how="Cross-platform delivery lands through Lakeflow, identity is unified on a graph, and household frequency is reconciled on Delta Lake and enforced from the Campaign Command Center.",
                    comps=["Campaign Command Center", "The Trade Desk", "LiveRamp RampID", "Lakehouse//RT", "Delta Lake"],
                    stories=[
                        ["Agentic AI and the future of advertising", "https://www.databricks.com/blog/agentic-ai-and-future-advertising-why-next-frontier-runs-unified-data"],
                    ],
                ),
                uc(
                    "Retail Media Activation",
                    "Commerce",
                    "product",
                    "Sponsored search and display tuned against on-shelf availability.",
                    problem="Retail media runs in walled gardens, so brands buy sponsored placements blind to on-shelf availability and cannot tie the spend back to the sales it actually moved.",
                    who="Media Planning",
                    how="Retailer and sales signals join first-party data on Delta Lake, segments are built in Audience Studio, and audiences are shared to Amazon Ads via clean rooms with results read in AI/BI.",
                    comps=["Audience Studio", "Amazon Ads", "LiveRamp Data Clean Room", "OpenSharing", "AI/BI"],
                    stories=[
                        ["Magnite and Databricks transform ad data activation", "https://www.databricks.com/blog/magnite-and-databricks-announce-new-partnership-transform-ad-data-activation"],
                    ],
                ),
                uc(
                    "Creative DCO",
                    "Creative",
                    "apps",
                    "Dynamic elements swapped by audience segment and performance.",
                    problem="Creative variants multiply faster than anyone can test them, so winning combinations are guessed at and underperforming assets keep serving long after the data would have killed them.",
                    who="Performance Marketing",
                    how="Creative and performance-by-element data conform on Delta Lake, and AI Functions and Model Serving rank variants by segment so the best combinations rotate to the ad server.",
                    comps=["Celtra Creative", "Bynder DAM", "Model Serving", "AI Functions", "Feature Store"],
                ),
                uc(
                    "Fraud & IVT Detection",
                    "Quality",
                    "gavel",
                    "Invalid traffic removed before it bills or pollutes attribution.",
                    problem="Invalid traffic and spoofed inventory drain budgets and poison attribution, and by the time verification reports flag it the money is spent and the models are already skewed.",
                    who="Brand Safety",
                    how="OpenRTB and delivery events stream into Lakehouse//RT, anomaly models score traffic in Model Serving, and confirmed IVT is filtered and surfaced by severity in the Brand Safety Console.",
                    comps=["Brand Safety Console", "IAS Brand Safety", "IAB Tech Lab OpenRTB", "Model Serving", "Lakehouse//RT"],
                ),
                uc(
                    "Agency Reconciliation",
                    "Finance",
                    "erp",
                    "Delivery, makegoods and rebates reconciled to contracted IO terms.",
                    problem="Delivery, makegoods and rebates are reconciled to insertion orders across spreadsheets and exports, so billing disputes drag on and margin leaks through over-pacing no one caught.",
                    who="Finance & Billing",
                    how="Delivery and spend from ad servers conform under Unity Catalog, are reconciled to contracted IO terms on Delta Lake, and variance is questioned in Genie One and tracked in AI/BI.",
                    comps=["Campaign Command Center", "Google Campaign Manager", "Genie One", "AI/BI", "Unity Catalog"],
                ),
                uc(
                    "Privacy-Safe Clean Rooms",
                    "Identity",
                    "partner",
                    "Overlap and attribution computed without raw PII leaving either party.",
                    problem="Overlap and attribution with retailers and publishers need matched records, but neither side will hand over raw PII, so measurement stalls in legal review and manual file swaps.",
                    who="Performance Marketing",
                    how="First-party data stays governed under Unity Catalog while overlap and attribution run in Audience Studio against partner data over OpenSharing, with no raw PII leaving either side.",
                    comps=["Audience Studio", "LiveRamp Data Clean Room", "Unity Catalog", "OpenSharing", "Delta Lake"],
                    stories=[
                        ["The Trade Desk and Databricks: secure identity collaboration in clean rooms", "https://www.databricks.com/blog/accelerating-secure-interoperable-identity-collaboration-trade-desk-and-databricks-partnership"],
                    ],
                ),
            ],
        ),
        "sources": {
            "google-cm360": {"t": "Google Campaign Manager 360", "u": "https://marketingplatform.google.com/about/campaign-manager-360/"},
            "trade-desk": {"t": "The Trade Desk", "u": "https://www.thetradedesk.com/"},
            "meta-ads": {"t": "Meta Ads Manager", "u": "https://www.facebook.com/business/tools/ads-manager"},
            "amazon-ads": {"t": "Amazon Ads", "u": "https://advertising.amazon.com/"},
            "google-ad-manager": {"t": "Google Ad Manager", "u": "https://admanager.google.com/"},
            "magnite": {"t": "Magnite SSP", "u": "https://www.magnite.com/"},
            "index-exchange": {"t": "Index Exchange", "u": "https://www.indexexchange.com/"},
            "sf-marketing-cloud": {"t": "Salesforce Marketing Cloud", "u": "https://www.salesforce.com/products/marketing-cloud/"},
            "adobe-aep": {"t": "Adobe Experience Platform", "u": "https://business.adobe.com/products/experience-platform/adobe-experience-platform.html"},
            "liveramp": {"t": "LiveRamp", "u": "https://liveramp.com/"},
            "nielsen-one": {"t": "Nielsen ONE", "u": "https://www.nielsen.com/solutions/nielsen-one/"},
            "ias": {"t": "Integral Ad Science", "u": "https://integralads.com/"},
            "appsflyer": {"t": "AppsFlyer", "u": "https://www.appsflyer.com/"},
            "kantar": {"t": "Kantar", "u": "https://www.kantar.com/"},
            "bynder": {"t": "Bynder DAM", "u": "https://www.bynder.com/"},
            "celtra": {"t": "Celtra", "u": "https://www.celtra.com/"},
            "iab-openrtb": {"t": "IAB OpenRTB", "u": "https://iabtechlab.com/standards/openrtb/"},
            "liveramp-cleanroom": {"t": "LiveRamp Data Collaboration", "u": "https://liveramp.com/data-collaboration/"},
            "comscore": {"t": "Comscore", "u": "https://www.comscore.com/"},
        },
    },
}
