import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_PROFESSIONAL_SERVICES = {
    "professional_services": {
        "label": "Professional Services",
        "blurb": "Consulting, agencies, accounting and audit, and engineering services: engagement delivery, consultant utilization, project margin, resourcing, pipeline and talent.",
        "medallion": medallion(
            "Raw engagement and time feeds",
            "Timesheets, project actuals, expenses and CRM opportunities from the PSA, finance and HR estates, landed exactly as received so a billed hour or a recognised dollar can always be replayed as it stood.",
            "Conformed engagement, person, client",
            "Engagements, consultants and clients resolved into single conformed entities across the PSA, CRM, finance and HR systems, with rate cards, cost rates and skills reconciled to one record.",
            "Utilization, margin, win-rate",
            "Contracted products leadership runs on: billable utilization and bench, engagement and practice margin, pipeline and win-rate, attrition and skills-to-demand coverage.",
        ),
        "rails": {
            "src": [
                {
                    "box": "PSA & Delivery",
                    "ic": "erp",
                    "tiles": [
                        tile("Kantata PSA", "erp", "Professional services automation: projects, resource plans, time and margin. The system of record for engagement delivery and billing.", "kantata",
                             cat="Professional Services Automation (PSA)",
                             what="System of record for engagement delivery and billing: projects, resource plans, time and margin.",
                             users="Delivery leads, resource managers and the PMO.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day", "Nightly batch + hourly deltas"),
                                 stream=flow(["semi-structured"], "tens of time and staffing events/sec", "Continuous CDC"))),
                        tile("NetSuite OpenAir", "sheet", "PSA for time capture, project accounting, utilization and invoicing across the engagement lifecycle.", "openair",
                             cat="Professional Services Automation (PSA)",
                             what="Handles time capture, project accounting, utilization and invoicing across the engagement lifecycle.",
                             users="Delivery, project accounting and billing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-6 GB/day", "Nightly batch + hourly deltas"))),
                        tile("Certinia PSA", "product", "Salesforce-native services automation linking opportunity, staffing, delivery and revenue on one record.", "certinia",
                             cat="Professional Services Automation (PSA)",
                             what="Salesforce-native services automation linking opportunity, staffing, delivery and revenue on one record.",
                             users="Practice leaders, delivery and revenue operations teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day", "Hourly / nightly sync"),
                                 stream=flow(["semi-structured"], "tens of engagement events/sec", "Continuous CDC"))),
                    ],
                },
                {
                    "box": "CRM & Pipeline",
                    "ic": "crm",
                    "tiles": [
                        tile("Salesforce Sales Cloud", "crm", "Accounts, opportunities and the sales pipeline, the source of proposals in flight and closed-won engagements.", "sfdc",
                             cat="CRM / Sales Pipeline",
                             what="Holds accounts, opportunities and the sales pipeline, the source of proposals in flight and closed-won engagements.",
                             users="Practice leaders, sector leads and business development.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-4 GB/day", "Hourly / nightly sync"),
                                 stream=flow(["semi-structured"], "tens of opportunity events/sec", "Continuous CDC"))),
                        tile("Dynamics 365 Sales", "crm", "Microsoft CRM pipeline, quotes and win/loss reasons feeding win-rate and bid analytics.", "dynamics",
                             cat="CRM / Sales Pipeline",
                             what="Microsoft CRM holding pipeline, quotes and win/loss reasons that feed win-rate and bid analytics.",
                             users="Business development, sector leads and sales operations.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-3 GB/day", "Hourly / nightly sync"))),
                        tile("HubSpot CRM", "crm", "Agency and boutique pipeline, deal stages and proposal tracking for the front of the funnel.", "hubspot",
                             cat="CRM / Sales Pipeline",
                             what="Agency and boutique CRM holding pipeline, deal stages and proposal tracking for the front of the funnel.",
                             users="Business development and marketing teams at agencies and boutiques.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Hourly sync"))),
                    ],
                },
                {
                    "box": "Finance & ERP",
                    "ic": "erp",
                    "tiles": [
                        tile("Workday Financials", "erp", "General ledger, project financials and revenue recognition for services firms.", "workday-fins",
                             cat="ERP / Financials Suite",
                             what="Runs the general ledger, project financials and revenue recognition as the finance system of record.",
                             users="CFO, controllership and revenue accounting teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "2-10 GB/day", "Nightly batch + monthly close"))),
                        tile("NetSuite ERP", "erp", "Services accounting, billing, revenue recognition and subcontractor payables.", "netsuite",
                             cat="ERP / Financials Suite",
                             what="Handles services accounting, billing, revenue recognition and subcontractor payables.",
                             users="Controllership, billing/AR and accounts payable teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-6 GB/day", "Nightly batch + close cycles"))),
                        tile("SAP S/4HANA", "erp", "Finance and project system core for large engineering and consulting firms.", "sap",
                             cat="ERP / Financials Suite",
                             what="Finance and project-system core for large engineering and consulting firms.",
                             users="Finance, project systems and controllership teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch + monthly close"))),
                    ],
                },
                {
                    "box": "Time & Billing",
                    "ic": "sheet",
                    "tiles": [
                        tile("Deltek Vantagepoint", "erp", "Project ERP for project-based firms: engagements, cost, time and billing for A&E and consulting.", "deltek",
                             cat="Project ERP / Time & Billing",
                             what="Project ERP covering engagements, cost, time and billing for architecture, engineering and consulting firms.",
                             users="Project accounting, delivery and billing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-6 GB/day", "Nightly batch + billing cycles"))),
                        tile("Replicon Time", "sheet", "Time capture and billing across billable and non-billable activity, the raw signal for utilization.", "replicon",
                             cat="Time Tracking & Billing System",
                             what="Captures time and billing across billable and non-billable activity, the raw signal behind utilization.",
                             users="Consultants, delivery leads and billing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-3 GB/day", "Nightly batch"),
                                 stream=flow(["semi-structured"], "tens of timecard events/sec", "Continuous"))),
                        tile("BigTime", "sheet", "Time, expense and billing for accounting and consulting practices, feeding WIP and invoicing.", "bigtime",
                             cat="Time Tracking & Billing System",
                             what="Handles time, expense and billing for accounting and consulting practices, feeding WIP and invoicing.",
                             users="Consultants, project accounting and billing teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.3-2 GB/day", "Nightly batch"))),
                    ],
                },
                {
                    "box": "Talent & Knowledge",
                    "ic": "people",
                    "tiles": [
                        tile("Workday HCM", "people", "Headcount, skills, compensation and attrition, the source of the talent and bench picture.", "workday-hcm",
                             cat="HCM / Talent Suite",
                             what="Holds headcount, skills, compensation and attrition, the source of the talent and bench picture.",
                             users="Chief People Officer, talent acquisition and L&D teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-4 GB/day", "Nightly batch + payroll cycles"))),
                        tile("Coupa Procurement", "docs", "Subcontractor and supplier spend, purchase orders and category commitments.", "coupa",
                             cat="Procurement / Spend Management",
                             what="Tracks subcontractor and supplier spend, purchase orders and category commitments across the firm.",
                             users="Procurement, finance and category management teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-3 GB/day", "Nightly batch"))),
                        tile("iManage Knowledge", "docs", "Documents, deliverables and matter/engagement knowledge, the corpus a GenAI assistant is grounded on.", "imanage",
                             cat="Knowledge / Document Management",
                             what="Holds documents, deliverables and engagement knowledge, the corpus a GenAI assistant is grounded on.",
                             users="Consultants, knowledge management and the GenAI assistant.",
                             data_out=data_out(
                                 batch=flow(["unstructured", "semi-structured"], "5-30 GB/day docs + metadata", "Nightly batch + hourly deltas"))),
                    ],
                },
                fed_group(
                    "Revenue & GL Mart",
                    "Audited revenue recognition and general-ledger marts left in the finance warehouse and queried in place under Unity Catalog, which avoids a second copy of the reported numbers.",
                    cat="Finance Data Warehouse / Marts",
                    what="Audited revenue-recognition and general-ledger marts kept in the finance warehouse and queried in place through federation.",
                    users="CFO, controllership and revenue accounting analysts.",
                    data_out=data_out(
                        batch=flow(["structured"], "TB-scale audited marts", "Queried on demand (federated)")),
                ),
            ],
            "ing": ing_rail(
                [
                    tile("SAP Concur Expense", "api", "Travel and expense line items joined to engagements for reimbursable and leakage analysis.", "concur",
                         cat="Travel & Expense Management",
                         what="Carries travel and expense line items joined to engagements for reimbursable and margin-leakage analysis.",
                         users="Finance, delivery leads and expense audit teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Daily feed"))),
                    tile("DocuSign CLM", "api", "Engagement contracts, SOWs and change orders parsed for rates, caps and milestones.", "docusign",
                         cat="Contract Lifecycle Management (CLM)",
                         what="Holds engagement contracts, SOWs and change orders parsed for rates, caps and milestones.",
                         users="Contract management, finance and delivery leads.",
                         data_out=data_out(
                             batch=flow(["structured", "unstructured"], "0.3-2 GB/day contracts + metadata", "Daily + on-signature"))),
                    tile("Jira & Confluence", "api", "Delivery tasks, sprints and engagement knowledge from technical and product engagements.", "atlassian",
                         cat="Delivery / Project Collaboration",
                         what="Carries delivery tasks, sprints and engagement knowledge from technical and product engagements.",
                         users="Delivery engineers, PMO and knowledge management teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "0.5-3 GB/day", "Hourly / nightly sync"),
                             stream=flow(["semi-structured"], "tens of issue events/sec", "Continuous (webhook)"))),
                ]
            ),
            "ppl": ppl2(
                [
                    biz("Firm Leadership", "Genie One",
                        "The Managing Partner and CEO on growth, utilization and firm profitability; the COO on delivery health and risk across the portfolio of engagements.",
                        [["Genie One", "Ask what utilization and margin ran last month across practices without booking analyst time."],
                         ["AI/BI", "Utilization, margin, pipeline and win-rate on one certified set of Metric Views."],
                         ["Unity Catalog", "Certification and the glossary, so \"utilization\" and \"margin\" mean one thing firm-wide."]],
                        sub=[["Managing Partner / CEO", "growth, firm profitability and the trade between hiring and utilization."],
                             ["Chief Operating Officer", "delivery health, engagement risk and quality across the portfolio."],
                             ["Board & Partners", "partner economics, distributions and the firm-wide scorecard."]],
                        ucs=["Engagement Margin", "Consultant Utilization", "Pipeline & Win-Rate", "Knowledge & GenAI"]),
                    biz("Practice Leaders", "AI/BI",
                        "Practice and sector leads owning a book of business: the pipeline they must win, the engagements they deliver and the margin those engagements return.",
                        [["AI/BI", "Practice margin, backlog and win-rate on governed data the leadership team also reads."],
                         ["Genie One", "Ask which engagements are slipping on margin without a finance pull."],
                         ["Model Serving", "Win probability scored on the pipeline behind proposal decisions."]],
                        sub=[["Practice leads", "the practice P&L: pipeline, utilization and margin by engagement."],
                             ["Sector leads", "the book of business and the win rate in their industry vertical."],
                             ["Engagement partners", "delivery quality, scope and profitability on live engagements."]],
                        ucs=["Engagement Margin", "Pipeline & Win-Rate", "Proposal Analytics", "Consultant Utilization"]),
                    biz("CFO & Finance", "AI/BI",
                        "The CFO and finance team on revenue recognition, days sales outstanding, subcontractor spend and the month-end close across a book of concurrent engagements.",
                        [["AI/BI", "Revenue, DSO, WIP and margin variance to plan on certified numbers."],
                         ["Lakeflow", "Time, rate and contract feeds reconciled to the general ledger continuously."],
                         ["Unity Catalog", "SOX-ready lineage and access across the finance and delivery estate."]],
                        sub=[["CFO", "revenue recognition, cash and firm margin under pressure."],
                             ["Controller", "the close, WIP and unbilled revenue across engagements."],
                             ["Billing & AR", "invoicing accuracy, DSO and dispute reduction."]],
                        ucs=["Revenue Recognition", "Subcontractor Spend", "Engagement Margin"]),
                    biz("Talent & HR", "Model Serving",
                        "Talent and HR leadership on attrition, skills coverage and the match between the people the firm has and the demand it has sold.",
                        [["Model Serving", "Attrition risk and skills-to-demand gaps scored per consultant."],
                         ["AI/BI", "Headcount, attrition and skills coverage on governed HR data."],
                         ["AI Search", "Skills and experience matched semantically to open engagement roles."]],
                        sub=[["Chief People Officer", "attrition, engagement and the talent brand."],
                             ["Talent acquisition", "hiring against the demand the firm has sold."],
                             ["L&D / capability", "reskilling to close skills-to-demand gaps."]],
                        ucs=["Talent Attrition", "Skills-to-Demand Match", "Staffing & Bench"]),
                    biz("Delivery & PMO", "Lakehouse//RT",
                        "Resource managers and the PMO on staffing the bench against demand, protecting utilization and keeping engagements on scope and on margin.",
                        [["Lakehouse//RT", "Live utilization, bench and staffing state at the cadence resourcing moves at."],
                         ["Model Serving", "Best-fit staffing recommendations scored against skills and availability."],
                         ["Apps", "Resourcing and utilization screens hosted next to governed delivery data."]],
                        sub=[["Resource managers", "matching the bench to demand week by week."],
                             ["PMO", "engagement health, scope and delivery risk across the portfolio."],
                             ["Delivery leads", "utilization and burn on their own engagements."]],
                        ucs=["Consultant Utilization", "Staffing & Bench", "Knowledge & GenAI"]),
                ],
                [
                    biz("Delivery Engineers", "Lakeflow",
                        "Land the PSA, CRM, finance and HR feeds from Kantata, Salesforce, Workday and NetSuite; own the Bronze to Silver path and the pager when a utilization table stalls.",
                        [["Lakeflow Connect", "Managed connectors for the PSA, CRM, ERP and HR sources."],
                         ["Lakeflow Designer", "Declarative pipelines with expectations on time, rate and contract feeds."],
                         ["Lakewatch", "Freshness on the utilization and margin tables leadership reads every Monday."]]),
                    biz("Insights & Analytics", "MLflow",
                        "Build the utilization, margin, attrition and win-rate models on top of governed engagement data, and prove they still hold as the book of business shifts.",
                        [["Feature Store", "Consultant, engagement and client features read identically in training and serving."],
                         ["MLflow", "Every attrition and win-rate experiment tracked for audit and reproduction."],
                         ["Model Serving", "Staffing, attrition and win models scored in the resourcing and pipeline path."]]),
                    biz("Knowledge & GenAI", "Agent Bricks",
                        "Ground a firm-wide assistant on deliverables, methods and prior work in iManage, SharePoint and Confluence, governed so an answer never crosses an engagement wall it should not.",
                        [["Agent Bricks", "Retrieval agents over deliverables and methods with governed tools."],
                         ["AI Search", "Semantic search across prior engagements and knowledge assets."],
                         ["Unity Catalog", "Fine-grained access so client and engagement walls hold inside the assistant."]]),
                ],
            ),
            "cons": cons_rail(
                [
                    {
                        "box": "BI & Productivity",
                        "ic": "chart",
                        "from": "bi",
                        "tiles": [
                            tile("Tableau / Power BI", "chart", "Partner and practice dashboards against serverless SQL with Unity Catalog permissions enforced end to end."),
                            tile("Microsoft Teams", "chat", "Genie in Teams for governed answers on utilization and margin in the channel the firm already works in (Beta)."),
                            tile("Notebooks & IDEs", "notebook", "Analyst notebooks, VS Code and JetBrains against governed engagement and finance data."),
                        ],
                    },
                    {
                        "box": "Delivery & Clients",
                        "ic": "partner",
                        "tiles": [
                            tile("Client Delta Sharing", "share", "Live engagement dashboards and data products shared to clients over Delta Sharing rather than emailed spreadsheets."),
                            tile("Client Portals", "globe", "Engagement status, deliverables and spend surfaced to clients through the firm's own portal."),
                            tile("Subcontractor Feeds", "partner", "Milestones and spend exchanged with subcontractors and alliance partners.", "coupa"),
                        ],
                    },
                    {
                        "box": "Operational Writeback",
                        "ic": "opdb",
                        "tiles": [
                            tile("PSA Writeback", "db", "Staffing decisions and revised forecasts written back into the PSA so the answer reaches the delivery path.", "kantata"),
                            tile("Staffing Assignments", "people", "Best-fit staffing and bench moves pushed to resource managers and consultant calendars."),
                            tile("Billing & Invoices", "erp", "Approved WIP and revenue schedules written to the finance system for invoicing.", "netsuite"),
                        ],
                    },
                    {
                        "box": "Regulatory & Reporting",
                        "ic": "gavel",
                        "tiles": [
                            tile("Audit & SOX Reporting", "gavel", "Revenue recognition and controls evidence produced from the same governed tables the firm runs on, audit-ready under Unity Catalog."),
                            tile("ESG & DE&I Reporting", "share", "Diversity, pay-equity and sustainability disclosures filed from contracted Gold products."),
                        ],
                    },
                    {
                        "box": "Published Products",
                        "ic": "product",
                        "tiles": [
                            tile("Data Products", "product", "Published, contracted utilization and margin products discoverable in Unity Catalog Domains."),
                            tile("Sharing Recipients", "share", "Clients and alliance partners reading live tables with no copy and no egress duplication."),
                        ],
                    },
                ],
                genie_spaces=[
                    genie("Utilization & Delivery", "Ask about billable utilization, bench and engagement health across practices in plain language.",
                          feeds=["Kantata PSA", "Replicon Time", "NetSuite OpenAir", "Utilization, margin, win-rate"],
                          teams=["Delivery & PMO", "Firm Leadership", "Resource managers"],
                          questions=[
                              "What was billable utilization last month by practice and consultant?",
                              "Who is on the bench this week and for how long?",
                              "Which engagements are burning ahead of plan?",
                              "Where is idle capacity likely next week?",
                              "How does utilization compare to target by sector?"]),
                    genie("Engagement Margin", "Explore realised margin, rate-versus-cost and leakage across engagements and practices.",
                          feeds=["Workday Financials", "DocuSign CLM", "Revenue & GL Mart", "Utilization, margin, win-rate"],
                          teams=["Practice Leaders", "CFO & Finance", "Engagement partners"],
                          questions=[
                              "Which engagements are slipping on margin this quarter?",
                              "What is realised margin by practice against the rate card?",
                              "Where is scope creep eroding margin the most?",
                              "How does margin compare across fixed-fee and T&M engagements?",
                              "Which clients consistently deliver below target margin?"]),
                    genie("Pipeline & Win-Rate", "Answer questions on pipeline health, win probability and proposal outcomes across the book.",
                          feeds=["Salesforce Sales Cloud", "Dynamics 365 Sales", "HubSpot CRM", "Utilization, margin, win-rate"],
                          teams=["Practice Leaders", "Firm Leadership", "Sector leads"],
                          questions=[
                              "What is our weighted pipeline by practice and sector?",
                              "Which open opportunities have the highest win probability?",
                              "What is our win rate by sector this year versus last?",
                              "Which proposals stalled and at what stage?",
                              "Which deals should partners prioritise this week?"]),
                    genie("Talent & Skills", "Ask about attrition risk, skills coverage and staffing fit across the workforce.",
                          feeds=["Workday HCM", "Jira & Confluence", "iManage Knowledge", "Conformed engagement, person, client"],
                          teams=["Talent & HR", "Delivery & PMO", "L&D / capability"],
                          questions=[
                              "Which consultants are at highest attrition risk right now?",
                              "Where are our biggest skills-to-demand gaps?",
                              "Who is the best-fit staffing for this open role?",
                              "Which skills are we overselling versus our bench?",
                              "How is attrition trending by practice and level?"]),
                ],
                dashboards=[
                    dashboard("Utilization & Bench", "Billable utilization, bench, burn and engagement health across practices on certified views.",
                              kpis=["Billable utilization", "Bench days", "Engagement burn", "Realization", "Delivery risk"],
                              teams=["Delivery & PMO", "Firm Leadership", "Resource managers"]),
                    dashboard("Engagement Margin", "Realised margin, rate-versus-cost and leakage by engagement and practice.",
                              kpis=["Engagement margin", "Rate realisation", "Cost rate variance", "Margin leakage", "Write-offs"],
                              teams=["Practice Leaders", "CFO & Finance", "Engagement partners"]),
                    dashboard("Pipeline & Growth", "Pipeline health, weighted forecast, win-rate and backlog across the book of business.",
                              kpis=["Weighted pipeline", "Win rate", "Backlog", "Proposal conversion", "Book-to-bill"],
                              teams=["Practice Leaders", "Firm Leadership", "Sector leads"]),
                    dashboard("Talent & Skills", "Attrition risk, skills coverage, staffing fit and hiring against sold demand.",
                              kpis=["Attrition rate", "Skills-to-demand gap", "Staffing fill rate", "Time-to-staff", "Hiring vs demand"],
                              teams=["Talent & HR", "Delivery & PMO", "L&D / capability"]),
                ],
            ),
        },
        "top": top_band(
            [
                app("Utilization Cockpit", "Billable & bench", "gauge",
                    "The screen resource managers run the week from: billable utilization, bench and burn by consultant and practice, with the roles that will sit idle flagged before the week starts, on Databricks Apps over Lakebase."),
                app("Margin Radar", "Engagement margin", "chart",
                    "Realised margin by engagement and practice against the rate card and cost rate, flagging the engagements slipping on scope and burn before the write-off is booked."),
                app("Staffing & Bench Board", "Resource matching", "people",
                    "Open demand matched to available skills and bench, with best-fit staffing recommendations a resource manager confirms rather than assembles by hand."),
                app("Knowledge Assistant", "GenAI on deliverables", "genie",
                    "A governed assistant grounded on prior deliverables, methods and engagement knowledge, answering within the client and engagement walls it is allowed to cross."),
            ],
            [
                uc("Consultant Utilization", "Billable rate", "gauge",
                    "Billable utilization and bench tracked live across consultants and practices so idle capacity is seen and filled before it is lost.",
                    problem="Utilization is the number the firm lives on, yet it is stitched together from timesheets days late, so idle capacity is only seen after the week it was lost.",
                    who="Delivery & PMO",
                    how="Time, project and HR feeds land in Lakehouse//RT; utilization and bench are computed on certified Metric Views and worked from the Utilization Cockpit on Lakebase.",
                    comps=["Utilization Cockpit", "Lakehouse//RT", "Replicon Time", "Kantata PSA", "AI/BI"],
                    stories=[
                        ["DXC Technology boosts productivity with GenAI", "https://www.databricks.com/customers/dxc-technology"],
                        ["How CFOs in consulting can recover margin with Databricks", "https://www.databricks.com/blog/how-cfos-consulting-can-recover-margin-databricks"],
                    ]),
                uc("Engagement Margin", "Profitability", "chart",
                    "Realised margin by engagement and practice against the rate card and cost rate, seen while the engagement can still be corrected.",
                    problem="Margin is discovered at close, after the scope creep and write-offs have already happened, when it is too late to reprice or restaff the engagement.",
                    who="Practice Leaders",
                    how="Time, rate, cost and contract data are conformed to Gold; margin by engagement is served on certified Metric Views and drilled from Margin Radar.",
                    comps=["Margin Radar", "AI/BI", "Workday Financials", "DocuSign CLM", "Unity Catalog"],
                    stories=[
                        ["How CFOs in consulting can recover margin with Databricks", "https://www.databricks.com/blog/how-cfos-consulting-can-recover-margin-databricks"],
                    ]),
                uc("Staffing & Bench", "Resourcing", "people",
                    "Open engagement demand matched to available skills and bench, so the right consultant is staffed instead of the first one free.",
                    problem="Staffing runs on who a resource manager happens to remember, so the bench sits idle while roles go to the nearest name rather than the best fit.",
                    who="Delivery & PMO",
                    how="Skills, availability and demand are conformed in the lakehouse; best-fit staffing is scored in Model Serving and confirmed from the Staffing & Bench Board.",
                    comps=["Staffing & Bench Board", "Model Serving", "Workday HCM", "AI Search", "Lakehouse//RT"],
                    stories=[
                        ["DXC Technology boosts productivity with GenAI", "https://www.databricks.com/customers/dxc-technology"],
                        ["NorthStar Anesthesia built a scheduling app in weeks", "https://www.databricks.com/blog/how-northstar-anesthesia-built-scheduling-app-workforce-3000-clinicians-weeks"],
                    ]),
                uc("Pipeline & Win-Rate", "Growth", "market",
                    "Pipeline health and win probability scored across the opportunity book so partners chase the deals the firm can actually win.",
                    problem="Pipeline is judged on gut and stage, so effort goes to deals that will not close while the winnable ones get too little partner attention.",
                    who="Practice Leaders",
                    how="Salesforce and PSA opportunity data are conformed; win probability is scored in Model Serving and read alongside backlog in AI/BI.",
                    comps=["Salesforce Sales Cloud", "Model Serving", "AI/BI", "Genie One"],
                    stories=[
                        ["MiQ scales campaign optimization with Genie", "https://www.databricks.com/customers/miq"],
                        ["Publicis Groupe unifies retail data on Databricks", "https://www.databricks.com/customers/publicis-groupe"],
                    ]),
                uc("Talent Attrition", "Retention", "people",
                    "Attrition risk scored per consultant so the firm intervenes on its best people before the resignation, not after.",
                    problem="The firm learns a consultant is leaving when the notice lands, after the knowledge, the client relationship and the utilization have already walked out the door.",
                    who="Talent & HR",
                    how="HR, utilization and engagement signals feed an attrition model tracked in MLflow and scored in Model Serving, with at-risk consultants flagged to people leaders.",
                    comps=["Model Serving", "MLflow", "Workday HCM", "AI/BI"],
                    stories=[
                        ["LA County democratizes hiring and retention data", "https://www.databricks.com/customers/la-county"],
                        ["Crafting a data-driven talent intelligence strategy", "https://www.databricks.com/blog/crafting-data-driven-talent-intelligence-strategy-healthcare"],
                    ]),
                uc("Proposal Analytics", "Bidding", "product",
                    "Proposals and bids analysed against past wins so pricing, staffing and scope reflect what actually closes.",
                    problem="Every proposal is priced from scratch, so the firm repeats the pricing and staffing mistakes of the last lost bid instead of learning from the won ones.",
                    who="Practice Leaders",
                    how="Won and lost proposals, rates and outcomes are conformed in the lakehouse; win drivers are analysed in AI/BI and surfaced against new bids.",
                    comps=["AI/BI", "Salesforce Sales Cloud", "DocuSign CLM", "Unity Catalog"]),
                uc("Skills-to-Demand Match", "Capability", "ztarget",
                    "The skills the firm has matched against the demand it has sold, so hiring and reskilling close the gap that would otherwise be subcontracted.",
                    problem="Firms sell skills they are short of and bench skills they oversold, because the supply of capability and the demand in the pipeline are never compared on one picture.",
                    who="Talent & HR",
                    how="Skills from HR and delivery are matched semantically to pipeline demand with AI Search; gaps are scored in Model Serving to steer hiring and L&D.",
                    comps=["AI Search", "Model Serving", "Workday HCM", "Salesforce Sales Cloud"],
                    stories=[
                        ["DXC Technology boosts productivity with GenAI", "https://www.databricks.com/customers/dxc-technology"],
                        ["Crafting a data-driven talent intelligence strategy", "https://www.databricks.com/blog/crafting-data-driven-talent-intelligence-strategy-healthcare"],
                    ]),
                uc("Revenue Recognition", "Finance", "erp",
                    "Billable hours, rates and contract terms reconciled to the general ledger continuously so the close is faster and audit-ready.",
                    problem="Revenue is knitted together each month by hand from time, rate and contract systems that do not agree, consuming finance days and inviting restatements.",
                    who="CFO & Finance",
                    how="Time, rate and DocuSign contract terms are reconciled to the Revenue & GL Mart with Lakeflow, computed once and made SOX-ready under Unity Catalog.",
                    comps=["Lakeflow", "Revenue & GL Mart", "Workday Financials", "Unity Catalog", "DocuSign CLM"],
                    stories=[
                        ["How CFOs in consulting can recover margin with Databricks", "https://www.databricks.com/blog/how-cfos-consulting-can-recover-margin-databricks"],
                        ["Beyond the spreadsheet: the modern CFO on Databricks", "https://www.databricks.com/blog/beyond-spreadsheet-how-databricks-delivering-modern-cfo-financial-services"],
                    ]),
                uc("Subcontractor Spend", "Procurement", "docs",
                    "Subcontractor and supplier spend joined to engagements so pass-through cost and margin leakage are seen per project.",
                    problem="Subcontractor cost sits in procurement, disconnected from the engagement it was bought for, so margin leakage and off-contract spend hide until the project is underwater.",
                    who="CFO & Finance",
                    how="Coupa purchase orders and invoices are conformed and joined to engagement actuals in the lakehouse, surfacing spend and leakage by project in AI/BI.",
                    comps=["Coupa Procurement", "AI/BI", "Workday Financials", "Lakeflow"]),
                uc("Knowledge & GenAI", "Assistant", "genie",
                    "A governed assistant over the firm's deliverables and methods so consultants reuse prior work instead of rebuilding it.",
                    problem="The firm's best thinking is buried in past deliverables no one can find, so every engagement rebuilds work that already exists somewhere in the practice.",
                    who="Firm Leadership",
                    how="Deliverables and methods in iManage and Confluence are indexed for AI Search; a retrieval assistant on Agent Bricks answers within Unity Catalog access walls from the Knowledge Assistant.",
                    comps=["Knowledge Assistant", "Agent Bricks", "AI Search", "iManage Knowledge", "Unity Catalog"],
                    stories=[
                        ["DXC Technology boosts productivity with GenAI", "https://www.databricks.com/customers/dxc-technology"],
                        ["The agentic marketing stack starts with the data layer", "https://www.databricks.com/blog/agentic-marketing-stack-starts-data-layer"],
                    ]),
            ],
        ),
        "sources": {
            "kantata": {"t": "Kantata PSA", "u": "https://www.kantata.com/"},
            "openair": {"t": "Oracle NetSuite OpenAir", "u": "https://www.netsuite.com/portal/products/openair.shtml"},
            "certinia": {"t": "Certinia PSA", "u": "https://certinia.com/"},
            "sfdc": {"t": "Salesforce Sales Cloud", "u": "https://www.salesforce.com/products/sales-cloud/"},
            "dynamics": {"t": "Microsoft Dynamics 365 Sales", "u": "https://www.microsoft.com/en-us/dynamics-365/products/sales"},
            "hubspot": {"t": "HubSpot CRM", "u": "https://www.hubspot.com/products/crm"},
            "workday-fins": {"t": "Workday Financial Management", "u": "https://www.workday.com/en-us/products/financial-management/overview.html"},
            "netsuite": {"t": "Oracle NetSuite ERP", "u": "https://www.netsuite.com/portal/products/erp.shtml"},
            "sap": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "deltek": {"t": "Deltek Vantagepoint", "u": "https://www.deltek.com/en/products/project-erp/vantagepoint"},
            "replicon": {"t": "Replicon time tracking", "u": "https://www.replicon.com/"},
            "bigtime": {"t": "BigTime time and billing", "u": "https://www.bigtime.net/"},
            "workday-hcm": {"t": "Workday HCM", "u": "https://www.workday.com/en-us/products/human-capital-management/overview.html"},
            "coupa": {"t": "Coupa procurement", "u": "https://www.coupa.com/"},
            "imanage": {"t": "iManage knowledge management", "u": "https://imanage.com/"},
            "concur": {"t": "SAP Concur expense", "u": "https://www.concur.com/"},
            "docusign": {"t": "DocuSign CLM", "u": "https://www.docusign.com/products/clm"},
            "atlassian": {"t": "Atlassian Jira", "u": "https://www.atlassian.com/software/jira"},
        },
    }
}
