import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_MEDICAL_DEVICES = {
    "medical_devices": {
        "label": "Medical Devices",
        "blurb": "Design, manufacture and post-market support of regulated medical devices: PLM and requirements, MES and quality, complaint and CAPA, connected-device telemetry, and regulatory submissions.",
        "medallion": medallion(
            "Raw device and quality feeds",
            "Complaint intake and MDR events, MES lot and process records, PLM change orders, LIMS results and connected-device telemetry, landed exactly as received so a complaint or a batch record can be replayed as it stood.",
            "Conformed device, lot, complaint",
            "Devices, lots, components and complaints resolved into single conformed entities across PLM, MES, QMS and field systems, with UDI-DI reconciled and device history stitched from component to finished good.",
            "Yield, complaint rate, CAPA",
            "Contracted products the quality and operations teams run on: first-pass yield and OEE by line, complaint and MDR rates by product and lot, CAPA cycle time, and field reliability by device family.",
        ),
        "rails": {
            "src": [
                {
                    "box": "PLM & Engineering",
                    "ic": "dev",
                    "tiles": [
                        tile("PTC Windchill", "dev", "Product lifecycle management: the system of record for device design, BOMs, change orders and the design history file.", "windchill"),
                        tile("Siemens Teamcenter", "erp", "PLM for BOM, requirements and change control where Teamcenter is the incumbent design backbone.", "teamcenter"),
                        tile("Jama Connect", "docs", "Requirements, verification and validation traceability from design inputs to test evidence for regulated products.", "jama"),
                    ],
                },
                {
                    "box": "Quality & Reg",
                    "ic": "gavel",
                    "tiles": [
                        tile("MasterControl QMS", "gavel", "Quality management: document control, training, nonconformances, CAPA and audit trails under 21 CFR Part 11.", "mastercontrol"),
                        tile("Veeva Vault Quality", "gavel", "Cloud QMS and QualityDocs for complaint, deviation and CAPA workflows across sites.", "veeva"),
                        tile("TrackWise Digital", "gavel", "Complaint management and CAPA of record: intake, MDR decisioning and adverse-event workflows.", "trackwise"),
                        tile("ETQ Reliance", "gavel", "Quality and EHS management for nonconformance, supplier quality and CAPA where ETQ is the incumbent.", "etq"),
                    ],
                },
                {
                    "box": "Manufacturing & MES",
                    "ic": "compute",
                    "tiles": [
                        tile("Siemens Opcenter MES", "compute", "Manufacturing execution: electronic batch records, work orders, genealogy and in-line quality on the line.", "opcenter"),
                        tile("Rockwell Plex MES", "compute", "Cloud MES for production tracking, quality and genealogy across discrete device manufacturing.", "plex"),
                        tile("Tulip Frontline Ops", "apps", "Composable frontline operations and digital work instructions on the manufacturing floor.", "tulip"),
                        tile("AVEVA PI Historian", "iot", "Process historian: equipment and process time-series that underpins SPC, OEE and anomaly detection.", "avevapi"),
                    ],
                },
                {
                    "box": "ERP, Service & CRM",
                    "ic": "erp",
                    "tiles": [
                        tile("SAP S/4HANA", "erp", "The ERP of record for procurement, inventory, production orders and finance across the device business.", "sap"),
                        tile("ServiceMax", "orch", "Field service management: installed base, service contracts, work orders and parts for the device fleet.", "servicemax"),
                        tile("Salesforce", "crm", "Commercial CRM for accounts, orders and device utilisation across sales and customer success.", "salesforce"),
                        tile("LabWare LIMS", "db", "Laboratory information management: test results, specifications and out-of-spec dispositions for release.", "labware"),
                    ],
                },
                {
                    "box": "Regulatory & Telemetry",
                    "ic": "iot",
                    "tiles": [
                        tile("FDA GUDID / UDI", "gavel", "Unique Device Identification records and the Global UDI Database, the reference for device identity and labelling.", "gudid"),
                        tile("FDA MAUDE Events", "gavel", "Manufacturer and User Facility Device Experience adverse-event reports, the public post-market safety record.", "maude"),
                        tile("Device Telemetry", "iot", "Connected-device and IoMT telemetry from the installed base: usage, alarms and sensor streams from every unit."),
                        tile("HL7 FHIR Feeds", "api", "Interoperability feeds carrying device, observation and outcome resources to and from clinical systems.", "fhir"),
                    ],
                },
                fed_group("Complaint & RWE Marts", "Historical complaint, clinical and real-world evidence marts left where they are and queried in place under Unity Catalog, which avoids a second copy of the audited numbers."),
            ],
            "ing": ing_rail([
                tile("openFDA APIs", "api", "Device classification, recall and adverse-event data ingested from the FDA open data APIs for benchmarking.", "openfda"),
                tile("EU EUDAMED", "gavel", "European device registration, UDI and vigilance data exchanged with the EUDAMED database under EU MDR.", "eudamed"),
                tile("Device Events", "stream", "MQTT and Kafka topics carrying connected-device telemetry, alarms and MES events, landed as structured events."),
            ]),
            "ppl": ppl2([
                biz("R&D & Engineering", "AI/BI",
                    "Design and systems engineering on product architecture and requirements in the design history file, verification and validation against design inputs, and reliability engineering turning field returns into design changes.",
                    [["AI/BI", "Design-verification coverage and field reliability on certified Metric Views."],
                     ["MLflow", "Reliability and failure-mode models tracked for design reviews and audit."],
                     ["Unity Catalog", "Requirements, design history and change control governed with lineage across the estate."]],
                    sub=[["Design & systems eng", "product architecture and requirements in the DHF."],
                         ["Verification & validation", "test evidence against design inputs and requirements."],
                         ["Reliability engineering", "failure modes and field returns feeding design changes."]],
                    ucs=["Design & Reliability", "Predictive Servicing", "Complaint & CAPA"]),
                biz("Quality & Reg", "Genie One",
                    "The head of quality on complaint and CAPA backlog and audit readiness; regulatory affairs on submissions, UDI registration and MDR timeliness; compliance and audit on QSR, ISO 13485 and recall exposure.",
                    [["Genie One", "Ask which lots and products drive this quarter's complaints without an analyst pull."],
                     ["AI/BI", "Complaint rate, CAPA cycle time and submission status on one certified set of Metric Views."],
                     ["Unity Catalog", "Audit trails and lineage supporting 21 CFR Part 11 and ISO 13485."]],
                    sub=[["Head of quality", "complaint and CAPA backlog and audit readiness."],
                         ["Regulatory affairs", "submissions, UDI registration and MDR timeliness."],
                         ["Compliance & audit", "QSR, ISO 13485 and recall exposure."]],
                    ucs=["Complaint & CAPA", "Post-Market Vigilance", "Regulatory Submissions", "Traceability & Recall"]),
                biz("Manufacturing Ops", "Lakehouse//RT",
                    "Process and plant engineering on first-pass yield, OEE and process capability, line quality on nonconformance and disposition, and supply chain on component availability and supplier quality.",
                    [["Yield & OEE Cockpit", "Line yield and downtime flagged before a lot is at risk."],
                     ["Lakehouse//RT", "Live MES and equipment state at the latency a line moves at."],
                     ["Model Serving", "Defect and yield models scored against in-line inspection."]],
                    sub=[["Process & plant eng", "first-pass yield, OEE and process capability."],
                         ["Line quality", "nonconformance, disposition and SPC at the line."],
                         ["Supply chain", "component availability and supplier quality."]],
                    ucs=["MES Yield & Quality", "Supply Chain Risk", "Traceability & Recall"]),
                biz("Commercial & Svc", "AI/BI",
                    "Sales and marketing on territory attainment and device utilisation, the field service organisation on installed-base uptime and service contracts, and customer success on onboarding and consumable replenishment.",
                    [["AI/BI", "Territory attainment, device utilisation and service SLAs on certified views."],
                     ["Model Serving", "Service and churn models scored in the dispatch and account path."],
                     ["Genie One", "Ask which accounts are below utilisation target this quarter."]],
                    sub=[["Sales & marketing", "territory attainment and device utilisation."],
                         ["Field service", "installed-base uptime and service contracts."],
                         ["Customer success", "onboarding and consumable replenishment."]],
                    ucs=["Sales & Territory", "Predictive Servicing", "Supply Chain Risk"]),
                biz("Clinical Affairs", "Model Serving",
                    "Medical affairs on real-world evidence and clinical value, post-market surveillance on complaint and adverse-event signal, and health economics on outcomes and value evidence.",
                    [["Model Serving", "Safety-signal and outcome models scored across complaint, RWD and registry data."],
                     ["AI Functions", "Adverse-event narratives and literature classified at scale from unstructured text."],
                     ["AI/BI", "Signal trends and real-world outcomes on governed, certified views."]],
                    sub=[["Medical affairs", "real-world evidence and clinical value."],
                         ["Post-market surveillance", "complaint and adverse-event signal."],
                         ["Health economics", "outcomes and value evidence."]],
                    ucs=["Post-Market Vigilance", "Real-World Evidence", "Complaint & CAPA"]),
            ], [
                biz("Telemetry Eng", "Lakeflow",
                    "Land connected-device and IoMT telemetry over MQTT and Kafka, complaint intake and MES events; own the Bronze to Silver path and the pager when the device-fleet tables stall.",
                    [["Lakeflow Connect", "Managed connectors for QMS, PLM, ERP and MES sources."],
                     ["Auto Loader", "Device event and log files landed incrementally into Bronze."],
                     ["Lakewatch", "Freshness on the fleet and complaint tables quality reads each morning."]]),
                biz("Quality DS", "MLflow",
                    "Complaint text classification, adverse-event coding, anomaly detection on process and telemetry, and reliability models, and whether they still hold as products and processes change.",
                    [["Feature Store", "Device, lot and complaint features read identically in training and serving."],
                     ["MLflow", "Every classifier and reliability model tracked for audit and reproduction."],
                     ["Model Serving", "Complaint triage and anomaly models scored in the quality path."]]),
                biz("Application Engineers", "Apps",
                    "Ship the CAPA Command Center, Device Fleet Monitor and Submission Workbench apps quality and service teams work in, hosted next to governed device data.",
                    [["Apps", "Device-connectivity and complaint-handling screens with no separate web tier to secure."],
                     ["Lakebase", "Serverless Postgres for CAPA state and disposition writes."],
                     ["Agent Bricks", "Agents that draft complaint summaries against governed tools."]]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Executive and quality dashboards against serverless SQL with Unity Catalog permissions."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for complaint and yield answers in the channel quality already works in."),
                    tile("Notebooks & IDEs", "notebook", "Engineering and data-science notebooks against governed device and quality data."),
                ]},
                {"box": "Providers & Partners", "ic": "partner", "tiles": [
                    tile("Provider FHIR Exchange", "api", "Device and outcome data exchanged with hospital systems over HL7 FHIR.", "fhir"),
                    tile("Distributor Portals", "globe", "Inventory, UDI and field-action status shared to distributors and GPOs."),
                    tile("Contract Mfg Sharing", "share", "CMOs and suppliers reading live quality and demand tables over Delta Sharing."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("QMS CAPA Writeback", "gavel", "CAPAs and dispositions written back into the QMS so the action reaches the system quality works in.", "mastercontrol"),
                    tile("MES Disposition", "compute", "Lot hold, release and rework decisions written back to the MES at the line.", "opcenter"),
                    tile("Field Service Orders", "orch", "Predicted service dispatch raised in the field-service system against the installed base.", "servicemax"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("FDA UDI & MDR Filing", "gavel", "UDI records and MDR reports filed to GUDID and MAUDE from governed device tables.", "gudid"),
                    tile("EU MDR / EUDAMED", "share", "Registration and vigilance reporting filed to EUDAMED under EU MDR from certified Gold.", "eudamed"),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Published, contracted device and quality products discoverable in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Suppliers, CMOs and registries reading live tables with no copy and no egress duplication."),
                ]},
            ]),
        },
        "top": top_band(
            [
                app("CAPA Command Center", "Complaint & CAPA", "gavel",
                    "Complaints, nonconformances and CAPAs triaged by risk with root-cause evidence assembled from QMS, MES and complaint text, on Databricks Apps over Lakebase."),
                app("Device Fleet Monitor", "Connected-device health", "iot",
                    "Installed-base telemetry by device and site, flagging units trending to failure so service is dispatched before a field event."),
                app("Yield & OEE Cockpit", "Line performance", "gauge",
                    "Live first-pass yield, downtime and SPC against the shift target, flagging lots and lines at risk before disposition."),
                app("Submission Workbench", "Regulatory & UDI", "docs",
                    "Where regulatory affairs assembles UDI, 510(k) and MDR submissions from governed device, design-history and complaint tables."),
            ],
            [
                uc("Complaint & CAPA", "Quality", "gavel",
                    "Complaints, nonconformances and MDR events triaged by severity and probable cause, with CAPA opened and tracked to closure.",
                    problem="Complaints, nonconformances and MDR events sit in separate systems, so severity is judged inconsistently, root cause is reconstructed by hand and CAPA backlog ages toward the next audit.",
                    who="Quality & Reg",
                    how="Complaint intake, MES nonconformances and adverse-event feeds land in the lakehouse; text models triage severity and probable cause in Model Serving and open CAPAs from the CAPA Command Center on Lakebase.",
                    comps=["CAPA Command Center", "TrackWise Digital", "MasterControl QMS", "Model Serving", "AI Functions", "Lakebase"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Post-Market Vigilance", "Safety", "ztarget",
                    "Emerging safety signal detected across complaints, adverse events and device telemetry before field exposure grows.",
                    problem="Safety signal hides across complaints, adverse events, registries and device telemetry; by the time a trend clears a manual review the field exposure has already grown.",
                    who="Clinical Affairs",
                    how="Complaint, adverse-event and telemetry feeds are conformed to Gold; signal-detection models score emerging trends in Model Serving and surface them to surveillance before they become recalls.",
                    comps=["FDA MAUDE Events", "Device Telemetry", "Model Serving", "AI/BI", "Complaint & RWE Marts"],
                    stories=[["Real-World Evidence Solution Accelerator", "https://www.databricks.com/solutions/accelerators/real-world-evidence"],
                             ["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Predictive Servicing", "Field service", "iot",
                    "Connected devices scored on telemetry so service is dispatched before an unplanned failure in the field.",
                    problem="Connected devices in the field fail between planned visits, and without telemetry the first signal is an unplanned service call or a complaint, not a prediction.",
                    who="Commercial & Svc",
                    how="IoMT telemetry streams into Lakehouse//RT; remaining-useful-life models score each unit in Model Serving and dispatch is raised in ServiceMax from the Device Fleet Monitor.",
                    comps=["Device Fleet Monitor", "Device Telemetry", "Lakehouse//RT", "Model Serving", "ServiceMax", "MLflow"],
                    stories=[["Insulet: connected Omnipod device analytics on Databricks", "https://www.databricks.com/customers/insulet/lakeflow-connect"],
                             ["GE Healthcare builds device and patient views on Databricks", "https://www.databricks.com/company/newsroom/press-releases/databricks-introduces-lakehouse-for-the-healthcare-and-life-sciences-industries-to-drive-transformation-across-healthcare-ecosystem"]]),
                uc("MES Yield & Quality", "Manufacturing", "gauge",
                    "First-pass yield and scrap attacked at the line with in-line defect scoring rather than at final inspection.",
                    problem="First-pass yield and scrap are reviewed after the lot, so a drifting process is caught at final inspection or in the field instead of at the line.",
                    who="Manufacturing Ops",
                    how="MES, historian and inspection data are conformed to certified Metric Views; defect and yield models score in-line in Model Serving and the Yield & OEE Cockpit flags lots at risk before disposition.",
                    comps=["Yield & OEE Cockpit", "Siemens Opcenter MES", "AVEVA PI Historian", "Model Serving", "AI/BI"],
                    stories=[["Insulet cuts manufacturing data latency on Databricks", "https://www.databricks.com/customers/insulet/lakeflow-connect"]]),
                uc("Supply Chain Risk", "Supply chain", "network",
                    "Supplier and component exposure scored so shortages and bad lots are moved before they stop a build or reach a device.",
                    problem="Single-source components and opaque supplier quality mean a shortage or a bad lot is discovered at the line, after it has already stopped a build or reached a device.",
                    who="Manufacturing Ops",
                    how="ERP, supplier and MES feeds are joined in the lakehouse; risk models score supplier and component exposure so buffers and qualifications are moved before a shortage or nonconformance lands.",
                    comps=["SAP S/4HANA", "Genie", "Model Serving", "AI/BI", "Lakeflow"],
                    stories=[["Integra Life Sciences gains a global supply and demand view", "https://www.databricks.com/customers/integra-life-sciences"]]),
                uc("Regulatory Submissions", "Regulatory", "docs",
                    "UDI, 510(k) and MDR submissions assembled from governed device, design-history and complaint tables with lineage.",
                    problem="UDI, 510(k) and MDR submissions are assembled by hand from PLM, QMS and complaint systems, so filing is slow and every regulator's format is a fresh manual export.",
                    who="Quality & Reg",
                    how="Device, design-history and complaint tables are governed under Unity Catalog; the Submission Workbench assembles UDI/GUDID and MDR packages with lineage from the same certified data.",
                    comps=["Submission Workbench", "FDA GUDID / UDI", "EU EUDAMED", "Unity Catalog", "AI Functions"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Sales & Territory", "Commercial", "market",
                    "Territory attainment and consumable forecasting grounded in how the installed base is actually used, not just orders.",
                    problem="Sales sees orders but not device utilisation, so territory calls and consumable forecasts are made blind to how the installed base is actually used.",
                    who="Commercial & Svc",
                    how="CRM, order and device-utilisation data are conformed to Gold; attainment and utilisation are read in AI/BI and Genie on the definitions the commercial team already reports.",
                    comps=["Salesforce", "AI/BI", "Genie One", "Unity Catalog"]),
                uc("Real-World Evidence", "Clinical", "chart",
                    "Real-world device performance assembled from registries, claims and telemetry for indications, value and safety.",
                    problem="Device performance in the real world lives in registries, claims and telemetry that never meet, so evidence for indications, value and safety takes months to assemble.",
                    who="Clinical Affairs",
                    how="Real-world data from registries, claims and device telemetry is conformed on the lakehouse using the RWE accelerator; outcome and comparative-effectiveness models run in Model Serving.",
                    comps=["HL7 FHIR Feeds", "Complaint & RWE Marts", "Model Serving", "AI/BI", "Delta Lake"],
                    stories=[["Real-World Evidence Solution Accelerator", "https://www.databricks.com/solutions/accelerators/real-world-evidence"],
                             ["Integra Life Sciences unifies data for patient care", "https://www.databricks.com/customers/integra-life-sciences"]]),
                uc("Traceability & Recall", "Traceability", "share",
                    "Device history and lot genealogy stitched so a recall is scoped from component to patient in minutes.",
                    problem="When a lot is suspect, tracing every affected device from component to patient and scoping the recall is a manual genealogy hunt across MES, PLM and distribution.",
                    who="Quality & Reg",
                    how="Device history and lot genealogy are stitched in Silver from MES, PLM and distribution; a recall query scopes affected units in minutes and writes disposition back to the QMS.",
                    comps=["Siemens Opcenter MES", "PTC Windchill", "MasterControl QMS", "Unity Catalog", "AI/BI"],
                    stories=[["Databricks for Healthcare and Life Sciences", "https://www.databricks.com/solutions/industries/healthcare-and-life-sciences"]]),
                uc("Design & Reliability", "Engineering", "dev",
                    "Field returns, complaints and telemetry joined to requirements so reliability lessons reach design reviews directly.",
                    problem="Field returns and complaints carry the design lessons, but they reach engineering as quarterly summaries, long after the next design freeze has passed.",
                    who="R&D & Engineering",
                    how="Complaint, return and telemetry signal is joined to requirements and design history in the lakehouse; failure-mode and reliability models in MLflow feed design reviews directly.",
                    comps=["PTC Windchill", "Jama Connect", "Device Telemetry", "MLflow", "Model Serving", "Feature Store"],
                    stories=[["Predictive maintenance on the Databricks Lakehouse", "https://www.databricks.com/blog/what-is-predictive-maintenance"],
                             ["Insulet guides product updates with live device data", "https://www.databricks.com/customers/insulet/lakeflow-connect"]]),
            ],
        ),
        "sources": {
            "windchill": {"t": "PTC Windchill PLM", "u": "https://www.ptc.com/en/products/windchill"},
            "teamcenter": {"t": "Siemens Teamcenter PLM", "u": "https://plm.sw.siemens.com/en-US/teamcenter/"},
            "jama": {"t": "Jama Connect", "u": "https://www.jamasoftware.com/platform/jama-connect/"},
            "mastercontrol": {"t": "MasterControl QMS", "u": "https://www.mastercontrol.com/"},
            "veeva": {"t": "Veeva Vault Quality", "u": "https://www.veeva.com/products/vault-quality/"},
            "trackwise": {"t": "TrackWise Digital QMS", "u": "https://www.trackwise.com/"},
            "etq": {"t": "ETQ Reliance", "u": "https://www.etq.com/"},
            "opcenter": {"t": "Siemens Opcenter Execution MES", "u": "https://plm.sw.siemens.com/en-US/opcenter/"},
            "plex": {"t": "Rockwell Plex MES", "u": "https://www.plex.com/products/manufacturing-execution-system"},
            "tulip": {"t": "Tulip Frontline Operations", "u": "https://tulip.co/"},
            "avevapi": {"t": "AVEVA PI System", "u": "https://www.aveva.com/en/products/aveva-pi-system/"},
            "sap": {"t": "SAP S/4HANA", "u": "https://www.sap.com/products/erp/s4hana.html"},
            "servicemax": {"t": "ServiceMax field service", "u": "https://www.servicemax.com/"},
            "salesforce": {"t": "Salesforce Health Cloud", "u": "https://www.salesforce.com/products/health-cloud/overview/"},
            "labware": {"t": "LabWare LIMS", "u": "https://www.labware.com/"},
            "gudid": {"t": "FDA GUDID (UDI database)", "u": "https://www.fda.gov/medical-devices/unique-device-identification-system-udi-system/global-unique-device-identification-database-gudid"},
            "maude": {"t": "FDA MAUDE adverse events", "u": "https://www.fda.gov/medical-devices/mandatory-reporting-requirements-manufacturers-importers-and-device-user-facilities/manufacturer-and-user-facility-device-experience-database-maude"},
            "fhir": {"t": "HL7 FHIR", "u": "https://www.hl7.org/fhir/"},
            "openfda": {"t": "openFDA device APIs", "u": "https://open.fda.gov/apis/device/"},
            "eudamed": {"t": "EU EUDAMED (EU MDR)", "u": "https://health.ec.europa.eu/medical-devices-eudamed_en"},
        },
    }
}
