import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_TRAVEL_HOSPITALITY = {
    'travel_hospitality': {
        "label": "Travel & Hospitality",
        "blurb": "Hotels, resorts and travel sellers: property management, central reservations, revenue management, guest loyalty, and distribution across direct and OTA channels.",
        "medallion": medallion(
            "Raw guest and booking feeds",
            "PMS reservations, CRS availability, POS folios, loyalty transactions and OTA bookings, landed exactly as received so a rate or a stay can always be replayed.",
            "Conformed guest, stay, room",
            "Guests, stays, room nights and rate plans resolved into single conformed entities across PMS, CRS and loyalty, with multi-property journeys stitched to one profile.",
            "RevPAR, ADR, occupancy",
            "Contracted products commercial and operations teams run on: RevPAR and ADR by segment, occupancy forecast, guest satisfaction and ancillary attach rate.",
        ),
        "rails": {
            "src": [
                {"box": "PMS & Operations", "ic": "erp", "tiles": [
                    tile("Oracle OPERA Cloud", "erp", "Property management: reservations, housekeeping, folios and night audit.", "opera-cloud",
                         cat="Property Management System (PMS)",
                         what="System-of-record for reservations, room inventory, housekeeping status and guest folios, and runs the night-audit cycle that closes each business day.",
                         users="Front office, Housekeeping, Night audit and Revenue teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "5-30 GB/day", "Night audit + hourly deltas"),
                             stream=flow(["semi-structured"], "tens-hundreds of events/sec", "Continuous CDC (reservations, status)"))),
                    tile("Mews PMS", "apps", "Cloud PMS for boutique and multi-property groups with open APIs.", "mews",
                         cat="Property Management System (PMS)",
                         what="Cloud-native PMS for boutique and multi-property groups, exposing reservations, folios and guest profiles over open APIs.",
                         users="Front office and Operations teams at boutique and independent groups.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens of events/sec", "Continuous (API / webhook)"))),
                    tile("Infor HMS", "db", "Hotel operations, group blocks and event catering for full-service properties.", "infor-hms",
                         cat="Property Management System (PMS)",
                         what="Full-service hotel operations platform covering reservations, group blocks and event catering for larger properties.",
                         users="Front office, Group sales and Catering operations teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "2-15 GB/day", "Nightly batch + intraday deltas"))),
                ]},
                {"box": "CRS & Distribution", "ic": "market", "tiles": [
                    tile("Amadeus iHotelier", "globe", "Central reservations, rate distribution and channel management.", "amadeus-ihotelier",
                         cat="Central Reservation System (CRS)",
                         what="Holds central availability and rates, distributes them to channels and captures bookings from web, GDS and voice.",
                         users="Central reservations, Distribution and Revenue management teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of booking msgs/sec at peak", "Continuous (booking notifications)"))),
                    tile("Sabre SynXis", "partner", "CRS, booking engine and GDS connectivity for hotel brands.", "sabre-synxis",
                         cat="Central Reservation System (CRS)",
                         what="Central reservation and booking-engine platform connecting brand websites and GDS to a single availability pool.",
                         users="Distribution, E-commerce and Brand reservations teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of events/sec", "Continuous (reservation events)"))),
                    tile("SiteMinder Channel", "api", "OTA and metasearch connectivity with parity monitoring.", "siteminder",
                         cat="Channel Manager",
                         what="Pushes rates and availability to OTAs and metasearch and pulls bookings back, monitoring rate parity across channels.",
                         users="Distribution and Revenue management teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens-hundreds of ARI + booking msgs/sec", "Continuous (ARI + bookings)"))),
                ]},
                {"box": "Revenue Management", "ic": "chart", "tiles": [
                    tile("IDeaS G3 RMS", "market", "Forecasting, price recommendations and length-of-stay controls.", "ideas-rms",
                         cat="Revenue Management System (RMS)",
                         what="Forecasts demand and recommends optimal rates and length-of-stay controls by segment for each property.",
                         users="Revenue management and Pricing teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/day forecasts + recommendations", "Multiple optimisation runs daily"))),
                    tile("Duetto GameChanger", "sheet", "Open pricing and segment-level optimisation for casinos and resorts.", "duetto",
                         cat="Revenue Management System (RMS)",
                         what="Open-pricing revenue platform optimising rate by segment and channel, tuned for casino and resort demand patterns.",
                         users="Revenue management and Casino marketing teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-4 GB/day", "Continuous optimisation cycles"))),
                    tile("Lighthouse", "observ", "Competitive rate shopping and hotel market demand intelligence.", "ota-insight",
                         cat="Rate Shopping & Market Intelligence",
                         what="Shops competitor rates and market demand signals to benchmark the property's price position against the compset.",
                         users="Revenue management and Commercial strategy teams.",
                         data_out=data_out(
                             batch=flow(["structured", "semi-structured"], "GBs of rate + demand data", "Multiple shops daily"))),
                ]},
                {"box": "Guest & Loyalty", "ic": "custlake", "tiles": [
                    tile("Salesforce Loyalty", "custlake", "Tier status, points accrual and partner earn across the portfolio.", "sf-loyalty",
                         cat="Loyalty Management Platform",
                         what="Manages member tiers, points accrual and redemption and partner-earn transactions across the portfolio.",
                         users="Loyalty, CRM and Marketing teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "1-5 GB/day", "Hourly / nightly sync"),
                             stream=flow(["semi-structured"], "tens of events/sec", "Continuous (accrual events)"))),
                    tile("Medallia Guest", "partner", "Post-stay surveys, sentiment and recovery workflows.", "medallia-guest",
                         cat="Guest Experience & Survey Platform",
                         what="Collects post-stay surveys and sentiment and drives service-recovery workflows tied to the guest and stay.",
                         users="Guest experience, Front office and Operations teams.",
                         data_out=data_out(
                             batch=flow(["structured", "unstructured"], "GBs of survey + verbatim text", "Continuous / daily"))),
                    tile("SevenRooms CRM", "product", "Restaurant reservations and guest preferences for F&B outlets.", "sevenrooms",
                         cat="Restaurant Reservation & Guest CRM",
                         what="Manages outlet reservations, waitlists and guest preferences for F&B venues within the property.",
                         users="F&B operations and Restaurant management teams.",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "tens of events/sec", "Continuous (reservation events)"))),
                ]},
                {"box": "Spa & Ancillary", "ic": "product", "tiles": [
                    tile("Book4Time Spa", "apps", "Spa and activity scheduling, therapist utilisation and retail attach.", "book4time",
                         cat="Spa & Activity Management System",
                         what="Schedules spa, wellness and activity appointments, tracks therapist utilisation and retail attach to the stay.",
                         users="Spa operations, Wellness and Ancillary revenue teams.",
                         data_out=data_out(
                             batch=flow(["structured"], "sub-GB/day", "Hourly / nightly sync"))),
                    tile("Agilysys InfoGenesis", "erp", "Outlet POS for restaurants, bars and room charges to folio.", "agilysys-pos",
                         cat="Food & Beverage POS",
                         what="Point-of-sale for restaurants, bars and outlets, posting F&B checks and room charges back to the guest folio.",
                         users="F&B operations, Outlet managers and Front office (room charges).",
                         data_out=data_out(
                             stream=flow(["semi-structured"], "hundreds of checks/sec at peak", "Continuous (POS transactions)"))),
                ]},
                fed_group("Ownership Group Marts", "Owner reporting and STR benchmark marts queried in place under Unity Catalog.",
                          cat="Owner Reporting Data Warehouse",
                          what="Owner-reporting and STR benchmark marts kept in the incumbent warehouse and queried in place through federation rather than copied.",
                          users="Asset management, Owner relations and Finance teams.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("STR Benchmark Feed", "chart", "Smith Travel Research comp set occupancy and rate benchmarks.", "str",
                     cat="Hotel Benchmarking Data",
                     what="Provides comp-set occupancy, ADR and RevPAR index benchmarks used to position the property against its competitive market.",
                     users="Revenue management, Commercial strategy and Owner reporting teams.",
                     data_out=data_out(
                         batch=flow(["structured"], "sub-GB/day", "Weekly + monthly benchmark files"))),
                tile("GDS Booking Messages", "stream", "Amadeus and Sabre hotel booking notifications parsed on arrival.", "amadeus-ihotelier",
                     cat="Global Distribution System (GDS)",
                     what="Carries hotel booking, modification and cancellation notifications from travel-agency GDS channels, parsed on arrival.",
                     users="Distribution and Central reservations teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "hundreds of msgs/sec at peak", "Continuous message flow"))),
                tile("Review Aggregator APIs", "observ", "TripAdvisor and Google review feeds for reputation monitoring.", "medallia-guest",
                     cat="Online Reputation & Review Data",
                     what="Aggregates public reviews and ratings from TripAdvisor, Google and OTAs for reputation monitoring and recovery.",
                     users="Guest experience, Marketing and Front office teams.",
                     data_out=data_out(
                         batch=flow(["semi-structured", "unstructured"], "GBs of review text", "Continuous / daily pulls"))),
            ]),
            "ppl": ppl2([
                biz("CEO & Brand Office", "Genie One", "The CEO on RevPAR and gross operating profit; the COO on guest satisfaction and labour productivity across the property portfolio.",
                    [["Genie One", "Ask what last weekend's RevPAR was without analyst delay."], ["AI/BI", "RevPAR and occupancy on certified Metric Views."], ["Unity Catalog", "One room night definition across PMS and finance."]],
                    sub=[
                        ["CEO", "portfolio RevPAR and gross operating profit, and the trade between growth and margin."],
                        ["COO", "guest satisfaction, labour productivity and service consistency across properties."],
                        ["Brand & Development", "brand standards, franchisee performance and the pipeline of new properties."],
                    ],
                    ucs=["Owner Reporting", "Occupancy Forecast", "Dynamic Pricing"]),
                biz("Revenue Management", "Model Serving", "Revenue managers on price ladders, overrides and group displacement, defending ADR and occupancy against the compset before rates publish.",
                    [["RMS Workbench", "Forecast, compset and recommendation history before override."], ["Model Serving", "Pricing models scored in the distribution path."]],
                    sub=[
                        ["Director of Revenue", "ADR, occupancy and RevPAR against the compset and the forecast."],
                        ["Pricing & Distribution", "rate ladders, channel mix and parity across OTA and direct."],
                        ["Group Revenue", "block pricing and displacement against transient demand."],
                    ],
                    ucs=["Dynamic Pricing", "Occupancy Forecast", "Channel Parity", "Group Displacement"]),
                biz("Front Office & Ops", "Lakehouse//RT", "GMs and front office on arrivals, housekeeping turn and service recovery, clearing rooms and VIP flags before the guest reaches the desk.",
                    [["Property Command", "Arrivals, VIP flags and housekeeping status on one screen."], ["Lakehouse//RT", "Room and task state at front-desk latency."]],
                    sub=[
                        ["General Manager", "arrivals, service recovery and the property's guest score."],
                        ["Front Office", "check-in flow, VIP flags and room readiness at the desk."],
                        ["Housekeeping & F&B Ops", "room turn, outlet covers and labour matched to forecast."],
                    ],
                    ucs=["Labour Scheduling", "Reputation Recovery", "Guest Personalization"]),
                biz("Sales & Groups", "AI/BI", "Sales directors on group blocks, catering revenue and conversion, watching pickup pace and wash against the block before the cutoff date.",
                    [["AI/BI", "Group pace and wash on certified views."], ["Genie One", "Ask which groups are below pickup pace."]],
                    sub=[
                        ["Director of Sales", "group pipeline, conversion and negotiated corporate rates."],
                        ["Group & Events", "block pickup, catering revenue and wash before the cutoff."],
                        ["Catering & Banquets", "event-space yield and F&B attach on group business."],
                    ],
                    ucs=["Group Displacement", "Occupancy Forecast", "Ancillary Attach"]),
                biz("Marketing & Loyalty", "CustomerLake", "CRM teams on campaigns, tier economics and personalisation, scoring offer propensity and tier migration across the guest portfolio.",
                    [["Loyalty Console", "Offer propensity and tier migration by segment."], ["CustomerLake", "Guest profiles without copying into a separate CDP."]],
                    sub=[
                        ["CRM & Loyalty", "tier economics, points liability and member retention."],
                        ["Guest Marketing", "segmentation, campaigns and pre-arrival personalisation."],
                        ["Ancillary & Partnerships", "spa, dining and partner-earn attach across the stay."],
                    ],
                    ucs=["Guest Personalization", "Loyalty Tier Migration", "Ancillary Attach"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land PMS reservations, CRS availability, POS folios and loyalty transactions; own Bronze to Silver and the pager when a RevPAR table stalls.",
                    [["Lakeflow Connect", "Managed connectors for PMS, CRS and loyalty sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on reservation and folio feeds."], ["Lakewatch", "Freshness on the RevPAR tables the revenue meeting reads."]],
                    sub=[
                        ["Ingestion Engineering", "PMS, CRS, POS and loyalty connectors and the Bronze-to-Silver path."],
                        ["Pipeline Reliability", "freshness and the pager when a RevPAR table stalls."],
                        ["Data Quality", "expectations on reservation and folio feeds before Gold publishes."],
                    ],
                    ucs=["Dynamic Pricing", "Occupancy Forecast", "Owner Reporting"]),
                biz("Data Scientists", "MLflow", "Demand-forecast, dynamic-pricing, personalisation and group-displacement models, and whether they still hold as compset and channel mix shift.",
                    [["Feature Store", "Guest and rate features read identically in training and serving."], ["MLflow", "Every forecast and pricing experiment tracked for audit."], ["Model Serving", "Pricing and offer models scored in the distribution path."]],
                    sub=[
                        ["Revenue Science", "demand-forecast and dynamic-pricing models against compset and mix."],
                        ["Personalisation Science", "offer-propensity and tier-migration models across the guest base."],
                        ["MLOps", "training-serving parity and whether a model still holds in season."],
                    ],
                    ucs=["Occupancy Forecast", "Guest Personalization", "Loyalty Tier Migration"]),
                biz("App Developers", "Apps", "Ship the Property Command, RMS Workbench and Loyalty Console apps revenue and front-office teams work in, next to governed PMS data.",
                    [["Apps", "Property screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for arrival and offer state writes."], ["Agent Bricks", "Agents that draft rate moves against governed tools."]],
                    sub=[
                        ["Front-of-House Apps", "Property Command arrivals, VIP and housekeeping screens."],
                        ["Commercial Apps", "RMS Workbench and Group Sales Hub for revenue and sales teams."],
                        ["Guest & Loyalty Apps", "Loyalty Console offers and stay history on governed data."],
                    ],
                    ucs=["Reputation Recovery", "Dynamic Pricing", "Ancillary Attach"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Portfolio and property dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for RevPAR and occupancy in the revenue meeting channel."),
                    tile("Notebooks & IDEs", "notebook", "Revenue science notebooks against governed PMS and RMS data."),
                ]},
                {"box": "Distribution & OTA", "ic": "partner", "tiles": [
                    tile("Channel Rate API", "api", "Rate and availability pushed to OTAs and metasearch.", "siteminder"),
                    tile("GDS Availability", "globe", "ARI updates to Amadeus and Sabre for travel agency bookings.", "sabre-synxis"),
                    tile("Corporate Travel Portal", "share", "Negotiated rates and booking rules shared to TMC partners."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("RMS Price Push", "market", "Recommended rates written back to CRS and channel manager.", "ideas-rms"),
                    tile("Housekeeping Tasks", "apps", "Room status and task lists pushed to attendant devices.", "opera-cloud"),
                    tile("Guest Pre-arrival", "custlake", "Upsell offers and preferences written to the arrival profile.", "mews"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Tourism Tax Filings", "gavel", "Occupancy and tourism taxes filed from night audit.", "opera-cloud"),
                    tile("Franchise Reporting", "share", "Brand-mandated KPIs submitted from contracted Gold products."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Portfolio performance products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Owners and brands reading live KPIs via Delta Sharing."),
                ]},
            ], genie_spaces=[
                genie("Revenue & Distribution", "Ask about RevPAR, ADR, pace and channel mix across properties in plain language.",
                      feeds=["IDeaS G3 RMS", "SiteMinder Channel", "Amadeus iHotelier", "RevPAR, ADR, occupancy"],
                      teams=["Revenue Management", "Director of Revenue", "Pricing & Distribution"],
                      questions=[
                          "What was RevPAR by property and segment last weekend versus the same weekend last year?",
                          "Which channels are driving the most bookings this week, and at what net ADR?",
                          "Where is booking pace behind the forecast for the next 30 days?",
                          "Which properties are out of rate parity against the compset right now?",
                          "How does length-of-stay mix compare to the same period last year?"]),
                genie("Guest 360 & Loyalty", "Explore guest profiles, loyalty tiers and stay history across the portfolio.",
                      feeds=["Salesforce Loyalty", "Oracle OPERA Cloud", "SevenRooms CRM", "Conformed guest, stay, room"],
                      teams=["Marketing & Loyalty", "CRM & Loyalty", "Guest Marketing"],
                      questions=[
                          "What is the total stay value of this guest across every property in the portfolio?",
                          "Which loyalty members are at risk of tier downgrade before their renewal?",
                          "Which high-value guests have an upcoming arrival with no upsell offered?",
                          "What is points liability by tier and how has it moved this quarter?",
                          "Which guests have strong ancillary attach but no spa booking on their next stay?"]),
                genie("Property Operations", "Answer questions on arrivals, housekeeping, service recovery and outlet performance.",
                      feeds=["Oracle OPERA Cloud", "Agilysys InfoGenesis", "Medallia Guest", "Conformed guest, stay, room"],
                      teams=["Front Office & Ops", "General Manager", "Housekeeping & F&B Ops"],
                      questions=[
                          "How many VIP arrivals are due today and are their rooms ready?",
                          "Which properties have the longest housekeeping turn times this week?",
                          "What are the top guest-complaint drivers by property this month?",
                          "How is outlet F&B revenue tracking against covers by daypart?",
                          "Which detractor surveys are still open past their recovery SLA?"]),
                genie("Owner & Portfolio", "Ask about owner statements, NOI and STR index position across the estate.",
                      feeds=["Ownership Group Marts", "STR Benchmark Feed", "RevPAR, ADR, occupancy"],
                      teams=["CEO & Brand Office", "Brand & Development", "Revenue Management"],
                      questions=[
                          "How does each property's RevPAR index compare to its compset this month?",
                          "What is gross operating profit by property versus budget?",
                          "Which owned assets are underperforming their STR fair-share?",
                          "How has ancillary revenue per available room trended this year?",
                          "What is portfolio occupancy forecast against target for the next quarter?"]),
            ], dashboards=[
                dashboard("RevPAR & Occupancy", "Portfolio RevPAR, ADR and occupancy on certified revenue Metric Views.",
                          kpis=["RevPAR", "ADR", "Occupancy", "RevPAR index", "Booking pace"],
                          teams=["Revenue Management", "CEO & Brand Office", "Sales & Groups"]),
                dashboard("Guest Experience & Reputation", "Survey scores, sentiment and recovery throughput across properties.",
                          kpis=["Guest satisfaction score", "Net promoter score", "Detractor recovery rate", "Review rating", "Response time"],
                          teams=["Front Office & Ops", "Marketing & Loyalty", "General Manager"]),
                dashboard("Loyalty & Ancillary", "Loyalty tier movement, points liability and ancillary attach across the stay.",
                          kpis=["Active members", "Tier migration", "Points liability", "Ancillary attach rate", "Redemption rate"],
                          teams=["Marketing & Loyalty", "CRM & Loyalty", "Ancillary & Partnerships"]),
                dashboard("Distribution & Channel", "Channel mix, cost of distribution and parity across OTA, GDS and direct.",
                          kpis=["Channel mix", "Cost of distribution", "Direct booking share", "Net ADR by channel", "Parity breaches"],
                          teams=["Revenue Management", "Pricing & Distribution", "CEO & Brand Office"]),
            ]),
        },
        "top": top_band(
            [app("Property Command", "Front office", "gauge", "Arrivals, VIP flags, housekeeping and service issues on Databricks Apps over Lakebase."),
             app("RMS Workbench", "Pricing decisions", "market", "Forecast, compset position and override history before rates publish."),
             app("Loyalty Console", "Guest CRM", "custlake", "Tier status, offer propensity and stay history for personalised engagement."),
             app("Group Sales Hub", "Blocks & events", "sheet", "Group pickup, catering revenue and wash risk before the cutoff date.")],
            [uc("Dynamic Pricing", "Revenue", "market", "Open pricing by segment and channel rather than fixed BAR ladders.",
                 problem="Rates move on fixed BAR ladders set days ahead, so when demand or the compset shifts the price is already wrong and revenue managers chase it with manual overrides.",
                 who="Revenue Management",
                 how="Booking pace, PMS demand and rate-shopping feeds land in Delta Lake, are scored for optimal open pricing in Model Serving, and publish from the RMS Workbench to the channel.",
                 comps=["RMS Workbench", "IDeaS G3 RMS", "Lighthouse", "Model Serving", "Delta Lake"],
                 stories=[
                     ["easyJet modernises airline revenue management on Databricks", "https://www.databricks.com/customers/easyjet/lakebase"],
                     ["Amadeus optimizes travel pricing and personalization", "https://www.databricks.com/customers/amadeus"],
                 ]),
             uc("Occupancy Forecast", "Planning", "chart", "Demand forecast by property, segment and length of stay.",
                 problem="Occupancy is projected from last year plus a manager's feel, so staffing, pricing and group decisions rest on a forecast that misses events, weather and shifting booking pace.",
                 who="Revenue Management",
                 how="Reservation, pace and STR benchmark history become features in Feature Store, scored by Model Serving into a property-segment-LOS forecast tracked in MLflow and read in the RMS Workbench.",
                 comps=["RMS Workbench", "STR Benchmark Feed", "Feature Store", "Model Serving", "MLflow"],
                 stories=[
                     ["Amadeus forecasts travel demand across the passenger journey", "https://www.databricks.com/customers/amadeus"],
                     ["JetBlue accelerates revenue and demand forecasting", "https://www.databricks.com/blog/accelerating-innovation-jetblue-using-databricks"],
                 ]),
             uc("Guest Personalization", "CRM", "custlake", "Pre-arrival upsell and in-stay offers scored per guest profile.",
                 problem="Booking, stay, spend and preference data sit in separate systems, so pre-arrival and in-stay offers are generic and the guest is treated as a stranger at every property in the portfolio.",
                 who="Marketing & Loyalty",
                 how="Guest profiles are unified in CustomerLake, offer-propensity features in Feature Store are scored by Model Serving, and ranked offers surface in the Loyalty Console and arrival profile.",
                 comps=["Loyalty Console", "Salesforce Loyalty", "CustomerLake", "Model Serving", "Feature Store"],
                 stories=[
                     ["Hotels.com personalizes recommendations at scale", "https://www.databricks.com/customers/hotels-com"],
                     ["Hilton Grand Vacations unifies guest data for personalization", "https://www.databricks.com/customers/hilton-grand-vacations"],
                 ]),
             uc("Reputation Recovery", "Service", "partner", "Negative reviews and survey detractors routed to recovery workflows.",
                 problem="Negative reviews and survey detractors surface days later across scattered inboxes and portals, so recovery happens after the guest has left and the rating is already public.",
                 who="Front Office & Ops",
                 how="Review and survey feeds land continuously, AI Functions classify sentiment and severity, and Model Serving routes at-risk guests to recovery tasks in Property Command.",
                 comps=["Property Command", "Medallia Guest", "Review Aggregator APIs", "AI Functions", "Model Serving"],
                 stories=[
                     ["How AI is redefining the travel and hospitality experience", "https://www.databricks.com/blog/booking-bon-voyage-how-ai-redefining-travel-hospitality-experience"],
                 ]),
             uc("Labour Scheduling", "Operations", "people", "Housekeeping and F&B labour matched to forecast occupancy.",
                 problem="Housekeeping and F&B rosters are built on static templates, so a demand swing leaves rooms unturned and outlets over- or understaffed, driving overtime and slow service recovery.",
                 who="Front Office & Ops",
                 how="Forecast occupancy and outlet covers from operations feeds are scored in Model Serving against labour standards, and the resulting shift plan is read in Property Command and AI/BI.",
                 comps=["Property Command", "Oracle OPERA Cloud", "Agilysys InfoGenesis", "Model Serving", "AI/BI"]),
             uc("Channel Parity", "Distribution", "api", "Rate and availability parity monitored across OTA and direct.",
                 problem="Rates and availability drift out of parity across OTAs, metasearch and direct, so the brand loses the buy box, pays avoidable commission and confuses guests comparing prices.",
                 who="Revenue Management",
                 how="Distribution and rate-shopping feeds stream into Lakehouse//RT, where AI Functions flag parity breaks against Delta Lake and alert revenue teams before bookings shift.",
                 comps=["SiteMinder Channel", "Lighthouse", "Lakehouse//RT", "AI Functions", "Delta Lake"]),
             uc("Group Displacement", "Sales", "sheet", "Group blocks evaluated against transient opportunity cost.",
                 problem="Group blocks are quoted without knowing what transient demand they push out, so sales books low-rate rooms on high-demand dates and displaces revenue the property would have earned.",
                 who="Sales & Groups",
                 how="Group requests are evaluated against the transient forecast and rate history in Model Serving, and displacement and catering value surface in the Group Sales Hub before the block is signed.",
                 comps=["Group Sales Hub", "IDeaS G3 RMS", "Model Serving", "AI/BI", "Delta Lake"]),
             uc("Ancillary Attach", "F&B", "product", "Spa, dining and experience attach scored at booking and check-in.",
                 problem="Spa, dining and experience revenue is left to chance at the desk, so high-intent guests are never offered the add-on that fits and ancillary spend trails the property's real potential.",
                 who="Marketing & Loyalty",
                 how="Stay and preference data feed attach-propensity features in Feature Store, scored by Model Serving to surface the right spa or dining offer in the Loyalty Console at check-in.",
                 comps=["Loyalty Console", "Book4Time Spa", "SevenRooms CRM", "Model Serving", "Feature Store"],
                 stories=[
                     ["From booking to bon voyage: dynamic offers across the guest journey", "https://www.databricks.com/blog/booking-bon-voyage-how-ai-redefining-travel-hospitality-experience"],
                 ]),
             uc("Loyalty Tier Migration", "Loyalty", "custlake", "Tier upgrade and churn risk scored before renewal windows.",
                 problem="Loyalty tiers are reviewed in slow batch cycles, so members drift toward downgrade or churn before anyone notices and high-value guests get the same generic nudge as everyone else.",
                 who="Marketing & Loyalty",
                 how="Accrual, stay and engagement data unify in CustomerLake, and tier-migration and churn models tracked in MLflow are scored by Model Serving into the Loyalty Console before the renewal window.",
                 comps=["Loyalty Console", "Salesforce Loyalty", "CustomerLake", "Model Serving", "MLflow"],
                 stories=[
                     ["How AI redefines loyalty engagement in travel and hospitality", "https://www.databricks.com/blog/booking-bon-voyage-how-ai-redefining-travel-hospitality-experience"],
                     ["MakeMyTrip achieves millisecond personalization at scale", "https://www.databricks.com/blog/how-makemytrip-achieved-millisecond-personalization-scale-databricks"],
                 ]),
             uc("Owner Reporting", "Finance", "erp", "Owner statements and STR index position from governed night audit.",
                 problem="Owner statements and STR index positions are assembled by hand from night-audit exports, so owners wait days for numbers and every management company reconciles a slightly different figure.",
                 who="CEO & Brand Office",
                 how="Night-audit and benchmark data are conformed under Unity Catalog and published as governed Data Products shared to owners and brands over Open Sharing, so everyone reads one live figure.",
                 comps=["Ownership Group Marts", "STR Benchmark Feed", "Unity Catalog", "Data Products", "Open Sharing"])],
        ),
        "sources": {
            "opera-cloud": {"t": "Oracle OPERA Cloud", "u": "https://www.oracle.com/hospitality/hotel-property-management/"},
            "mews": {"t": "Mews PMS", "u": "https://www.mews.com/"},
            "infor-hms": {"t": "Infor HMS", "u": "https://www.infor.com/industries/hospitality"},
            "amadeus-ihotelier": {"t": "Amadeus iHotelier", "u": "https://amadeus.com/en/industries/hotels"},
            "sabre-synxis": {"t": "Sabre SynXis", "u": "https://www.sabrehospitality.com/"},
            "siteminder": {"t": "SiteMinder", "u": "https://www.siteminder.com/"},
            "ideas-rms": {"t": "IDeaS G3 RMS", "u": "https://ideas.com/"},
            "duetto": {"t": "Duetto", "u": "https://www.duettocloud.com/"},
            "ota-insight": {"t": "Lighthouse", "u": "https://www.mylighthouse.com/"},
            "sf-loyalty": {"t": "Salesforce Loyalty Management", "u": "https://www.salesforce.com/products/loyalty-management/"},
            "medallia-guest": {"t": "Medallia for hospitality", "u": "https://www.medallia.com/industries/hospitality/"},
            "sevenrooms": {"t": "SevenRooms", "u": "https://sevenrooms.com/"},
            "book4time": {"t": "Book4Time", "u": "https://www.book4time.com/"},
            "agilysys-pos": {"t": "Agilysys InfoGenesis", "u": "https://www.agilysys.com/"},
            "str": {"t": "STR benchmarks", "u": "https://str.com/"},
        },
    },
}
