import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (
    app, biz, cons_rail, dashboard, data_out, fed_group, flow, genie, ing_rail,
    medallion, tile, top_band, uc,
)


def ppl_rail2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles instead of shared TECH_PPL."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles},
    ]


INDUSTRIES_BATCH_MINING = {
    'mining': {
        "label": "Mining",
        "blurb": "Extraction and processing: pit and underground operations, fleet and plant telemetry, grade control, and export logistics for metals and bulk commodities.",
        "medallion": medallion(
            "Raw pit feeds",
            "Fleet dispatch, shovel and truck cycles, plant SCADA tags, lab assays and port load events, landed exactly as received so a ton or a grade can always be replayed as it stood.",
            "Conformed block, fleet",
            "Blocks, benches, equipment and shipments resolved into single conformed entities across dispatch, plant and commercial systems, with sample IDs reconciled and stockpile movements stitched to one inventory position.",
            "Grade, cost, recovery",
            "Contracted products operations and commercial teams run on: recovered metal per tonne milled, unit cash cost, fleet productivity and port demurrage exposure by cargo.",
        ),
        "rails": {
            "src": [
                {"box": "Fleet & Dispatch", "ic": "iot", "tiles": [
                        tile("Modular Mining DISPATCH", "iot", "Shovel-truck assignment, queue times and payload cycles from the open-pit dispatch system.", "modular",
                             cat="Fleet Management System (FMS)",
                             what="Runs open-pit shovel-truck assignment, queue times and payload cycles as the real-time fleet dispatch system of record.",
                             users="Dispatch controllers, mine operations and production engineers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "1-5 GB/day cycle history", "Shift-end + hourly rollups"),
                                 stream=flow(["semi-structured"], "1-10k events/sec", "Continuous (real-time assignments)"))),
                        tile("Hexagon MineOperate", "stream", "Underground and surface fleet location, production reporting and operator logs.", "hexagon",
                             cat="Fleet Management System (FMS)",
                             what="Tracks underground and surface fleet location, production reporting and operator logs across the operation.",
                             users="Mine operations, dispatch controllers and production reporting teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "1-8k events/sec", "Continuous (location + production)"))),
                        tile("Maptek BlastLogic", "sheet", "Drill and blast designs, actuals and fragmentation linked to dig blocks.", "maptek",
                             cat="Drill & Blast Management System",
                             what="Holds drill and blast designs, actuals and fragmentation results linked to dig blocks for grade and productivity analysis.",
                             users="Drill & blast engineers, grade control geologists and mine planning.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Per-blast + daily updates"))),
                    ]},
                {"box": "Plant & Processing", "ic": "stream", "tiles": [
                        tile("AVEVA PI System", "iot", "Mill throughput, reagent flows and recovery tags from concentrator historians.", "aveva-pi",
                             cat="Process/Time-Series Historian",
                             what="Stores mill throughput, reagent flows and recovery tags from concentrator plants as the processing time-series system of record.",
                             users="Plant metallurgists, concentrator operators and reliability engineers.",
                             data_out=data_out(
                                 batch=flow(["structured"], "10-50 GB/day tag history", "Hourly aggregates"),
                                 stream=flow(["semi-structured"], "10-100k tags/sec", "Continuous (sub-second)"))),
                        tile("Metso Metrics", "gauge", "Cloud monitoring of crusher, mill and screen performance against nameplate and maintenance windows.", "metso",
                             cat="Equipment Performance Monitoring",
                             what="Cloud monitoring of crusher, mill and screen performance against nameplate and maintenance windows for reliability and throughput.",
                             users="Reliability engineers, maintenance planning and plant operations.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-2 GB/day", "Hourly / daily"),
                                 stream=flow(["semi-structured"], "hundreds of readings/sec", "Continuous equipment telemetry"))),
                        tile("LIMS Assay Lab", "gavel", "Sample preparation, assay results and QA/QC duplicates for grade control.", "lims",
                             cat="Laboratory Information Management (LIMS)",
                             what="Manages sample preparation, assay results and QA/QC duplicates that grade control and metal accounting depend on.",
                             users="Assay lab, grade control geologists and metallurgists.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-2 GB/day assays", "Per-batch + daily"))),
                    ]},
                {"box": "Commercial & ERP", "ic": "erp", "tiles": [
                        tile("SAP IS-Mining", "erp", "Production orders, inventory, sales contracts and settlement postings.", "sap-mining",
                             cat="Mining ERP",
                             what="Runs production orders, inventory, sales contracts and settlement postings on the industry SAP mining core.",
                             users="Commercial, supply chain and Finance teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "5-20 GB/day", "Nightly batch + monthly close"))),
                        tile("Metal Bulletin", "market", "Benchmark prices and index curves the marketing desk hedges against.", "metal-bulletin",
                             cat="Commodity Price Benchmark Provider",
                             what="Supplies benchmark metal prices and index curves the marketing and treasury desks mark and hedge physical delivery against.",
                             users="Commercial, marketing and treasury/hedging teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "MBs reference data", "Daily price publication"))),
                        tile("Port Community System", "globe", "Vessel nominations, stow plans and weighbridge tickets at export terminals.", "pcs",
                             cat="Port & Terminal Operating System",
                             what="Manages vessel nominations, stow plans and weighbridge tickets at export terminals for bulk commodity shipping.",
                             users="Logistics & shipping, port operations and commercial teams.",
                             data_out=data_out(
                                 batch=flow(["structured"], "0.5-2 GB/day", "Per-vessel + daily updates"))),
                    ]},
                {"box": "Safety & Environment", "ic": "gavel", "tiles": [
                        tile("Intelex EHS", "gavel", "Incidents, near-misses and permit-to-work records tied to site and crew.", "intelex",
                             cat="EHS Management System",
                             what="Records incidents, near-misses and permit-to-work compliance tied to site and crew for safety analytics.",
                             users="HSE managers, site safety and operations supervisors.",
                             data_out=data_out(
                                 batch=flow(["structured", "semi-structured"], "0.5-2 GB/day", "Hourly / daily"))),
                        tile("Envirosuite", "observ", "Dust, noise and blast vibration monitoring against community thresholds.", "envirosuite",
                             cat="Environmental Monitoring System",
                             what="Monitors dust, noise and blast vibration against community and regulatory thresholds around the operation.",
                             users="Environment leads, community relations and compliance teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "hundreds of readings/sec", "Continuous sensor monitoring"))),
                        tile("Wearable Proximity", "iot", "Tag collision and zone breach events from personnel and equipment proximity systems.",
                             cat="Proximity Detection / Collision Avoidance",
                             what="Emits tag collision and zone-breach events from personnel and equipment proximity systems for fatal-risk protection.",
                             users="HSE managers, mine operations and safety analytics teams.",
                             data_out=data_out(
                                 stream=flow(["semi-structured"], "1-10k events/sec", "Continuous (event-driven)"))),
                    ]},
                fed_group("Corporate Risk Ledger", "Hedging and working-capital marts queried in place under Unity Catalog for treasury reporting.",
                          cat="Enterprise Data Warehouse",
                          what="Corporate hedging and working-capital marts kept in the incumbent treasury warehouse and queried in place through federation rather than copied.",
                          users="Treasury & hedging, Finance and Risk analysts.",
                          data_out=data_out(
                              batch=flow(["structured"], "TB-scale historical marts", "Queried on demand (federated)"))),
            ],
            "ing": ing_rail([
                tile("High-Precision GPS", "iot", "RTK survey and machine guidance files normalised for block model updates.", "hexagon",
                     cat="Survey & Machine Guidance Feed",
                     what="RTK survey and machine-guidance files normalised for block-model updates and as-mined reconciliation.",
                     users="Surveyors, grade control geologists and mine planning.",
                     data_out=data_out(
                         batch=flow(["structured"], "0.5-2 GB/day", "Per-survey + shift updates"))),
                tile("Satellite Imagery", "globe", "Pit shell and stockpile volumetrics from periodic earth-observation feeds.", "planet",
                     cat="Earth Observation / Remote Sensing",
                     what="Pit shell and stockpile volumetrics derived from periodic earth-observation imagery for inventory and progress reconciliation.",
                     users="Survey, stockpile management and mine planning teams.",
                     data_out=data_out(
                         batch=flow(["unstructured"], "GBs/scene", "Periodic (revisit cycle)"))),
                tile("Rail Wagon Telemetry", "stream", "Load, location and brake events from outbound rail convoys to port.", "pcs",
                     cat="Rail Logistics Telemetry",
                     what="Load, location and brake events from outbound rail convoys, streamed in to reconcile the mine-to-port flow.",
                     users="Logistics & shipping and rail operations teams.",
                     data_out=data_out(
                         stream=flow(["semi-structured"], "100s-1000s of events/sec", "Continuous (in-transit telemetry)"))),
            ]),
            "ppl": ppl_rail2([
                biz("Site Leadership", "Genie One", "The general manager on tonnes milled, grade recovery and unit cash cost when weather or an unplanned equipment stop limits the month's plan.", [["Genie One", "Ask what yesterday's mill recovery was without waiting on the morning report."], ["AI/BI", "Grade, cost and fleet KPIs on one certified set of Metric Views."], ["Unity Catalog", "Certification so \"head grade\" means one thing across mine and plant."]],
                    sub=[["General Manager", "the monthly plan: tonnes milled, head grade and unit cash cost against budget."], ["Operations Superintendent", "pit-to-plant coordination and where the shift is losing productivity."], ["Site Finance", "cost per tonne, sustaining capital and the stockpile and demurrage working capital."]],
                    ucs=["Mine Planning", "Mill Recovery", "Fleet Optimisation", "Energy & Emissions"]),
                biz("Mine Operations", "Lakehouse//RT", "Pit sequencing, dig rates and truck queue times when a shovel goes down, protecting fleet productivity and unit cost per tonne moved.", [["Pit Control Tower", "Fleet reallocation options costed before the shift plan changes."], ["Lakehouse//RT", "Dispatch state at the latency a queue builds at."], ["AI/BI", "Payload and cycle time on governed definitions."]],
                    sub=[["Mine Manager", "the pit sequence, dig rates and whether the fleet is meeting the daily plan."], ["Dispatch Controller", "shovel-truck assignment and truck queue time in real time across the pit."], ["Drill & Blast Engineer", "blast design, fragmentation and how it feeds the dig blocks and grade."]],
                    ucs=["Grade Control", "Fleet Optimisation", "Predictive Maintenance", "Mine Planning"]),
                biz("Processing", "AI/BI", "Mill stability, reagent consumption and recovered metal per tonne milled when feed grade and ore hardness shift through the shift.", [["Plant Performance", "Recovery and throughput variance flagged before metal is lost."], ["Model Serving", "Grade-control models scored on blast and assay feeds."], ["Genie One", "Ask which circuit is constraining recovery today."]],
                    sub=[["Plant Metallurgist", "recovery, reagent dosing and recovered metal per tonne milled as feed shifts."], ["Concentrator Superintendent", "mill throughput, circuit stability and the constraint through the shift."], ["Grade Control Geologist", "ore-versus-waste calls and reconciling assays back to the block model."]],
                    ucs=["Mill Recovery", "Grade Control", "Predictive Maintenance"]),
                biz("Marketing & Sales", "AI/BI", "Contract delivery, assay disputes and hedge exposure against benchmark moves, tracked on realised price and TC/RC terms by cargo.", [["Shipment Tracker", "Cargo assay and moisture reconciled before invoice."], ["AI/BI", "Realised price and TC/RC on certified Metric Views."], ["Unity Catalog", "One definition of contained metal across mine and port."]],
                    sub=[["Commercial Manager", "realised price, TC/RC terms and contract delivery by cargo."], ["Logistics & Shipping", "vessel laytime, demurrage exposure and the stockpile-to-port flow."], ["Treasury & Hedging", "benchmark exposure and hedge effectiveness against the physical book."]],
                    ucs=["Export Logistics", "Stockpile Management", "Commodity Hedging"]),
                biz("Safety & ESG", "Unity Catalog", "Fatal-risk protocols, Scope 1 emissions and community commitments the board signs, tracked on TRIFR and permit-breach counts before audit.", [["Safety Dashboard", "Leading indicators and permit breaches before audit."], ["Unity Catalog", "Lineage from sensor to regulatory disclosure."], ["AI/BI", "TRIFR and emissions on governed definitions."]],
                    sub=[["HSE Manager", "fatal-risk protocols, TRIFR and permit-to-work compliance before audit."], ["Environment Lead", "dust, noise, tailings and Scope 1 emissions against community thresholds."], ["Community & Governance", "the commitments the board signs and the disclosures regulators read."]],
                    ucs=["Safety Analytics", "Energy & Emissions"]),
            ], [
                biz("Data Engineers", "Lakeflow", "Land the dispatch, plant SCADA, assay lab and port load feeds; own the Bronze to Silver path and the pager when a site pipeline breaks.", [["Lakeflow Connect", "Managed connectors for DISPATCH, historian and LIMS sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on cycle and assay feeds."], ["Lakewatch", "Freshness on the grade and fleet tables the morning report reads."]],
                    sub=[["Pipeline Engineers", "the Bronze-to-Silver path for dispatch, historian, LIMS and port feeds."], ["Streaming Engineers", "SCADA and telemetry landed at the latency a truck queue builds at."], ["Platform & Governance", "Unity Catalog lineage so head grade means one thing mine to plant."]],
                    ucs=["Grade Control", "Fleet Optimisation", "Export Logistics"]),
                biz("Data Scientists", "MLflow", "Grade-control, recovery, haul-truck RUL and demurrage models, and whether they still hold six months after deployment across pit and plant.", [["Feature Store", "Blast and assay features read identically in training and serving."], ["MLflow", "Every grade and recovery run tracked for audit and reproduction."], ["Model Serving", "Grade-control models scored on blast and assay feeds."]],
                    sub=[["Geometallurgy ML", "grade-control and recovery models across the blast and assay feeds."], ["Reliability Data Science", "haul-truck and mill remaining-life models on streaming telemetry."], ["Operations Research", "fleet, blending and logistics optimisation against demurrage and cost."]],
                    ucs=["Mill Recovery", "Predictive Maintenance", "Grade Control"]),
                biz("App Developers", "Apps", "Ship the pit control, plant performance and shipment applications operators and marketers work in, hosted next to governed mine data.", [["Apps", "Operational screens with no separate web tier to run or secure."], ["Lakebase", "Serverless Postgres for dispatch state and governed writes."], ["Agent Bricks", "Agents that draft a fleet reallocation against governed tools."]],
                    sub=[["Operational App Devs", "the pit control, plant performance and shipment screens operators live in."], ["Integration Engineers", "writeback to DISPATCH, DCS setpoints and CMMS work orders."], ["Agent Builders", "governed agents that draft a fleet reallocation or a work order."]],
                    ucs=["Fleet Optimisation", "Mill Recovery", "Export Logistics"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                        tile("Tableau / Qlik / ThoughtSpot", "chart", "External BI against serverless SQL warehouses, with Unity Catalog permissions enforced end to end."),
                        tile("Microsoft Teams", "chat", "Genie in Teams for governed answers and shift updates in the channel the pit already works in (Beta)."),
                        tile("Notebooks & IDEs", "notebook", "Notebooks, VS Code and JetBrains against governed data and Genie Code."),
                    ]},
                {"box": "Operations Writeback", "ic": "opdb", "tiles": [
                        tile("DISPATCH Reassignment", "iot", "Truck and shovel assignments written back when the optimiser changes the shift plan.", "modular"),
                        tile("Plant Setpoint", "stream", "Approved reagent and density targets pushed to DCS within operating envelopes.", "aveva-pi"),
                        tile("Maintenance Work Order", "erp", "Predicted component failures raised in CMMS before the truck leaves service.", "metso"),
                    ]},
                {"box": "Customers & Port", "ic": "partner", "tiles": [
                        tile("Assay Certificate API", "api", "Cargo certificates served to smelters and traders from governed lab lineage.", "lims"),
                        tile("Trader Data Sharing", "share", "Stockpile and shipment positions shared to offtake partners over Delta Sharing.", "metal-bulletin"),
                        tile("Rail & Port Partners", "globe", "Nomination and stow data exchanged without nightly spreadsheet reconciliation.", "pcs"),
                    ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                        tile("Mine Safety Reporting", "gavel", "Regulator submissions produced from the same governed tables operations runs on.", "intelex"),
                        tile("Emissions & Tailings", "share", "Scope 1 and water disclosures filed from contracted Gold products.", "envirosuite"),
                    ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                        tile("Data Products", "product", "Published, contracted products discoverable in Unity Catalog Domains and shared over OpenSharing."),
                        tile("Sharing Recipients", "share", "Traders, smelters and joint-venture partners reading live tables with no copy."),
                    ]},
            ], genie_spaces=[
                genie("Fleet & Pit Productivity", "Ask about payload, cycle time, queue and fleet productivity across the pit in plain language.",
                      feeds=["Modular Mining DISPATCH", "Hexagon MineOperate", "High-Precision GPS", "Conformed block, fleet"],
                      teams=["Mine Operations", "Site Leadership", "Dispatch Controller"],
                      questions=[
                          "What was fleet productivity by shift yesterday?",
                          "Where are truck queues building right now and why?",
                          "Which trucks and shovels are underperforming their payload target?",
                          "How much did idle time cost us in diesel this week?",
                          "Which pit areas are limiting dig rate against the plan?"]),
                genie("Grade & Recovery", "Explore head grade, recovery and metal accounting across mine and plant.",
                      feeds=["LIMS Assay Lab", "Maptek BlastLogic", "AVEVA PI System", "Grade, cost, recovery"],
                      teams=["Processing", "Grade Control Geologist", "Plant Metallurgist"],
                      questions=[
                          "What was mill recovery yesterday versus plan?",
                          "Which circuit is constraining recovery today?",
                          "How does reconciled grade compare to the block model this month?",
                          "How much metal did we lose to tailings this shift?",
                          "Which blast blocks are diluting mill feed right now?"]),
                genie("Commercial & Shipping", "Answer questions on realised price, TC/RC terms, cargoes and demurrage.",
                      feeds=["SAP IS-Mining", "Metal Bulletin", "Port Community System", "Rail Wagon Telemetry"],
                      teams=["Marketing & Sales", "Logistics & Shipping", "Treasury & Hedging"],
                      questions=[
                          "What is our realised price versus benchmark by cargo this month?",
                          "What is our current demurrage exposure across vessels?",
                          "Which cargoes are at risk of missing their laycan?",
                          "How effective are our hedges against the physical book?",
                          "Which contracts have open assay disputes right now?"]),
                genie("Safety & ESG", "Ask about safety leading indicators, permits and emissions across the operation.",
                      feeds=["Intelex EHS", "Wearable Proximity", "Envirosuite", "Corporate Risk Ledger"],
                      teams=["Safety & ESG", "HSE Manager", "Environment Lead"],
                      questions=[
                          "What is our TRIFR trend this year?",
                          "How many proximity or zone-breach events happened this week?",
                          "Which permits are closest to a breach right now?",
                          "What is our Scope 1 emissions intensity per tonne this month?",
                          "Where are dust or vibration readings approaching community thresholds?"]),
            ], dashboards=[
                dashboard("Pit & Fleet Productivity", "Payload, cycle time, queue and fleet productivity on certified operations Metric Views.",
                          kpis=["Fleet productivity", "Payload variance", "Truck queue time", "Cycle time", "Idle time"],
                          teams=["Mine Operations", "Site Leadership", "Dispatch Controller"]),
                dashboard("Grade & Recovery", "Head grade, recovery, throughput and metal accounting across mine and plant.",
                          kpis=["Mill recovery", "Head grade", "Throughput", "Recovered metal per tonne", "Grade reconciliation"],
                          teams=["Processing", "Grade Control Geologist", "Plant Metallurgist"]),
                dashboard("Commercial & Logistics", "Realised price, TC/RC, demurrage and cargo performance.",
                          kpis=["Realised price vs benchmark", "TC/RC terms", "Demurrage exposure", "Cargo on-time rate", "Hedge effectiveness"],
                          teams=["Marketing & Sales", "Logistics & Shipping", "Treasury & Hedging"]),
                dashboard("Safety & ESG", "Safety leading indicators, permit compliance and Scope 1 emissions intensity.",
                          kpis=["TRIFR", "Proximity events", "Permit exceedances", "Scope 1 intensity", "Dust/vibration exceedances"],
                          teams=["Safety & ESG", "HSE Manager", "Environment Lead"]),
            ]),
        },
        "top": top_band(
            [
                app("Pit Control Tower", "Fleet dispatch", "gauge", "Shovel queues, payload variance and reallocation options on Databricks Apps over Lakebase."),
                app("Plant Performance", "Recovery live", "stream", "Mill throughput and recovery against plan with constraint flags before metal is lost."),
                app("Grade Control", "Block model", "sheet", "Blast, dig and assay reconciled for short-term model updates before the shovel moves."),
                app("Shipment Tracker", "Export cargo", "globe", "Port stock, vessel laytime and assay disputes on one surface for marketing."),
            ],
            [
                uc("Grade Control", "Ore body", "sheet", "Short-term model updates from blast, dig and assay before material is misrouted.",
                    problem="Ore and waste are called from sparse blast-hole assays on a model that lags the dig face, so misrouted material dilutes mill feed and grade is reconciled long after the shovel has moved.",
                    who="Mine Operations",
                    how="Blast, dig and assay feeds land through Lakeflow and conform on Delta Lake, then grade-control models score short-term block updates in the Grade Control app before the shovel moves.",
                    comps=["Grade Control", "Maptek BlastLogic", "LIMS Assay Lab", "Model Serving", "Delta Lake", "Unity Catalog"],
                    stories=[["Nexa mines less waste and more value with AI-driven insights", "https://www.databricks.com/customers/nexa"]]),
                uc("Fleet Optimisation", "Productivity", "iot", "Truck and shovel matching tuned to queue time and fuel not static rules.",
                    problem="Truck and shovel assignment runs on static rules and a controller's judgement, so queues build at shovel and crusher, diesel burns idling and fleet productivity swings shift to shift.",
                    who="Mine Operations",
                    how="Dispatch, GPS and payload state stream into Lakehouse//RT, and matching models scored in Model Serving feed reallocation options to the Pit Control Tower before the shift plan changes.",
                    comps=["Pit Control Tower", "Modular Mining DISPATCH", "High-Precision GPS", "Lakehouse//RT", "Model Serving", "Delta Lake"],
                    stories=[["Sandvik enables collaboration and real-time equipment insight", "https://www.databricks.com/customers/sandvik"]]),
                uc("Mill Recovery", "Processing", "gauge", "Circuit recovery maximised when feed grade and hardness shift.",
                    problem="Feed grade and ore hardness drift through the shift, and by the time recovery drops in the lab result metal has already been lost to tailings that no reagent change can bring back.",
                    who="Processing",
                    how="Concentrator historian and assay tags conform on Delta Lake, and recovery models scored in Model Serving flag circuit constraints in the Plant Performance app before metal is lost.",
                    comps=["Plant Performance", "AVEVA PI System", "Metso Metrics", "Model Serving", "MLflow", "Delta Lake"],
                    stories=[["Nexa mines less waste and more value with AI-driven insights", "https://www.databricks.com/customers/nexa"]]),
                uc("Predictive Maintenance", "Assets", "stream", "Haul truck and mill failures predicted before they remove capacity from the plan.",
                    problem="Haul trucks and mills fail between inspections and pull capacity out of the plan, so a component is found broken after the machine stops rather than predicted from its own telemetry.",
                    who="Mine Operations",
                    how="Equipment telemetry streams into Lakehouse//RT and feeds remaining-life models tracked in MLflow and scored in Model Serving, raising a CMMS work order before the truck leaves service.",
                    comps=["Metso Metrics", "AVEVA PI System", "Lakehouse//RT", "Model Serving", "MLflow", "Feature Store"],
                    stories=[["Sandvik enables collaboration and real-time equipment insight", "https://www.databricks.com/customers/sandvik"], ["What is predictive maintenance on the Databricks platform", "https://www.databricks.com/blog/what-is-predictive-maintenance"]]),
                uc("Stockpile Management", "Blending", "product", "Grade engineering across ROM and product piles to hit contract spec.",
                    problem="Grade is engineered across ROM and product piles on spreadsheets and memory, so blends drift off contract spec and either penalty tonnes ship or premium ore is buried in a low-grade pile.",
                    who="Marketing & Sales",
                    how="Assay, survey and movement data conform to one inventory position on Delta Lake, and blending is optimised against contract spec and served to the Shipment Tracker for the marketing desk.",
                    comps=["Shipment Tracker", "LIMS Assay Lab", "Satellite Imagery", "Model Serving", "AI/BI", "Delta Lake"]),
                uc("Export Logistics", "Port", "globe", "Rail and vessel scheduling aligned to production and demurrage exposure.",
                    problem="Rail convoys, port stock and vessel nominations are reconciled by nightly spreadsheet, so a cargo waits on ore or a ship waits on a berth and demurrage runs up before anyone sees the chain.",
                    who="Marketing & Sales",
                    how="Rail telemetry and port feeds land through Lakeflow and conform on Delta Lake, and scheduling is aligned to production and demurrage exposure on the Shipment Tracker for the marketing desk.",
                    comps=["Shipment Tracker", "Rail Wagon Telemetry", "Port Community System", "Lakeflow", "Delta Lake", "AI/BI"]),
                uc("Safety Analytics", "Risk", "gavel", "Leading indicators and proximity events surfaced before a recordable occurs.",
                    problem="Incidents, near-misses and proximity events sit in separate systems and are read after the fact, so leading indicators of fatal-risk exposure are joined up only after a recordable happens.",
                    who="Safety & ESG",
                    how="Incident, permit and proximity feeds conform on Delta Lake under Unity Catalog, and leading indicators are surfaced in AI/BI and the Safety Dashboard before a recordable occurs.",
                    comps=["Intelex EHS", "Wearable Proximity", "Unity Catalog", "Delta Lake", "AI/BI", "Model Serving"],
                    stories=[["BP's geospatial AI engine transforms safety and operations", "https://www.databricks.com/blog/bps-geospatial-ai-engine-transforming-safety-and-operations-databricks"], ["Nexa mines less waste and more value with AI-driven insights", "https://www.databricks.com/customers/nexa"]]),
                uc("Energy & Emissions", "ESG", "observ", "Diesel and electricity intensity per tonne for reporting and cost reduction.",
                    problem="Diesel and power are metered per site weeks late, so intensity per tonne is a month-end estimate and neither the cost lever nor the Scope 1 disclosure traces back to the equipment that drove it.",
                    who="Safety & ESG",
                    how="Fuel, power and production data conform on Delta Lake under Unity Catalog, and energy intensity per tonne is served in AI/BI with lineage from meter to the emissions and cost disclosure.",
                    comps=["Envirosuite", "AVEVA PI System", "Unity Catalog", "Delta Lake", "AI/BI", "Data Products"],
                    stories=[["Gerdau delivers world-class steel with Databricks", "https://www.databricks.com/customers/gerdau"], ["How Dow built a carbon footprint ledger on Databricks", "https://www.databricks.com/blog/how-dow-built-carbon-footprint-ledger-databricks-accelerate-sustainability-scale"]]),
                uc("Mine Planning", "Sequence", "chart", "Pit phases scored on NPV with geotechnical and water constraints explicit.",
                    problem="Pit phasing is optimised in specialist tools cut off from live grade, cost and geotechnical data, so the plan the board commits to is stale when signed and NPV trade-offs stay hidden.",
                    who="Site Leadership",
                    how="Block model, cost and geotechnical data conform on Delta Lake, and phase options are scored on NPV with water and geotechnical constraints explicit in AI/BI and Genie One for leadership.",
                    comps=["Maptek BlastLogic", "SAP IS-Mining", "Delta Lake", "Unity Catalog", "AI/BI", "Genie One"]),
                uc("Commodity Hedging", "Treasury", "market", "Physical delivery marked to benchmark with hedge effectiveness in one view.",
                    problem="Physical delivery and hedge positions live in different books, so realised price to benchmark and hedge effectiveness are stitched in spreadsheets long after treasury needed the number.",
                    who="Marketing & Sales",
                    how="Contract, shipment and price feeds conform on Delta Lake under Unity Catalog, and physical delivery is marked to benchmark with hedge effectiveness in one AI/BI view for the marketing desk.",
                    comps=["Metal Bulletin", "Corporate Risk Ledger", "SAP IS-Mining", "Unity Catalog", "Delta Lake", "AI/BI"],
                    stories=[["Vale transforms finance with agentic AI at scale", "https://www.databricks.com/customers/vale/agent-bricks"]]),
            ],
        ),
        "sources": {
            "modular": {"t": "Modular Mining DISPATCH", "u": "https://www.modularmining.com/"},
            "hexagon": {"t": "Hexagon MineOperate", "u": "https://hexagon.com/products/product-groups/mineoperate"},
            "maptek": {"t": "Maptek BlastLogic", "u": "https://www.maptek.com/products/blastlogic/"},
            "aveva-pi": {"t": "AVEVA PI System", "u": "https://www.aveva.com/en/products/pi-system/"},
            "metso": {"t": "Metso Metrics", "u": "https://www.metso.com/portfolio/metso-metrics/"},
            "lims": {"t": "Laboratory information management", "u": "https://www.thermofisher.com/us/en/home/digital-solutions/lab-informatics.html"},
            "sap-mining": {"t": "SAP for mining", "u": "https://www.sap.com/industries/mining.html"},
            "metal-bulletin": {"t": "Fastmarkets Metal Bulletin", "u": "https://www.fastmarkets.com/"},
            "pcs": {"t": "Port community systems", "u": "https://ipcsa.international/"},
            "intelex": {"t": "Intelex EHS", "u": "https://www.intelex.com/"},
            "envirosuite": {"t": "Envirosuite", "u": "https://envirosuite.com/"},
            "planet": {"t": "Planet Labs", "u": "https://www.planet.com/"},
        },
    },
}
