import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_CONSUMER_GOODS = {
    'consumer_goods': {
        "label": "Consumer Goods",
        "blurb": "CPG manufacturing and distribution: demand planning, trade promotion, retail execution, and supply chain across brands and categories.",
        "medallion": medallion(
            "Raw sell-in and sell-out",
            "ERP shipments, retailer POS, syndicated scan and promo calendars landed exactly as received.",
            "Conformed products and markets",
            "SKUs, banners, geographies and promotions resolved across ERP, TPM and syndicated data.",
            "Shipments, share, promo ROI",
            "Contracted products sales and finance run on: shipment volume, market share, promo lift and trade spend ROI.",
        ),
        "rails": {
            "src": [
                {"box": "ERP & Manufacturing", "ic": "erp", "tiles": [
                    tile("SAP IBP / S/4", "erp", "Demand, supply and production planning with financials.", "sap-ibp"),
                    tile("Oracle JD Edwards", "erp", "Batch manufacturing, lot trace and DSD routes.", "jde"),
                    tile("Kinaxis RapidResponse", "sheet", "Concurrent planning and scenario simulation.", "kinaxis"),
                ]},
                {"box": "Retail & Syndicated", "ic": "market", "tiles": [
                    tile("NielsenIQ Connect", "market", "Syndicated scan and market share by category.", "nielseniq"),
                    tile("Circana Liquid Data", "chart", "Omni-channel consumption and household panels.", "circana"),
                    tile("IRI Market Advantage", "market", "Promo decomposition and competitive tracking.", "iri"),
                ]},
                {"box": "Trade Promotion", "ic": "partner", "tiles": [
                    tile("SAP TPM", "partner", "Promo planning, accruals and settlement.", "sap-tpm"),
                    tile("Vistex GTM", "market", "Chargebacks, rebates and contract compliance.", "vistex"),
                    tile("Blacksmith TPM", "chart", "ROI analytics and post-event evaluation.", "blacksmith"),
                ]},
                {"box": "Field & DSD", "ic": "stream", "tiles": [
                    tile("Salesforce Consumer Goods", "custlake", "Retail visits, audits and perfect store scores.", "sf-cg"),
                    tile("HighJump WMS", "stream", "Warehouse picking and DSD route sequencing.", "highjump"),
                    tile("o9 Demand Planning", "sheet", "Statistical and ML forecasts by SKU-region.", "o9"),
                ]},
                {"box": "E-commerce", "ic": "apps", "tiles": [
                    tile("Amazon Vendor Central", "partner", "Purchase orders, chargebacks and traffic.", "amazon-vc"),
                    tile("Instacart Ads & Data", "product", "Retail media and basket insights.", "instacart"),
                ]},
                fed_group("Finance Close Mart", "Trade spend accrual marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("Weather Source", "stream", "Weather-driven demand signals by market.", "weather-source"),
                tile("USDA ERS Food Data", "api", "Commodity input cost indices for margin planning.", "usda-ers"),
                tile("Google Trends", "observ", "Search interest proxies for emerging demand.", "google-trends"),
            ]),
            "ppl": ppl2([
                biz("Brand & Category", "Genie One",
                    "The CEO on category share and innovation pipeline; the CFO on trade-spend efficiency and gross margin against promo ROI.",
                    [["Genie One", "Ask what last promo's ROI was by retailer."], ["AI/BI", "Share and margin on certified Metric Views."], ["Unity Catalog", "One SKU definition across syndicated and ERP."]],
                    sub=[
                        ["Chief Marketing Officer", "category share, brand equity and the innovation pipeline across the portfolio."],
                        ["CFO & Revenue Growth", "gross margin, trade-spend efficiency and price-pack economics by brand."],
                        ["Category Insights", "shopper trends and where the category is growing by channel."],
                    ],
                    ucs=["Price Pack Architecture", "New Product Intro", "Retail Media"]),
                biz("Sales & Accounts", "AI/BI",
                    "Joint business plans, distribution and perfect store execution, judged on market share, on-shelf availability and distribution points.",
                    [["Perfect Store Scorecard", "On-shelf availability and compliance by banner."], ["AI/BI", "Sell-through and share on governed syndicated data."]],
                    sub=[
                        ["National Account Managers", "joint business plans, distribution and deductions with each retailer."],
                        ["Field Sales Leadership", "on-shelf availability and perfect store execution across banners."],
                        ["Revenue Management", "chargeback recovery and net revenue by customer."],
                    ],
                    ucs=["Perfect Store", "Chargeback Recovery", "Trade Promotion ROI"]),
                biz("Demand Planning", "Model Serving",
                    "Statistical forecasts, consensus and supply alignment, tracked on forecast accuracy, bias and consensus attainment by SKU-region.",
                    [["Consensus Forecast", "Sales and finance aligned on one number."], ["Model Serving", "ML forecasts in the planning path."]],
                    sub=[
                        ["Demand Planners", "statistical baseline, consensus and forecast accuracy by SKU-region."],
                        ["S&OP Lead", "one number aligning sales, finance and supply each cycle."],
                        ["Forecast Analytics", "bias, error and the demand signals that move the plan."],
                    ],
                    ucs=["Demand Forecasting", "Inventory Optimization", "New Product Intro"]),
                biz("Trade Marketing", "Apps",
                    "Promo design, accrual management and post-event analytics, measured on promo lift, incrementality and trade-spend ROI.",
                    [["Promo ROI Analyzer", "Lift and incrementality by event."], ["Apps", "Field audit apps on governed visit data."]],
                    sub=[
                        ["Trade Marketing Managers", "promo design, mechanics and accruals by event and retailer."],
                        ["Shopper Marketing", "retail media and in-store activation tied to sell-through."],
                        ["Revenue Growth Management", "incrementality and trade-spend ROI across the plan."],
                    ],
                    ucs=["Trade Promotion ROI", "Retail Media", "Price Pack Architecture"]),
                biz("Supply Chain", "Lakehouse//RT",
                    "Service levels, inventory and production scheduling, run on OTIF, case fill rate and days of inventory against demand across DCs and SKUs.",
                    [["Supply Command", "OTIF and fill rate by DC and SKU."], ["Lakehouse//RT", "Inventory positions at operational latency."]],
                    sub=[
                        ["Supply Planners", "service levels, allocation and days of inventory across DCs."],
                        ["Logistics & DSD", "OTIF, fill rate and route execution to the store."],
                        ["Sustainability Ops", "packaging, sourcing and emissions by brand and site."],
                    ],
                    ucs=["Supply Allocation", "Inventory Optimization", "Sustainability Tracking"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land ERP shipments, retailer POS, syndicated scan and promo calendars; own Bronze to Silver and the pager when the share and promo tables stall.",
                    [["Lakeflow Connect", "Managed connectors for ERP, TPM and syndicated-data sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on shipment and scan feeds."], ["Lakewatch", "Freshness on the share and promo tables account teams read weekly."]],
                    sub=[
                        ["Ingestion Engineers", "ERP shipments, retailer POS and syndicated scan landed on time."],
                        ["Pipeline Owners", "Bronze to Silver and the pager when share and promo tables stall."],
                        ["Data Quality", "expectations on shipment, scan and promo feeds before they publish."],
                    ],
                    ucs=["Demand Forecasting", "Trade Promotion ROI", "Chargeback Recovery"]),
                biz("Data Scientists", "MLflow",
                    "Demand-forecast, promo-lift and price-pack elasticity models, and whether they still hold across a new innovation launch and channel shift.",
                    [["Feature Store", "SKU and market features read identically in training and serving."], ["MLflow", "Every forecast and lift model tracked for audit and reproduction."], ["Model Serving", "Forecast and lift models scored in the planning path."]],
                    sub=[
                        ["Forecasting Scientists", "demand, elasticity and promo-lift models across launches and channels."],
                        ["Optimization Scientists", "allocation and safety-stock models under service and cost constraints."],
                        ["MLOps", "every forecast and lift model tracked for audit and reproduction."],
                    ],
                    ucs=["Demand Forecasting", "Price Pack Architecture", "Inventory Optimization"]),
                biz("App Developers", "Apps",
                    "Ship the perfect store scorecard, consensus forecast, promo ROI analyzer and supply command apps sales and planning work in, next to governed SKU data.",
                    [["Apps", "Field and planning screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for audit and accrual state."], ["Agent Bricks", "Agents that draft promo and allocation moves against governed tools."]],
                    sub=[
                        ["Frontend Engineers", "perfect store, consensus and promo ROI screens next to governed data."],
                        ["Backend Engineers", "Lakebase state for audits, accruals and allocation writeback."],
                        ["Agent Builders", "agents that draft promo and allocation moves against governed tools."],
                    ],
                    ucs=["Perfect Store", "Supply Allocation", "Trade Promotion ROI"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Category and finance dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for share and promo questions."),
                    tile("Notebooks & IDEs", "notebook", "Planning notebooks on governed syndicated data."),
                ]},
                {"box": "Retailers & Brokers", "ic": "partner", "tiles": [
                    tile("EDI 852/867", "api", "Store-level inventory and consumption to retailers.", "nielseniq"),
                    tile("Retailer Portals", "globe", "Promo calendars and deductions reconciled digitally.", "sap-tpm"),
                    tile("DSD Route Updates", "stream", "Delivery sequences pushed to driver devices.", "highjump"),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("Promo Accruals", "market", "Accrual rates updated in ERP from planned events.", "sap-tpm"),
                    tile("Allocation Releases", "stream", "Scarce SKU allocation to priority banners.", "kinaxis"),
                    tile("Perfect Store Tasks", "custlake", "Corrective actions assigned to field reps.", "sf-cg"),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("Nutrition Labeling", "gavel", "Label compliance tracked from recipe to package."),
                    tile("ESG Packaging Reports", "share", "Recycled content disclosures to retailers."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Category insight products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Retail partners via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Perfect Store Scorecard", "Retail execution", "market", "On-shelf availability, facings and promo compliance by store."),
             app("Consensus Forecast", "Demand planning", "sheet", "Statistical, sales and finance inputs merged into one plan."),
             app("Promo ROI Analyzer", "Trade spend", "chart", "Lift, incrementality and payback by event and retailer."),
             app("Supply Command", "Service levels", "gauge", "OTIF, fill rate and inventory health by DC and SKU.")],
            [uc("Demand Forecasting", "Planning", "chart", "ML forecasts refreshed with syndicated and weather signals.",
                problem="Forecasts run on stale shipment history in spreadsheets, so sales, finance and supply each defend a different number and stockouts and overstocks appear before anyone trusts the plan.",
                who="Demand Planning",
                how="Syndicated scan, POS and weather signals land through Lakeflow, features are engineered in Feature Store and scored in Model Serving into the Consensus Forecast plan.",
                comps=["Consensus Forecast", "Model Serving", "MLflow", "Feature Store", "NielsenIQ Connect"],
                stories=[
                    ["Unilever transforms with AI", "https://www.databricks.com/customers/unilever"],
                    ["Mondelēz facilitates model experimentation at enterprise scale", "https://www.databricks.com/customers/mondelez"],
                ]),
             uc("Trade Promotion ROI", "Marketing", "partner", "Promo events evaluated on true incrementality.",
                problem="Trade spend is the second-largest line on the P&L, yet promo results are judged on gross lift, so teams keep funding events that simply pulled forward volume they would have sold anyway.",
                who="Trade Marketing",
                how="Promo calendars, shipments and syndicated scan are conformed on Delta Lake and decomposed with Model Serving, so the Promo ROI Analyzer shows true incrementality on certified AI/BI views.",
                comps=["Promo ROI Analyzer", "SAP TPM", "Model Serving", "AI/BI", "Delta Lake"],
                stories=[
                    ["How modern retailers and CPG brands win together", "https://www.databricks.com/blog/collaboration-advantage-how-modern-retailers-and-cpg-brands-win-together"],
                    ["Mars Wrigley scales global insights", "https://www.databricks.com/customers/mars-wrigley"],
                ]),
             uc("Perfect Store", "Sales", "custlake", "Store-level execution scored and actioned.",
                problem="Retail execution lives in field-rep screenshots and paper audits, so on-shelf availability, planogram compliance and promo presence are only known weeks later, once the sale is already lost.",
                who="Sales & Accounts",
                how="Visit, audit and POS data land through Salesforce Consumer Goods, are scored with AI Functions and Model Serving, and surface store fixes in the Perfect Store Scorecard app for reps.",
                comps=["Perfect Store Scorecard", "Salesforce Consumer Goods", "AI Functions", "Model Serving", "Apps"],
                stories=[
                    ["Grupo Bimbo delivers insights with Agent Bricks", "https://www.databricks.com/dataaisummit/session/beyond-dashboards-how-grupo-bimbo-delivers-insights-databricks"],
                    ["Mars Wrigley scales global insights", "https://www.databricks.com/customers/mars-wrigley"],
                ]),
             uc("Supply Allocation", "Operations", "stream", "Finite supply allocated to highest-value markets.",
                problem="When a SKU goes short, allocation is decided in a hurried call and the biggest customer wins, so scarce stock rarely lands where service, margin and strategic accounts matter most.",
                who="Supply Chain",
                how="Inventory, orders and demand feed Lakehouse//RT and optimization models in Model Serving, and the Supply Command app releases allocation to priority banners with state held in Lakebase.",
                comps=["Supply Command", "Kinaxis RapidResponse", "Lakehouse//RT", "Model Serving", "Lakebase"],
                stories=[
                    ["Mondelēz facilitates model experimentation at enterprise scale", "https://www.databricks.com/customers/mondelez"],
                    ["Unilever transforms with AI", "https://www.databricks.com/customers/unilever"],
                ]),
             uc("Price Pack Architecture", "Strategy", "product", "SKU mix optimized by channel and elasticity.",
                problem="Pack sizes and price points drift per market with no view of elasticity, so a change meant to protect margin quietly trades down shoppers or hands share to a cheaper competitor.",
                who="Brand & Category",
                how="Syndicated consumption from Circana Liquid Data feeds elasticity features in Feature Store and simulations in Model Serving, so brand teams size price-pack moves by channel in AI/BI.",
                comps=["Circana Liquid Data", "Model Serving", "AI/BI", "Feature Store", "Delta Lake"],
                stories=[
                    ["Mondelēz facilitates model experimentation at enterprise scale", "https://www.databricks.com/customers/mondelez"],
                ]),
             uc("Retail Media", "Digital", "market", "Retail media spend tied to sell-through outcomes.",
                problem="Retail media budgets grow every year, but spend on retailer platforms is reported in each retailer's walled garden, so nobody can tie an impression to real sell-through and true return.",
                who="Trade Marketing",
                how="Retail media data from Amazon Vendor Central and Instacart Ads & Data is conformed on Delta Lake and joined to sell-through, so ROAS and incremental sales surface in AI/BI and Model Serving.",
                comps=["Instacart Ads & Data", "Amazon Vendor Central", "AI/BI", "Model Serving", "Delta Lake"],
                stories=[
                    ["How modern retailers and CPG brands win together", "https://www.databricks.com/blog/collaboration-advantage-how-modern-retailers-and-cpg-brands-win-together"],
                    ["Heineken brews better decisions with data and AI", "https://www.databricks.com/customers/heineken-international"],
                ]),
             uc("Chargeback Recovery", "Finance", "erp", "Retailer deductions reconciled to shipment proof.",
                problem="Retailers deduct for shortages, pricing and promo claims faster than teams can check them, so valid disputes expire and invalid deductions are written off every year without proof.",
                who="Sales & Accounts",
                how="Deductions from Vistex GTM and SAP TPM are matched to shipment and promo proof in SAP IBP / S/4 with AI Functions on Delta Lake, so recoverable claims are flagged with evidence.",
                comps=["Vistex GTM", "SAP TPM", "SAP IBP / S/4", "AI Functions", "Delta Lake"]),
             uc("New Product Intro", "Innovation", "ztarget", "Launch curves tracked against distribution targets.",
                problem="A launch gets one shot at the shelf, yet distribution, velocity and cannibalization are tracked in separate reports, so a stalling SKU is spotted only after the reset window has closed.",
                who="Brand & Category",
                how="Syndicated scan from NielsenIQ Connect is joined to shipments and scored in Model Serving, so launch curves against distribution targets surface in AI/BI and Genie One for brand teams.",
                comps=["NielsenIQ Connect", "Model Serving", "AI/BI", "Genie One", "Delta Lake"]),
             uc("Sustainability Tracking", "ESG", "gavel", "Packaging and sourcing metrics by brand.",
                problem="ESG commitments are made at the brand level, but packaging, recycled content and sourcing data sit in supplier emails and PDFs, so disclosures are assembled by hand and hard to defend.",
                who="Supply Chain",
                how="Sourcing and packaging data from SAP IBP / S/4 are conformed under Unity Catalog into governed Data Products, so recycled-content and emissions metrics report by brand in AI/BI.",
                comps=["SAP IBP / S/4", "Unity Catalog", "AI/BI", "Delta Lake", "Data Products"],
                stories=[
                    ["Mondelēz facilitates model experimentation at enterprise scale", "https://www.databricks.com/customers/mondelez"],
                ]),
             uc("Inventory Optimization", "Finance", "chart", "Safety stock right-sized by service and cost.",
                problem="Safety stock is set by a flat rule of thumb, so cash is tied up in slow SKUs while the fast movers still stock out, and no one can see the trade between service level and working capital.",
                who="Supply Chain",
                how="Demand, lead-time and service signals from o9 Demand Planning feed optimization models in Model Serving on Lakehouse//RT, so the Supply Command app right-sizes safety stock by SKU.",
                comps=["Supply Command", "o9 Demand Planning", "Model Serving", "Lakehouse//RT", "MLflow"],
                stories=[
                    ["Unilever transforms with AI", "https://www.databricks.com/customers/unilever"],
                    ["Mondelēz facilitates model experimentation at enterprise scale", "https://www.databricks.com/customers/mondelez"],
                ])],
        ),
        "sources": {
            "sap-ibp": {"t": "SAP IBP", "u": "https://www.sap.com/products/scm/integrated-business-planning.html"},
            "jde": {"t": "Oracle JD Edwards", "u": "https://www.oracle.com/applications/"},
            "kinaxis": {"t": "Kinaxis", "u": "https://www.kinaxis.com/"},
            "nielseniq": {"t": "NielsenIQ", "u": "https://nielseniq.com/"},
            "circana": {"t": "Circana", "u": "https://www.circana.com/"},
            "iri": {"t": "Circana Market Advantage", "u": "https://www.circana.com/"},
            "sap-tpm": {"t": "SAP Trade Promotion Management", "u": "https://www.sap.com/products/scm/trade-promotion-management.html"},
            "vistex": {"t": "Vistex", "u": "https://www.vistex.com/"},
            "blacksmith": {"t": "Blacksmith Applications", "u": "https://www.blacksmithapplications.com/"},
            "sf-cg": {"t": "Salesforce Consumer Goods Cloud", "u": "https://www.salesforce.com/consumer-goods/"},
            "highjump": {"t": "Körber HighJump", "u": "https://koerber-supplychain.com/"},
            "o9": {"t": "o9 Solutions", "u": "https://o9solutions.com/"},
            "amazon-vc": {"t": "Amazon Vendor Central", "u": "https://vendorcentral.amazon.com/"},
            "instacart": {"t": "Instacart", "u": "https://www.instacart.com/company/business"},
            "weather-source": {"t": "Weather Source", "u": "https://weathersource.com/"},
            "usda-ers": {"t": "USDA ERS", "u": "https://www.ers.usda.gov/"},
            "google-trends": {"t": "Google Trends", "u": "https://trends.google.com/"},
        },
    },
}
