import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import app, biz, cons_rail, fed_group, ing_rail, medallion, tile, top_band, uc


def ppl2(business_tiles, tech_tiles):
    """People rail with per-industry Technical roles (never common.TECH_PPL)."""
    return [
        {"box": "Business", "ic": "zbrief", "tiles": business_tiles[:5]},
        {"box": "Technical", "ic": "code", "tiles": tech_tiles[:3]},
    ]


INDUSTRIES_BATCH_AGRICULTURE = {
    'agriculture': {
        "label": "Agriculture",
        "blurb": "Farm operations, crop planning, input supply, commodity trading, and sustainability reporting across grower networks and co-ops.",
        "medallion": medallion(
            "Raw field and market feeds",
            "Telemetry from equipment, weather stations, satellite imagery and exchange ticks, landed exactly as received so a yield estimate can be replayed.",
            "Conformed fields and assets",
            "Fields, parcels, equipment and contracts resolved into single entities across FMIS, ERP and trading systems.",
            "Yield, margin and carbon",
            "Contracted products agronomy and finance run on: yield per acre, input cost per bushel, basis and carbon intensity scores.",
        ),
        "rails": {
            "src": [
                {
                    "box": "Farm Management",
                    "ic": "sheet",
                    "tiles": [
                        tile("John Deere Operations Center", "iot", "Machine telemetry, as-applied maps and field boundaries from connected equipment.", "john-deere"),
                        tile("Climate FieldView", "iot", "Planting, spraying and harvest layers with hybrid performance by field.", "climate-fieldview"),
                        tile("Granular FMIS", "sheet", "Field plans, input applications and profitability by acre.", "granular"),
                    ],
                },
                {
                    "box": "ERP & Supply Chain",
                    "ic": "erp",
                    "tiles": [
                        tile("SAP S/4HANA Agribusiness", "erp", "Grain contracts, settlements and inventory across elevators and processing.", "sap-agri"),
                        tile("Oracle Food & Beverage", "erp", "Procurement, production and lot traceability for processors.", "oracle-fb"),
                        tile("Bushel ERP", "erp", "Co-op accounting, patronage and grain accounting.", "bushel"),
                    ],
                },
                {
                    "box": "Commodity Markets",
                    "ic": "market",
                    "tiles": [
                        tile("CME Group Futures", "market", "Corn, soybean and wheat futures, options and settlement prices.", "cme"),
                        tile("DTN Prophet", "market", "Cash bids, basis and local elevator prices by location.", "dtn"),
                        tile("Barchart cmdty", "chart", "Historical cash and futures curves for hedging analysis.", "barchart"),
                    ],
                },
                {
                    "box": "Weather & Imagery",
                    "ic": "stream",
                    "tiles": [
                        tile("DTN Weather", "stream", "Hyperlocal forecasts, growing degree days and spray windows.", "dtn-weather"),
                        tile("Planet Labs Imagery", "iot", "Daily satellite NDVI and change detection by parcel.", "planet"),
                        tile("Sentinel Hub", "globe", "Copernicus optical and radar scenes for crop condition.", "sentinel"),
                    ],
                },
                {
                    "box": "Sustainability",
                    "ic": "gavel",
                    "tiles": [
                        tile("Regrow MRV", "gavel", "Practice verification and carbon quantification for regenerative programs.", "regrow"),
                        tile("Indigo Carbon", "partner", "Carbon credit issuance and soil carbon sampling workflows.", "indigo"),
                    ],
                },
                fed_group("Legacy Co-op Mart", "Patronage and historical elevator marts queried in place under Unity Catalog."),
            ],
            "ing": ing_rail([
                tile("USDA NASS QuickStats", "api", "County yield, acreage and production statistics ingested for benchmarking.", "usda-nass"),
                tile("USDA RMA Crop Insurance", "gavel", "Policy, acreage and indemnity files for risk programs.", "usda-rma"),
                tile("AgGateway ADAPT", "zplug", "Standardized machine and application data from mixed OEM fleets.", "aggateway"),
            ]),
            "ppl": ppl2([
                biz("Co-op Executive Board", "Genie One",
                    "The CEO on margin per bushel and land strategy; the COO on harvest logistics, elevator throughput and cost per acre.",
                    [["Genie One", "Ask what last harvest cost per acre without analyst delay."], ["AI/BI", "Margin and yield on certified Metric Views."], ["Unity Catalog", "One bushel definition across operations and finance."]],
                    sub=[["CEO", "margin per bushel, land strategy and the trade between growth and grower returns."],
                         ["Chief Operating Officer", "harvest logistics, elevator throughput and cost per acre across the network."],
                         ["Member Board", "patronage returns and the long-term value delivered back to grower-owners."]],
                    ucs=["Harvest Logistics", "Weather Risk Alerts", "Patronage Planning", "Input Cost Optimization"]),
                biz("Agronomy", "AI/BI",
                    "Hybrid selection, variable-rate prescriptions and scouting priorities, judged on yield per acre, input cost per bushel and nitrogen use.",
                    [["Prescription Workbench", "VR seed and nitrogen plans by productivity zone."], ["AI/BI", "Yield response curves on governed trial data."]],
                    sub=[["Lead Agronomist", "hybrid selection and variable-rate plans that lift yield per acre."],
                         ["Field Scouts", "scouting priorities and where pest and disease pressure is building."],
                         ["Precision Ag Specialist", "productivity-zone mapping and nitrogen use efficiency by field."]],
                    ucs=["Yield Forecasting", "Variable-Rate Prescriptions", "Weather Risk Alerts"]),
                biz("Grain Merchandising", "Model Serving",
                    "Basis trading, hedging and origination against futures and local bids, managed on position, basis exposure and hedge P&L.",
                    [["Merchandising Desk", "Position and basis exposure by location."], ["Model Serving", "Basis forecast models in the pricing path."]],
                    sub=[["Head Merchandiser", "basis positions and hedge P&L against futures and local bids."],
                         ["Origination", "grower contracts and where to bid to fill the elevator at target basis."],
                         ["Risk Desk", "position limits and futures and basis exposure across locations."]],
                    ucs=["Basis Trading", "Harvest Logistics", "Input Cost Optimization"]),
                biz("Sustainability", "Lakehouse//RT",
                    "Carbon programs, practice verification and Scope 3 reporting, tracked on carbon intensity, enrolled acres and credits issued per grower.",
                    [["Carbon Registry", "Issuance pipeline and practice compliance by grower."], ["Lakehouse//RT", "Practice events at operational latency."]],
                    sub=[["Carbon Program Lead", "enrolled acres, practice compliance and credits issued per grower."],
                         ["MRV & Verification", "the measurement and verification behind every credit sent to a buyer."],
                         ["Scope 3 Reporting", "carbon intensity and water metrics reported to food-company buyers."]],
                    ucs=["Carbon MRV", "Supply Chain Traceability"]),
                biz("Finance & Risk", "AI/BI",
                    "Patronage, crop insurance and counterparty exposure, watching patronage pools, indemnity exposure and off-margin contracts.",
                    [["AI/BI", "Patronage and hedge P&L on certified views."], ["Genie One", "Ask which contracts are off-margin this week."]],
                    sub=[["CFO & Controller", "patronage pools, working capital and grain accounting through fiscal close."],
                         ["Crop Insurance", "acreage reporting, indemnity exposure and RMA program compliance."],
                         ["Counterparty Risk", "off-margin contracts and counterparty exposure across the book."]],
                    ucs=["Crop Insurance Analytics", "Input Cost Optimization", "Patronage Planning"]),
            ], [
                biz("Data Engineers", "Lakeflow",
                    "Land equipment telemetry, satellite imagery, FMIS field plans and exchange ticks; own Bronze to Silver and the pager when the basis and yield tables stall.",
                    [["Lakeflow Connect", "Managed connectors for FMIS, ERP and commodity-market sources."], ["Lakeflow Designer", "Declarative pipelines with expectations on machine and imagery feeds."], ["Lakewatch", "Freshness on the basis and yield tables merchandisers read at open."]],
                    sub=[["Ingestion Engineering", "equipment telemetry, imagery and exchange ticks landed Bronze to Silver."],
                         ["Pipeline On-Call", "the pager when the basis and yield tables stall before market open."],
                         ["Data Quality", "expectations on machine, imagery and FMIS feeds before agronomy reads them."]],
                    ucs=["Yield Forecasting", "Basis Trading", "Harvest Logistics"]),
                biz("Data Scientists", "MLflow",
                    "Yield-forecast, basis and soil-carbon quantification models built from imagery and trial data, and whether they still hold across a shifting season.",
                    [["Feature Store", "Field and weather features read identically in training and serving."], ["MLflow", "Every yield and basis model tracked for audit and reproduction."], ["Model Serving", "Basis and yield models scored in the pricing and prescription path."]],
                    sub=[["Yield Modeling", "in-season yield forecasts from imagery, weather and hybrid response."],
                         ["Quant & Basis", "basis and hedge models that hold across a shifting season."],
                         ["Carbon Quantification", "soil-carbon models that survive third-party verification."]],
                    ucs=["Yield Forecasting", "Basis Trading", "Carbon MRV"]),
                biz("App Developers", "Apps",
                    "Ship the harvest command, prescription workbench and carbon registry apps agronomy and merchandising work in, hosted next to governed field data.",
                    [["Apps", "Operational screens with no separate web tier to secure."], ["Lakebase", "Serverless Postgres for prescription and contract state."], ["Agent Bricks", "Agents that draft prescriptions and offers against governed tools."]],
                    sub=[["Operational Apps", "harvest command and prescription workbench next to governed field data."],
                         ["Registry & Contracts", "carbon registry and contract state on serverless Postgres."],
                         ["Agent Builders", "agents that draft prescriptions and offers against governed tools."]],
                    ucs=["Harvest Logistics", "Variable-Rate Prescriptions", "Carbon MRV"]),
            ]),
            "cons": cons_rail([
                {"box": "BI & Productivity", "ic": "chart", "from": "bi", "tiles": [
                    tile("Tableau / Power BI", "chart", "Grower and elevator dashboards on serverless SQL."),
                    tile("Microsoft Teams", "chat", "Genie in Teams for basis and yield questions in the merchandising channel."),
                    tile("Notebooks & IDEs", "notebook", "Agronomy notebooks against governed field and trial data."),
                ]},
                {"box": "Grower & Retail", "ic": "partner", "tiles": [
                    tile("Deere Ops Center API", "api", "Prescriptions and harvest summaries shared back to grower accounts.", "john-deere"),
                    tile("FieldView Plus", "partner", "Field layers and recommendations delivered to farmer subscriptions.", "climate-fieldview"),
                    tile("Retail Input Portal", "product", "Seed and chemical orders tied to field-level plans."),
                ]},
                {"box": "Operational Writeback", "ic": "opdb", "tiles": [
                    tile("VR Prescription Export", "iot", "Variable-rate files pushed to applicators before the window closes."),
                    tile("Contract Offers", "market", "Origination offers written to grower CRM at target basis.", "bushel"),
                    tile("Elevator Receiving", "stream", "Scale tickets and moisture discounts flowing to settlement."),
                ]},
                {"box": "Regulatory & Reporting", "ic": "gavel", "tiles": [
                    tile("USDA Reporting", "gavel", "Production and stocks reports filed from governed inventory.", "usda-nass"),
                    tile("Sustainability Disclosures", "share", "Carbon and water metrics shared to food company buyers."),
                ]},
                {"box": "Published Products", "ic": "product", "tiles": [
                    tile("Data Products", "product", "Yield and sustainability products in Unity Catalog Domains."),
                    tile("Sharing Recipients", "share", "Food companies and lenders reading live tables via Delta Sharing."),
                ]},
            ]),
        },
        "top": top_band(
            [app("Harvest Command", "Season operations", "gauge", "Live harvest progress, elevator queues and dryer capacity across the network."),
             app("Prescription Workbench", "Variable-rate plans", "iot", "Seed, nitrogen and chemical prescriptions by productivity zone before application."),
             app("Merchandising Desk", "Basis and hedges", "market", "Position, basis and hedge effectiveness by location and crop."),
             app("Carbon Registry", "MRV pipeline", "gavel", "Practice enrollment, verification status and credit issuance by grower.")],
            [uc("Yield Forecasting", "Production", "chart", "In-season yield estimates from imagery, weather and hybrid response.",
                problem="Yield is guessed from last year's average and a windshield survey, so seed, input and marketing decisions are made months before anyone has a defensible number per field.",
                who="Agronomy",
                how="Satellite imagery, weather and hybrid-trial features are engineered in Feature Store and scored through Model Serving, with runs tracked in MLflow across the season.",
                comps=["Harvest Command", "Planet Labs Imagery", "Model Serving", "Feature Store", "MLflow"],
                stories=[["Agerpoint partners with Databricks for agriculture data intelligence", "https://www.agerpoint.com/blog/agerpoint-partners-with-databricks-to-scale-enterprise-data-intelligence-for-agriculture-and-nature-systems"],
                         ["Databricks spatial joins for crop yield analysis and forecasting", "https://www.databricks.com/blog/databricks-spatial-joins-now-17x-faster-out-box"]]),
             uc("Variable-Rate Prescriptions", "Agronomy", "iot", "Input rates optimized by zone rather than flat application.",
                problem="Inputs go on at flat rates because field, soil and yield layers live in different tools and never line up, so money is spent on acres that cannot return it.",
                who="Agronomy",
                how="Soil, yield and imagery layers are scored with AI Functions and Model Serving in the Prescription Workbench, then written back to the applicator and Deere Operations Center as VR files.",
                comps=["Prescription Workbench", "Model Serving", "AI Functions", "John Deere Operations Center", "Delta Lake"],
                stories=[["Geospatial Unbounded: variable-rate prescription from soil, zones and weather", "https://www.databricks.com/blog/geospatial-unbounded-spatial-sql-ga-aibi-maps-delta-sharing-and-iceberg-v3"]]),
             uc("Basis Trading", "Merchandising", "market", "Local basis positions managed against futures and storage.",
                problem="Basis is tracked on spreadsheets against futures and a dozen local bids, so positions and hedge exposure lag the market and a bad basis call quietly erodes margin on every bushel.",
                who="Grain Merchandising",
                how="Futures, cash bids and position feeds land in Lakehouse//RT and basis-forecast models scored in Model Serving surface position and exposure in the Merchandising Desk.",
                comps=["Merchandising Desk", "Lakehouse//RT", "Model Serving", "CME Group Futures", "DTN Prophet"]),
             uc("Harvest Logistics", "Operations", "stream", "Truck routing and elevator scheduling to minimize wait and shrink.",
                problem="At harvest, trucks, elevators and dryers are coordinated by phone, so queues build, grain shrinks in the wait and no one sees where the network is bottlenecked until it is too late.",
                who="Co-op Executive Board",
                how="Scale tickets, equipment telemetry and elevator status stream into Lakehouse//RT and route-and-scheduling logic surfaces live queues and dryer capacity in Harvest Command.",
                comps=["Harvest Command", "Lakehouse//RT", "John Deere Operations Center", "Model Serving", "Delta Lake"]),
             uc("Crop Insurance Analytics", "Risk", "gavel", "Acreage and indemnity exposure modeled before planting decisions.",
                problem="Acreage and indemnity exposure is pieced together from policy files after planting, so coverage and risk decisions are made without a clear picture of what is really at stake.",
                who="Finance & Risk",
                how="USDA RMA policy and acreage files are conformed under Unity Catalog and modeled in AI/BI, so indemnity exposure and coverage scenarios are analysed before planting decisions are locked.",
                comps=["USDA RMA Crop Insurance", "Unity Catalog", "AI/BI", "Delta Lake", "Genie One"],
                stories=[["Real-Time Agricultural Risk Portfolio Management", "https://www.databricks.com/resources/demos/videos/real-time-agricultural-risk-portfolio-management"]]),
             uc("Carbon MRV", "Sustainability", "partner", "Practice verification and quantification for credit programs.",
                problem="Carbon programs enroll acres faster than they can prove the outcome, and practice evidence stitched from spreadsheets and one-off models will not survive third-party verification.",
                who="Sustainability",
                how="Imagery, practice and soil data feed carbon models scored in Model Serving, with Unity Catalog holding auditable lineage from field practice to issued credit in the Carbon Registry.",
                comps=["Carbon Registry", "Model Serving", "Regrow MRV", "Unity Catalog", "Planet Labs Imagery"],
                stories=[["Agerpoint partners with Databricks for agriculture and nature systems", "https://www.agerpoint.com/blog/agerpoint-partners-with-databricks-to-scale-enterprise-data-intelligence-for-agriculture-and-nature-systems"]]),
             uc("Supply Chain Traceability", "Traceability", "product", "Lot lineage from field through elevator to customer.",
                problem="Provenance from field to customer is scattered across ERP, elevator and grower systems, so lot lineage and sourcing claims are assembled by hand and hard to defend to a buyer or auditor.",
                who="Sustainability",
                how="Field, elevator and ERP data are conformed under Unity Catalog and published as governed data products shared to food-company buyers and lenders over Open Sharing.",
                comps=["SAP S/4HANA Agribusiness", "Unity Catalog", "Data Products", "Open Sharing", "Delta Lake"],
                stories=[["UPL optimizes supply chain operations with demand forecasting", "https://www.databricks.com/customers/upl"]]),
             uc("Input Cost Optimization", "Finance", "erp", "Seed and chemical spend per bushel against plan.",
                problem="Seed and chemical spend is reconciled against plan long after the season, so overspend on an acre or a hybrid is found at close rather than while there is still time to change the order.",
                who="Finance & Risk",
                how="Application records, ERP purchases and yield outcomes are conformed on Delta Lake and tracked in AI/BI, so cost per bushel is measured against plan by field, hybrid and input.",
                comps=["Granular FMIS", "SAP S/4HANA Agribusiness", "Delta Lake", "AI/BI", "Genie One"],
                stories=[["UPL optimizes supply chain operations with demand forecasting", "https://www.databricks.com/customers/upl"],
                         ["FMC optimizes harvests with data and AI", "https://www.databricks.com/customers/fmc-corporation"]]),
             uc("Weather Risk Alerts", "Risk", "stream", "Frost, drought and spray window alerts pushed to operations.",
                problem="Frost, drought and spray-window warnings arrive as generic regional forecasts, so operations cannot tell which fields are actually at risk or act before the window to protect them closes.",
                who="Co-op Executive Board",
                how="Hyperlocal forecasts stream into Lakehouse//RT and are joined to field boundaries, so frost, drought and spray-window alerts push to operations in Harvest Command as risk emerges.",
                comps=["Harvest Command", "DTN Weather", "Lakehouse//RT", "Planet Labs Imagery", "AI Functions"],
                stories=[["Real-Time Agricultural Risk Portfolio Management", "https://www.databricks.com/resources/demos/videos/real-time-agricultural-risk-portfolio-management"]]),
             uc("Patronage Planning", "Finance", "chart", "Patronage pools modeled before fiscal close.",
                problem="Patronage pools are modeled in spreadsheets against provisional volumes, so the board reaches fiscal close without a reliable view of what can be returned to grower-members.",
                who="Finance & Risk",
                how="Grain accounting, volume and margin data are conformed on Delta Lake and modeled in AI/BI, so patronage pools and member returns can be scenario-tested before fiscal close.",
                comps=["Bushel ERP", "Delta Lake", "AI/BI", "Genie One", "Unity Catalog"])],
        ),
        "sources": {
            "john-deere": {"t": "John Deere Operations Center", "u": "https://www.deere.com/en/technology-products/precision-ag-technology/operations-center/"},
            "climate-fieldview": {"t": "Climate FieldView", "u": "https://www.climate.com/"},
            "granular": {"t": "Granular", "u": "https://granular.ag/"},
            "sap-agri": {"t": "SAP Agribusiness", "u": "https://www.sap.com/industries/agribusiness.html"},
            "oracle-fb": {"t": "Oracle Food and Beverage", "u": "https://www.oracle.com/food-beverage/"},
            "bushel": {"t": "Bushel", "u": "https://bushelpowered.com/"},
            "cme": {"t": "CME Group", "u": "https://www.cmegroup.com/markets/agriculture.html"},
            "dtn": {"t": "DTN", "u": "https://www.dtn.com/"},
            "barchart": {"t": "Barchart", "u": "https://www.barchart.com/cmdty"},
            "dtn-weather": {"t": "DTN Weather", "u": "https://www.dtn.com/weather/"},
            "planet": {"t": "Planet Labs", "u": "https://www.planet.com/"},
            "sentinel": {"t": "Sentinel Hub", "u": "https://www.sentinel-hub.com/"},
            "regrow": {"t": "Regrow", "u": "https://www.regrow.ag/"},
            "indigo": {"t": "Indigo Ag", "u": "https://www.indigoag.com/"},
            "usda-nass": {"t": "USDA NASS", "u": "https://quickstats.nass.usda.gov/"},
            "usda-rma": {"t": "USDA RMA", "u": "https://www.rma.usda.gov/"},
            "aggateway": {"t": "AgGateway ADAPT", "u": "https://www.aggateway.org/"},
        },
    },
}
