#!/usr/bin/env node
'use strict';
/* Build the industry -> Lucide line-art silhouette map and inject it into
   app/industry_icons.js between the SVG-MAP markers. Each industry maps to a
   Lucide icon chosen to read as a large FADED watermark (elongated / open
   silhouettes survive the mask; boxy glyphs do not). Run after changing the map.
   Fallbacks cover icon-name drift across Lucide versions. */
const https = require('https');
const fs = require('fs');
const path = require('path');

const VER = '1.42.0';
const url = (n) => `https://unpkg.com/lucide-static@${VER}/icons/${n}.svg`;

// id -> ordered candidate Lucide names (first that resolves wins)
const MAP = {
  advertising: ['megaphone'], aerospace_space: ['rocket'], agriculture: ['wheat'], agtech: ['sprout'],
  airlines: ['plane'], apparel_fashion: ['shirt'], automotive: ['car'], banking: ['landmark', 'building-columns'],
  capital_markets: ['trending-up'], chemical_mfg: ['flask-conical'], clinical_trials: ['test-tube-diagonal', 'test-tube'],
  construction: ['hard-hat'], consumer_goods: ['shopping-bag'], crypto_digital_assets: ['bitcoin'],
  cybersecurity: ['shield-check'], data_centers: ['database'], diagnostics_labs: ['microscope'],
  digital_health: ['stethoscope'], ecommerce: ['shopping-cart'], edtech: ['graduation-cap'],
  education: ['book-open'], energy_utilities: ['zap'], food_beverage: ['sandwich'], gaming: ['gamepad-2'],
  genomics_biotech: ['dna'], grocery: ['shopping-basket'], health_insurance: ['shield-plus', 'shield-check'],
  healthcare: ['heart-pulse'], insurance_pandc: ['umbrella'], legal: ['scale'], life_insurance: ['bird'],
  manufacturing: ['factory'], market_data_exchanges: ['chart-candlestick', 'candlestick-chart'],
  media_broadcasting: ['clapperboard'], medical_devices: ['syringe'], mining: ['pickaxe'], mortgage_lending: ['house'],
  ngo: ['heart-handshake'], oil_gas: ['fuel'], paper_packaging: ['package', 'package-2'], payments_fintech: ['credit-card'],
  pharmaceuticals: ['pill'], pharmacy_pbm: ['cross'], professional_services: ['briefcase'],
  public_safety: ['siren'], public_sector: ['building'], rail_transit: ['train-front', 'tram-front'],
  real_estate: ['building-2'], renewables: ['leaf'], restaurants: ['utensils-crossed'], retail: ['store'],
  semiconductors: ['circuit-board', 'cpu'], shipping_ports: ['anchor'], software_technology: ['code'],
  sports_entertainment: ['trophy'], staffing_hr: ['users'], telecommunication: ['radio-tower'],
  transport_shipping: ['ship'], travel_hospitality: ['palmtree', 'palm-tree', 'tent-tree'],
  waste_management: ['trash-2'], water_utilities: ['droplets'], wealth_management: ['gem'],
  wholesale_distribution: ['truck'],
  generic: ['layers'],
};

function get(u) {
  return new Promise((res, rej) => {
    https.get(u, (r) => {
      if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) return res(get(r.headers.location));
      if (r.statusCode !== 200) { r.resume(); return rej(new Error(r.statusCode + ' ' + u)); }
      let d = ''; r.on('data', c => d += c); r.on('end', () => res(d));
    }).on('error', rej);
  });
}

// keep only the drawable shapes from the Lucide <svg>, drop the wrapper
function inner(svg) {
  const shapes = svg.match(/<(path|circle|line|rect|polyline|polygon|ellipse)\b[^>]*\/>/g) || [];
  return shapes.join('').replace(/\s+/g, ' ').trim();
}

(async () => {
  const out = {};
  for (const [id, names] of Object.entries(MAP)) {
    let ok = null, used = null;
    for (const n of names) {
      try { const svg = await get(url(n)); const body = inner(svg); if (body) { ok = body; used = n; break; } }
      catch (e) { /* try next */ }
    }
    if (!ok) { console.error('MISSING icon for ' + id + ' (tried ' + names.join(', ') + ')'); process.exit(1); }
    out[id] = ok;
    console.log(id.padEnd(24) + ' <- ' + used);
  }

  // emit a stable, sorted object literal
  const ids = Object.keys(out).sort();
  const lines = ids.map(id => '    ' + id + ': ' + JSON.stringify(out[id]) + ',');
  const block = '  // SVG-MAP-START (generated by tools/fetch_industry_svg.js — do not edit by hand)\n' +
    '  const SVG = {\n' + lines.join('\n') + '\n  };\n' +
    '  // SVG-MAP-END';

  const file = path.join(__dirname, '..', 'app', 'industry_icons.js');
  let src = fs.readFileSync(file, 'utf8');
  const re = /  \/\/ SVG-MAP-START[\s\S]*?  \/\/ SVG-MAP-END/;
  if (re.test(src)) src = src.replace(re, block);
  else src = src.replace(/  const GENERIC = /, block + '\n  const GENERIC = ');
  fs.writeFileSync(file, src);
  console.log('\ninjected ' + ids.length + ' SVG glyphs into ' + file);
})();
