#!/usr/bin/env python3
"""Fetch official Databricks product marks and emit the inline PRODUCT_MARKS map.

Every file is downloaded from www.databricks.com, transformed here, and embedded
into app/index.html. The app makes no network call for artwork at runtime.

Usage:
    python3 tools/markgen.py            # rewrite the PRODUCT_MARKS block in app/index.html
    python3 tools/markgen.py --check    # verify the embedded block matches a fresh build
"""
import argparse
import pathlib
import re
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "app" / "index.html"
CACHE = ROOT / "tools" / ".markcache"

CANVAS = 48.0
PAD = 2.0
UA = "Mozilla/5.0 (compatible; idea-markgen/1.0)"

BEGIN = "/* PRODUCT_MARKS:BEGIN generated by tools/markgen.py */"
END = "/* PRODUCT_MARKS:END */"

# tile name -> official artwork published by Databricks
MARKS = {
    "AI Functions": "https://www.databricks.com/sites/default/files/2025-08/primary-icon-orange-built-in-functions.svg",
    "AI Search": "https://www.databricks.com/sites/default/files/2024-11/SearchDataIcon.svg",
    "AI/BI": "https://www.databricks.com/sites/default/files/2026-01/icon-ai-bi.svg",
    "Agent Bricks": "https://www.databricks.com/sites/default/files/2026-01/icon-mosaic-ai-bricks.svg",
    "Agent Mode": "https://www.databricks.com/sites/default/files/2026-02/GenieDeepResearchIcon.svg",
    "Apps": "https://www.databricks.com/sites/default/files/2025-06/appsIcon-orange.svg",
    "Auto Loader": "https://www.databricks.com/sites/default/files/2026-06/primary-icon-orange-access-connector.svg",
    "Classic & Serverless Compute": "https://www.databricks.com/sites/default/files/2025-01/primary-icon-orange-scale.svg",
    "CustomerLake": "https://www.databricks.com/sites/default/files/2026-06/icon-customerlake.svg",
    "Delta Lake": "https://www.databricks.com/sites/default/files/2023-03/icon-orange_delta-lake.svg",
    "Feature Store": "https://www.databricks.com/sites/default/files/2024-10/primary-icon-orange-cache-sync-reduction.svg",
    "Genie": "https://www.databricks.com/sites/default/files/2026-05/icon-genie.svg",
    "Genie Agents": "https://www.databricks.com/sites/default/files/2025-02/speechBubbleIcon.svg",
    "Genie Code": "https://www.databricks.com/sites/default/files/2026-03/GenieCodeIcon.svg",
    "Genie One": "https://www.databricks.com/sites/default/files/2026-06/icon-genie-one-16x16.svg",
    "Lakebase": "https://www.databricks.com/sites/default/files/2026-01/icon-lakebase.svg",
    "Lakebridge": "https://www.databricks.com/sites/default/files/2023-03/icon-orange-reserved-keywords-parser.svg",
    "Lakeflow": "https://www.databricks.com/sites/default/files/2026-01/icon-lakeflow.svg",
    "Lakeflow Connect": "https://www.databricks.com/sites/default/files/2023-09/primary-icon-orange-connectors.svg",
    "Lakeflow Designer": "https://www.databricks.com/sites/default/files/2025-05/dagicon.svg",
    "Lakehouse": "https://www.databricks.com/sites/default/files/2024-06/primary-icon-orange-delta-lakehouse.svg",
    "Lakehouse//RT": "https://www.databricks.com/sites/default/files/2026-06/icon-lakehouse-rt.svg",
    "Lakewatch": "https://www.databricks.com/sites/default/files/2023-02/icon-orange-SIEM.svg",
    "MLflow": "https://www.databricks.com/sites/default/files/2023-01/icon-orange-Full-Lifecycle-Machine-Learning.svg",
    "Marketplace Listings": "https://www.databricks.com/sites/default/files/2026-06/dataMarketplaceIcon.svg",
    "Model Serving": "https://www.databricks.com/sites/default/files/2025-05/CloudModelIcon.svg",
    "Notebooks & IDEs": "https://www.databricks.com/sites/default/files/2026-03/notebookIcon.svg",
    "Open Sharing": "https://www.databricks.com/sites/default/files/2026-03/primary-icon-orange-open-source.svg",
    "SQL Warehouses": "https://www.databricks.com/sites/default/files/2026-06/TableLightningIcon.svg",
    "System Tables": "https://www.databricks.com/sites/default/files/2026-02/visibleIcon.svg",
    "Unity Catalog": "https://www.databricks.com/sites/default/files/2026-01/icon-unity-catalog.svg",
    "Unity Catalog OSS": "https://www.databricks.com/sites/default/files/2026-01/icon-unity-catalog.svg",
    "Unity Gateway": "https://www.databricks.com/sites/default/files/2024-10/primary-icon-orange-authentication-service.svg",
    "Zerobus": "https://www.databricks.com/sites/default/files/2025-04/primary-icon-orange-input-ingest_.svg",
}

OPACITY_RAMP = [1.0, 0.62, 0.38, 0.24]


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def fetch(name, url, refresh=False):
    if not url.startswith("https://www.databricks.com/"):
        raise ValueError("%s: artwork must come from www.databricks.com" % name)
    CACHE.mkdir(exist_ok=True)
    hit = CACHE / (slug(name) + ".svg")
    if hit.exists() and hit.stat().st_size > 80 and not refresh:
        return hit.read_text()
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    for attempt in range(3):
        try:
            body = urllib.request.urlopen(req, timeout=45).read().decode("utf-8", "replace")
            break
        except Exception as exc:
            if attempt == 2:
                raise RuntimeError("%s: %s" % (name, exc))
            time.sleep(2 + attempt * 3)
    if "<svg" not in body[:800]:
        raise ValueError("%s: response is not an SVG" % name)
    hit.write_text(body)
    return body


COLOUR = re.compile(r"#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)|\b(?:white|black)\b")


def channels(colour):
    """Return r, g, b in 0..1 for any colour syntax the exports actually use.

    Some marks are traced rather than drawn and come back as
    `fill:rgb(100%,37.25%,27.45%)` inside a style attribute instead of
    `fill="#ff5f46"`. Reading only hex left those marks with a literal colour,
    so they ignored the palette and the theme.
    """
    c = colour.strip().lower()
    if c == "white":
        return 1.0, 1.0, 1.0
    if c == "black":
        return 0.0, 0.0, 0.0
    if c.startswith("#"):
        h = c.lstrip("#")
        if len(h) == 3:
            h = "".join(x * 2 for x in h)
        h = h[:6]
        return tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    parts = re.split(r"[,\s/]+", c[c.index("(") + 1:c.rindex(")")].strip())
    out = []
    for p in parts[:3]:
        out.append(float(p.rstrip("%")) / 100.0 if p.endswith("%") else float(p) / 255.0)
    while len(out) < 3:
        out.append(0.0)
    return tuple(out)


def luminance(colour):
    r, g, b = channels(colour)
    f = lambda c: c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def is_plate(colour):
    return luminance(colour) >= 0.86


PROTECTED = re.compile(r"<(defs|clipPath|mask|pattern)\b.*?</\1>", re.S)


def strip_plates(body):
    """Drop the white backing plate, but never touch a clip or mask shape.

    A Figma export clips with <clipPath><rect fill="white"/></clipPath>. Deleting
    that rect empties the clip and the whole mark disappears.
    """
    keep = []

    def park(m):
        keep.append(m.group(0))
        return "\x00%d\x00" % (len(keep) - 1)

    body = PROTECTED.sub(park, body)

    def drop(m):
        tag = m.group(0)
        col = re.search(r'fill="([^"]+)"', tag) or re.search(r"fill:\s*([^;\"']+)", tag)
        if not col or not COLOUR.fullmatch(col.group(1).strip()):
            return tag
        return "" if is_plate(col.group(1).strip()) else tag

    for tag in ("rect", "path", "circle", "ellipse", "polygon"):
        body = re.sub(r"<%s\b[^>]*/>" % tag, drop, body)
        body = re.sub(r"<%s\b[^>]*>.*?</%s>" % (tag, tag), drop, body, flags=re.S)

    return re.sub(r"\x00(\d+)\x00", lambda m: keep[int(m.group(1))], body)


ATTR_PAINT = re.compile(r'(fill|stroke|stop-color)="([^"]+)"')
STYLE_PAINT = re.compile(r"(fill|stroke|stop-color)\s*:\s*([^;\"']+)")


def tone_map(body):
    """Repaint every colour in the artwork as currentColor.

    This is what lets one embedded copy serve light, dark and all thirteen
    palettes: the mark has no colour of its own, it takes the `color` of
    whatever container draws it. Both the attribute form (`fill="#ff3621"`) and
    the style form (`style="fill:rgb(100%,37%,27%)"`) have to be covered, or a
    mark silently keeps its own colour and stops following the theme.
    """
    cols = set()
    for pat in (ATTR_PAINT, STYLE_PAINT):
        for m in pat.finditer(body):
            val = m.group(2).strip()
            if COLOUR.fullmatch(val):
                cols.add(val.lower())
    ranked = sorted(cols, key=luminance)
    level = {c: OPACITY_RAMP[min(i, len(OPACITY_RAMP) - 1)] for i, c in enumerate(ranked)}

    def repaint(attr, val, style):
        val = val.strip()
        if not COLOUR.fullmatch(val):
            return None
        op = level.get(val.lower(), 1.0)
        prop = "stroke" if attr == "stroke" else "fill"
        if style:
            out = "%s:currentColor" % attr
            return out if op == 1.0 else "%s;%s-opacity:%g" % (out, prop, op)
        out = '%s="currentColor"' % attr
        return out if op == 1.0 else '%s %s-opacity="%g"' % (out, prop, op)

    body = ATTR_PAINT.sub(lambda m: repaint(m.group(1), m.group(2), False) or m.group(0), body)
    return STYLE_PAINT.sub(lambda m: repaint(m.group(1), m.group(2), True) or m.group(0), body)


""" ---------------------------------------------------------------------------
Weight.

A tile icon on the canvas is 19px. Databricks draws a lot of its marks as fine
line art on a 100-unit canvas, and at 19px those lines fall below one device
pixel and grey out. Enlarging the icon does not help: the artwork is vector, so
the strokes shrink with it and ink coverage stays flat (measured: Delta Lake
0.030 at 19px, 0.031 at 22px).

Two shapes of thin, two fixes:

* stroke-drawn marks already carry a stroke, so the width is raised to a floor.
  The floor is expressed on the 48-unit canvas and divided by the fit scale, so
  the number written into the file always lands on the same visual weight.
* fill-drawn marks have no stroke to raise, so they get one: an outline in their
  own colour at a constant device width. `vector-effect="non-scaling-stroke"`
  is what makes it constant, which is the property that matters here. It adds
  weight at 19px on the canvas and stays discreet at 48px in the detail drawer,
  instead of scaling up and turning the mark into a blob.

HAIRLINE lists the fill-drawn marks that measured below the legibility floor.
Regenerate it with `python3 tools/markgen.py --measure` (needs Chrome) rather
than editing by eye: the numbers in the comment are ink coverage at 19px,
where the marks that read well sit between 0.19 and 0.31.
--------------------------------------------------------------------------- """

STROKE_FLOOR = 2.6      # effective stroke width on the 48-unit canvas
OUTLINE = 0.6           # device px, constant at every render size
INK_FLOOR = 0.13        # ink coverage at 19px below which a mark greys out

HAIRLINE = {
    "AI Functions",                  # 0.096
    "Feature Store",                 # 0.103
    "Genie",                         # 0.118
    "Lakebridge",                    # 0.088
    "Lakeflow Connect",              # 0.126
    "Lakehouse",                     # 0.065
    "Lakehouse//RT",                 # 0.128
    "Lakewatch",                     # 0.088
    "MLflow",                        # 0.107
    "Open Sharing",                  # 0.098
    "Unity Gateway",                 # 0.061
    "Zerobus",                       # 0.091
    "Delta Lake",                    # 0.030
}

PAINTED = re.compile(r"<(path|circle|ellipse|polygon|rect)\b([^>]*?)(/?)>")


def thicken_strokes(body, scale):
    def sub(m):
        return 'stroke-width="%g"' % max(float(m.group(1)), STROKE_FLOOR / scale)

    return re.sub(r'stroke-width="([0-9.]+)"', sub, body)


STROKE_OFF = re.compile(r'stroke="none"|stroke:\s*none')


def add_outline(body, width=OUTLINE):
    """Outline every filled shape in its own colour, in place of no stroke.

    A shape that already strokes is left alone, that one is thicken_strokes'
    job. A shape that says `stroke:none` in a style attribute has to be
    rewritten rather than given a stroke attribute, because the style wins over
    presentation attributes and the outline would never paint.
    """
    decls = ('stroke:currentColor;stroke-width:%g;vector-effect:non-scaling-stroke;'
             'stroke-linejoin:round' % width)
    attrs_form = (' stroke="currentColor" stroke-width="%g"'
                  ' vector-effect="non-scaling-stroke" stroke-linejoin="round"' % width)

    def sub(m):
        tag, attrs, close = m.group(0), m.group(2), m.group(3)
        if 'fill="currentColor"' not in attrs and "fill:currentColor" not in attrs:
            return tag
        off = STROKE_OFF.search(attrs)
        if off:
            attrs = attrs[:off.start()] + decls + attrs[off.end():]
        elif "stroke=" in attrs or "stroke:" in attrs:
            return tag
        else:
            attrs += attrs_form
        return "<%s%s%s>" % (m.group(1), attrs, close)

    return PAINTED.sub(sub, body)


def namespace_ids(body, key):
    ids = set(re.findall(r'\bid="([^"]+)"', body))
    for i in sorted(ids, key=len, reverse=True):
        safe = "%s-%s" % (key, i)
        body = body.replace('id="%s"' % i, 'id="%s"' % safe)
        body = body.replace("url(#%s)" % i, "url(#%s)" % safe)
        body = body.replace('href="#%s"' % i, 'href="#%s"' % safe)
    return body


def transform(name, raw):
    key = slug(name)
    m = re.search(r"<svg\b([^>]*)>(.*)</svg>", raw, flags=re.S)
    if not m:
        raise ValueError("%s: no <svg> root" % name)
    head, body = m.group(1), m.group(2)

    vb = re.search(r'viewBox="([\d.\-\s,]+)"', head)
    if vb:
        x, y, w, h = [float(v) for v in re.split(r"[\s,]+", vb.group(1).strip())]
    else:
        w = float(re.search(r'width="([\d.]+)', head).group(1))
        h = float(re.search(r'height="([\d.]+)', head).group(1))
        x = y = 0.0
    if w <= 0 or h <= 0:
        raise ValueError("%s: bad viewBox" % name)

    body = re.sub(r"<title>.*?</title>", "", body, flags=re.S)
    body = re.sub(r"<desc>.*?</desc>", "", body, flags=re.S)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    body = strip_plates(body)
    body = tone_map(body)
    body = namespace_ids(body, key)

    inner = CANVAS - 2 * PAD
    s = min(inner / w, inner / h)

    body = thicken_strokes(body, s)
    if name in HAIRLINE:
        body = add_outline(body)

    tx = PAD + (inner - w * s) / 2.0 - x * s
    ty = PAD + (inner - h * s) / 2.0 - y * s
    fmt = lambda v: ("%.4f" % v).rstrip("0").rstrip(".") or "0"
    body = '<g transform="translate(%s %s) scale(%s)">%s</g>' % (fmt(tx), fmt(ty), fmt(s), body.strip())

    body = shrink_numbers(body)
    body = re.sub(r">\s+<", "><", body)
    body = re.sub(r"\s{2,}", " ", body).strip()
    return body


GEOM_ATTR = re.compile(r'\b(d|cx|cy|r|rx|ry|x|y|x1|y1|x2|y2|width|height|points)="([^"]*)"')


def shrink_numbers(body, places=2):
    """Round geometry to `places`. On a 48px canvas this stays far below one pixel."""
    def round_all(text):
        return re.sub(
            r"-?\d+\.\d+",
            lambda m: (("%." + str(places) + "f") % float(m.group(0))).rstrip("0").rstrip(".") or "0",
            text,
        )

    return GEOM_ATTR.sub(lambda m: '%s="%s"' % (m.group(1), round_all(m.group(2))), body)


def build(refresh=False):
    out = {}
    for name, url in sorted(MARKS.items()):
        out[name] = transform(name, fetch(name, url, refresh))
    return out


def render(marks):
    lines = [BEGIN, "const PRODUCT_MARKS = {"]
    for name in sorted(marks):
        body = marks[name].replace("\\", "\\\\").replace('"', '\\"')
        lines.append('  "%s": "%s",' % (name, body))
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"


def measure(marks, px=19):
    """Ink coverage per mark at canvas size, so HAIRLINE is evidence, not taste.

    Renders every mark into one strip of `px`-wide cells and reads the mean
    darkness of each cell back out. Needs Chrome and Pillow, which is why it is
    a separate mode and not part of the build.
    """
    import subprocess
    import tempfile
    from PIL import Image

    names = sorted(marks)
    cells = "".join('<i><svg viewBox="0 0 48 48" fill=none>%s</svg></i>' % marks[n] for n in names)
    page = ("<!doctype html><meta charset=utf-8><style>html,body{margin:0;background:#fff}"
            "#g{display:grid;grid-template-columns:repeat(%d,%dpx);width:max-content}"
            "i{display:block;width:%dpx;height:%dpx;line-height:0}"
            "svg{width:%dpx;height:%dpx;color:#000;display:block}</style>"
            "<div id=g>%s</div>" % (len(names), px, px, px, px, px, cells))

    with tempfile.TemporaryDirectory() as tmp:
        src = pathlib.Path(tmp) / "strip.html"
        shot = pathlib.Path(tmp) / "strip.png"
        src.write_text(page)
        subprocess.run(
            [CHROME, "--headless=new", "--disable-gpu", "--hide-scrollbars",
             "--force-device-scale-factor=1",
             "--window-size=%d,%d" % (len(names) * px + 20, px + 20),
             "--virtual-time-budget=5000", "--screenshot=%s" % shot, src.as_uri()],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        img = Image.open(shot).convert("L")
        out = {}
        for i, name in enumerate(names):
            px_vals = list(img.crop((i * px, 0, (i + 1) * px, px)).getdata())
            out[name] = sum(255 - v for v in px_vals) / (255.0 * len(px_vals))
    return out


def orphaned_keys(html):
    """MARKS is keyed by tile name, so a rename would silently drop the mark."""
    body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", html, flags=re.S)
    tiles = set(re.findall(r'\bn:"([^"]+)"', body))
    return sorted(name for name in MARKS if name not in tiles)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--refresh", action="store_true")
    ap.add_argument("--measure", action="store_true")
    args = ap.parse_args()

    marks = build(args.refresh)

    if args.measure:
        ink = measure(marks)
        faint = [n for n, v in ink.items() if v < INK_FLOOR]
        for name in sorted(ink, key=ink.get):
            print("%-30s %.3f%s" % (name, ink[name], "  <- under the floor" if ink[name] < INK_FLOOR else ""))
        print("\n%d of %d marks under %.2f ink at 19px" % (len(faint), len(ink), INK_FLOOR))
        return 1 if faint else 0

    block = render(marks)
    html = APP.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

    if args.check:
        found = pat.search(html)
        if not found:
            print("FAIL: PRODUCT_MARKS block missing from app/index.html")
            return 1
        if found.group(0) != block:
            print("FAIL: embedded PRODUCT_MARKS differs from a fresh build")
            return 1
        orphans = orphaned_keys(html)
        if orphans:
            print("FAIL: no tile carries these names, the mark can never show:")
            for name in orphans:
                print("  %s" % name)
            return 1
        print("OK: %d marks embedded, current, and all matched to a tile" % len(MARKS))
        return 0

    if not pat.search(html):
        print("FAIL: no PRODUCT_MARKS block to replace, add the markers first")
        return 1
    APP.write_text(pat.sub(lambda _: block, html, count=1))
    print("wrote %d marks, block %d bytes" % (len(MARKS), len(block)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
